- NetKAN/KOSMOS-SSPP.netkan
- NetKAN/RN-SalyutStations.netkan
- NetKAN/RN-SovietProbes.netkan
- NetKAN/RN-SovietSpacecraft.netkan
- NetKAN/SovietPackCore.netkan
Nothing but whitespace changes
> Remove the devil tabs!

- NetKAN/TheCube.netkan
Add epoch due to whacky numbering.
> Move The Cube to Spacedock

- NetKAN/KSCSwitcher.kerbalstuff
- NetKAN/KSCSwitcher.netkan
- NetKAN/KerbalRenamer.kerbalstuff
- NetKAN/KerbalRenamer.netkan
> Move KerbalRenamer and KSCSwitcher to KSP-RO Githubs

- NetKAN/RN-USRockets.netkan
-Change the description to be more relevant
> RN us rockets description fix

- NetKAN/SurfaceExperimentPack.netkan
Closes #2991
Use of BSD Simplified licence advised via PM on KSP forums. I have asked for that to be added to the OP on the forums.
> Add Surface Experiment Pack

- NetKAN/EnduranceSpaceExplorationSystem.netkan
Builds on and closes #3411, with many thanks to @ILM126
> Move Endurance Space Exploration System to Spacedock

- NetKAN/InterstellarFuelSwitch-Core.netkan
No changes to anything functional, just what users see.
> Fix name and abstract for InterstellarFuelSwitch-Core

- t/metadata.t
Permit identifiers to start with digits or hyphen as per KSP-CKAN/CKAN#1570.
@politas @pjf @techman83 @Dazpoet
> Update Identifier Test

- NetKAN/RealSolarSystem.netkan
Next RSS will have its cache files in its own folder, no need to deal with that.
**DO NOT MERGE UNTIL NEXT RSS**
> RSS: Update netkan for next RSS

- NetKAN/DunaSpaceProgram.netkan
- NetKAN/EveSpaceProgram.netkan
- NetKAN/LaytheSpaceProgram.netkan
Set homepage to forums for the alien space programs
> Update Duna, Eve, Laythe Space Programs

- NetKAN/WW2Warships.netkan
Mod author moved from 0.41.1 to 0.5
> Update WW2Warships - add epoch

- NetKAN/CareerManager.netkan
Self-hosted netkan file
Closes #3449
> Add CareerManager

- NetKAN/ColorfulFuelLines.netkan
It is included in the zip file
> ColorfulFuelLines - Add dependency on InterstellarFuelSwitch

- NetKAN/JoolDIRECT.netkan
This is an automated commit on behalf of Daelkyr
> Add Jool DIRECT from SpaceDock

- NetKAN/OrbitalTug.netkan
> Move OrbitalTug.netkan to correct folder

- NetKAN/KerbolOrigins.netkan
I don't have @Olympic1 's setup for testing potential planetary collisions, but he is down as an author for this mod, so...
> Add Kerbol Origins from Spacedock

- NetKAN/KduffersKorpHotrodWheels.kerbalstuff
- NetKAN/KduffersMultiwheels.kerbalstuff
- NetKAN/kdufferskorpracewheel.kerbalstuff
Multiwheels contains the other two packs.
Hopefully we'll get a new source eventually
Ref KSP-CKAN/CKAN-meta#1031
> Add conflicts for Kduffers Wheels packs

- NetKAN/GregroxsColoredEVAIVASuits.netkan
- NetKAN/MulticolorSuitsPack.netkan
This is a semi-automated submission on behalf of GregroxMun, fixed by @politas
> Move Gregroxs' multicolor suits pack to Spacedock

- NetKAN/SigmaModExpansions.netkan
- NetKAN/SigmaRTExpansion.netkan
According to mod author, latest version is compatible with 1.0.5 as well, see http://forum.kerbalspaceprogram.com/index.php?/topic/123202-105-sigma-outerspacecomms/&do=findComment&comment=2293354
Closes KSP-CKAN/CKAN#1641
> SigmaModExpansions add version override

- NetKAN/ContractConfigurator-HistoricMissions.netkan
- NetKAN/ContractConfigurator-HistoricMissionsRSS.netkan
Also create separate entry for RSS version
> Move Historic missions pack to new Spacedock

- NetKAN/HotContents.netkan
- NetKAN/HotContentsOrbitalSystems.netkan
This is a semi-automated commit on behalf of Sequinox
> Add HotContents Orbital Systems from SpaceDock

- NetKAN/SpeedUnitChanger.netkan
This is a semi-automated commit on behalf of uncreative_user
> Add Speed Unit Changer from SpaceDock

- NetKAN/KerbalSports.netkan
For great fishing. :fish: 
http://forum.kerbalspaceprogram.com/index.php?/topic/135728-10511-kerbal-sports-jebediah-kermans-fishing-challenge-v100-2016-04-01/
> Added KerbalSports.

- NetKAN/BurgerMod.netkan
- NetKAN/KerbalSpacePonies.kerbalstuff
- NetKAN/KerbalSpacePonies.netkan
Whew, after several busy days I can finally sit down and get this pushed!
Doesn't look like there are any problems with this push ^_^
Not sure if I wrote the BurgerMod's netkan file correctly, if there are any mistakes I'll quickly push it again XP
Thanks for being patient with me, with my last derp up ^^"
> Updated KerbalSpacePonies and Added BurgerMod!

- NetKAN/NavballUpDefault.netkan
* Updated to v1.1
* Added `asset_match` qualifier to download correct releases
> NavballUpDefault updated to v1.1

- NetKAN/KSPInterstellarExtended.netkan
An attempt to unblock this mod on http://status.ksp-ckan.org/. We're currently not index the most recent version because of it.
> Modify install stanza of KSPInterstellarExtended

- NetKAN/G-Effects.netkan
An attempt to unblock this mod on http://status.ksp-ckan.org/. We're currently not indexing the most recent version because of it.
> Add install stanza to G-Effects

- NetKAN/DeepSpaceExplorationVessels.netkan
I'm hoping this resolves the schema error that's appearing on http://status.ksp-ckan.org/
> List a license for DeepSpaceExplorationVessels

- NetKAN/KerbalConfigEditor.netkan
spacedock/260 is 404. spacedock/446 is new home.
> Update kref for KerbalConfigEditor

- build.sh
Noticed some build failures due to the 1.1 short version.
> Update version overrides for 1.1

- NetKAN/EVAHandrailsPackContinued.netkan
Reverts KSP-CKAN/NetKAN#3536
New version uploaded with fixed .version file.
> Revert "EVAHandrailsPackContinued"

- NetKAN/Mk2Expansion.netkan
Should pick up the 1.1 release there.
> Move Mk2Expansion to Spacedock

- NetKAN/Contares-Common.netkan
- NetKAN/Contares.netkan
Common files between multiple mods.
> Split Agencies folder from Contares

- NetKAN/MethaneRockets.netkan
This is a semi-automated commit on behalf of Joco223
> Add Methane Rockets! from SpaceDock

- NetKAN/Contares-REXFreeFlyer.netkan
- NetKAN/ContaresREXFreeFlyer.netkan
This is a semi-automated commit on behalf of hraban
> Add Contares REX Free Flyer from SpaceDock

- NetKAN/Mk1CockpitRPMInternals.netkan
- NetKAN/Mk1RPMInternal.netkan
This is a semi-automated commit on behalf of fast_de_la_speed
> Add Mk1 Cockpit RPM Internals from SpaceDock

- NetKAN/EveBiomesPlus.netkan
This is a semi-automated commit on behalf of Snark
> Add EveBiomesPlus from SpaceDock

- NetKAN/StockalikeMiningExtension.netkan
This is an automated commit on behalf of SuicidalInsanity
> Add Stockalike Mining Extension from SpaceDock

- NetKAN/YellowGreenJool.netkan
- NetKAN/YellowGreenJoolRecolor.netkan
This is a semi-automated commit on behalf of GregroxMun
> Add Yellow-Green Jool Recolor from SpaceDock

- NetKAN/RealLaunchSites.netkan
- NetKAN/RealLaunchSitesRealKSCinKSP.netkan
This is a semi-automated commit on behalf of tristonwilson12
> Add Real Launch Sites/Real KSC in KSP from SpaceDock

- NetKAN/HazardTanksTextures.netkan
- NetKAN/HazardTanksTexturesforProceduralParts.netkan
This is a semi-automated commit on behalf of Enceos
> Add Hazard Tanks Textures for Procedural Parts from SpaceDock

- NetKAN/StarWarsBDAddon.netkan
This is a semi-automated commit on behalf of KSP_Bros
> Add Star Wars BD Addon from SpaceDock

- build.sh
- t/metadata.t
I noted we didn't have any tests for spec v1.16. This rectifies that.
> Add tests for spec v1.16

- NetKAN/SpiceLaunchSystem.kerbalstuff
- NetKAN/SpiceLaunchSystem.netkan
This is a semi-automated commit on behalf of maccollo
> Add Spice Launch System from SpaceDock

- NetKAN/KerbinSideSkyways.netkan
This is a semi-automated commit on behalf of AlphaAsh
To mesh with #3118, setting conflicts to all KerbinSide* mods.
> Add Kerbin-Side Skyways from SpaceDock

- NetKAN/ScienceMod.netkan
This is a semi-automated commit on behalf of ScienceModder
> Add Science! Mod from SpaceDock

- NetKAN/NavBallsToYou.netkan
This is a semi-automated commit on behalf of cerebrate
> Add NavBallsToYou from SpaceDock

- NetKAN/RSSExtrasolar.netkan
- NetKAN/RSSExtrasolarPlanetsBeyondOurSun.netkan
This is a semi-automated commit on behalf of AndyDrawsPrettyPictures
> Add RSS Extrasolar: Planets Beyond Our Sun from SpaceDock

- NetKAN/HabTech.netkan
This is a semi-automated commit on behalf of Benjee10
> Add HabTech from SpaceDock

- NetKAN/SpaceXLandingLegs.netkan
- NetKAN/SpaceXLegs.netkan
This is a semi-automated commit on behalf of svendii
> Add SpaceX Landing Legs from SpaceDock

- NetKAN/ItsTheLittleThings.netkan
- NetKAN/Itsthelittlethings.netkan
This is a semi-automated commit on behalf of TMasterson5
> Add Its the little things from PizzaDock

- NetKAN/DecoupleFromHeatshield.netkan
- NetKAN/Decouplefromheatshield.netkan
This is a semi-automated commit on behalf of jtackman
> Add Decouple from heatshield from SpaceDock

- NetKAN/DockingPortSoundFX.netkan
This is a semi-automated commit on behalf of TG626
> Add Docking Port Sound FX from SpaceDock

- NetKAN/NuclearPropulsionDrive.netkan
- NetKAN/Nuclearpropulsiondrivebysonichood1.netkan
This is a semi-automated commit on behalf of sonichood1
> Add Nuclear propulsion drive by sonichood1 from SpaceDock

- NetKAN/DepthCharge.netkan
- NetKAN/KerwisModuleDepthCharge.netkan
This is a semi-automated commit on behalf of GeorgeDuty
> Add KerwisModuleDepthCharge from SpaceDock

- NetKAN/PL-IRC.netkan
- NetKAN/PanzerLabsImprovedResourceConverters.netkan
This is an automated commit on behalf of PanzerLabs
> Add PanzerLabs Improved Resource Converters from SpaceDock

- NetKAN/KerbalWeights.netkan
This is an automated commit on behalf of SkylerA
> Add Kerbal Weights from SpaceDock

- NetKAN/FarloPlanetaryPack.netkan
This is a semi-automated commit on behalf of PVP_PlayerPro
> Add Farlo Planetary Pack from SpaceDock

- NetKAN/PL-Common.netkan
- NetKAN/PL-KSat.netkan
Split up into main and flagmod, looks like this modder plans to continue.
> Add PanzerLabs K-Sat and Common

- NetKAN/LargeBoatPartsPack-Modern.netkan
- NetKAN/LargeBoatPartsPack-WW2.netkan
- NetKAN/LargeBoatPartsPack.netkan
Closes https://github.com/KSP-CKAN/NetKAN/issues/3537
> Large Boat Parts Pack fixed and split

- NetKAN/KerbinSide.netkan
- NetKAN/KerbinSideAirRace.kerbalstuff
- NetKAN/KerbinSideGroundControl.netkan
- NetKAN/KerbinSideSkyways.netkan
> Update KerbinSide relationships

- NetKAN/RN-SovietRockets.netkan
-I forgot to edit this file when I separate the recommended mods into 2
different mods.
> RN fix recommends for rockets

- NetKAN/Contares-Antennas.netkan
> Contares-Antennas is included in the full Contares

- NetKAN/MechJeb2.netkan
Hopefully this fixes the 2.5.7 CKAN file when the bot runs
> MechJeb is now on 1.1

- NetKAN/RasterPropMonitor-Core.netkan
- NetKAN/RasterPropMonitor.netkan
Adjust install stanza based on new archive structure, additional tweaks made to future-proof the install.
Closes https://github.com/KSP-CKAN/CKAN-meta/issues/1057
> Fix RPM/RPM-core relationship

- NetKAN/ContractParser.netkan
- NetKAN/ProgressParser.netkan
Is including a .version file the simplest way to automate this?
> Manually change Contract Parser and Progress Parser to KSP 1.1

- NetKAN/NavHud.netkan
attempt #2 NavHud has been ported to 1.1
> Change ksp version to 1.1.0

- build.sh
Also decide once and for all how to spell "override"
Ref: https://github.com/KSP-CKAN/CKAN-meta/pull/1063
Closes https://github.com/KSP-CKAN/CKAN/issues/1670
> Update ksp_version defaults and add overrides for 1.1.X versions

- NetKAN/KIEFighter.netkan
Extant `abstract` is `NEW FEATURES!`.
Fails by each: @plague006, @Dazpoet, and @politas who each looked at PRs involving this mod twice and each time missed this. =)
> Hardcode an informative abstract for KIEFighter

- NetKAN/StockVisualEnhancements.netkan
> Move StockVisualEnhancements to Spacedock for KSP1.1

- NetKAN/StockVisualEnhancements.netkan
> Revert "Move StockVisualEnhancements to Spacedock for KSP1.1"

- NetKAN/FerramAerospaceResearch.netkan
> Use FAR AVC .version file

- NetKAN/RasterPropMonitor-Core.netkan
- NetKAN/RasterPropMonitor.netkan
Closes https://github.com/KSP-CKAN/CKAN/issues/1672
> Fix RPM install, add epoch to force update.

- NetKAN/KSPLogiRGB.netkan
A fork of @cguckes ksp-chroma plugin to support logitech keyboards.
> New Mod: KSPLogiRGB

- NetKAN/StockVisualEnhancements.netkan
Allows 1.1 compatibility
Closes #3647
> Move StockVisualEnhancements to Spacedock

- NetKAN/AlternateResourcePanel.netkan
- NetKAN/KerbalAlarmClock.netkan
- NetKAN/TransferWindowPlanner.netkan
Flags not vital to working of mod.
> Changed TriggerAu flags from depends to recommends

- NetKAN/HaystackContinued.netkan
Personally really happy to see this.
> HaystackContinued to SpaceDock, closes #3646

- NetKAN/DistantObject-RealSolarSystem.netkan
- NetKAN/DistantObject-default.netkan
- NetKAN/DistantObject.netkan
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/1080
> Update ksp_ver compat.

- NetKAN/GPOSpeedFuelPump.netkan
This is a continuation of `GoodSpeed`
> Add GPOSpeedFuelPump, closes #3649

- NetKAN/HeatControl.netkan
> Move HeatControl to Spacedock

- NetKAN/StockVisualEnhancements.netkan
This will help avoid, and closes https://github.com/KSP-CKAN/CKAN-meta/issues/1094
> Have SVE conflict the old SVE-Textures virtual module

- NetKAN/KerboKatzSmallUtilities-FPSLimiter.netkan
- NetKAN/KerboKatzSmallUtilities-FPSViewer.netkan
- NetKAN/KerboKatzSmallUtilities-PhysicalTimeRatioViewer.netkan
These minimods have been updated to KSP1.1
Will move other minimods over to github as they are released.
Ref #3670
> Move KerboKatz SmallUtilities minimods to github

- NetKAN/Contares-Antennas.netkan
- NetKAN/Contares-Common.netkan
- NetKAN/Contares.netkan
- NetKAN/ContaresCA1CanadianArrow.netkan
/GameData/Contares/Patches/CONTARES_TweakScale.cfg is shared across Contares mods.
Closes KSP-CKAN/CKAN#1676
> Additional shared file in Contares mods

- NetKAN/DestructionEffects.netkan
> Add DestructionEffects

- NetKAN/KerbinSideAirRace.netkan
- NetKAN/KerbinSideCore.netkan
- NetKAN/KerbinSideKSC2.netkan
- NetKAN/KerbinSideKampus.netkan
Closes #3681, #3678, #3674, #3671
> New Kerbin-Side packs on Spacedock

- NetKAN/MusicMuteContinued.netkan
MusicMute recompiled for KSP 1.1+
> Add MusicMuteContinued

- NetKAN/UbioWeldContinued.netkan
...rather than a hardcoded ksp-version setting.
Should help to address UbioWeldingLtd/UbioWeldContinued#38
> Use AVC integration for UbioWeldContinued

- NetKAN/PartAngleDisplay.netkan
To include the Part Angle Display mod by @Gerry1135
> Add PartAngleDisplay.netkan

- NetKAN/NearFuturePropulsion.netkan
Updates Near Future Propulsion.
Added version checking (hope I did that right?), removed some deprecated relationships.
> Update for 1.1, primary moved to SpaceDock

- NetKAN/CommunityTechTree.netkan
Let's see if I can get *one* pull request done without errors today :P
> Update CommunityTechTree for 1.1, primary moved to SpaceDock

- NetKAN/SmartParts.netkan
http://forum.kerbalspaceprogram.com/index.php?/topic/58338-104-smart-parts-v166-dds-textures-and-bug-fixes-july-5/&do=findComment&comment=2533243
> Switch to 1.1 maintained version

- NetKAN/KerbalAtomics.netkan
> KerbalAtomics to GitHub

- NetKAN/NorthKerbinDynamics.netkan
http://spacedock.info/mod/214
http://forum.kerbalspaceprogram.com/index.php?/topic/118667-wip10x-north-kerbin-dynamics-nuclear-bombs-and-heavy-ordnance-pack-and-other-things-06/
> Add NorthKerbinDynamics

- NetKAN/MasterTechWeapons.netkan
This is a semi-automated commit on behalf of TMasterson5
> Add Master Tech Weapons from SpaceDock

- NetKAN/ExceptionDetector.netkan
Updated because people have been asking me :)
> Add ExceptionDetector back into CKAN

- NetKAN/HideEmptyTechNodes.netkan
Closes https://github.com/KSP-CKAN/NetKAN/pull/3747
> HideEmptyTechNodes to SpaceDock, closes #3707

- NetKAN/SmartParts.netkan
Edit by @pjf: LinuxGuruGamer is the new maintainer, being transferred with blessings of the old maintainer.
> LinuxGuruGamer is now the new maintainer of SmartParts!

- NetKAN/InfernalRobotics-LegacyParts.netkan
- NetKAN/InfernalRobotics.netkan
Including parts is helpful.
Closes https://github.com/KSP-CKAN/CKAN-meta/issues/1103
> Add InfernalRobotics-LegacyParts

- NetKAN/KOSMOS-SSPP.netkan
still works on 1.1.1 without changes
> added 1.1.1

- NetKAN/StockVisualEnhancements.netkan
Use bundled EVE and conflict with the full EVE.
> StockVisualEnhancements fix

- NetKAN/HangarExtender.netkan
Alewx has released 3.4.8, which is 1.1-compatible
> Update HangarExtender to 1.1

- NetKAN/XAGM.netkan
> Add Tbone's XAGM

- NetKAN/SDHI-ServiceModuleSystem.netkan
Dependencies should be a-OK as well.
If not, we'll deal with them.
> Update SDHI SMS compat to KSP 1.1.2

- NetKAN/MusicMuteContinued.netkan
> Changed homepage

- NetKAN/ModularFlightIntegrator.netkan
Until Jenkins generates more open .version files @sarbian
> Temp override to MFI KSP version

- NetKAN/InterstellarFuelSwitch-Core.netkan
The core dll does not have external mo dependencies,
> removed all depandencies

- NetKAN/KOSMOS-SSPP.netkan
> added 1.1.2 compatibility

- NetKAN/TimeControl.netkan
Add Time Control Mod for KSP 1.1.2 to CKAN from my fork.
> Add TimeControl

- NetKAN/Biomatic.netkan
- NetKAN/BiomaticForAll.netkan
Note to self: install this once available.
> Add Biomatic and BiomaticForAll

- NetKAN/SigmaDimensions.netkan
FYI @Sigma88
`min_version` for `ModuleManager` is from [this comment](http://forum.kerbalspaceprogram.com/index.php?/topic/126548-/&page=10#comment-2402864).
@Sigma88 is there a newer minimum or a minimum required version for Kopernicus?
Since there is no KSP 1.1.x compatible version at the moment, this will currently generate the most recent version compatible with KSP 1.0.5.
Output from `ckan show` on my test KSP 1.0.5 install.
```
D:\Users\Dwayne\Projects\CKAN\NetKAN [feature/sigma_dimensions]> ckan show SigmaDimensions --ksp test-1.0.5.1028
Sigma Dimensions: A universal rescale mod
Module info:
- version:      0.4.3
- authors:      Sigma88
- status:       development
- license:      restricted
Depends:
- ModuleManager, min: 2.6.16
- Kopernicus
Provides:
- SigmaDimensions
Resources:
- …
```
> Add SigmaDimensions

- NetKAN/BDAnimationModules.netkan
- NetKAN/RN-USProbesPack.netkan
-Update us probes config, remove broken dependency
-Change bdanimation as it was abandoned? and update the code for 1.1.2,
if the author returns this can be changed back but the mod was
completely broken in 1.1+
> RN us probes update

- NetKAN/KSPX.netkan
Reverts KSP-CKAN/NetKAN#3899 - Author has fixed homepage on Spacedock.
> Revert "Hardcode homepage for KSPX"

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- ISSUE_TEMPLATE.md
- README.md
A PR template should reduce the WTF moments new contributors sometimes have. The readme changes are to coincide with the changes we'll be making with https://github.com/KSP-CKAN/NetKAN/issues/3890. Moving the templated into .github just reduces the number of items in the root by 1.
> Update docs, add PR template, move templates to folder.

- NetKAN/TacFuelBalancer.netkan
Original author has moved on and it has been taken over by @thewebbooth.
> Move TacFuelBalancer to Spacedock

- NetKAN/KerbinSideGAP.netkan
> Update install for KerbinSideGAP

- NetKAN/InfernalRobotics.netkan
That last asset_match I wrote was true facepalm. :(
> Update asset_match for InfernalRobotics

- NetKAN/LEAForKSP.netkan
> Fix install for LEAForKSP

- NetKAN/AGroupOnStage.netkan
- NetKAN/AnyRes.netkan
- NetKAN/CactEye2.frozen
- NetKAN/CactEyeTelescopesContinued.netkan
- NetKAN/ClampsBeGone.netkan
- NetKAN/ContractConfigurator-UsefulSpaceStations.netkan
- NetKAN/EnduranceSpaceExplorationSystem.netkan
- NetKAN/FarFromKerbin.netkan
- NetKAN/HeatControl.netkan
- NetKAN/HotContents.netkan
- NetKAN/InFlightFlagSwitcher.netkan
- NetKAN/InterstellarFuelSwitch-Core.netkan
- NetKAN/KSPInterstellarExtended.netkan
- NetKAN/KustomKerbals.netkan
- NetKAN/UniversalStorage.netkan
- NetKAN/WildBlueTools.netkan
See https://github.com/KSP-CKAN/NetKAN/issues/1455#issuecomment-217134778 for full rationale.
Closes https://github.com/KSP-CKAN/NetKAN/issues/1455
> Remove all mini-avc filters

- NetKAN/KerbitingSystemPlanetpack.netkan
> Fix install for KerbitingSystemPlanetpack

- NetKAN/Mk3Expansion.netkan
~~Waiting on author to clarify license and whether KM_Gimbal is required.~~ All set.
> Add Mk3Expansion

- NetKAN/BSGOfficerRanksFinalFrontierAddOn.netkan
> Add BSGOfficerRanksFinalFrontierAddOn

- NetKAN/BSGEnlistedRanksRedFinalFrontierAddOn.netkan
> Add BSGEnlistedRanksRedFinalFrontierAddOn

- NetKAN/BSGEnlistedRanksGreyFinalFrontierAddOn.netkan
> Add BSGEnlistedRanksGreyFinalFrontierAddOn

- NetKAN/RN-USRockets.netkan
-Update to install craft files now that I include them with latest
release
> RN us rockets update

- NetKAN/Chatterer.netkan
Chatterer now supports KSP-AVC
> Chatterer add $vref

- NetKAN/DockingPortSoundFX.netkan
> Move DockingPortSoundFX to Github

- NetKAN/StockVisualEnhancements.netkan
Mod is now supporting AVC, too.
> StockVisualEnhancements ksp_version override

- NetKAN/PoliticalMap4kTexture.netkan
- NetKAN/PoliticalMap8kTexture.netkan
- NetKAN/PoliticalMapMilitaryTexture.netkan
Added dependency on TectureReplacer and they conflict with each other now.
Closes #3987
> PoliticalMaps textures Depends and conflicts

- NetKAN/LaunchPad39B.netkan
> Add LaunchPad 39B from Spacedock

- NetKAN/AviationLights.frozen
- NetKAN/AviationLights.netkan
Making use of the new abstract scraping from GitHub
> AviationLights to GitHub, new maintainer.

- NetKAN/JSIAdvancedTransparentPods.netkan
- NetKAN/RasterPropMonitor.netkan
Tested without RPM-Core as a dependency, works fine.
Replaces #3812
> Add JSIAdvTransparentPods from Github

- NetKAN/Mk1RPMInternal.netkan
> Add RPM Dependency to Mk1RPMInternals

- NetKAN/DistantObject-RealSolarSystem.netkan
- NetKAN/DistantObject-default.netkan
- NetKAN/DistantObject.netkan
Latest version is compatible with 1.1.2 according to http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1161-13-mar-2016/&do=findComment&comment=2572794
> DistantObjectEnhancement KSP Compatibility

- NetKAN/B9-PWings-Fork.netkan
Mod went from 2.1 to 0.40.3 when it upgraded for 1.1
> Add Epoch to B9-PWings-Fork

- NetKAN/Kerbalism-Profile-Default.netkan
> Add dependency on CRP to Kerbalism-Default-Profile

- NetKAN/ResearchBodies.frozen
- NetKAN/ResearchBodies.netkan
> Move ResearchBodies to Spacedock

- NetKAN/TACLS.netkan
Fixes https://github.com/KSP-CKAN/NetKAN/pull/3972
Closes https://github.com/KSP-CKAN/NetKAN/issues/4023
> Add name for TACLS

- NetKAN/DMagicScienceAnimate.netkan
Release 0.14 is "Update for KSP 1.1.2"
> DMagicScienceAnimate to KSP 1.1.2

- NetKAN/TACLS.netkan
> TACLS fix install

- NetKAN/RealisticRemodel1x.netkan
`find` worked for the earlier version of this mod but not this one. *shrug*
> RealisticRemodel1x fix install

- NetKAN/AllTheseWorlds.netkan
> Add AllTheseWorlds

- NetKAN/imkSushisPlanetSystem.netkan
> Add imkSushisPlanetSystem

- NetKAN/RealSolarSystemExpanded.netkan
> Add RealSolarSystemExpanded

- NetKAN/JDLiquidFuelCell.netkan
> Add JDLiquidFuelCell

- NetKAN/Wraithforge.netkan
Without BDArmory dependency (which is only available for 1.1.0):
````
|   ModuleManager.2.6.24.dll
|   
\---Wraithforge
+---Agencies
|       Agents.cfg
|       Wraithforge.png
|       Wraithforge_scaled.truecolor
|       
\---Parts
+---Denel 35mm Dual Purpose Gun
|       Denel35mmCIWSAOX.dds
|       Denel35mmDualPurposeGun.cfg
|       model.mu
|       muzzle.png
|       smoke.png
|       
+---Denel A-Darter
|       A-Darter.cfg
|       A-DarterAOX.dds
|       model.mu
|       muzzle.png
|       srbsmoke.png
|       
+---Denel Al-Tariq
|       Al-Tariq.cfg
|       Al-TariqAOX.dds
|       model.mu
|       muzzle.png
|       srbsmoke.png
|       
+---Denel G6 Howitzer
|       DenelG-6HowitzerAOX.dds
|       DenelG6Howitzer.cfg
|       model.mu
|       muzzle.png
|       smoke.png
| …
```
> Add Wraithforge

- NetKAN/TACLS.netkan
Removed TACLS resource definitions in favor of adding CRP dependency
> Update TACLS.netkan, add CRP dependency

- NetKAN/WalkAbout.netkan
Author went from "v1.2" to "1.3". Le sigh.
> Force_v on Walkabout

- NetKAN/KSPRankRibbons.netkan
> Add KSPRankRibbons from Spacedock

- NetKAN/MilitaryVehicleChassis.netkan
> Add Military Vehicle Chassis on Spacedock

- NetKAN/LarinaxSolarSystem.netkan
License should be correct, but waiting on confirmation from mod author: http://forum.kerbalspaceprogram.com/index.php?/topic/134890-wip-larinax-solar-system-v0040/&do=findComment&comment=2574882
> Add LarinaxSolarSystem

- NetKAN/HoldTheMonoprop.netkan
> Add HoldTheMonoprop on Spacedock

- NetKAN/PatentPurchase.netkan
> Add PatentPurchase on Spacedock, closes #4049

- NetKAN/QuizTechAeroPack-internals.netkan
- NetKAN/QuizTechAeroPack.netkan
I've no idea if `InternalsMod` will be a thing, but they're definitely their own class and nearly certain to not be broken by any change to modding. And if they do break we have a comment to search for.
Unblocks https://github.com/KSP-CKAN/NetKAN/pull/3561
> Split off QuizTechAeroPack-internals

- NetKAN/InterstellarFuelSwitch-Core.netkan
> InterstellarFuelSwitch-Core fix install

- NetKAN/EnvironmentalVisualEnhancements-HR.netkan
- NetKAN/EnvironmentalVisualEnhancements.netkan
We have been advised that it works fine in 1.1.2
> Increase EVE compatibility

- NetKAN/AntaresCygnus.netkan
-I forgot to update this mod to install ships when I did my other mods
> RN antares fix

- NetKAN/K2CommandPod.frozen
- NetKAN/K2CommandPod.netkan
> Move K2CommandPod to Spacedock

- NetKAN/RSS-Airports.netkan
some real airports locations as new additional KSC
> Airports for Real Solar System / KSC Switcher

- NetKAN/RSS-FictionalKSC.netkan
some fictive ( but cool / lol / or interesting) locations added as new ksc
> Fictional KSC for Real Solar System / KSC Switcher

- NetKAN/RandomishEclipses.netkan
> Add RandomishEclipses from Spacedock

- NetKAN/ETT.netkan
- NetKAN/YongeTechTreesPlugin.frozen
- NetKAN/YongeTechTreesPlugin.netkan
Will probably get a separate Spacedock entry soon.
> Split YongeTechTreesPlugin from ETT

- NetKAN/VenStockRevamp.netkan
- NetKAN/VensStockPartRevamp-CTTPatch.netkan
Before this is merged...
@NathanKell would you like to get in touch with the author about integrating this into VSPR itself?
> Add VensStockPartRevamp-CTTPatch

- NetKAN/ProceduralProbes.netkan
Closes https://github.com/KSP-CKAN/NetKAN/issues/4088
> Unfreeze ProceduralProbes, move download

- NetKAN/HGR.netkan
> Unfreeze HGR, move download

- NetKAN/kOSPropMonitor.netkan
> Add kOSPropMonitor

- NetKAN/SpaceLaunchSystemStockDimension.netkan
> Add SpaceLaunchSystemStockDimension from Spacedock

- NetKAN/Snacks.netkan
@Angel-125 has updated `Snacks` for KSP 1.1.2 and is the new maintainer for it.
> New maintainer for Snacks

- NetKAN/SigmaBinary-DunaIke.netkan
Needs to be kept in sync with SigmaBinary-Core
> KSP Version Update for SigmaBinary-DunaIke

- NetKAN/CommunityTerrainTexturePack.netkan
New dependency for OuterPlanetsMod 2.0.
> Add CommunityTerrainTexturePack

- NetKAN/AirplanePlus.netkan
> Add AirplanePlus

- NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
- NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
- NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan
- NetKAN/CustomAsteroids.netkan
Pushing some queued corrections to the CustomAsteroids compatibility data. This should be the last PR I make for a while, don't worry.
> CustomAsteroids compatibility fixes

- NetKAN/DresPlus.netkan
> Add DresPlus from Spacedock (Proper)

- NetKAN/NavHud.netkan
> NavHud KSP Version fix

- NetKAN/Races.netkan
> Add Races from Spacedock

- NetKAN/CivilianPopulationsRevived.netkan
> Add CivilianPopulationsRevived from Spacedock

- NetKAN/Races.netkan
Every time I see the identifier I think it's a mod that adds ethnic Kerbals...
> Fix install for Races

- NetKAN/AdvancedSASForAll.netkan
> Add Advanced SAS For All from Spacedock

- NetKAN/ActivateWhenShielded.netkan
- NetKAN/TweakScale.netkan
Noted when addressing KSP-CKAN/xKAN-meta_testing#13
> Spec license v1.2 required for WTFPL

- NetKAN/Kosmodrome.netkan
Ref https://github.com/KSP-CKAN/CKAN-meta/pull/1175
> Fix install Kosmodrome

- NetKAN/CoolRockets.netkan
- NetKAN/CrowdSourcedScience.netkan
- NetKAN/DepthCharge.netkan
- NetKAN/RCSBuildAid.netkan
- NetKAN/VesselMover.netkan
Ref https://github.com/KSP-CKAN/CKAN-meta/pull/1175
> `status` and `release-status` to `release_status`

- NetKAN/KerbinSideGAP.netkan
Updated required version of Contract Configurator since I want to use new "HasCrew.excludeKerbal" feature.
> KerbinSideGAP mod dependencies updating

- NetKAN/StarWarsBDAddon.netkan
Ref https://github.com/KSP-CKAN/CKAN/issues/1477
> Fix install StarWarsBDAddon

- NetKAN/ContractConfigurator-SoundingRockets.netkan
> Add ContractConfigurator-SoundingRockets from Spacedock

- NetKAN/TWSAs-Payload-Adapters.netkan
> Add TWSA-Payload-Adapters from Spacedock

- NetKAN/ContractConfigurator-KerbalAcademy.netkan
> Fix bad forum thread link for ContractConfigurator-KerbalAcademy

- NetKAN/RocketdyneF-1.frozen
- NetKAN/RocketdyneF-1.netkan
Need to update KSP version compatibility
Closes #4179
> Make Rocketdyne-F1 Netkan

- NetKAN/imkSushisSunToKerbol.netkan
> Add imkSushiSunToKerbol from SpaceDock

- NetKAN/KumarsDwarfStars.netkan
> Add KumarsDwarfStars

- NetKAN/CrewManifest.netkan
See [this forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1161-13-mar-2016/&do=findComment&comment=2615981).
[Verified](http://forum.kerbalspaceprogram.com/index.php?/topic/55485-11-kerbal-crew-manifest-v0620-apr-23/).
> Update CrewManifest KSP Version Compatability

- NetKAN/KRnD.netkan
- NetKAN/KerbalResearchAndDevelopment.netkan
Based off #4195, this will get the old release supporting KSP 1.0.5 into CKAN
> Add KerbalResearchAndDeveleopment 1.3 for KSP1.0.5

- NetKAN/KRnD.netkan
This should wrap up this mod (at least for now).
> KRnD move to author-hosted metadata

- NetKAN/DraggableMenu.netkan
It's for 1.0.5 but might as well in case it gets updated.
> Add DraggableMenu

- NetKAN/KSP-64k.netkan
- NetKAN/Races.netkan
- NetKAN/RocketdyneF-1.netkan
- NetKAN/TWSAs-Payload-Adapters.netkan
Seems the latest forum update has changed the URL requirements for threads.
> Fix homepages

- NetKAN/JW-Patches.netkan
> Add JW-Patches from Spacedock

- NetKAN/InterKalactic.netkan
> Add InterKalactic

- NetKAN/imkSushisBetterDensities.netkan
> Add imkSushi's Better Densities

- NetKAN/imkSushisModdedChallenges.netkan
> Add imkSushis Modded Challenges

- NetKAN/RedOktober.netkan
> Add RedOktober

- NetKAN/AntaresSolarSystem.netkan
> Add AntaresSolarSystem

- NetKAN/DockingcameraKURSstyle.netkan
> Move Docking Camera (KURS style) to Spacedock

- NetKAN/GameofKerbals.netkan
> Add GameofKerbals

- NetKAN/SovietEnginePack.netkan
Given the confusion in the forum threads, the new maintainers' decision to use a different name, and the restarted versioning, I decided make this a fork of SovietEngines rather than a continuation.
Replaces #4183
> Add SovietEnginePack

- NetKAN/TributetoHarversteR.netkan
> Add TributetoHarvesteR

- NetKAN/Historian-expanded.netkan
> Update Historian to KSP 1.1.2

- NetKAN/ProceduralFairingsRetext.netkan
See [forum thread.](http://forum.kerbalspaceprogram.com/index.php?/topic/141636-11x-procedural-fairings-retexture/) Tested and got a valid CKAN out of this.
And after a couple hours doing a disgusting amount of rebasing, reverting, and so on on my fork of NetKAN, I fixed my tomfoolery that caused the mess. Woo. :persevere: 
Replaces #4242
> Add Procedural Fairings Retexture

- NetKAN/CommonCorePods.netkan
> Add CommonCorePods

- NetKAN/Astro-Cosmonauts.netkan
> Add Astro/Cosmonauts from Spacedock

- NetKAN/CoatlAerospace.netkan
CKAN/Netkan support for the [ProbesPlus](https://spacedock.info/mod/768/ProbesPlus%21) mod by @raveloda
Major thanks to zengei and blowfish from #ckan for the troubleshooting help
> Creating CoatlAerospace.netkan

- NetKAN/PSA-Greenhouse.netkan
See [forum thread](http://forum.kerbalspaceprogram.com/index.php?/topic/141704-112-psa-greenhouse-for-usi-life-support-v-1123-2016jun13/).
> Add PSA-Greenhouse

- NetKAN/LaserDist.netkan
I just released LaserDist on spacedock and github (soon to be Curse also once I finish submitting this PR for NETKAN).  This is the new netkan entry for it.
> New entry for LaserDist mod I just released

- NetKAN/SimpleLife.netkan
Alternative to #4248.
This one includes correct dependencies.
> Add Simple Life with correct dependencies

- NetKAN/LCFP.netkan
Alternative to #4252.
Just needed to add a depends for MM.
> Add Launch Clamp Fuel Pumping

- NetKAN/Historian-expanded.netkan
A dot after the v? Really?
Closes #4264
> Set epoch due to past version weirdness

- NetKAN/NavUtilities.netkan
Forum thread makes it clear that the 1.1 pre-release updates are intended to work with all KSP 1.1.x
> NavUtilities Add override

- NetKAN/UKS-Kerbalism-Patch.netkan
> UKS isn't supported on CKAN anymore, so remove it as a dependency.

- NetKAN/AntaresCygnus.netkan
- NetKAN/KOSMOS-SSPP.netkan
- NetKAN/RN-MiscParts.netkan
- NetKAN/RN-SalyutStations.netkan
- NetKAN/RN-Skylab.netkan
- NetKAN/RN-SovietProbes.netkan
- NetKAN/RN-SovietRockets.netkan
- NetKAN/RN-SovietSpacecraft.netkan
- NetKAN/RN-USProbesPack.netkan
- NetKAN/RN-USRockets.netkan
-Update files for new ksp version
> RN fix for new ksp version

- NetKAN/CactEyeCommunity.netkan
- NetKAN/CactEyeCommunityDOEPatch.netkan
* Fix CactEye Community directory structure
* Actually fix directory structure
* create DOE compatibility patch for CactEyeCommunity
* Add resources entry to NetKANs, recommends to CactEye
* Fix dependency on wrongly named DistantObject
* add indentation
* add missing end sq bracket
> Fix CactEyeCommunity Directory Structure

- NetKAN/AsteroidDay.netkan
- NetKAN/KerbinCup.netkan
I updated Asteroid Day and added Kerbin Cup (It seems it wasn't indexed)
Tested, they works.
> updated Sqad mods

- NetKAN/PersistentRotation.netkan
Fix directory structure to reflect new changes since 1.1 as per #4295
> Update Persistent Rotation directory structure

- NetKAN/DistantObject-default.netkan
- NetKAN/DistantObject.netkan
Carries on from #4312 
* increments version number
* Filters Settings.cfg from DOEdefault, preventing installation from trying to overwrite files
> Update Distant Object Enhancement

- NetKAN/ExtraPlanetaryLaunchpads.netkan
Updates fixed .NetKAN file for EPL to point at 5.4.0 instead of 5.3.2
> Update EPL 5.4.0 for 1.1.3

- NetKAN/SETI-Greenhouse.netkan
Hey,
I m consolidating all my ckan metadata in a single repository.
Best regards,
Yemo/Y3mo
> Consolidating metadata in single repository

- NetKAN/FerramAerospaceResearch.netkan
> Change FAR to restricted

- NetKAN/ReentryParticleEffect.netkan
Advised by mod author on #ckan
> ReentryParticles Install dir fix

- NetKAN/AdvancedJetEngine.netkan
> Retarget AJE to new home

- NetKAN/RSS-Airports.netkan
bad and ugly forum - changed thread URL ( after change of title )
> fix homepage url

- NetKAN/PartWizard.netkan
See the following link:
http://forum.kerbalspaceprogram.com/index.php?/topic/72468-113-part-wizard-125-22-jun-2016/&do=findComment&comment=2662958
where the author says I can do this
> Updated PartWizard netkan file to reflect 1.1.3 compatibility

- NetKAN/BDAnimationModules.netkan
- NetKAN/TextureReplacer.netkan
-These are still compatible and fully working in ksp 1.1.3
> RN dependency meta update for TR and BD

- NetKAN/RadioFreeKerbin
https://github.com/benjwgarner/RadioFreeKerbin
> Add RadioFreeKerbin to NetKAN

- NetKAN/KSPInterstellarExtended.netkan
I added FilterExtensions to dependancies, although technically not required, it prevents the user from using the deprecated parts
> Updated dependancies

- NetKAN/PEBKACIndustriesLaunchEscapeSystem.netkan
Closes #4344
See this link for permission for me to do this: http://forum.kerbalspaceprogram.com/index.php?/topic/106518-113-pebkac-industries-launch-escape-system-20160706-now-includes-mk1-les/&do=findComment&comment=2665638
> PEBKACIndustriesLaunchEscapeSystem.netkan

- NetKAN/FlexibleDocking.netkan
> Fixed FlexibleDocking for DMagic

- NetKAN/PilotAssistant.netkan
Tested various core functions in 1.1.3 - seems to work.  No obvious compatibility reports on forums.
No response from author despite #4052 and Crzyrndm/Pilot-Assistant/issues/25.
> PilotAssistant KSP 113

- NetKAN/KerbalKrashSystem.netkan
Checked download - ModuleManager unchanged and no new folders needing install.
> KerbalKrashSystem 035 update

- NetKAN/KerbalKrashSystem.netkan
We'll need to restrict the version of older releases.
> KerbalKrashSystem 0.3.6 release

- NetKAN/MiniSampleReturnCapsule.netkan
> MiniSampleReturnCapsule

- NetKAN/UnmannedBeforeManned.netkan
> SETI metadata relocation - UbM

- SETI-RebalanceMaterialsGoo
Metadata copied and adjusted from existing mod.
> New SETI mini mod

- NetKAN/SETI-BalanceMod.netkan
> Metadata relocation

- NetKAN/SETI-Contracts.netkan
> SETI metadata relocation

- NetKAN/SETI-RemoteTech.netkan
> SETI metadata relocation - RT config

- NetKAN/SETI-ProbeControlEnabler.netkan
> SETI metadata relocation - ProbeControl

- NetKAN/ContractFilterContinued.netkan
- NetKAN/FTLDriveContinued.netkan
- NetKAN/QuizTechAeroPackContinued.netkan
Netkans for 3 mods I'm continuing
> ContractFilterContinued, FTLDriveContinued, & QuizTechAeroPackContinued

- NetKAN/SoyuzSpacecraftandRocketPack.netkan
> SoyuzSpacecraftandRocketPack

- NetKAN/AngaraRocketPack.netkan
> AngaraRocketPack

- NetKAN/GregroxMunsJupiteryJoolRecolorforKopernicusorTextureReplacer.netkan
- NetKAN/PlanetWiki.netkan
> PlanetWiki

- NetKAN/TimeControl.netkan
> TimeControl Epoch

- NetKAN/ChineseTianGongScienceSpaceStation.netkan
>  ChineseTianGongScienceSpaceStation

- NetKAN/QuickCursorHider.netkan
- NetKAN/QuickFineControl.netkan
> Quickfinecontrol

- NetKAN/2KASJ0523Planetarysystem.netkan
- NetKAN/a2KASJ0523Planetarysystem.netkan
> 2KASJ0523Planetarysystem.netkan

- NetKAN/FASTCORPAutogarage.netkan
> FASTCORPAutogarage

- NetKAN/WindowShineTR.frozen
- NetKAN/WindowShineTR.netkan
Author has explicitly granted permission for CKAN listing
Closes #4413
> New WindowShineTR release V12

- NetKAN/ImprovedChaseCamera.netkan
> ImprovedChaseCamera Force_v

- NetKAN/SVE-HighResolution.frozen
- NetKAN/SVE-HighResolution.netkan
- NetKAN/SVE-LowResolution.frozen
- NetKAN/SVE-LowResolution.netkan
- NetKAN/SVE-MediumResolution.frozen
- NetKAN/SVE-MediumResolution.netkan
- NetKAN/SVE-Sunflare.netkan
- NetKAN/SVE-Terrain.netkan
Requested by new maintainer, Berlin
Closes #4381
> Adding new StockVisualEnhancements (WIP)

- NetKAN/AngaraRocketPack.netkan
- NetKAN/FASTCORPAutogarage.netkan
- NetKAN/PlanetWiki.netkan
- NetKAN/QuickCursorHider.netkan
- NetKAN/QuickFineControl.netkan
Following up on the excellent work by @linuxgurugamer
> Some minor updates to recent additions

- NetKAN/AT-Utils.netkan
- NetKAN/ThrottleControlledAvionics.netkan
Added ModuleManager and AT-Utils as dependencies to
ThrottleControlledAvionics metadata.
> Added metadata for AT-Utils library.

- NetKAN/Year2200.netkan
Fixed Spacedock submission
Closes #4225
Waiting on confirmation from author that this submission was intentional, and clarification of whether SimpleConstruction should indeed be a conflict, or a dependency.
> Add Year2200

- NetKAN/HistoricalProgressionTechTree.netkan
> HistoricalProgressionTechTree

- NetKAN/KerbalKommander.netkan
> KerbalKommander

- NetKAN/BrazilianFlagBandeiradoBrasil.netkan
> Brazilian Flags

- NetKAN/MalemuteRover.netkan
Requested by @ArnePeirs for https://github.com/BobPalmer/CKAN/pull/6
> Add MalemuteRover

- NetKAN/DMagicScienceAnimate.netkan
Updated with author's permission for 1.1.3
> DMagicScienceAnimate

- NetKAN/SolarSailNavigator.netkan
Module has been modified and compiled to work with KSP 1.1 and Unity 5
> Update SolarSailNavigator.netkan to KSP 1.1

- NetKAN/ESLDJumpBeacons.netkan
> ESLDJumpBeacons

- NetKAN/RCSBuildAid.netkan
> RCSBuildAid v0.8.1

- NetKAN/AviationLights.netkan
The author reckons this still works. Seems to work for me, too.
> Update compatibility for Aviation Lights

- NetKAN/VesselMoverContinued.netkan
VesselMover has a new maintainer, so here's a new netkan file.
I'm not sure whether KSP-AVC should be a suggests or supports.
http://forum.kerbalspaceprogram.com/index.php?/topic/144421-*/
> Add VesselMover Continued

- NetKAN/ContractConfigurator-ContractPackHistoricalProgression.netkan
> ContractConfigurator-ContractPackHistoricalProgression

- NetKAN/CentauriDreams.netkan
First netkan created by new automated script
hand verified
> CentauriDreams

- NetKAN/SETI-ProbeParts.netkan
created by new automated script
hand verified
Closes #4412
> SETI-ProbeParts

- NetKAN/SearchAndRescue.netkan
netkan created by new automated script
hand verified
> SearchAndRescue

- NetKAN/AdditionalProgressionContracts.netkan
created by new automated script
hand verified
Closes #4437
> AdditionalProgressionContracts

- NetKAN/TanksButNoTanks.netkan
created by new automated script
hand verified
Closes #4391
Added MM depends stanza manually, it wasn't in the zip file
> TanksButNoTanks

- NetKAN/KepsilonKeridani.netkan
Closes #4403
using new netkan.sh generation script
> KepsilonKeridani

- NetKAN/BDArmoryContinued.netkan
> BDArmoryContinued

- NetKAN/RN-SalyutStations.netkan
- NetKAN/RN-Skylab.netkan
- NetKAN/RN-SovietProbes.netkan
- NetKAN/RN-SovietRockets.netkan
- NetKAN/RN-SovietSpacecraft.netkan
- NetKAN/RN-USProbesPack.netkan
- NetKAN/RN-USRockets.netkan
-Added module manager as a dependency to all mods that always needed it
-Added animated decouplers to 2 mods that now use it
> RN add new dependencies

- NetKAN/BrazilianFlagBandeiradoBrasil.netkan
We added the functionality to rename folders on installation with v1.18
Closes #4305
> Install Brazilian Flags outside Squad folder

- NetKAN/BDRailgun.netkan
> Add BDRailGun

- NetKAN/KerbalAlarmClock.netkan
> Add MinKSP override to KerbalAlarmClock

- NetKAN/HullcamVDSContinued.netkan
I deleted the old branch thinking it was accepted
> HullcamVDSContinued redo, with provides statement

- NetKAN/SVE-HighResolution.netkan
- NetKAN/SVE-LowResolution.netkan
- NetKAN/SVE-MediumResolution.netkan
Activate staging as per KSP-CKAN/CKAN#1679
> Activate Staging for main SVE mods

- NetKAN/KerbalGalaxyRevamped.netkan
I've collaborated with the mod's author to get this working.
Closes #4480
> Add Kerbal Galaxy Revamped

- NetKAN/RetractableLiftingSurface.netkan
Changed source from Spacedock to Github, and added some details
> RetractableLiftingSurface update

- NetKAN/TrackingStationAmbientlight.netkan
Please review before accepting.
> Migrate TrackingStationAmbientlight Mod from Kerbalstuff to Spacedock.

- NetKAN/KerBalloons.netkan
> Update Kerballoons to 0.4.1 

- NetKAN/AtomicAge.netkan
Forum users report this mod is working (mostly) fine in KSP 1.1
> Increase Atomic Age KSP Compatibility

- NetKAN/KerbalAircraftExpansion.netkan
> Set KAX KSP version to match Curse

- NetKAN/KerbalFlightData.netkan
- NetKAN/KerbalFlightIndicators.netkan
- NetKAN/KerbalWind.netkan
Kerbal flight data
kerbal flight indicators
kerbal wind
> updated my mod metadata

- NetKAN/DeadSkins.frozen
- NetKAN/DeadSkins.netkan
Author removed mod from Spacedock due to the great CKAN/modder conflict.
> Freeze Deadskins

- NetKAN/MilitaryVehicleChassis.netkan
Discovered this was failing on http://status.ksp-ckan.org/ - Completely messed up zip file structure, this is ugly as heck, and will probably be wrong for the next release. Staging activated.
> Fix Installation for MilitaryVehicleChassis

- NetKAN/StarWarsBDAddon.netkan
Discovered this was failing on http://status.ksp-ckan.org/
> Fix Installation for StarWarsBDAddon

- NetKAN/ContractConfigurator-HistoricMissions.netkan
- NetKAN/ContractConfigurator-HistoricMissionsRSS.netkan
Discovered these were failing  on http://status.ksp-ckan.org/ Folders have been switched around again. Will probably happen again in the future.
> Fix Installation for ContractConfigurator-HistoricMissions*

- NetKAN/MethaneRockets.netkan
Discovered this was failing on http://status.ksp-ckan.org/
> Fix install on MethaneRockets

- NetKAN/LTechContinued.netkan
> Prep for next release

- NetKAN/TALRadiallyAttachedExperimentalDataStorageContainer.netkan
> TALRadiallyAttachedExperimentalDataStorageContainer

- NetKAN/LCDLaunchCountDown.netkan
> LCDLaunchCountDown

- NetKAN/PiratesoftheKeribbean.netkan
> PiratesoftheKeribbean

- NetKAN/PeriscopeMod.netkan
> PeriscopeMod

- NetKAN/RPMEnhancedDockingPorts.netkan
Closes #4508
I've asked the author to fix a couple of problems (space in names, excess fiels from OSX).  If he does, I'll redo this.
> RPMEnhancedDockingPorts

- NetKAN/RN-SovietRockets.netkan
-Update config for changes to folder structure of mod
> RN soviet rockets update

- NetKAN/RN-SPP.netkan
-Add config for solar panels pack
> RN solar panels pack add

- NetKAN/PoodsMilkyWaySkybox.netkan
Manually generated .netkan file.
Please close the pull request generated by Space Dock for the mod.
Closes #4574
> Add Pood's Milky Way Skybox - Manual .netkan File Submission

- NetKAN/PoodsDeepStarMap.netkan
Manually generated .netkan file.
Please close the pull request generated by Space Dock for the mod.
Closes #4573
> Add Pood's Deep Star Map Skybox - Manual .netkan File Submission

- NetKAN/PoodsCalmNebulaSkybox.netkan
Manually generated .netkan file.
Please close the pull request generated by Space Dock for the mod.
> Add Pood's Calm Nebula Skybox - Manual .netkan File Submission

- NetKAN/RealismOverhaulCraftFiles.netkan
> Add RealismOverhaulCraftFiles

- NetKAN/PartOrganizer.netkan
> PartOrganizer

- NetKAN/Scatterer.netkan
> Add self-conflict to Scatterer

- NetKAN/RSSExtrasolar.netkan
Found to be broken via Netkan status page. Quite a few changes to the organisation on this one. Enabled staging
> Fix RSSExtrasolar installation and details

- NetKAN/PlanetWiki-OPM.netkan
> Add PlanetWiki-OPM Edition 

- NetKAN/BritishRockets.netkan
> BritishRockets new maintainer

- NetKAN/AdvancedJetEngine.netkan
- NetKAN/B9-PWings-Modified.netkan
- NetKAN/EVAManager.netkan
- NetKAN/EditorExtensionsRedux.netkan
- NetKAN/EvaFollower.netkan
- NetKAN/ForScienceContinued.netkan
- NetKAN/KerbalAircraftExpansion.netkan
- NetKAN/Kopernicus.netkan
- NetKAN/MK2KSPIIntegration.netkan
- NetKAN/ProceduralFairings.netkan
- NetKAN/Races.netkan
- NetKAN/RealisticAtmospheres.netkan
- NetKAN/RocketdyneF-1.netkan
- NetKAN/SAVE.netkan
- NetKAN/SMURFF.netkan
- NetKAN/SigmaDimensions.frozen
- NetKAN/StockBugFixPlus.netkan
- NetKAN/TWSAs-Payload-Adapters.netkan
- NetKAN/Taerobee.netkan
- NetKAN/UnchartedLands.netkan
> Homepage fixes following forum change

- NetKAN/TACLS-Config-Stock.netkan
- NetKAN/TACLS.netkan
Simplifies #4594 
Not entirely sure about the TACLS filter, though. Let's see what Jenkins says
> TACLS-Config Simplify installs

- NetKAN/TACLS.netkan
> TACLS filter_regexp

- NetKAN/PartsUnlimited.netkan
> PartsUnlimited

- NetKAN/FourianFuelSystems.netkan
> Add FourianFuelSystems

- NetKAN/Airlocks.netkan
> Add Airlocks by Tiktaalik

- NetKAN/KerbalOlympics.netkan
No forum thread for contacting mod author.
closes #4347
> Add KerbalOlympics

- NetKAN/xScience.netkan
Fixes https://github.com/KSP-CKAN/CKAN-meta/pull/1220
> Add leading 'v' to xScience

- NetKAN/SimpleRefuel.netkan
> SimpleRefuel

- NetKAN/LargeStructuralComponentsRedux.netkan
> LargeStructuralComponentsRedux

- NetKAN/AirParkContinued.netkan
> AirParkContinued

- NetKAN/DeflatableHeatShield.netkan
> DeflatableHeatShield

- NetKAN/TheDeathStar.netkan
> TheDeathStar

- NetKAN/LanderControl.netkan
> LanderControl move to Curse

- NetKAN/UbioWeldContinued.netkan
> Add override to uBioWeldContinued

- NetKAN/PlanetShine-Config-Default.netkan
- NetKAN/PlanetShine.netkan
> Move PlanetShine to Curse

- NetKAN/LTechContinued.netkan
Also removed MM because it isn't available for 1.2 so I removed the references.
> Temporarily move LTech to github

- NetKAN/LightsOut-Fwiffo.netkan
> Add LightsOut-Fwiffo

- NetKAN/PartOverhauls.netkan
The problems with #4643 have been resolved.
I am hosting the .zip as the original .zip was 15 times larger because it contained the source. It also seemed to be throttled to 72KB/s, so it took way too long to download. See link for original source:
http://forum.kerbalspaceprogram.com/index.php?/topic/147582-update-12-pre-release-is-here
> Add PartOverhauls.netkan

- NetKAN/KSTS.netkan
> Add KSTS meta-netkan

- NetKAN/WaterSounds.netkan
> Move WaterSounds to Curse

- NetKAN/MemGraph.netkan
> Add MemGraph

- NetKAN/BDAnimationModules.netkan
-Update bdanim for KSP 1.2
-I have taken to updating the mod again
@politas this version will only work with 1.2 and not previous versions
> RN bd anim fix

- NetKAN/CargoTransportationSolutions.netkan
Move CargoTransportationSolutions to Github untill SpaceDock adds an 1.2 tag
> Move CargoTransportationSolutions to Github

- NetKAN/PersistentRotation.netkan
Latest release was build for 1.2
> PersistentRotation 1.2

- NetKAN/PhoenixIndustriesCubeSat.netkan
- NetKAN/PhoenixIndustriesFlags.netkan
Add dependency on PhoenixIndustriesFlags, filter flags. Also filter Thumbs.db from Flagmod
closes #4671
> Fix PhoenixIndustriesCubeSat

- NetKAN/DockingPortSoundFX.netkan
> DockingPortSoundFX - force-v

- NetKAN/LTechContinued.netkan
Add ModuleManager back to file
> Add MM to LTech

- NetKAN/DistantObject-RealSolarSystem.netkan
- NetKAN/DistantObject-default.netkan
- NetKAN/DistantObject.netkan
Latest build is for KSP 1.2 according to github release
> DistantObject for 1.2

- NetKAN/AviationLights.netkan
Latest build is for KSP 1.2 according to github release
> AviationLights for 1.2

- NetKAN/Konstruction.netkan
- NetKAN/USI-MKSLite.frozen
- NetKAN/USI-MKSLite.netkan
- NetKAN/USI-UKS-Shared.frozen
- NetKAN/USI-UKS-Shared.netkan
Remove deprecated mods
Add Konstruction
Looks like github wants to rename the file instead of creating a new one. Lazy github 💤
> Update USI mods

- NetKAN/LTechContinued.netkan
- NetKAN/Olympic1ARPIcons.netkan
I'm switching over to host metadata for my mods
> Self hosting metadata

- NetKAN/ExperimentTracker.netkan
> Experiment Tracker Force-v

- NetKAN/Mk2Expansion.netkan
Release sequence is 1.7.12, 1.13, 1.7.20
> Mk2Expansion add epoch

- NetKAN/EnvironmentalVisualEnhancements-HR.netkan
- NetKAN/EnvironmentalVisualEnhancements.netkan
> EVE 1.2 maintainer move

- NetKAN/OdysseusPlanetPack.netkan
> OdysseusPlanetPack

- NetKAN/MissionPatchManager.netkan
> MissionPatchManager

- NetKAN/TrainPartsPack.netkan
> TrainPartsPack

- NetKAN/KerbolExpandedBodies.netkan
> KerbolExpandedBodies

- NetKAN/BasicOrbit.netkan
> BasicOrbit

- NetKAN/KerbnetController.netkan
> KerbnetController

- NetKAN/JoolRecolor.frozen
- NetKAN/JupiteryJoolRecolor-Kopernicus.netkan
- NetKAN/JupiteryJoolRecolor-TextureReplacer.netkan
The Homepage for this mod shows a couple of alternate recolor schemes, thus the choice for the provides/conflicts
Closes #4268
> Add GregroxMun's JupiteryJoolRecolor versions

- NetKAN/AudioMufflerRedux.netkan
> AudioMufflerRedux

- NetKAN/LowExpectations.netkan
> Low Expectations

- NetKAN/SETI-ProbeParts.netkan
Noticed that this was not controlled by me directly (as all the other seti mods), which prevents me from setting the ksp version.
Thank you and best regards,
Y3mo
> Direct Control of the NetKAN file

- NetKAN/WarpEverywhere.netkan
> WarpEverywhere

- NetKAN/InterplanetaryTransportSystem.netkan
> InterplanetaryTransportSystem.netkan

- NetKAN/CZ2LaunchSystem.netkan
> CZ2 Launch System

- NetKAN/DumpAndBurn.netkan
> DumpandBurn

- NetKAN/SVE-HighResolution.netkan
- NetKAN/SVE-LowResolution.netkan
- NetKAN/SVE-MediumResolution.netkan
- NetKAN/SVE-Sunflare.netkan
Phase 2 of #4712
Part of #4711
> SVE for 1.2

- NetKAN/CommunityCategoryKit.netkan
A new mod of BobPalmer and JPLRepo
Closes #4761
> Add CommunityCategoryKit

- NetKAN/MusicMuteContinued.netkan
A new release which supports KSP 1.2 is available on my GitHub
> Updated metadata to support KSP 1.2

- NetKAN/ShipEffects.frozen
Per Arne, in an attempt to make https://github.com/KSP-CKAN/NetKAN/pull/4772 work.
> Delete frozen ShipEffects netkan file

- NetKAN/ShipEffects.netkan
Add the KSP 1.2 compatible version of ShipEffects
> ShipEffects update 2 of 2

- NetKAN/KerbalPlanetaryBaseSystems.netkan
Added CommunityCategoryKit as dependency
Added CommunityResourcePack as dependency
> Updated KerbalPlanetaryBaseInc netcan file

- NetKAN/SVE-HighResolution.netkan
- NetKAN/SVE-LowResolution.netkan
- NetKAN/SVE-MediumResolution.netkan
- NetKAN/SVE-Sunflare.netkan
Switching to `ksp_version` until there is regex available
> Update SVE again

- NetKAN/OPTSpacePlaneParts.netkan
> OPT-SpaceplaneParts to Spacedock, temporarily

- NetKAN/LanderControl.netkan
> LanderControl working on 1.2

- NetKAN/RCSBuildAid.netkan
Ref #4685 
Ping @m4v - With this change, as long as your AVC .version file is correct, CKAN should stay updated.
> RCSBuildAid switch to Auto-updating

- NetKAN/SVE-Terrain.frozen
- NetKAN/SVT-HighResolution.netkan
- NetKAN/SVT-LowResolution.netkan
Freezing `SVE-Terrain.netkan` and adding low and high resolution downloads.
> SVE-Terrain now has multiple downloads

- NetKAN/EdenSunflare.netkan
> Add abstract to EdenSunflare

- NetKAN/SVE-HighResolution.netkan
- NetKAN/SVE-LowResolution.netkan
- NetKAN/SVE-MediumResolution.netkan
- NetKAN/SVE-Scatterer-Config.netkan
- NetKAN/SVE-Sunflare.netkan
- NetKAN/Scatterer-config.netkan
- NetKAN/Scatterer.netkan
Same name collapses all three releases into a single entry
> SVE "CKAN friendly" redevelopment

- NetKAN/DockingcameraKURSstyle.netkan
> DockingCameraKURS

- NetKAN/ExtendedInfoSciExp.netkan
> ExtendedInformationAboutScientificExp

- NetKAN/ThroughTheEyesOfaKerbal.netkan
> ThroughTheEyesOfaKerbal.netkan

- NetKAN/ModularPods.netkan
> Modular Pods

- NetKAN/TheGoldStandard.netkan
> TheGoldStandard

- NetKAN/StructuralDisks.netkan
> StructuralDisks

- NetKAN/ToadicusTools.netkan
A bit out of date, but best to get it fixed.
> ToadicusTools install fix

- NetKAN/SpaceDock.netkan
Please include that file to get my new mod on ckan. Thank you very much.
> netkan file for SpaceDock mod

- NetKAN/RealisticRemodel1x.netkan
This PR is a bit older then #4847 but this was never merged.
Closes #4847
> Fix RealisticRemodel1x

- NetKAN/WheelsCollection.netkan
> wheelsCollection

- NetKAN/BKDBluekerbindynamicsMk1FuelTanksPlus.netkan
- NetKAN/BKDMk1FuelTanksPlus.netkan
> Blue kerbin dynamics Mk1 Fuel Tanks Plus

- NetKAN/QuickBrake.netkan
- NetKAN/QuickContracts.netkan
- NetKAN/QuickCursorHider.netkan
- NetKAN/QuickExit.netkan
- NetKAN/QuickFineControl.netkan
- NetKAN/QuickGoTo.netkan
- NetKAN/QuickHide.netkan
- NetKAN/QuickIVA.netkan
- NetKAN/QuickMute.netkan
- NetKAN/QuickRevert.netkan
- NetKAN/QuickSAS.netkan
- NetKAN/QuickSearch.netkan
- NetKAN/QuickStart.netkan
Hello, I've changed the default directory of all my QuickMods. I want to know if it will break some things on CKAN, thanks ;)
> update QuickMods with a new directory

- NetKAN/StageRecovery.netkan
StageRecovery 1.6.5 supports KSP 1.2.
> Update StageRecovery versions

- NetKAN/EstesParachutePack.netkan
- NetKAN/QuizTechAeroPackContinued.netkan
> Estes Parachute Pack

- NetKAN/AntaresCygnus.netkan
- NetKAN/KOSMOS-SSPP.netkan
- NetKAN/RN-MiscParts.netkan
- NetKAN/RN-SPP.netkan
- NetKAN/RN-SalyutStations.netkan
- NetKAN/RN-Skylab.netkan
- NetKAN/RN-SovietProbes.netkan
- NetKAN/RN-SovietRockets.netkan
- NetKAN/RN-SovietSpacecraft.netkan
- NetKAN/RN-USProbesPack.netkan
- NetKAN/RN-USRockets.netkan
- NetKAN/TextureReplacer.netkan
-no changes needed to mods, just updated version info
> RN update for ksp 1.2.1

- NetKAN/Landertron.frozen
- NetKAN/Landertron.netkan
Message sent to mod author on forums to allow opt-out.
closes #4863
> Add Landertron.frozen

- NetKAN/CVX.netkan
> Add Carrier Vessel eXpansion (CVX)

- NetKAN/BDArmoryContinued.netkan
> Extend compatibility for latest BDArmoryContinued

- NetKAN/ExtraPlanetaryLaunchpads.netkan
Extended KSP version as per forum thread.
KIS is now a dependency rather than a recommend, as per forum thread
> ExtraPlanetaryLaunchpads new release

- NetKAN/ModularFlightIntegrator.netkan
> ModularFlightIntegrator KSP Version widening

- NetKAN/KittopiaTech.netkan
Apparantly this wasn't updated yet.
Closes #4900
> KittopiaTech for 1.2

- NetKAN/HideEmptyTechNodes.netkan
Remove Module Manage dependency, as it is no longer needed (mod author here).
> Remove HideEmptyTechNodes.netkan dependency

- NetKAN/KerbalKrashSystem.netkan
I love this mod. So happy to see it for 1.2!
> KerbalKrashSystems update

- NetKAN/OPTSpacePlaneMain.netkan
- NetKAN/OPTSpacePlaneParts.netkan
Mod author requested change via Forum message.
> OPTSpacePlanes New release with legacy split

- NetKAN/BDynamicsMk22Cockpits.netkan
KSP compatibility to match forum thread.
Should enable #4496 to build
> BDynamics Mk22 Cockpit KSP version override

- NetKAN/GravityTurnContinued.netkan
Previous version was "V1.7.1", messing up the order.
> GravityTurnContinued epoch bump

- NetKAN/AsteroidDay.netkan
> Fix AsteroidDay 1.2 download location

- NetKAN/CameraTools.netkan
As advised in KSP-CKAN/CKAN-meta#1236
Heads-up to @jrodrigv, @Nerfclasher
> CameraTools to BDArmory (Continued) development team

- NetKAN/SearchAndRescue.netkan
Mod has been removed from Spacedock
> SearchAndRescue to Dropbox

- NetKAN/SurfaceExperimentPack.netkan
> Surface Experiment Package

- NetKAN/Scatterer-config.netkan
- NetKAN/Scatterer-sunflare.netkan
- NetKAN/Scatterer.netkan
To match forum thread
Closes #4940
> Scatterer ksp compatibility increase

- NetKAN/LLL-Extras.netkan
- NetKAN/LLL.netkan
There's a version 14 that's holding Max KSP at 1.0.5
> Add epoch to LLL and LLL-Extra

- NetKAN/AmpYearPowerManager.netkan
- NetKAN/DeepFreeze.netkan
- NetKAN/RSTKSPUtils.netkan
- NetKAN/TACLS.netkan
> Create RSTKSPUtils, set relevant filters and dependencies

- NetKAN/NoCrewRequirementContinued.netkan
- NetKAN/Overdrive.netkan
- Added Orbinaut to authors array as he is the initial creator
- Made mod KSP version independent as it relies on MM
- Added Module Manager to dependencies
- Added RadioFreeKerbin to recommended
> Update NoCrewRequirementContinued.netkan, create Overdrive.netkan

- NetKAN/CLLS.netkan
> Add CLLS metanetkan

- NetKAN/InFlightFlagSwitcher.netkan
> InFlightFlagSwitcher - new maintainer

- NetKAN/ZeroMiniAVC.netkan
Hello, I want to add my last mod to CKAN.
Thanks ;)
> add ZeroMiniAVC

- NetKAN/EngineLighting.netkan
As advised in Forum thread and Netkan status
> EngineLighting installation fix

- NetKAN/PartOverhauls.netkan
Also removed manually added download size and hash.
> Update for 1.2.x compatibility

- NetKAN/DMagicScienceAnimate.netkan
Updated after author confirmed it was 1.2.1
> DMagicScienceAnimate update for 1.2.1

- NetKAN/SimpleConstruction.netkan
> SimpleConstruction Add epoch

- NetKAN/LightsOut.netkan
> LightsOut add Force-V 

- NetKAN/IndicatorLightsCommunityExtensions.netkan
- Add additional supported mods
- Alphabetize `supports` list for consistency
> Update Indicator Lights Community Extensions

- NetKAN/RealTimeClock2.netkan
I'm the author of the mod
[](https://github.com/Li0n-0/Real-Time-Clock-2)
> Real Time Clock 2

- NetKAN/KerbalImprovedSaveSystem.netkan
Closes #4997
The old repo was deleted, so this is replacing the previous commit
> KerbalImprovedSaveSystem

- NetKAN/ELMKSDepartsing.netkan
> ELMKSDepartsing

- NetKAN/EnvironmentalVisualEnhancements-HR.netkan
- NetKAN/EnvironmentalVisualEnhancements.netkan
> Make EVE compatible with 1.2.2

- NetKAN/TextureReplacer.netkan
> TextureReplacer - KSP versioning fix

- NetKAN/RCSBuildAid.netkan
Matching version to forum thread details.
> RCSBuild - Add override for AVC limitation

- NetKAN/AntaresCygnus.netkan
- NetKAN/RN-MiscParts.netkan
- NetKAN/RN-SPP.netkan
- NetKAN/RN-SalyutStations.netkan
- NetKAN/RN-Skylab.netkan
- NetKAN/RN-SovietProbes.netkan
- NetKAN/RN-SovietRockets.netkan
- NetKAN/RN-SovietSpacecraft.netkan
- NetKAN/RN-USProbesPack.netkan
- NetKAN/RN-USRockets.netkan
- NetKAN/TextureReplacer.netkan
change compatible version since the mods all still work
> RN mod update for ksp 1.2.2

- NetKAN/ActiveAblation.netkan
> Active Ablation

- NetKAN/AnimatedDecouplers.netkan
> AnimatedDecouplers - Add override

- NetKAN/SDHI-ServiceModuleSystem.netkan
Also added a couple more suggested add-ons.
(Note: I nuked my fork because I was unable to reset it to upstream, and I was pressed for time.)
> Update SDHI SMS to v3.2.3

- NetKAN/DestructionEffects.netkan
> Updated per approval from author

- NetKAN/DecalStickers.netkan
> DecalStickers

- NetKAN/RFStockalike.netkan
OP also strongly recommends RealPlume since stock effects are broken in some cases, so that is reflected as well
> RF Stockalike provides RealPlume configs

- NetKAN/KSPInterstellarExtended.netkan
> KSPInterstellarExtended remove vref

- NetKAN/MK1StkOpenCockpit.netkan
> MK1StkOpenCockpit.netkan

- NetKAN/VesselView.netkan
Removed dependency on toolbar
Added suggestion for Janitors Closet
> Vessel Viewer updated

- NetKAN/KerbalHacksDroptankWrapper.netkan
> KerbalHacksDroptankWrapper.netkan

- NetKAN/EmDriveByBeale.netkan
> EM Drive By Beale

- NetKAN/KerbalHacksDroptankWrapper.netkan
> Specifying the install folder

- NetKAN/ExtendedInfoSciExp.netkan
- NetKAN/SimpleRefuel.netkan
Extended Science Info from Experiments
Simple Refuel
Both are offering earlier version upgrades dues to ordering issues.
> Epochs to fix version ordering

- NetKAN/BurnTogetherContinued.netkan
Closes #5075 
Submitted change of online .version file, hopefully we won't need overrides for future releases.
> Update KSP version of BurnTogetherContinued

- NetKAN/DSDMobileProcessingLabs.netkan
> DSD MobileLabs - Make abstract match contents

- NetKAN/Historian-expanded.netkan
> Historian-expanded - Add vref

- NetKAN/DiverseKerbalHeads.frozen
- NetKAN/DiverseKerbalHeads.netkan
> DiverseKerbalHeads new download location

- NetKAN/AnimatedStationScreens.netkan
> Forgot to put a spaaace!

- NetKAN/LessGrindyScience.netkan
> LessGrindyScience

- NetKAN/OctosatContinued.netkan
> Octosat Continued

- NetKAN/EVAHandrailsPackContinued.netkan
> File to Find

- NetKAN/NEBULADecalsContinued.netkan
Just trying to see why this isn't picking up the latest version.
> NEBULADecals testing

- NetKAN/DockingcameraKURSstyle.netkan
> Force-v on DockingcameraKURSstyle

- NetKAN/KerbalAircraftExpansion.netkan
> KerbalAircraftExpanstion update for 1.2.2 with authors permission

- NetKAN/AoATechnologies.netkan
Closes #5098 
Removed the ASET_Props dependency for now, author included it in the mod
ASET_Props is not available at all in CKAN, since kerbalstuff went down. 
If/when it is available again, I'll update this
Same issue with ASETAvionics
> AoATechnologies

- NetKAN/DockingcameraKURSstyle.netkan
Closes #5134 
(Hopefully for good this time)
> DockingCameraKURSstyle- Remove force-v, add epoch

- NetKAN/PolishFlagPack.netkan
Update PolishFlagPack metadata to 1.2.2,
as contents of the mod are pure binary files,
no other change is required
> Update PolishFlagPack to 1.2.2

- NetKAN/ModularFuelTanks.netkan
> Update ModularFuelTanks to v5.8.3 

- NetKAN/KerbalStats.netkan
Updated version, ksp version and download link
> Update for new version of Kerbalstats.

- NetKAN/StationScienceContinued.netkan
> Station Science Continued update

- NetKAN/StationScienceContinued.netkan
> Station Science Colntinued

- NetKAN/RSSExtrasolar.netkan
> Move RSSExtraSolar to Constellations Spacedock

- NetKAN/KerbinSideGAP.netkan
Dependencies changed to fit v1.2.2 CKAN realities :)
> Support KSP v1.2.2 in KerbinSideGAP

- NetKAN/ChopShop.netkan
> Added epoch of 1 to fix wrong 1.10.0.2 ordering

- NetKAN/AircraftCarrierAccessories.netkan
I;ve asked the author to add a version file
> Added version

- NetKAN/FlyingWingCargo.netkan
> FlyingWingCargo.netkan

- NetKAN/AutomatedAerialRefueling.netkan
> AutomatedAerialRefueling.netkan

- NetKAN/BallastNukSub.netkan
> BallastNukSub

- NetKAN/KASFrench.netkan
> KASFrenchTranslationPatch

- NetKAN/StockAntennaBalance.netkan
> StockAntennaBalance

- NetKAN/ASETProps-CE.netkan
Community fixes for ASET Props. Avionics will follow later.
> Add ASET Props Community Edition

- NetKAN/KSPInterstellarExtended.netkan
UniversalStorage is used for some optional parts
> Added UniversalStorage as recommendation

- NetKAN/PebkacSaturnV.netkan
> Pebkac Saturn V

- NetKAN/SVE-Scatterer-Config.netkan
- NetKAN/SVE-Sunflare.netkan
- Filename changed so change `asset_match` to match on anything with "scatterer" in it (case-insensitively)
- Remove duplicate `abstract` properties
Should close #5228
> Update SVE Scatterer Config and Sunflare

- NetKAN/BluedogDB.netkan
Added following as a dependency:
CommunityResourcePack
Added following as supported:
HullcamVDSContinued
KIS
CommunityTechTree
RealChute
USI-LS
> Bluedog Design Bureau change in dependency and supported info

- NetKAN/VenStockRevamp.netkan
AVC version information for newest release is wrong.
> Update Ven Stock Revamp

- NetKAN/Astrogator.netkan
Index new Astrogator mod, essentially a transfer window calculator plus a few conveniences.
> Add entry for Astrogator

- NetKAN/KerbalHealth.netkan
Mod info: [http://forum.kerbalspaceprogram.com/index.php?/topic/155313-wip-122-kerbalhealth-044-2017-02-01-even-more-health-factors/](http://forum.kerbalspaceprogram.com/index.php?/topic/155313-wip-122-kerbalhealth-044-2017-02-01-even-more-health-factors/)
> Add Kerbal Health mod

- NetKAN/GTIndustries.netkan
> GT Industries

- NetKAN/SVT-MacLinux.netkan
- NetKAN/SVT-Windows.netkan
> Updated files for SVT

- NetKAN/ScienceSituationInfo.netkan
- NetKAN/StockAntennaBalance.netkan
Updated for spacedoc, and 1.2.2 (as mentioned in the thread)
> Science Situation Info

- NetKAN/GroundConstruction-Core.netkan
Can't see anything wrong with the netkan, so this is a minimal change to engage Jenkins' testing
ref #5289
> Attempt to fix GroundConstruction-Core

- NetKAN/USIKolClassSuits.netkan
> USIKolClassSuits

- NetKAN/ReworkedStockSystem.netkan
> Reworked Stock System

- NetKAN/TacFuelBalancer.netkan
> TACFuelBalancer - add Force-v

- NetKAN/NetherdyneMassDriver.netkan
> NetherdyneMassDriver

- NetKAN/FuturisticEngines.netkan
> FuturisticEngines

- NetKAN/NewTantares.netkan
- NetKAN/NewTantaresLV.netkan
> Add NewTantares and NewTantaresLV

- NetKAN/SpecialMissionProjects.netkan
> SpecialMissionProjects

- NetKAN/ExtraPlanetaryLaunchpads.netkan
> Update Extraplanetary Launchpad to 5.7.1

- NetKAN/AirlineKuisine.netkan
> AirlineKuisine

- NetKAN/SSRSS-Cont.netkan
- NetKAN/SSRSS_Cont.netkan
> SSRSS Cont

- NetKAN/OuterPlanetsMod.netkan
Should enable #5354 to pass checks
> Outer Planets extend to 1.2.2

- NetKAN/OPTSpacePlaneParts.netkan
> OPTSpacePlaneParts Epoch Bump

- NetKAN/PoliticalMapMilitaryTexture.netkan
There are times when I wish we had usage statistics per mod. No idea if anyone is actually using these.
> Netkan failing. No author contact

- NetKAN/UpgradesUIextensions.netkan
Collection of user interface tweaks aimed at making the part/module upgrades feature introduced in 1.2 a bit less painful to use for the player
forum post here :
http://forum.kerbalspaceprogram.com/index.php?/topic/158081-122-upgradesuiextensions-v10-qol-vabsph-tweaks-for-part-upgrades/
> Add Upgrades UI extensions plugin

- NetKAN/FASA.netkan
-Update FASA for 1.2.2 under new team management.
> RN FASA update

- NetKAN/TransferWindowPlanner.netkan
> TransferWindowPlanner URL fix

- NetKAN/CommNetConstellation.netkan
> CommNetConstellation

- NetKAN/FMRSContinued.netkan
Added dependency on RecoveryController
> FMRSContinued

- NetKAN/EVAEnhancementsContinued.netkan
> EVAEnhancements udpate

- NetKAN/BDArmoryContinued.netkan
Added an epoch
Updated version number
> BDArmoryContinued update

- NetKAN/VentralDrill.netkan
> VentralDrill

- NetKAN/newReactionWheels.netkan
> newReactionWheels

- NetKAN/UpgradesUIextensions.netkan
> Updated abstract

- NetKAN/SVE-HighResolution.netkan
- NetKAN/SVE-LowResolution.netkan
- NetKAN/SVE-MediumResolution.netkan
- NetKAN/StockVisualEnhancements.frozen
- NetKAN/StockVisualEnhancements.netkan
I hope that setting a conflict on a version range works. Don't know whether this PR will test properly.
> SVE Change of packaging again

- NetKAN/KerbalFlightData.netkan
The current R22 release is for 1.2, not 1.1.
> * NetKAN/KerbalFlightData.netkan: Update ksp_version

- NetKAN/EnvironmentalVisualEnhancements-HR.netkan
- NetKAN/EnvironmentalVisualEnhancements.netkan
> EnvironmentalVisualEnhancements zip renames 

- NetKAN/ProceduralFairings-ForEverything.netkan
the v0.2.0 release has been unchanged since KSP 1.0.x and has
been getting playtested on 1.2.x
> Allow PF4E on KSP 1.2.x

- NetKAN/KISFrenchTranslationPatch.netkan
> Add KISFrenchTranslationPatch

- NetKAN/StationKeeping.netkan
> Add StationKeeping

- NetKAN/PartOverhauls.netkan
Point to the file in the Internet Archive
> PartOverhauls - new link

- NetKAN/KSPScienceRedone.netkan
> Add KSPScienceRedone

- NetKAN/CargoFreighter.netkan
> Fixed CargoFreighter dependency

- NetKAN/SpaceLink.netkan
Mod that redirects the Addons & Mods Link in the main menu to SpaceDock.
> Add SpaceLink

- NetKAN/ProceduralParts.netkan
there's a new 1.2.9 release for KSP 1.2.2
> starwaster has taken over ProceduralParts

- NetKAN/ForScience.netkan
> For Science switch to automated discovery 

- NetKAN/HalfRSS-Textures2048.netkan
- NetKAN/HalfRSS-Textures4096.netkan
- NetKAN/HalfRSS-Textures8192.netkan
- NetKAN/HalfRSS.netkan
**HalfRSS**
* Reformat file
* `asset_match` new zip name
* Remove ksp version
**Textures**
* Reformat files
* `asset_match` new zip names
* Increase max ksp version of textures
> Fix HalfRSS

- NetKAN/QuarterRSS-Textures2048.netkan
- NetKAN/QuarterRSS-Textures4096.netkan
- NetKAN/QuarterRSS-Textures8192.netkan
- NetKAN/QuarterRSS.netkan
Same structure as `HalfRSS` but now quarter size.
Closes #5475
> Add QuarterRSS

- NetKAN/BDArmoryContinued.netkan
- NetKAN/PhysicsRangeExtender.netkan
Waiting on author ok to list.
Closes #5469
> Add PhysicsRangeExtender

- NetKAN/KSPChromaControl.netkan
- NetKAN/LudicrousPropulsionSystems.netkan
Author posted on CKAN thread asking for this mod to be added.
Waiting on mod author to publish a full release on GitHub before this will test.
> Add Ludicrous Propulsion Systems

- NetKAN/PhoenixIndustriesEVASuit.netkan
> Add PhoenixIndustriesEVASuit

- NetKAN/BluedogDB.netkan
> BluedogDB set Force-V

- NetKAN/ShipManifest.netkan
[Requested by mod author on the forums](http://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1221-georgy/&do=findComment&comment=3064806)
> Move ShipManifest to GitHub

- NetKAN/SpearofLonginus.netkan
I have a feeling that force-v may be a good idea.
> Set SpearofLonginus homepage to forum thread and add force-v

- NetKAN/AviationLights.netkan
Latest release of Aviation Lights is for 1.3
> AviationLights for 1.3

- NetKAN/SpearofLonginus.netkan
My local Netkan repo was messed up and thought this change had already gone in.
> Set SpearofLonginus homepage to GitHub

- NetKAN/XKOM.netkan
Merge after https://github.com/KSP-CKAN/CKAN-meta/pull/1264
> Cleanup: Last one

- NetKAN/KerbinSide.netkan
- NetKAN/KerbinSideAirRace.netkan
- NetKAN/KerbinSideCore.netkan
- NetKAN/KerbinSideGroundControl.netkan
- NetKAN/KerbinSideKSC2.netkan
- NetKAN/KerbinSideKampus.netkan
- NetKAN/KerbinSideSkyways.netkan
> KerbinSide clean up & Air Race separation

- NetKAN/EnvironmentalVisualEnhancements-HR.netkan
- NetKAN/EnvironmentalVisualEnhancements.netkan
> EVE Compatibility max to 1.3.0 

- NetKAN/Mk2Expansion.netkan
- NetKAN/ShuttleLiftingBodyCormorantAeronology.netkan
> Mk2Expansion - up epoch

- NetKAN/Asclepius.netkan
- NetKAN/Kronkus.netkan
New 1.3 releases for Asclepius and Kronkus
> Asclepius & Kronkus update

- NetKAN/VesselMoverContinued.netkan
This time create a branch for a change
> VesselMoverContinued add ksp version

- NetKAN/BackgroundResources.netkan
- NetKAN/TACLS.netkan
> TACLS + BackgroundResources

- NetKAN/ExtraPlanetaryLaunchpads.netkan
> EPL  5.8.0 NetKAN update

- NetKAN/BurnTogetherContinued.netkan
- NetKAN/VesselMoverContinued.netkan
Remove ksp version
Override ksp version
Remove a duplicate `name`
> Update BurnTogether and VesselMover

- NetKAN/TWR1.netkan
Just changed the ksp version to 1.3, other changes are reformatting the file
> Update TWR to 1.3

- NetKAN/MaerdaCorpPack.netkan
Reopening #5534 by author request (@Warsoul112)
> Because i was missclicked in SpaceDock. but now i'm ready i think.
Closes #5580
> Add MaerdaCorp

- NetKAN/GravityTurnContinued.netkan
> Updated for 1.3

- NetKAN/VenStockRevamp.netkan
> Updated to fix badk push by @todi

- NetKAN/FwiffoRaredenSkybox.netkan
> Redo to fix bad commit b @todi

- NetKAN/PersistentRotation.netkan
> PersistentRotation override for 1.8.4 

- NetKAN/SmartStage.netkan
> Smartstage

- NetKAN/SETI-CareerChallenge.netkan
With self-administered netkan file as usual.
Best regards,
Yemo
> Another small SETI mod

- NetKAN/PartOverhaulsSETI.netkan
Self administered netkan file as usual.
Thank you very much!
Yemo
> And the next SETI administered mod

- NetKAN/SETI-MetaModPack.netkan
Self-administered netkan file as usual.
Thank you and best regards,
Yemo
> Final SETI addition to CKAN for the current project

- NetKAN/AntaresCygnus.netkan
- NetKAN/FASA.netkan
- NetKAN/RN-MiscParts.netkan
- NetKAN/RN-SPP.netkan
- NetKAN/RN-SalyutStations.netkan
- NetKAN/RN-Skylab.netkan
- NetKAN/RN-SovietProbes.netkan
- NetKAN/RN-SovietRockets.netkan
- NetKAN/RN-SovietSpacecraft.netkan
- NetKAN/RN-USProbesPack.netkan
- NetKAN/RN-USRockets.netkan
-Update mods for ksp 1.3 compatibility
> RN update mods for ksp 1.3

- NetKAN/CryoTanks.netkan
- NetKAN/DynamicBatteryStorage.netkan
- NetKAN/NearFutureElectrical.netkan
Permanent fix for KSP-CKAN/CKAN-meta#1280
> Add dynamic battery storage and fix metadata for dependent mods

- NetKAN/DynamicBatteryStorage.netkan
> DynamicBatteryStorage to Spacedock kref

- NetKAN/64k-overhaul.netkan
@Kerbinorbiter, does this look ok?
Closes #5566
> Add 64k-overhaul

- NetKAN/OSEWorkShopCont.netkan
> OSE Workshop Continued

- NetKAN/MeterStick.netkan
> Meterstick

- NetKAN/ASupremePartsMod.netkan
> A_Supreme_Parts_Mod

- NetKAN/RealisticHeatMgmt.netkan
> Realistic Heat Management

- NetKAN/ExplodiumBreathingEngines.netkan
> Explodium Breathing Engines

- NetKAN/AirlockPlus.netkan
- NetKAN/CommunityTraitIcons.netkan
- NetKAN/PortraitStats.netkan
To facilitate release of next version of PortraitStats, which will require this as a dependency.
> Add Community Trait Icons

- NetKAN/FixSeatEject.netkan
> FixSeatEject

- NetKAN/NavUtilitiesContinued.netkan
> Nav Utilities Continued

- NetKAN/RoverScienceCont.netkan
> Rover Science Continued

- NetKAN/BDAnimationModules.netkan
- NetKAN/ReflectionPlugin.frozen
- NetKAN/ReflectionPlugin.netkan
-remove ksp avc required from bdanim
-update reflection plugin for ksp 1.2.2: license of original is public
domain
> RN fix bdanim and update reflection plugin

- NetKAN/Trajectories.netkan
http://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1223-mahia/&do=findComment&comment=3132734
> Add Vref to Trajectories

- NetKAN/Trajectories.netkan
> Trajectories Force-V

- NetKAN/MusicMuteContinued.netkan
Also updated the spec version to v1.16 because of `ksp_version_strict` and added repository URL.
> Update MusicMuteContinued supported KSP versions

- NetKAN/NMSG.netkan
Resolves https://github.com/KSP-CKAN/CKAN-meta/pull/1281
> Resolve CKAN-meta#1281

- NetKAN/PartOverhauls.netkan
Tested compatible with KSP versions 1.1-1.3.
> Update for PartOverhauls version compatibility

- NetKAN/ResearchBodies.netkan
> Update ResearchBodies installation

- NetKAN/NearFutureSpacecraft.netkan
> Near Future Spacecraft add B9Part Switch dependency

- NetKAN/KerbalFlightData.netkan
- NetKAN/KerbalFlightIndicators.netkan
Update ksp_version of my mods to 1.3 to conform to my latest github release.
> KSP version update for DaMichels mods.

- NetKAN/KerBalloons.netkan
> KerBalloons Installation fix

- NetKAN/EarnYourStripes.netkan
See demo of the mod here:  https://www.youtube.com/watch?v=DGyRyLtEYmk
> Add 'Earn Your Stripes' from GitHub source

- NetKAN/KSPInterstellarExtended.netkan
> Update KSPI-Extended forum link

- NetKAN/REKT.netkan
> REKT update $kref, install and dependencies

- NetKAN/BDArmoryWeaponsExtension.netkan
> BDArmoryWeaponsExtension add Epoch

- NetKAN/StreamlineEnginesRCSsandfueltanks.netkan
> Streamline - Engines, RCSs and fueltanks

- NetKAN/LanderCanMk12.netkan
> LanderCanMk12

- NetKAN/VesselCategorizer.netkan
> VesselCategorizer

- NetKAN/AnalogControlContinued.netkan
> AnalogControlContinued KSP version fix

- NetKAN/KerbalLaunchVehicles.netkan
I attempted a pull request a few days ago for this, but being a complete GitHub rookie, I believe it never went through. Apologies if this is a duplicate!
Basic install - KerbalLaunchVehicles folder into GameData
> Add mod KerbalLaunchVehicles

- NetKAN/BackInBlack.netkan
> Back in Black

- NetKAN/SimpleRapierPatch.netkan
> Simple Rapier Patch

- NetKAN/DrillActionFix.netkan
> Drill Action Fix

- NetKAN/BackInBlackTexturePack.netkan
> Back In Black Texture Pack

- NetKAN/RealisticAscension.netkan
> Realistic Ascension

- NetKAN/UselessRearrangement.netkan
> UselessRearrangement

- NetKAN/ComfortableLanding.netkan
> ComfortableLanding

- NetKAN/Kerbalized-SpaceX.netkan
This SpaceX parts mod includes the latest BFR craft.
Author's permission to add: https://forum.kerbalspaceprogram.com/index.php?/topic/162949-kerbalized-spacex-command-podbfr-editionwip/&do=findComment&comment=3184716
> Add harrisjosh2711's SpaceX mod

- NetKAN/ISRUThanksButNoTanks.netkan
This mod includes the name of the Git branch in the directory in the download.
Current [status page](http://status.ksp-ckan.org/) error: "Could not find ISRUThanksButNoTanks entry in zipfile to install"
Example file:
```
Length      Date    Time    Name
---------  ---------- -----   ----
621  2017-09-08 21:59   GameData/ISRUThanksButNoTanks-master/ISRUThanksButNoTanks.cfg
```
> Match branch name with regexp

- NetKAN/KSPFrenchTranslation.netkan
Latest download of this mod changed the ordering of the words in the directory name.
> Update folder path

- NetKAN/KerbalXMod.netkan
- NetKAN/PartMapper.netkan
> Add new KerbalXMod 

- NetKAN/Scatterer-config.netkan
- NetKAN/Scatterer-sunflare.netkan
- NetKAN/Scatterer.netkan
Should allow #5929 to pass Jenkins
> Match Scatterer compatility to Forum thread

- NetKAN/EnvironmentalVisualEnhancements-HR.netkan
- NetKAN/EnvironmentalVisualEnhancements.netkan
Forum Thread says 1.3, so bumping max version to 1.3.9
> Match EVE compatility to Forum thread

- NetKAN/GenericInlineCockpits.netkan
> Unfreeze GenericInlineCockpits 

- NetKAN/EarnYourStripes.netkan
- NetKAN/KesslerSyndrome.netkan
- NetKAN/PAWS.netkan
I've been a bit lax getting my mods onto the CKAN - so thought I'd correct it. Also the license you had for EarnYourStripes was incorrect it's actually MIT.
> Add Kessler Syndrome and PAWS - correct license for EarnYourStripes

- NetKAN/ModularPods.netkan
Adding dependency to newly created prop asset split from this mod.
> Adding a dependency

- NetKAN/TextureReplacerReplaced.netkan
Tired of not having this in CKAN!!
_I am not the author of this mod, I have linked to the author's page in the entry, however_
> Adds TextureReplacedReplaced

- NetKAN/ExceptionDetector.netkan
I put it through JSONLint. I also made it so:
version 1 supports 1.0-1.0.5
2 supports 1.1-1.1.3
3 supports 1.3+
> Exception detector version overrides

- NetKAN/DoubleDouble.netkan
- NetKAN/OptionalAtm.netkan
- NetKAN/SamBelangerFlags.netkan
> Add DoubleDouble and SamBelangerFlags

- NetKAN/Spectra.netkan
woops, didn't notice I got the WindowShine identifier wrong
> fixes Spectra reccomendation

- NetKAN/TDProps.netkan
Folder name in recent release has included version number
> Fix TDProps installation

- NetKAN/ScienceRevisitedRevisited.netkan
Latest release puts GameData into a subfolder, otherwise format is the same
> Switch ScienceRevisitedRevisited to use find

- NetKAN/TexturesUnlimited.netkan
This is today's "StarMod". #6046 currently includes a bundled copy, so we should probably resolve this one before that gets merged.
Permission from author:
- https://forum.kerbalspaceprogram.com/index.php?/topic/167450-131-textures-unlimited-pbr-shader-texture-and-model-api-11-11-17/&do=findComment&comment=3224004
@shadowmage45, this isn't going to index anything yet because CKAN skips GitHub pre-releases. Do you anticipate a long testing period before a full release?
> Add Textures Unlimited

- NetKAN/MoneroFlags.netkan
> Add MoneroFlags

- NetKAN/FilterExtensionsDefaultConfig.netkan
> New maintainer for FE

- NetKAN/SearchAndRescue.netkan
This mod is hosted on DropBox and thus the metadata is manually maintained.
https://forum.kerbalspaceprogram.com/index.php?/topic/144548-search-and-rescue/&do=findComment&comment=3230311
Changes:
- New download URL, version number, and KSP version
- License updated according to License.txt in the download
- Added dependencies based on Instructions.txt in the download
> SearchAndReplace v11
