NetKAN/AMEG.netkan
NetKAN/AVeryKerbalChristmas.netkan
NetKAN/AlcubierreStandalone.netkan

Added Homepages for AMEG, AlcubierreStandalone and AVeryKerbalChristmas

Added Homepages for three mods

---

NetKAN/ToadicusTools.netkan

Revised the license and formatting because KerbalStuff doesn't recognize the different BSDs and I'm OCD or something.

ToadicusTools: Revised license.

---

NetKAN/AlternateResourcePanel.netkan
NetKAN/KSPTips.netkan
NetKAN/KerbalAlarmClock.netkan
NetKAN/TransferWindowPlanner.netkan

Should fix KSP-CKAN/CKAN-support#50 , KSP-CKAN/CKAN-support#51 and some remarks on the forums.

Remove suggestion stanzas for TriggerAu-Flags

---

NetKAN/RoutineMissionManager.netkan

would like to update the netkan file for my mod Routine Mission Manager
file tested with ckan.exe and netkan.exe utilities.

update to RoutineMissionManager netkan file

---

NetKAN/ActiveTextureManagement-x64-Aggressive.netkan
NetKAN/ActiveTextureManagement-x64-Basic.netkan
NetKAN/ActiveTextureManagement-x86-Aggressive.netkan
NetKAN/ActiveTextureManagement-x86-Basic.netkan

This requires https://github.com/KSP-CKAN/CKAN-netkan/pull/30 (asset_name regexp in github releases) to be merged.

Netkans for all four different kinds of ATM

---

NetKAN/ContractConfigurator-RemoteTech.netkan

Added ContractConfigurator-RemoteTech.netkan

---

NetKAN/WernherChecker.netkan

Added WernherChecker on request of author

---

NetKAN/ProceduralAirships.netkan

Install missing Ships and Tutorial Saves of ProceduralAirships

---

NetKAN/PlaneMode.netkan

Adds [Plane Mode](https://kerbalstuff.com/mod/493/Plane%20Mode) to NetKAN. Didn't see the Kerbal Stuff bot add it, so making pull request myself.

Add PlaneMode

---

NetKAN/KerbalMechanics.netkan

Added KerbalMechanics on author request

---

NetKAN/CC-CP-SCANSat.netkan

New contract pack for Contract Configurator.

Add CC-CP-SCANSat to CKAN

---

NetKAN/ThrottleControlledAvionics.netkan

The suffix "Continued" is not a part of the mod's title.
Removed stray commas.

Added handmade metadata for the Throttle Controlled Avionics instead of the one made by KerbalStuffBot.

---

NetKAN/B9AerospaceProceduralParts.netkan

tested :smiley: 
closes #550  :airplane:

Added B9 Procedural Wings

---

NetKAN/QuickMute.netkan

As per request of the author, https://github.com/KSP-CKAN/CKAN-meta/issues/281

Added QuickMute to CKAN

---

NetKAN/TACLS.netkan

Resubmitted #597
Is that better?

Filled in more fields of the TACLS netkan file.

---

NetKAN/AdvancedJetEngine.netkan

it did install in Gamedata/AJE/AJE, now fixed

fixed AJE install dir

---

NetKAN/ExceptionDetector.netkan

A little silly mod to hunt down errors in other mods.

Add ExceptionDetector

---

NetKAN/QuickIVA.netkan

closes #651 
What bot can not, I will do :wink:

Added QuickIVA

---

NetKAN/CommandPodRebalance.netkan

CommandPodRebalance

---

NetKAN/FerramAerospaceResearch.netkan

Can anyone tell me why this was added in the first place? It seems to mostly end up with people installing it for no good reason....

Remove KIDS suggestion

---

NetKAN/AdjustableLandingGear.netkan

Adjustable Landing Gear works for 0.90

---

NetKAN/EnduranceSpaceExplorationSystem.netkan

Adds Endurance.

---

NetKAN/KSPSerialIOMacLinuxWin.netkan
NetKAN/SerialIO.netkan

Adds SerialIO multiplatform

---

NetKAN/ADIOS.netkan

(needed dependency on TechManager)

Fixes ADIOS' metadata

---

NetKAN/ODFC.netkan
NetKAN/OkramSA.netkan
NetKAN/SatBatts.netkan

Hopefully fixed a conflict between my two mods installing similar files.  Tested in my fork of the CKAN-meta repo.

Fixing mod conflicts, and some cleanup

---

NetKAN/AdvancedJetEngine.netkan

hopefully the final fix for AJE

---

NetKAN/TantaresLV.netkan

Add Tantares LV from Kerbal Stuff

add-TantaresLV

---

NetKAN/FARNEARusabilityPackage.netkan

closes #748 
I'm not sure about MiniAVC plug-in, should I filter this? I don't think so because is intended to be bundled with mods so I left this..

Added FAR/NEAR usability Package

---

NetKAN/RP-0.netkan

Added VSR to recommends list to match RP-0 forum post

Added Ven's Stock Revamp to RP-0 recommends list

---

dockingtube.netkan

Adds dockingtube

---

NetKAN/AAResourceTanks.netkan

Adds AAResourceTanks

---

NetKAN/MunarSurfaceExperimentPack.netkan

Adds MunarSurfaceExperimentPackage

---

NetKAN/TweakScale.netkan

As per #821, TweakScale has a new maintainer, and a new repo location.  This commit indexes that.
Attn @pellinor0, to check that everything here looks good.
Installed mod information (while it's not shown, v1.52 is taggedas being for KSP 0.90):
```
$ ckan.exe show TweakScale
TweakScale - Rescale Everything!: TweakScale lets you change the size of a part. Not just that, but it will figure out how much fuel is in the resized part. And if it's an engine, it will become more powerful by scaling it bigger, or weaker by scaling it smaller.
Module info:
- version:	v1.52
- authors:	Biotronic, pellinor
- status:	stable
- license:	WTFPL
Depends:
- ModuleManager, min:
Provides:
- TweakScale
Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/112693
- kerbalstuff: …
```

Update TweakScale to new repo by pellinor0.

---

NetKAN/B9StyleShuttleWings.netkan

Fixing the first part of https://github.com/KSP-CKAN/CKAN-support/issues/87

Adding dependency

---

NetKAN/OTHOABsTankMergerforProceduralParts.netkan

for ProceduralParts
It comes from OTHOABs procedural part textures but in fact it can be
used as independent mod

OTHOABs TankMerger config

---

NetKAN/OTHOABsTexturesForProcedualParts.netkan

It was installing in wrong directory

Fixed OTHOAB's Textures For Procedual Parts

---

NetKAN/ContractConfigurator-Banking.netkan

Clashes with #847 and makes it obsolete, is there a better way for me to do this?

Add bankingcontracts

---

NetKAN/ContractsWindowPlus.netkan

Removed spaces from installation folder

Fix install location

---

NetKAN/MapResourceOverlay.netkan

Wrong bug tracker link.. :wink:

Please don't raise MapResourceOverlay bugs against Contract Configurator

---

NetKAN/ContractConfigurator-KerbinSpaceStation.netkan

As requested here https://github.com/KSP-CKAN/NetKAN/issues/860

Add ContractPack for Kerbin Space Station

---

NetKAN/CivilianPopulation.netkan

A user came onto the irc-channel saying this mod didn't seem to install properly. This patch fixes the problem locally for me so let's hope Jenkins approves aswell.

Patch CivilianPopulation with dependencies and filters

---

NetKAN/ContractConfigurator-UnmannedContracts.netkan

Added back dependcy for spacetux

Added dependcy for spacetux agency

---

NetKAN/ContractConfigurator-AdvancedProgression.netkan
NetKAN/ContractConfigurator-Banking.netkan
NetKAN/ContractConfigurator-InitialContracts.netkan

With permission from the various authors ([see here](http://forum.kerbalspaceprogram.com/threads/113855-Contract-Configurator-Contract-Pack-Naming)).

Rename contract packs to sort together.

---

NetKAN/RealismOverhaul.netkan

Doing a reorganization of the RO repo, so things will be in different folders.

Update RealismOverhaul in prep for next RO release

---

NetKAN/NearFutureElectrical.netkan
NetKAN/NearFuturePropulsion.netkan

Permission from mod author [here](http://forum.kerbalspaceprogram.com/threads/52042-0-90-0-25-Near-Future-Technologies-%28NFPropulsion-0-90%29?p=1807385&viewfull=1#post1807385)

Adding 0.90 support for NFE and suggest LH2 NTRs for NFP

---

NetKAN/RealFuels.netkan

This PR makes it index friendly again.

RealFuels no longer has a TweakScale directory in the zip

---

NetKAN/Impact.netkan

Please can you add my mod to CKAN

Add impact mod

---

NetKAN/Workshop.netkan

closes #926
Thanks to @obivandamme for writing netkan. Always nice to see mod author contributing to CKAN by itself :+1:

Added OSE Workshop

---

NetKAN/ContractConfigurator-Round8.netkan

Contract Pack for the ROUND-8.

---

NetKAN/RoadToKosmosCore.netkan

Added manually a  NetKAN for my RtK core files mod

RoadToKosmos-core Support

---

NetKAN/MoarEggs.netkan

Such Egg, many easter, very festive, WOW
supercedes https://github.com/KSP-CKAN/NetKAN/pull/907

Add MoarEggs.netkan

---

NetKAN/FTLDrive.netkan

Add FTLDrive.netkan

---

NetKAN/ShipEffects.netkan

Add ShipEffects.netkan

---

NetKAN/JasperAerospaceTechnologies.netkan

Add JasperAerospaceTechnologies.netkan

---

NetKAN/RecoverAll.netkan

Add RecoverAll.netkan

---

NetKAN/OMSKSpaceProducts.netkan

Add OMSKSpaceProducts.netkan

---

NetKAN/BurnTogether.netkan

Add BurnTogether.netkan

---

NetKAN/MoonRocketfromTinTin.netkan

This mod made me happy
Supercedes #909

Add MoonRocketfromTinTin.netkan

---

NetKAN/QuickGoTo.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/858

Add QuickGoTo.netkan

---

NetKAN/MK2CockpitExpansion.netkan

Add MK2CockpitExpansion.netkan

---

NetKAN/SETI-Greenhouse.netkan

Supercedes https://github.com/KSP-CKAN/NetKAN/pull/887
Hopefully this won't mess with https://github.com/KSP-CKAN/CKAN-meta/pull/361 or I'll hate myself now :smiling_imp:

Add SETI-Greenhouse.netkan

---

NetKAN/NetherdyneRnD.netkan

Add NetherdyneRnD.netkan

---

NetKAN/Scatterer.netkan

Add Scatterer.netkan

---

NetKAN/Targetron.netkan

Add Targetron.netkan

---

NetKAN/KerboKatzSmallUtilities.netkan

Add KerbotKatzSmallUtilities.netkan

---

NetKAN/Mk1CargoBay.txt

closes https://github.com/KSP-CKAN/NetKAN/pull/981

Add Mk1CargoBay.netkan

---

NetKAN/B9AerospaceProceduralParts.netkan

@BasharMilesTeg informed me that this mod no longer depends on KSPAPIExtensions.dll

B9Procedural unneeded dependency

---

NetKAN/IR-Model-Rework-Core.netkan
NetKAN/IR-Model-Rework-Expansion.netkan
NetKAN/InfernalRobotics.netkan

Jenkins allowed these through the first time, now I wonder how that happened.

Patching a brainfart in IR

---

build.sh
t/inflate.t
t/lib/Test/NetKAN.pm

And if my jenkins changes have stuck, this should run and pass. :)

CI/Jenkins: Run prove tests before anything else.

---

NetKAN/InfernalRobotics-Sequencer.netkan

How many IR-Seg PRs can we collect?

---

NetKAN/EvePlus.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/912

Add EvePlus.netkan

---

NetKAN/DunaPlus.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/920

Add DunaPlus.netkan

---

NetKAN/Insystem.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/839

Add Insystem.netkan

---

NetKAN/KerbolPlus.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/796

Add KerbolPlus.netkan

---

NetKAN/TundraExploration.netkan

Add TundraExploration.netkan

---

NetKAN/ProceduralParts-Extended.netkan

Add ProceduralParts-Extended.netkan

---

NetKAN/InterstellarAdventure.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/893

Add InterstellarAdventure.netkan

---

NetKAN/ContractConfigurator-SpriteMissions.netkan

Shjould work :-)
Copied another which does

Initial release

---

NetKAN/IR-Model-Rework-Core.netkan
NetKAN/IR-Model-Rework-Expansion.netkan

One of these days these files will be perfect and never have to be touched again.

Remove hardcoded version field from IR model rw

---

NetKAN/ChopShop.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/1005
notifying @doktorjet

Add ChopShop.netkan

---

NetKAN/BaconLabs.netkan

Add BaconLabs.netkan

---

NetKAN/AMEG.netkan
NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids.netkan
NetKAN/EnvironmentalVisualEnhancements-HR.netkan
NetKAN/EnvironmentalVisualEnhancements-LR.netkan
NetKAN/EnvironmentalVisualEnhancements.netkan
NetKAN/Firespitter.netkan
NetKAN/KDEX.netkan
NetKAN/KWRocketry.netkan
NetKAN/KerbalFoundries.netkan
NetKAN/LandingHeight.netkan
NetKAN/MOVAP.netkan
NetKAN/ModularRocketSystem.netkan
NetKAN/NavHud.netkan
NetKAN/PartMapper.netkan
NetKAN/Proton-Bobcat.netkan
NetKAN/RasterPropMonitor-Core.netkan
NetKAN/RealRoster.netkan
NetKAN/SovietEngines.netkan
NetKAN/SpaceY-Lifters.netkan
NetKAN/StripSymmetry.netkan
NetKAN/Tantares.netkan
NetKAN/TantaresLV.netkan
NetKAN/Targetron.netkan
NetKAN/TransferWindowPlanner.netkan
NetKAN/ZeroPointInlineFairings-Lite.netkan
NetKAN/ZeroPointInlineFairings.netkan
NetKAN/kribubble.netkan
NetKAN/krispeeder1.netkan

Don't merge until discussed in https://github.com/KSP-CKAN/NetKAN/issues/1002
After a potential merge, update the list of hardcoded mods in the above discussion.

Add ksp_version_max field to mods which lack it

---

NetKAN/TransferWindowPlanner.netkan

Revert "Add vref to TransferWindowPlanner.netkan"

---

NetKAN/AMEG.netkan
NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids.netkan
NetKAN/EnvironmentalVisualEnhancements-HR.netkan
NetKAN/EnvironmentalVisualEnhancements-LR.netkan
NetKAN/EnvironmentalVisualEnhancements.netkan
NetKAN/Firespitter.netkan
NetKAN/KDEX.netkan
NetKAN/KWRocketry.netkan
NetKAN/KerbalFoundries.netkan
NetKAN/LandingHeight.netkan
NetKAN/MOVAP.netkan
NetKAN/ModularRocketSystem.netkan
NetKAN/NavHud.netkan
NetKAN/PartMapper.netkan
NetKAN/Proton-Bobcat.netkan
NetKAN/RasterPropMonitor-Core.netkan
NetKAN/RealRoster.netkan
NetKAN/SovietEngines.netkan
NetKAN/SpaceY-Lifters.netkan
NetKAN/StripSymmetry.netkan
NetKAN/Targetron.netkan
NetKAN/TransferWindowPlanner.netkan
NetKAN/ZeroPointInlineFairings-Lite.netkan
NetKAN/ZeroPointInlineFairings.netkan
NetKAN/kribubble.netkan
NetKAN/krispeeder1.netkan

Reverts KSP-CKAN/NetKAN#1003
This was a way to sweeping change. Reseting it back and taking another look.

Revert "Add ksp_version_max field to mods which lack it"

---

NetKAN/KerbalFoundries.netkan
NetKAN/RealRoster.netkan

Both of these had some small problems which this PR fixes.

Fix KerbalFoundries and RealRoster metadata

---

NetKAN/PilotAssistant.netkan

Hoping this works, some .version files seem less worky than others. If worst comes to worse I'll change to a hardcoded 1.0.

Remove hardcoded version from pilot assistant, add avc

---

NetKAN/IFILS.netkan

To match the github release now saying 1.0 compatible.

Update IFILS to 1.0

---

NetKAN/MissionController2.netkan

mod no longer has dependencies

removed deprecated dependencies to missioncontroller2, updated license

---

NetKAN/SmartStage.netkan

Hoping ksp-avc will work, else I'll hardcode it.

Fix version for SmartStage

---

NetKAN/StageRecovery.netkan

mod has updated, removed hardcoded version number as its on kerbalstuff

update Stage recovery

---

NetKAN/EditorExtensions.netkan

Unclear why it's not indexing from KS but this might poke it into action.

EditorExtensions isn't indexing, poke it

---

NetKAN/BaconLabs.netkan

One might think that this is an attempt to try out how netkan handles ampersands for this file now, but really it's just for beautification reasons!

Making Baconlabs.netkan easier to read

---

NetKAN/RasterPropMonitor-Core.netkan
NetKAN/RasterPropMonitor.netkan

Update the homepage URLs and author fields of RasterPropMonitor to reflect
MOARdv's maintainership.

Update RasterPropMonitor URLs and Authors

---

NetKAN/CryoEngines.netkan

Add CryoEngines.netkan

---

NetKAN/SmartStage.netkan

New and hopefully improved version of https://github.com/KSP-CKAN/NetKAN/pull/1041

Add AVC to SmartStage.netkan

---

NetKAN/KerbalFlightIndicators.netkan

Latest version is a recompile for 1.0 according to the projects github, ergo I'm updating the metadata.
No .version file available so this is done the hard way.

Update KerbalFlightIndicators.netkan to 1.0

---

NetKAN/InterstellarFuelSwitch.netkan

Seeing if this resolves without an install stanza, else I'll add one.
License in initial PR was MIT, license on forums and KS is CC-BY-NC so I'm going with that one.

Add InterstellarFuelSwitch.netkan

---

NetKAN/SensibleScreenshot.netkan

Worked fine from KS but I filtered out the source.

Add SensibleScreenshot.netkan

---

NetKAN/KWRocketry.netkan

It's with great sadness I'm adding this. According to the KW forumthread this mod is horribly borked in 1.0 and requires external configs to fix it and even then it's not balanced. KickAssKyle have claimed he'll take a look at it in a few weeks so until then we'll mark it as version_max 0.90 :(

Fix version compat for KW

---

NetKAN/ActiveTextureManagement-x86-Aggressive.netkan
NetKAN/ActiveTextureManagement-x86-Basic.netkan

These files are confusing to me but I think these should work, let's see what Jenkins says.

Attempt at patching ATM for 1.0

---

NetKAN/ActiveTextureManagement-x64-Aggressive.netkan
NetKAN/ActiveTextureManagement-x64-Basic.netkan

Right now x64 appears dead, we'll see what happens in the future so I'll patch these to be 0.90 for now.

hardcoding 0.90 into ATM_x64 for now

---

NetKAN/kOS.netkan

Add conflict with -Classic to kOS

---

NetKAN/UniversalStorage.netkan

Regolith is now part of stock and will not be updated.
http://forum.kerbalspaceprogram.com/threads/100162?p=1879307#post1879307

Remove Regolith from UniversalStorage dependencies

---

NetKAN/AntennaRange.netkan
NetKAN/TweakableEverything.netkan

Please don't merge this one until after #1093.  Thanks!

AntennaRange and TweakableEverything depend on EVAManager.

---

NetKAN/GlassPanesandEnclosures.netkan

Add GlassPanesandEnclosures.netkan

---

NetKAN/AeroArrows.netkan
NetKAN/KerbalRenamer.netkan
NetKAN/ThermalHelper.netkan

closes #1097 
closes #1100 
closes #1099

Add mods from Regex emporium

---

NetKAN/AeroGUI.netkan

closes https://github.com/KSP-CKAN/CKAN-meta/issues/430

Fixing homepage entry for AeroGUI

---

NetKAN/ForScienceContinued.netkan

closes https://github.com/KSP-CKAN/CKAN-meta/issues/429

Fix dependencies for ForScienceContinued

---

NetKAN/MFS.netkan
NetKAN/StorkDeliverySystem.netkan

These have .version files.
@pjf recently explained to me the awesomeness of .version files
I now add ksp-avc so we can read said .version files because they are awesome.

Change MFS and SDS to use ksp-avc versioning

---

NetKAN/Kerbonov.netkan

Kerbonov.netkan

---

NetKAN/RealRoster.netkan

see https://github.com/KSP-CKAN/CKAN-meta/pull/433

Fixing version to correspond with forum thread

---

NetKAN/SpaceY-Lifters.netkan

http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-12-30-Apr-2015?p=1897057&viewfull=1#post1897057

SpaceY now recommends ModuleManager

---

NetKAN/HotRockets.netkan

HotRockets.netkan

---

NetKAN/KerbalScienceExchange.netkan

adresses https://github.com/KSP-CKAN/CKAN-meta/issues/450

Fix installpath for KerbalScieneExchange

---

NetKAN/PAPIPluginContinued.netkan

https://github.com/bssthu/PAPIPlugin
http://forum.kerbalspaceprogram.com/threads/112589

add PAPIPluginContinued from github

---

NetKAN/AtomicAge.netkan
NetKAN/Firespitter.netkan

closes https://github.com/KSP-CKAN/NetKAN/pull/1151
closes https://github.com/KSP-CKAN/NetKAN/pull/1150
I have absolutly no freaking idea what happened here but it seems TIAS method worked out for me and this does everything I wanted this PR and my last one to do, but combined into 1.
Going by the old: If it works, don't change it paradigm I'll just chalk this up to a success and merge it.

Add atomic age

---

NetKAN/USI-LS.netkan

Because who doesn't want Life support? O_O

Add USI-LS.netkan

---

NetKAN/RemoteTech.netkan

I've reverted my changes from #346 (2014-12-28) back to kerbalstuff. I've now access to the kerbalstuff-page and i've also updated the x_maintained_by value.

RemoteTech.netkan - #346 reverted

---

NetKAN/UKS.netkan

Also cleaned up the formatting.

Adds missing author line for USI-(MKS/OSI)

---

NetKAN/SETI-CommunityTechTree.netkan

Add SETI-CommunityTechTree.netkan

---

NetKAN/MusicMute.netkan

This mod looks like something I've always wanted but never knew I wanted until I saw it :o

MusicMute.netkan

---

NetKAN/ImprovedChaseCamera.netkan

Already exists in CKAN, but now is on Kerbal Stuff.
This should also close KSP-CKAN/NetKAN#1144

Add ImprovedChaseCamera

---

NetKAN/QuickBrake.netkan
NetKAN/QuickStart.netkan
NetKAN/StockPlugins.netkan

Hello, I don't know if it's here to pull request, but I try ;)
I wan't to add my new mods to CKAN: QuickBrake and QuickStart and to update StockPlugins
KSP-CKAN/NetKAN#1195
KSP-CKAN/NetKAN#1194

Added QuickBrake, QuickStart and updated StockPlugins

---

NetKAN/PersistentRotation.netkan

MarkusA380 asked to get an update to the CKAN file, as it no longer requires Toolbar (Or has any interaction with it at all).

Removed dependency on Toolbar. Mod is standalone now.

---

NetKAN/KerbalFlightData.netkan
NetKAN/KerbalWind.netkan

It might have been downloadable nonetheless but i better update ksp_version.

updated KerbalFlightData and KerbalWind ksp_version

---

NetKAN/CapCom.netkan
NetKAN/ContractRewardModifier.netkan
NetKAN/ContractsWindowPlus.netkan
NetKAN/DMagicOrbitalScience.netkan
NetKAN/SCANsat.netkan

Includes:
Orbital Science
SCANsat
CapCom
Contracts Window + 
Contract Reward Modifier

Update recommends and suggests

---

NetKAN/ActiveTextureManagement-x64-Aggressive.netkan
NetKAN/ActiveTextureManagement-x64-Basic.netkan
NetKAN/ActiveTextureManagement-x86-Aggressive.netkan
NetKAN/ActiveTextureManagement-x86-Basic.netkan
NetKAN/AtomicAge.netkan
NetKAN/BDArmory.netkan
NetKAN/CactEye2.netkan
NetKAN/CrowdSourcedScience.netkan
NetKAN/DavonTCsystemsMod.netkan
NetKAN/EVAManager.netkan
NetKAN/EditorExtensions.netkan
NetKAN/Firespitter.netkan
NetKAN/FirespitterCore.netkan
NetKAN/InfernalRobotics.netkan
NetKAN/LSPFlags.netkan
NetKAN/OMSKSpaceProducts.netkan
NetKAN/Protractor.netkan
NetKAN/StockBugFixModules.netkan
NetKAN/Targetron.netkan

Added homepages to a handful of mods that did not specify one (usually using KSP Forums as a source), and tweaked metadata for EditorExtensions to use its forum post as its homepage rather than its github repository (which is now moved to 'repository')

Added homepages to a handful of mods that did not specify one

---

NetKAN/Kerbulator.netkan

[Project repo](https://github.com/wmvanvliet/Kerbulator)

Add netkan file for Kerbulator

---

NetKAN/AGroupOnStage.netkan

Was requested by a few users, so I figured I might as well. Tests came back A-OK.

Add .netkan for AGroupOnStage

---

NetKAN/PlanetShine.netkan

[Reported upstream](http://forum.kerbalspaceprogram.com/threads/96497?p=1925304#post1925304)

Filter MiniAVC.xml from PlanetShine

---

NetKAN/RadialEngineMountsPPI.netkan

Currently the build fails with the old file, adding the install stanza fixes it.

Add install stanza to fix the build.

---

NetKAN/TACLS-Config-RealismOverhaul.netkan

RO has updated their folder structure on GitHub, this change should reflect that in the netkan file such that the mod can be indexed properly again.

TACLS-RO-config: Updated install stanza to match the new folder structure.

---

NetKAN/KerbalRPNCalculator.netkan

Change in the naming scheme. There is most likely a more efficient way of doing this, maybe @Dazpoet knows a way?

KerbalRPNCalculator: Fix install stanza.

---

NetKAN/CollisionFX.netkan

Per this [post](http://forum.kerbalspaceprogram.com/threads/100067?p=1936071#post1936071).

Add ModuleManager as a dependency of CollisionFX

---

NetKAN/ContractFilter.netkan

Add ContractFilter

---

NetKAN/TakeCommand.netkan

Hi, I'm the author of "Take Command" and would like to have it added to CKAN.
Thanks,
Sean.

Added TakeCommand.netkan

---

NetKAN/JSIPartUtilities.netkan

I hope this is correct, at least it produces a ckan file with no errors.
I'm not quite dead, but I don't have much time for KSP these days.

Adding the .netkan for JSIPartUtilities

---

NetKAN/TreeToppler.netkan

Filters source file.
Closes #1132.

Add TreeToppler, modified from automated PR.

---

NetKAN/MiniAirbrakes.netkan

Add dependency on ModuleManager, fix install stanza. Change the license to what is stated in the readme and convert it to shortform.
Closes #1189.

Add MiniAirbrakes, modified from automated PR.

---

NetKAN/PersistentTrails.netkan

Should fix the missing dependency on Toolbar from the automated PR in #1266.
Closes #1266.

Add PersistentTrails, modified from automated PR.

---

NetKAN/TACLSMining.netkan

Fixed up KS request for TACLSMining

---

NetKAN/PIDTuner.netkan

Fixing #1196, adding missing dependency and suppressing warning on accepted license.
Closes #1196.

Add PIDTuner, modified from automated PR.

---

NetKAN/CameraTools.netkan

Add GitHub and KerbalStuff resources to CameraTools.netkan

Camera tools

---

NetKAN/BeCoolStockNuke.netkan

KerbalStuff's auto-submit failed - Needed installation instructions.

Add BeCoolStockNuke.netkan

---

NetKAN/WaterSounds.netkan

Fixed license, added abstract and installation directives.

Add WaterSounds.netkan

---

NetKAN/ContractConfigurator-KerbinSideJobs.netkan
NetKAN/KerbinSideJobs.netkan

Add ContractConfigurator-KerbinSideJobs.netkan

---

NetKAN/EngineLighting.netkan

Fixed broken KerbalStuffBot submission

Add EngineLighting.netkan

---

NetKAN/StarTrekTOSSpaceSuits.netkan
NetKAN/StarTrekTOScoloredSpaceSuitsPackforTextureReplacer.netkan

Added Dependency and Installation details to KerbalStuffBot's #1287

Add Star Trek: TOS colored Space Suits Pack for TextureReplacer from KerbalStuff

---

NetKAN/GeometricShapeAeroTests.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1185.

Fix GeometricShapeAeroTests PR.

---

NetKAN/FogOfTech.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1192.

Fix fog of tech PR

---

NetKAN/MkerbIncScienceInstruments.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1209.

Fix mkerb inc science instruments

---

NetKAN/ORIONMonkeyBusinessIncParts.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1210.

Fix ORION, Monkey Business Inc. Parts

---

NetKAN/ORIONMonkeyBusinessIncParts.netkan

I forgot to check the dependencies in the previous PR.

Add missing dependencies.

---

NetKAN/PlanetScrambler.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1198.

Fix planet scrambler.

---

NetKAN/ElectricalParts.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1078, though I am unsure of what to do with EngineEnhancement.dll, as I can't find the originating plugin.

Add electrical parts

---

NetKAN/ElectricThrustEngineETE.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1284.

Add Electric Thrust Engine

---

NetKAN/RN-Solar-Panels.netkan

This should be committed at the same time as #939.

Mods by RaiderNick part B (RN-Solar-Panels)

---

NetKAN/Sarkomand.netkan

Thought I may as well share my flag with the world.

Add Sarkomand.netkan

---

NetKAN/Mk3MiniExpansionPack.netkan

Closes https://github.com/KSP-CKAN/CKAN-meta/issues/513 with a reinstall.

Move the license to another file to avoid clashes with other OPT mods.

---

NetKAN/NearFutureProps.netkan
NetKAN/StockFuelSwitch.netkan

unable to reopen #1360 and #1349 so here's a new PR that does exactly the same thing.

Add homepages

---

NetKAN/KSPInterstellarExtended.netkan

@ChucklesTheBeard is poking me on irc so I'm fixing this

Fixing KSPIE due to rabbles on irc

---

NetKAN/StarTrekEngines.netkan

Seeing as I just fixed KSPIE I guess I might aswell fix #1128 aswell.
Shoutout to @ABZB

Add StarTrekEngines

---

NetKAN/SpaceX-LaunchPack-Standard.netkan

Remove filter to allow Flags install on base mods

---

NetKAN/CryoEngines.netkan
NetKAN/InterstellarFuelSwitch-Core.netkan
NetKAN/InterstellarFuelSwitch.netkan
NetKAN/NearFutureConstruction.netkan

See reasoning at https://github.com/KSP-CKAN/NetKAN/issues/1126

Break InterstellarFuelSwitch.dll into it's own -Core.netkan

---

NetKAN/A7Corsair2.netkan

Add A7Corsair2.netkan

---

NetKAN/InterstellarFuelSwitch-Core.netkan

Also a tiny bit of formatting changes.

Filter MiniAVC.xml in InterstellarFuelSwitch-Core.

---

NetKAN/WarpShip.netkan

Revert "Revert "Create WarpShip.netkan""

---

NetKAN/ChenowthMPPV.netkan

Add ChenowthMPPV.netkan

---

NetKAN/FilterExtensions.netkan
NetKAN/FilterExtensionsDefaultConfig.netkan

New release package will have the configuration files shifted to "000_FilterExtensions Configs" and installed separately
Release has now been made

Split Filter Extensions

---

NetKAN/SmartParts.netkan

This is always intended to be an auto-generated file, and should never
be installed by a mod, which not only removes user-choice, but which can
also cause errorson upgrade.
Closes KSP-CKAN/CKAN#856.
Results of the generated `.ckan` file:
```
$ ckan.exe show SmartParts
Smart Parts: Smart Parts can trigger all 10 action groups, as well as various other functionality such as SAS, lights, stage, or abort.
Module info:
- version:      1.6.5
- authors:      BrettWebb
- status:       stable
- license:      CC-BY-NC-SA-3.0
Provides:
- SmartParts
Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/64227
- repository: https://github.com/BrettWebb/KerbalSmartParts
Filename: C13B00F9-SmartParts-1.6.5.zip
Showing 42 installed files:
- GameData/SmartParts
- …
```

Prevent SmartParts from installing MiniAVC.xml

---

build.sh

Mirroring the fixes in https://github.com/KSP-CKAN/CKAN-meta/commit/076177beb81d275d99e45e03e08a4430444f589b

Updating build.sh to have all the subfolders of thumbs

---

NetKAN/OpenTree.netkan

Add OpenTree.netkan

---

NetKAN/EpicSuits.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/1214.

Fix epic suits

---

NetKAN/Trajectories.netkan

http://forum.kerbalspaceprogram.com/threads/104694?p=1968414#post1968414 and the KS changelog states that stock aero is supported.

Remove FAR requirement, works for stock now.

---

NetKAN/BetterEmissives.netkan
NetKAN/NinjaTechEnterprises.netkan

Closes #1393
Closes #1391
When Ninja5tyl3/NinjaTechEnterprises#10 is resolved, AVC support can be added to netkan.

Add BetterEmissives and NinjaTech Enterprises

---

NetKAN/RavenspearMkO.netkan

Install stanza defined in another way than mentioned on KS since I can find absolutly no reason to put this inside the Squad Folder. Thought it might be looking for certain files in hardcoded places first but looking through the part.cfg files that does not appear to be the case so I'm installing this into its own folder in GameData.
@politas have been hard at work trying to find a homepage but have been unable too so none is listed for this mod.

RavenspearMkO.netkan

---

NetKAN/superspaceparts.netkan

Add superspaceparts.netkan

---

NetKAN/CrewQueue.netkan
NetKAN/RavenspearMkO.netkan

Added 2 homepages, hardcoded the description for RavenspearMkO because, of the 445 mods compatible with my KSP install, it was the only one with an all-caps abstract. #OCD

Homepage updates

---

NetKAN/MrFusionmk3.netkan

Closes #1416
Builds fine on my local netkan and installs ok on my 0.90 instance of KSP

Add MrFusionmk3.netkan

---

NetKAN/Corvus125mTwoKerbalPod.netkan

- Fixes errors with original netkan file
- Adds some metadata
- Adds dependency on HGR props
- Closes #1397
DO-NOT-MERGE until #1261 is resolved

Fix HGR's Corvus

---

NetKAN/ScienceContainers.netkan

Changed ksp_version to 0.90 since that is the latest official version of the game that this mod works on.

New version of #1355

---

NetKAN/AmpYearPowerManager.netkan

This should not be merged! It's me testing how this works and we should not merge until https://github.com/KSP-CKAN/CKAN-netkan/pull/60 is merged so we get a consistent naming schema.
resolves https://github.com/KSP-CKAN/CKAN/issues/931

Adding epoch to Ampyear

---

NetKAN/ContractConfigurator-ScanSatLite.netkan

Which will probably fail as well since the .version file is invalid.

Updates ScanSatLite file.

---

NetKAN/KerbinSideAirRace.netkan

Add KerbinSideAirRace.netkan

---

NetKAN/HotPlume.netkan

HotPlume ckan initial commit

---

NetKAN/KSIPlacementServices.netkan

Closes #1471
2 licenses in the archive: MIT and GPL3. GPL3 more restrictive so it's the one hardcoded. Abstract also hardcoded because

Add KSI - Placement Services

---

NetKAN/HGR-Props.netkan

Reusing identifier and install stanza from the ones found in CKAN-meta for this mod.

First part of fixing #1467

---

NetKAN/TarsierSpaceTechnologyWithGalaxies.netkan

For https://github.com/KSP-CKAN/CKAN/issues/1066
Seeing as I don't know why it refuses to update I'll just do the old install stanza juggle and see if that nudges it into working.

Tarsier isn't updating, nudging it

---

NetKAN/F5ATalonFighterAggressor.netkan

No dependencies listed on KS page, see #1497 for explanation of license + depends.

Add F5A Talon Fighter (Aggressor)

---

NetKAN/FreedomTex.netkan

Yet another .netkan hack to mark that mod works with new version of ksp :+1:

FreedomTex works with 1.0.2

---

NetKAN/HeatControl-Core.netkan
NetKAN/NearFutureElectrical-Core.netkan

I'm tired of these things not being around, the mods have been out for days now and we have a responsibility to our users to index mods to the best of our abilities.
I've made adjustments as per https://dl.dropboxusercontent.com/u/44754370/ckan.txt which was linked as the official NF mod matrix for CKAN [here](http://forum.kerbalspaceprogram.com/threads/52042-1-02-Near-Future-Technologies-%28All-packs-updated-to-1-02-Finally%21%29?p=1997811&viewfull=1#post1997811) and will upload fixed versions of all files in short order.
Starting with these Core ones as their own PR to be able to have Jenkins build and approve everything.

Add HeatControl-Core and NFE-Core

---

NetKAN/CryoEngines.netkan
NetKAN/NearFutureConstruction.netkan
NetKAN/NearFuturePropulsion.netkan

depends on #1536 and #1539 for Jenkins to perfectly do his dance
Everything updated to match the official list: https://dl.dropboxusercontent.com/u/44754370/ckan.txt

add more NF stuff

---

build.sh

Now that travis is uploading these artefacts to S3, we should download
them from there as well. :)
Part of my quest to make @Dazpoet happy. :)

build.sh: Download CKAN/Netkan artefacts from S3.

---

NetKAN/CryoEngines-LFO.netkan
NetKAN/NearFutureElectrical-DecayingRTGs.netkan
NetKAN/NearFuturePropulsion-LowThrustEP.netkan
NetKAN/NearFuturePropulsionExtras.netkan

depends on #1536 #1539 #1540 
Everything updated according to https://dl.dropboxusercontent.com/u/44754370/ckan.txt
I practically verbatimed @Felger for the reduced thrust stuff so this supercedes #1530

Add NF Extras

---

NetKAN/KashCorpSA.netkan

pseudo-mod created for RoversAndRoadsters and KAP apps which share these resources and base directory.

Adding KashCorp Virtual mod

---

NetKAN/Mk3KISCargoContainers.netkan

Add Mk3KISCargoContainers.netkan

---

NetKAN/B9AerospaceProceduralParts.netkan

Add CrossFeedEnabler to B9AerospaceProceduralParts

---

NetKAN/FuelSwitchtoeverytank-ThermalPaint.netkan
NetKAN/FuelSwitchtoeverytank-default.netkan

Part 2/2 to resolve #1489.
See  KSP-CKAN/CKAN-meta#582 for part 1.

Add FuelSwitch to every tank

---

NetKAN/StockNoContracts.netkan

Add StockNoContracts

---

NetKAN/HeatControl.netkan

Includes #1569, but without the rename.
Submitting as a PR as I'm too lazy to test manually when we've got bots. :)

HeatControl adjustments

---

NetKAN/NearFutureElectrical.netkan

Includes #1573, but without the renames.
Sending as a PR so our bots can test. :)

NearFutureElectrical with ident adjustments.

---

NetKAN/KAP.netkan
NetKAN/RoversAndRoadsters.netkan

Inital shared assets already on board as KashCorp

Adding KAP and RoversAndRoadsters addons

---

NetKAN/LayeredAnimations.netkan

Dependency for Porkjet's new release of Habitat Pack.

Add LayeredAnimations

---

NetKAN/Mk2Expansion.netkan

Update to the netkan to include new dependancy

Mk2Expansion.Netkan

---

NetKAN/KSP-KScale2.netkan
NetKAN/KScale2.netkan

there was a CKAN folder inside the .zip for this and lo and behold it held a netkan file. So I grabbed it and added it to here. The identifier has therefore been chosen by the author and not by me.

KScale2.netkan

---

NetKAN/ModelRocketry.netkan

I can't find a single .ckan file for this, so it has yet to be built since the inclusion, most likely due to the license/licenses issue.

Rename licences to license to match spec.

---

NetKAN/EditorExtensions.netkan

Seriously. 1.0.3 and 1.0.4 are almost the same.

Editor extensions is 1.0.3/1.0.4 compatible.

---

NetKAN/CoherentContracts.netkan

Replaces KSP-CKAN/CKAN-meta#634

Override CoherentContracts KSP versions

---

NetKAN/ExtensiveEngineerReport.netkan

Add ExtensiveEngineerReport

---

NetKAN/ProceduralParts.netkan

[Compatible with KSP 1.0.4](http://forum.kerbalspaceprogram.com/threads/106975?p=2045656&viewfull=1#post2045656)
Replaces KSP-CKAN/CKAN-meta#631

Override Procedural Parts

---

NetKAN/TACLS-Config-Stock.netkan

OMG I forgot these with the other PR.

TACLS-Config-Stock overrides.

---

NetKAN/AdjustableLandingGear.netkan

supported version override for AdjustableLandingGear

---

NetKAN/KerbalHistoricalInstitute.netkan

Add KerbalHistoricalInstitute

---

NetKAN/TacFuelBalancer.netkan

TacFuelBalancer overrides

---

NetKAN/ModularRocketSystem.netkan

ModularRocketSystem conflicts with ModularRocketSystemsLITE

---

NetKAN/ModularRocketSystemsLITE.netkan

ModularRocketSystemsLITE conflicts with ModularRocketSystem

---

NetKAN/NavballDockingIndicator.netkan

http://forum.kerbalspaceprogram.com/threads/54303?p=1967443&viewfull=1#post1967443

Marking NavballDockingAlignmentIndicator 1.0.4 compatible

---

NetKAN/TweakableEverythingExtras

Takes care of issue #1580 https://github.com/KSP-CKAN/NetKAN/issues/1580

Added The "Extra" configs for Tweakable Everything

---

NetKAN/TweakableEverything.netkan

Suggest TweakableEverythingExtras

---

NetKAN/Goodspeed.netkan

override ksp version with min 1.0.2 and max 1.0.4
Also cleaning up white space

GPOSpeedFuelPump 1.4 min-max override ksp_verison

---

NetKAN/ImprovedChaseCamera.netkan

provide v 1.5.1 override for 1.0.4 as well as 1.0.3 and .2

ImprovedChaseCamera 1.5.1 min-max override

---

NetKAN/KerbalFoundries.netkan

its set to "include in the install" at kerbalspace, correcting thsi with the actual download URL"

KerbalFoundries Fix respository error from KSpace

---

NetKAN/FilterExtensions.netkan
NetKAN/FilterExtensionsDefaultConfig.netkan
NetKAN/FilterExtensionsStockRework.netkan

Add another configuration for FE

---

NetKAN/QuickContracts.netkan
NetKAN/QuickMute.netkan
NetKAN/QuickRevert.netkan

Hello, I've updated the NetKAN's files of my mods to stop the support of KSP-AVC on CKAN.

Updated of QuickRevert, QuickMute and QuickContracts

---

NetKAN/SovietEngines.netkan

My guess is that this is the correct way rather than https://github.com/KSP-CKAN/CKAN-meta/pull/673 @pjf @Dazpoet

SovietEngines update override versioning

---

NetKAN/TrizzleAeroSpaceCompany.netkan

Regex isn't my strong suit, needs verification.

Add Trizzle AeroSpace Company

---

NetKAN/ModularComputerPackage.netkan

Closes #1732
My regex needs verification (I'm a newb).

Add Modular Computer Package

---

NetKAN/DockingSounds.netkan

Add DockingSounds.netkan

---

NetKAN/SovietConversion.netkan

Add SovietConversion.netkan

---

NetKAN/Deathstarwithlaser.netkan

Add Deathstarwithlaser.netkan

---

NetKAN/SolarisHypernautics.netkan

Add SolarisHypernautics.netkan

---

NetKAN/SmallFatTechnologies.netkan

Add SmallFatTechnologies.netkan

---

NetKAN/Kurrikane.netkan

Add Kurrikane.netkan

---

NetKAN/EagleTransporterSP1999.netkan

Add EagleTransporterSP1999.netkan

---

NetKAN/Area21SCraft.netkan

Add Area21SCraft.netkan

---

NetKAN/ABLaunchers.netkan

Add ABLaunchers.netkan

---

NetKAN/Antennas.netkan

Add Antennas.netkan

---

NetKAN/Kazza197sNukeAddonToBahamutoDsArmoury.netkan

Add Kazza197sNukeAddonToBahamutoDsArmoury.netkan

---

NetKAN/NASACareerModeTotalConversion.netkan
NetKAN/USAConversion.netkan

Add USAConversion.netkan

---

NetKAN/VanguardAstrodynamicsVXSeries.netkan
NetKAN/VanguardAstrodynamicsVXSeriesStockalikeEnginePack.netkan

While I usually keep the bot-assigned ID, it seemed a bit long. If anyone feels strongly about it, I'll change it back.

Add VanguardAstrodynamicsVXSeries.netkan

---

NetKAN/EBRCPartspack.netkan

Should cover us if he increments `EBRC-PACKS_PACK-1`

EBRCPartspack futureproofing

---

NetKAN/MaritimePack.netkan
NetKAN/TheMaritimePack.netkan

Add TheMaritimePack.netkan

---

NetKAN/KerbalFuels.netkan

Add KerbalFuels.netkan

---

NetKAN/MarkOneLaboratoryExtensions.netkan

Add MarkOneLaboratoryExtensions

---

NetKAN/HotRocketsFireworksPack.netkan
NetKAN/HotRocketsFireworkspack

Pull/1829 Fix

---

NetKAN/Area21SCraft.netkan
NetKAN/ContractConfigurator-KerbalAircraftBuilders.netkan
NetKAN/ContractConfigurator-RemoteTechLite.netkan
NetKAN/EagleTransporterSP1999.netkan
NetKAN/Kazza197sNukeAddonToBahamutoDsArmoury.netkan
NetKAN/LLL-Extras.netkan
NetKAN/LLL.netkan
NetKAN/RaptorAerospacial-Textures.netkan
NetKAN/Super100ShootingStarCommandPod-heatshield.netkan
NetKAN/Super100ShootingStarCommandPod.netkan
NetKAN/Super67LittleStarCommandPod-heatshield.netkan
NetKAN/Super67LittleStarCommandPod.netkan

Noted a number of spec version issues cropped up during the bots little holiday.

Metadata fixes

---

NetKAN/BetterScienceLabsContinued.netkan
NetKAN/ContractConfigurator-GrandTours.netkan
NetKAN/ContractConfigurator-UnmannedContracts.netkan
NetKAN/EVAHandrailsPackContinued.netkan
NetKAN/SpacetuxSA.netkan

A copy of, and closes #1646
Each netkan tested with no errors on netkan or ckan install.

Added AVC vrefs

---

NetKAN/VenStockRevamp.netkan

I got permission from @NathanKell who 'fixes stuff' in VSR, though not from Ven himself.
Also wasn't sure how the "version" section works in this so it may be wrong.

Ven's Stock Revamp works fine on 1.0.4

---

NetKAN/ColorfulFuelLines.netkan

Closes  #1867
Pinging @NecroBones just to let you know this is being added.

Add ColorfulFuelLines.netkan

---

NetKAN/InfernalRobotics-Sequencer.netkan

Version dependency added in most recent changelog

Update dependent version of IR in InfernalRobotics-Sequencer.netkan

---

NetKAN/DatedQuickSaves.netkan

Add DatedQuickSaves.netkan

---

NetKAN/KerbalPlanetaryBaseSystems.netkan

Add KerbalPlanetaryBaseSystems.netkan

---

NetKAN/LolexCar.netkan

Add LolexCar.netkan

---

NetKAN/Mk3MiniExpansionPack.netkan

This will allow us to index v1.2 onward.

Correct install for Mk3MiniExpansionPack.netkan

---

NetKAN/KineticPenetratorbyVanguardAstrodynamics.netkan

Add KineticPenetratorbyVanguardAstrodynamics.netkan

---

NetKAN/ClampOTronAPAS.netkan

Add ClampOTronAPAS.netkan

---

NetKAN/BZ1RadialAttachmentPoint.netkan

Add BZ1RadialAttachmentPoint.netkan

---

NetKAN/DeadlyReentry.netkan

Yay for folder structure changes~~

Change DeadlyReentry.netkan to adapt to new archive directory structure

---

NetKAN/Asclepius-clouds.netkan
NetKAN/Asclepius.netkan

Add Asclepius and Asclepius-clouds

---

NetKAN/KSPInterstellarLite.netkan
NetKAN/MunarSurfaceExperimentPackage.netkan
NetKAN/ODFC.netkan
NetKAN/SatBatts.netkan
NetKAN/dockingtube.netkan

A remake of, and closes #1831 because my gitfu is gitignored

License fixes

---

NetKAN/DogeCoinFlag.netkan
NetKAN/EntchenFlag.netkan
NetKAN/LSPFlags.netkan
NetKAN/Sarkomand.netkan
NetKAN/TriggerAu-Flags.netkan

One more step toward KSP-CKAN/CKAN-meta#623's completion.

Bring flag-only mods to the same version, and add a comment to identify them.

---

NetKAN/ModuleSolarTracking.netkan

Add ModuleSolarTracking.netkan

---

NetKAN/FuelTanksPlus.netkan

Update FuelTanksPlus.netkan dependencies

---

NetKAN/ChuteSafetyIndicator.netkan

Copy paste of KerbalStuffBot PR with avc line added.
Closes #1951

Add ChuteSafetyIndicator.netkan

---

NetKAN/Airlock.netkan

Add Airlock.netkan

---

NetKAN/BetterIonDrives.netkan

Closes #1906
Want to wait a few days to see if mod author corrects the folder name having an extra whitespace at the end.

[WIP] Add BetterIonDrives.netkan

---

NetKAN/RealPlume.netkan

RealPlume epoch bump

---

NetKAN/ContractConfigurator-RoverMissionsbyWhyren.netkan

Add ContractConfigurator-RoverMissionsbyWhyren

---

NetKAN/MK12PodIVAReplacementbyASET.netkan

Add MK12PodIVAReplacementbyASET.netkan

---

NetKAN/SmallSolarSystem.netkan

Add SmallSolarSystem

---

NetKAN/OldSchoolTurrets.netkan

Add OldSchoolTurrets.netkan

---

NetKAN/ContractConfigurator-GrandTours.netkan
NetKAN/ContractConfigurator-UnmannedContracts.netkan
NetKAN/EVAHandrailsPackContinued.netkan
NetKAN/SpacetuxSA.netkan

1.0.4 overrides for linuxgurugamer's mods

---

NetKAN/RealFuels.netkan

Add override to RealFuels: after rf-v10.4.9 remove IFS conflict

---

NetKAN/ASETAvionics.netkan

Add ASETAvionics.netkan

---

NetKAN/SteampunkColorCodedSpaceSuits.netkan

This mod might need a .cfg file to make it work. I've [contacted the author](http://forum.kerbalspaceprogram.com/threads/107471-1-0-4-TextureReplacer-2-4-7-%284-7-2015%29?p=2094491&viewfull=1#post2094491) for clarification.

[WIP] Add SteampunkColorCodedSpaceSuits.netkan

---

NetKAN/RealPlume-StockConfigs.netkan

Make RealPlume a metanetkan

---

NetKAN/CargoTransportationSolutions.netkan

Add CargoTransportationSolutions.netkan

---

NetKAN/KerdiAutoCavalcade.netkan

Add KerdiAutoCavalcade.netkan

---

NetKAN/JSCMonopropellantDecoupler.netkan

Add JSCMonopropellantDecoupler.netkan

---

NetKAN/FerramAerospaceResearch.netkan

KSP-CKAN/CKAN#1321 Would help with this a lot.

Bump FAR Epoch

---

NetKAN/AutomatedScreenshots.netkan

Add AutomatedScreenshots.netkan

---

NetKAN/HexisRoundedAttachmentKit.netkan

Add HexisRoundedAttachmentKit.netkan

---

NetKAN/VesselAssembly.netkan

Add VesselAssembly.netkan

---

NetKAN/ContractConfigurator-HistoricMissions.netkan

Add ContractConfigurator-HistoricMissions.netkan

---

NetKAN/RealSolarSystem.netkan

RealSolarSystem needs a leading version 'v'.

---

NetKAN/SentarExpansion.netkan

KS page: https://kerbalstuff.com/mod/1029
Closes #2023
Waiting on info from author about cache folders included in archive.

Add SentarExpansion.netkan

---

NetKAN/KAINET.netkan

Changes per mod author @Kerbas-ad-astra in #1548

Update KAINET.netkan to use github as kref

---

NetKAN/SolarSailNavigator.netkan

I am the author of SolarSailNavigator. The latest version uses ModuleManager to patch the stock ion engine with new features and properties.

Add ModuleManager dependency

---

NetKAN/OrbitalDecay.netkan

@Whitecat106 is ModuleManager a dependency? I noticed MM_StationKeepingModule.cfg and it seems like the mod needs it to apply its effects to stations, but if I'm wrong let me know please.

Add OrbitalDecay.netkan

---

NetKAN/kal9000.netkan

Adding this with Ignobil's permission

---

build.sh
t/metadata.t

I'll add some comments in line for discussion. Extends @mgsdk's work in #1947

Extra Tweaks to Build Script

---

NetKAN/BDArmory.netkan

Force v on BDArmory

---

NetKAN/HullcamVDS.netkan

See also https://github.com/KSP-CKAN/CKAN/issues/1364

Mod update requires new dependency and file filter

---

NetKAN/OPMclouds.netkan

Add OPMclouds.netkan

---

NetKAN/TACLS.netkan

Adding a tag to unify the author name field with his other mods

unifying author name

---

NetKAN/SigmaStockRecolor.netkan

Waiting on info if it depends MM

Add SigmaStockRecolor.netkan

---

NetKAN/EVAEnhancements.netkan

Revert "Add KSP forum thread as homepage for EVAEnhancements"

---

NetKAN/ColorCodedCans.netkan
NetKAN/FuelTanksPlus.netkan

Add ksp-avc for FuelTanksPlus. Have ColorCodedCans recommend FTP while FTP suggests CCC

---

NetKAN/RN-USProbesPack.netkan

Fix incorrect description that was copy-pasted from skylab mod

RN fix description

---

NetKAN/AMEG.netkan
NetKAN/AnimatedDecouplers-x86.netkan
NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids.netkan
NetKAN/Tantares.netkan
NetKAN/TantaresLV.netkan

Small steps towards https://github.com/KSP-CKAN/CKAN-meta/issues/623
Companion PR to: https://github.com/KSP-CKAN/CKAN-meta/pull/735

Version wranglin 01

---

build.sh

I wish there were a way to know if this ever comes into play.

Add @tehcman83's fixes for ksp_ver 0.23 and 0.25 from ckan-meta to netkan's build script

---

NetKAN/CrowdSourcedFlags.netkan

Also fixed the weird indenting and edited the description.

Change author from my GitHub name to my forum name

---

NetKAN/Mk2Expansion.netkan

Institutes the changes in and closes #2093

Update relationships for Mk2Expansion

---

NetKAN/EvaFuel.netkan

See comment in #2088 for context.

Add EvaFuel.netkan

---

NetKAN/EditorTime.netkan

On hold awaiting @magico13's final word on the correct license (GPL3 in KerbalStuff page and KSP thread but ARR license in the .zip).

Add EditorTime.netkan

---

NetKAN/Olympic1ARPIcons.netkan

I just updated my Olympic1ARPIcons

Add my last mod

---

NetKAN/OblivionAerospace.netkan
NetKAN/SovietEngines.netkan
NetKAN/kribubble.netkan
NetKAN/krispeeder1.netkan

Some mods have their version_max changed, some mods have the range removed and replaced with "1.0" instead.

Assign a ksp_version range.

---

NetKAN/RaceKerbol.netkan

Depends upon KSP-CKAN/CKAN#1360 .
Attn @Lyneira.

Added RaceKerbol

---

build.sh

Should prevent future confusion like #1415

Display version info about ckan/netkan

---

NetKAN/Olympic1ARPIcons.netkan

Add suggestion for Olympic1ARPIcons

---

NetKAN/KSPInterstellarExtended.netkan

This should have been done some time ago

Community Tech Tree is not required or adds any benefit to KSPI

---

build.sh

Mirror PR of https://github.com/KSP-CKAN/CKAN-meta/pull/749
Most recent case in the netkan repo is https://github.com/KSP-CKAN/NetKAN/pull/2160

Use ksp_version_max instead of ksp_version_min

---

NetKAN/6seatMk3cockpit.netkan
NetKAN/SixSeatMk3cockpit.netkan

A few more lines in this netkan and it would be larger than the mod itself. =)

Add SixSeatMk3cockpit.netkan

---

NetKAN/AmpYearPowerManager.netkan
NetKAN/DeepFreeze.netkan
NetKAN/KabinKraziness.netkan
NetKAN/REPOSoftTech-Agencies.netkan
NetKAN/TarsierSpaceTechnologyWithGalaxies.netkan

Split REPOSoftTech's Agencies into its own mod. Add AVC support for all of JPLRepo's mods. Some formatting changes.
Closes KSP-CKAN/CKAN-meta#759

Create REPOSoftTech-Agencies, misc changes to JPLRepo's other .netkans.

---

NetKAN/NanoGauges.netkan

Nanogauges override for 1.0.4 compatibility

---

NetKAN/StockSCANsat.netkan

Hello, I want to add StockSCANsat to CKAN ;)
https://github.com/KSP-CKAN/NetKAN/pull/2226

add StockSCANsat

---

NetKAN/TrackingStationAmbientlight.netkan

Performed the tests according to the wiki-manual, and they worked.

Add netkan file for the new addon TrackingStationAmbientlight

---

NetKAN/SpaceY-Expanded.netkan

Correcting the recommendation to Interstellar's Core.

Update SpaceY-Expanded.netkan, recommendation correction.

---

NetKAN/SuperHeavyBoostersHistoricalNexus.netkan

Fix change in structure - closes #2275

---

NetKAN/LVNNuclearEngineClusters.netkan

Will chip away at the broken NetKANs, would be nice if we had 100% health.

Fix LVNNuclearEngineClusters

---

NetKAN/TestFlight.netkan
NetKAN/TestFlightConfigRO.netkan
NetKAN/TestFlightConfigStock.netkan

1.0.4 override for TestFlight

---

NetKAN/SigmaBinary-core.netkan

I'm not sure this will be enough
@plague006 let me know if I need to change something

download mirror moved from kerbalstuff to github

---

NetKAN/WasdEditorCameraContinued.netkan

Add WasdEditorCameraContinued.netkan

---

NetKAN/AmbientLightAdjustment.netkan

Add AmbientLightAdjustment's dependency on Toolbar

---

NetKAN/Deltaglider.netkan
NetKAN/DeltagliderXR1forKSP.netkan

Actual Netkan work by the fabulous RedNeck, I'm just doing the gitomancy.
:)

Add Deltaglider from KerbalStuff

---

NetKAN/KerbalKonstructs.netkan

NetKAN currently failing to inflate.

fix 'No files found in medsouz to install'

---

NetKAN/ShadowWorksStockalikeSLSandMore.netkan

Squee! Made 'find_regexp' do a thing!

fix Module contains no files to install.

---

NetKAN/PEWPromethiumExperimentalWeaponry.netkan

Add PEWPromethiumExperimentalWeaponry

---

NetKAN/KaribouExpeditionRover.netkan

Add KaribouExpeditionRover

---

NetKAN/ShuttleLiftingBodyCormorantAeronology.netkan

Add ShuttleLiftingBodyCormorantAeronology

---

NetKAN/Kartographer.netkan

Add Kartographer

---

NetKAN/CarcharothAeronautics.netkan

Add CarcharothAeronautics

---

NetKAN/BDArmoryFPS.netkan

Add BDArmoryFPS

---

NetKAN/MK3PodIVAReplacementbyApex.netkan

Add MK3PodIVAReplacementbyApex

---

NetKAN/QArmory.netkan

Add QArmory

---

NetKAN/ProtonMBreezeM.netkan

Add ProtonMBreezeM

---

NetKAN/kOSBFSMultipleArchiveManager.netkan

Add kOSBFSMultipleArchiveManager

---

NetKAN/DatedQuickSaves.netkan
NetKAN/KerbalConstructionTime.netkan
NetKAN/MagiCore.netkan
NetKAN/SensibleScreenshot.netkan

And fixed a "conflicts" in Kerbal Construction Time that isn't actually true. Also added the new mod that Dated QuickSaves and SensibleScreenshots depend on (MagiCore)

Added a new depends to two of my modlets

---

NetKAN/USAFOrionMod-TD-subedition.netkan

According to Kerbal stuff this is already CKAN'ed, but it ain't.  Adding this with a recommend link to the accompanying upper stage mod (which I'll edit to also recommend this, once this is live).
I think I got me commas right this time.  :-)

Adding USAF TD Ed Orion

---

NetKAN/TDIndustrysOrionbits10m.netkan

Adding the "recommends" to match the other companion mod, and changing the file to find.  
Not sure if this means I should remove the x_via tag or not.

Adding cross recommendation

---

NetKAN/Pathfinder-AntennarangePatch.netkan

Add patch for Antennarange mod to Pathfinder

---

NetKAN/Pathfinder-USILS-CommunityPatch.netkan

Add Pathfinder-USILS-CommunityPatch.netkan

---

NetKAN/Deltaglider.netkan

Add epoch to Deltaglider

---

NetKAN/PAPIPluginContinued.netkan

Closes https://github.com/KSP-CKAN/CKAN-meta/issues/765

Add 1.0.4 override for PAPIPluginContinued

---

NetKAN/Kronkus.netkan

Would appreciate your input on this @Olympic1 if it conflicts with any other packs.

Add Kronkus.netkan

---

NetKAN/Mk2Expansion.netkan

Closes #2341, closes https://github.com/KSP-CKAN/CKAN/issues/1484

Update dependencies, update install stanza for Mk2Expansion 

---

NetKAN/LittleGreenMenFromMars.netkan

Add LittleGreenMenFromMars

---

NetKAN/Deltaglider.netkan

Changes by @RacerXx, being tested by me now. :)

Updates to Deltaglider.netkan

---

NetKAN/ThrottleControlledAvionics.netkan

TCA supports but doesn't require Toolbar. Here's metadata to reflect
that.

TCA suggests Toolbar

---

NetKAN/HideEmptyTechNodes.netkan

This closes #2403, closes  #2406.
@jyanjyanjyan: let me know if you have more changes to the netKAN file. Btw, should community tech tree be a dependency for this mod instead of a recommendation? Will it work without CCT?

Fix pull request #2403 - Hide empty tech nodes

---

NetKAN/KerbodynePlus01Alpha.netkan

KS says this is 1.0.2, so that's what ends up in the metadata. I'm trying
to burn through as many PRs as I can, so I'm happy with us doing a second
PR to mark this as 1.0.4 compatible if it turn out it is.
This gives me a good looking list of files:
``` Showing 68 installed files:
- GameData/Custom
- GameData/Custom/license.txt
- GameData/Custom/Parts
- GameData/Custom/Parts/booster
- GameData/Custom/Parts/booster/booster.cfg
- GameData/Custom/Parts/booster/booster.mu
- GameData/Custom/Parts/booster/booster.png
- GameData/Custom/Parts/decoupler
- GameData/Custom/Parts/decoupler/decoupler.cfg
- GameData/Custom/Parts/decoupler/decoupler.mu
- GameData/Custom/Parts/decoupler/decoupler.png
- GameData/Custom/Parts/extremeDockingPort
- GameData/Custom/Parts/extremeDockingPort/extremeDockingPort.c …
```

Add KerbodynePlus01Alpha

---

NetKAN/NinjaTechEnterprises.netkan

Removed the need for Module Manager and changed my file structure.

NinjaTechEnterprises: Change to file structure and requirements

---

NetKAN/Buffalo.netkan
NetKAN/BuffaloNASAInspiredMSEVExploreInStyle.netkan

Includes and supersedes #2394.

Add Buffalo (NASA Inspired MSEV) from KS

---

NetKAN/MunPocketEdition.netkan
NetKAN/TheMunPocketEdition.netkan

Obsoletes #2331. PR so I can have the bots take a look. :)

Add Mun (pocket ed) to the CKAN.

---

NetKAN/KerbalPlanetaryBaseSystems.netkan

Closes https://github.com/KSP-CKAN/CKAN-meta/pull/781

KerbalPlanetaryBaseSystems force v

---

NetKAN/HangarExtender.netkan

Closes https://github.com/KSP-CKAN/NetKAN/issues/2310

Change target for HangarExtender to new maintainer

---

NetKAN/AlternisKerbolRekerjiggered-flags.netkan
NetKAN/AlternisKerbolRekerjiggered.netkan

Original: https://github.com/KSP-CKAN/NetKAN/pull/2255
Since then the configs are no longer included.
@Olympic1 another planetpack.  https://github.com/KSP-CKAN/CKAN-meta/issues/588

Add AlternisKerbolRekerjiggered and AlternisKerbolRekerjiggered-flags.

---

NetKAN/CommunityAmmunitionLibrary.netkan
NetKAN/NAS.netkan
NetKAN/PEWPromethiumExperimentalWeaponry.netkan

Original https://github.com/KSP-CKAN/NetKAN/pull/2347

Add CommunityAmmunitionLibrary and fix its dependent mods.

---

NetKAN/Contares.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2363

Add Contares

---

NetKAN/KSCFloodlight.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2368

Add KSCFloodlight

---

NetKAN/TheMartianRockets.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2379

Add TheMartianRockets

---

NetKAN/SpannersBoomsticksContinued.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2380

Add SpannersBoomsticksContinued

---

NetKAN/PhoenixIndustriesBoosters.netkan
NetKAN/PhoenixIndustriesCargoResupplySystem.netkan
NetKAN/PhoenixIndustriesFlags.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2385

Add PhoenixIndustriesBoosters and split PhoenixIndustriesFlags

---

NetKAN/RSS64kA64RescaleforRSS.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2391

Add RSS64kA64RescaleforRSS

---

NetKAN/UnmannedBeforeManned.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2393

Add UnmannedBeforeManned

---

NetKAN/ToySolarSystem.netkan

@Olympic1 another scaled solar system. https://github.com/KSP-CKAN/CKAN-meta/issues/588
Closes https://github.com/KSP-CKAN/NetKAN/pull/2432

Add ToySolarSystem

---

NetKAN/NebiaAndShomma.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2426
@Olympic1 more https://github.com/KSP-CKAN/CKAN-meta/issues/588 for you.. Seems like a pretty intense flurry of them.

Add NebiaAndShomma

---

NetKAN/CloakingDevice.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2421

Add CloakingDevice

---

NetKAN/AirPark.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2439

Add AirPark

---

NetKAN/GenericInlineCockpits.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2437

Add GenericInlineCockpits

---

NetKAN/GregroxsColoredEVAIVASuits.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2436

Add GregroxsColoredEVAIVASuits

---

NetKAN/KramaxAutoPilot.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2377

Add KramaxAutoPilot

---

NetKAN/SimpleRealism.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2404

Add SimpleRealism

---

NetKAN/TheSeparon.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2408

Add TheSeparon

---

NetKAN/MysteriousProjectsDrLiriusRover.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2417

Add MysteriousProjectsDrLiriusRover

---

NetKAN/CactEyeTelescopesContinued.netkan

~~I fully expect this will fail Jenkins because of an error in the .zip file itself. I test with a hardcoded `download` directed to the previous release of the mod and had no issues. With that said @Angel-125 would you be able to push a new release of the mod and let us know when it's done?~~
It passed, it must have been a corrupt download on my end (or something).
Closes https://github.com/KSP-CKAN/NetKAN/pull/2414

Add CactEyeTelescopesContinued

---

NetKAN/Buffalo.netkan

Always a PITA to find these kinds of conflicts. I had the benefit of writing the metadata for the other WildBlue mods.

Remove install conflict with and instead depend on WildBlueTools

---

NetKAN/CrowdSourcedScience.netkan
NetKAN/EpicSuits.netkan
NetKAN/KSP-64k-12HourDay.netkan
NetKAN/KSP-64k-imgviewer.netkan
NetKAN/KSP-64k.netkan
NetKAN/Karbonite.netkan
NetKAN/KduffersKorpHotrodWheels.netkan
NetKAN/KduffersMultiwheels.netkan
NetKAN/KerbolPlus.netkan
NetKAN/ModOrientedTechTree.netkan
NetKAN/ProceduralProbes.netkan
NetKAN/QArmory.netkan
NetKAN/RedversusBlue.netkan
NetKAN/RocketWatch.netkan
NetKAN/ShuttleLiftingBodyCormorantAeronology.netkan
NetKAN/StarTrekTOSSpaceSuits.netkan
NetKAN/StockHeatManagementforKSPI.netkan
NetKAN/TheBlueDrill.netkan

Over time these install stanzas have broken. Thanks to @techman83's netkan status for helping find all these wanderers.

Fixes for multiple mods with broken install stanzas

---

NetKAN/sidosUraniaSystem.netkan

name, ksp_version, release_staus and author removed as requested
I didn't have the repo I initially added this, so I had to add it again since it wasn't merged.
Closes: #2398

Re-added sidos with changes:

---

NetKAN/sidosUraniaSystem.netkan

Also tabs to spaces, because aesthetics.

License correction for sidosUraniaSystem

---

NetKAN/VenStockRevamp.netkan

Locally this still works (but so does the original) and the hope is that it'll get this mod unstuck from the fail list on http://status.ksp-ckan.org

Attempt to fix VenStockRevamp by adding an install stanza

---

NetKAN/AntennaRangePatches.netkan

Mod wants to install and run AutoPruner or `RemoteTech` breaks, so added as a `conflict`.
Closes https://github.com/KSP-CKAN/NetKAN/pull/2427

Add AntennaRangePatches

---

NetKAN/Antennas.netkan
NetKAN/JackOLantern.netkan

From http://status.ksp-ckan.org/

Fix broken installs

---

NetKAN/UNSCPillarofAutumn.netkan

Add UNSCPillarofAutumn

---

NetKAN/M12LRVwarthog.netkan

Add M12LRVwarthog

---

NetKAN/heatshieldtile.netkan

Add heatshieldtile

---

NetKAN/halocharactercostumes.netkan

Add halocharactercostumes

---

NetKAN/covenantcapitalship.netkan

Add covenantcapitalship

---

NetKAN/HarderSolarSystem-1x.netkan
NetKAN/HarderSolarSystem-2x.netkan
NetKAN/HarderSolarSystem-3x.netkan
NetKAN/HarderSolarSystem-4x.netkan

Each netkan file is for a different scaled solar system.

Add Harder Solar System netkan files

---

NetKAN/ContractConfigurator-HistoricMissions.netkan

The lastest release (v1.6.0) of `HistoricMissions` changed its folder structure.

Folder change

---

NetKAN/EnduranceSpaceExplorationSystem.netkan

Mod author removed the `VAB` & `SPH` folders. He also changed the license.

Removed VAB/SPH folders

---

NetKAN/StockPlus.netkan

Search for the `.zip` file.
Testing locally installs the required file

Fix StockPlus

---

NetKAN/ShipSections.netkan

Add my new mod ShipSections to the NetKAN indexer.

Add ShipSections NetKAN file to the indexer.

---

NetKAN/TheRATPack.netkan

TheRATPack

---

NetKAN/KSABetterFairings.netkan

Add KSABetterFairings

---

NetKAN/SkyTonemapper.netkan

Add SkyTonemapper

---

NetKAN/StockjetTurbinesresurrected.netkan

Add StockjetTurbinesresurrected

---

NetKAN/OctoSat.netkan

Add OctoSat

---

NetKAN/AntennaRangePatch4ORIGAMEAntenna
NetKAN/AntennaRangePatch4ORIGAMEAntenna.netkan

Add AntennaRangePatch4ORIGAMEAntenna

---

NetKAN/Kerbulator.netkan

The author just released a recompile against 1.0.5. This updates the netKAN to reflect the change.

Update Kerbulator to support KSP 1.0.5

---

NetKAN/SurfaceMountedLights.netkan

Add SurfaceMountedLights

---

NetKAN/Ballistanks.netkan

Add Ballistanks

---

NetKAN/PulsejetArgusAs014.netkan

Add PulsejetArgusAs014

---

NetKAN/CactEyeTelescopesContinued.netkan

First time I use the `x_netkan_override` stanza, so this maybe needs some adjustments

Make sure v0.6.10 is compatible with KSP 1.0.5

---

NetKAN/Mk2Expansion.netkan

Add dependency

---

NetKAN/VectorRepurposed.netkan

Closes #2582 
Changed license to proper syntax

Closes #2582

---

NetKAN/ActivateWhenShielded.netkan

Add ActivateWhenShielded

---

NetKAN/SVE-HighResolution.netkan
NetKAN/SVE-LowResolution.netkan
NetKAN/SVE-MediumResolution.netkan
NetKAN/SVE-UltraResolution.netkan
NetKAN/StockVisualEnhancements.netkan

I added a filter for the `EVE` folder in `StockVisualEnhancements.netkan` so that the textures, that will be chosen by the user, don't get overwritten.
Merge **after** #2553
closes #2581

Add StockVisualEnhancements

---

NetKAN/FMRS.netkan

Reformat and min/max ksp version

---

NetKAN/SubmarineSystems.netkan

Add SubmarineSystems

---

NetKAN/Sirens.netkan

Add Sirens

---

NetKAN/AtmosphericPartsSupplyCo.netkan

Add AtmosphericPartsSupplyCo

---

NetKAN/FuelTanksTIMES2.netkan

Add FuelTanksTIMES2

---

NetKAN/USI-FTT.netkan

The newest release corrects the errors present in the previous version's .version file.

Add KSP-AVC support for FTT

---

NetKAN/Kopernicus.netkan

Merge after release of Kopernicus v0.5

Update Kopernicus for 1.0.5

---

NetKAN/RealFuels.netkan

Don't merge until next RF release...

Update RF netkan for KSP 1.0.5.

---

NetKAN/AdvancedJetEngine.netkan

* Remove KS link since it's outdated
* Use AVC for KSP versioning.

AJE netkan updates

---

NetKAN/ChineseTianGongScienceSpaceStation.netkan

Add ChineseTianGongScienceSpaceStation

---

NetKAN/DefaultActionGroups.netkan

Add DefaultActionGroups

---

NetKAN/DiscontinuedParts.netkan

Add DiscontinuedParts

---

NetKAN/SpaceLaunchSystemPartPack.netkan

Add SpaceLaunchSystemPartPack

---

NetKAN/DIRECTLaunchVehicles.netkan

Add DIRECTLaunchVehicles

---

NetKAN/RealHumans.netkan

Add RealHumans

---

NetKAN/HumanColoredFaces.netkan

Add HumanColoredFaces

---

NetKAN/ChenowthMPPV.netkan
NetKAN/EagleTransporterSP1999.netkan
NetKAN/MrFusionmk3.netkan

Install more of luiz' mods into Skunk_Works and updated licenses

Luiz update

---

NetKAN/FrozenTechnologies125mExpansion.netkan

Inlcudes MM into the download, but doesn't require it for any files.
Closes #2653

Add FrozenTechnologies125mExpansion

---

NetKAN/StrykersAerospaceandIVAs.netkan

Add StrykersAerospaceandIVAs

---

NetKAN/AGExt.netkan

Remove support fields. Not sure why they were added, AGX explicitly supports all actions in any mod.

Remove "supports" fields from AGX

---

NetKAN/B1BLancer.netkan
NetKAN/B2SpiritStealthBomber.netkan
NetKAN/B52H.netkan
NetKAN/DassaultRafale.netkan
NetKAN/EF111bRaven.netkan
NetKAN/F111Aardvark.netkan
NetKAN/F4E1PhantomInterceptor.netkan
NetKAN/MiG21Fishbed.netkan
NetKAN/Mig25Foxbat.netkan
NetKAN/Mirage2000.netkan
NetKAN/Mq9PredatorDrone.netkan
NetKAN/SukhoiAircraftSU25FrogFoot.netkan
NetKAN/TheF8Crusader.netkan
NetKAN/WingDropTanks.netkan
NetKAN/YT1300StockLightFreighter.netkan

Add 15 more of LuizChacon's craft mods
**Close PR's**
Closes #2528, Closes #2530, Closes #2534, Closes #2579, Closes #2594, Closes #2610, Closes #2611, Closes #2632, Closes #2634, Closes #2636, Closes #2652, Closes #2665, Closes #2669, Closes #2675, Closes #2677

Add more mods of LuizChacon

---

NetKAN/GimbalForAll.netkan

Add GimbalForAll

---

NetKAN/AlternatorsForAll.netkan

Add AlternatorsForAll

---

NetKAN/SuperStrongStruts.netkan

Add SuperStrongStruts

---

NetKAN/KerbalTubes.netkan

Add KerbalTubes

---

NetKAN/Mari-HighTorqueRW.netkan

Add Mari-HighTorqueRW

---

NetKAN/BalastanksExtended.netkan

Add BalastanksExtended

---

NetKAN/ASETAvionics.netkan
NetKAN/ASETProps.netkan

Update for 1.0.5

---

NetKAN/StrykersAerospaceandIVAswithASET.netkan
NetKAN/StrykersandAerospaceIVAswithASET.netkan

Add StrykersandAerospaceIVAswithASET

---

NetKAN/BDynamicsMk22Cockpits.netkan

Add BDynamicsMk22Cockpits

---

NetKAN/Outboardmotor.netkan

Add Outboardmotor

---

NetKAN/SigmaBinary-core.netkan
NetKAN/SigmaJoolRecolor.netkan
NetKAN/SigmaOPMExpansion.netkan
NetKAN/SigmaOPMRecolor.netkan
NetKAN/SigmaPluronKhato.netkan
NetKAN/SigmaStockRecolor.netkan

Update the Korpernicus version and use `min_version` instead of `version`

Update Sigma's mods

---

NetKAN/PlanetShine-Config-Default.netkan
NetKAN/PlanetShine.netkan

Fix PlanetShine

---

NetKAN/HumanColoredFaces.netkan
NetKAN/RealHumans.netkan

These mods made a `TextureReplacer` folder inside `TextureReplacer`

Duplicate folders

---

NetKAN/AGroupOnStage.netkan
NetKAN/ClampsBeGone.netkan
NetKAN/InFlightFlagSwitcher.netkan

Update forum links

---

NetKAN/StarTrekTOSTunics.netkan

Add StarTrekTOSTunics

---

NetKAN/SR71BlackbirdMk2wIVA.netkan

Add SR71BlackbirdMk2wIVA

---

NetKAN/ThrustIndicationModule.netkan

Add ThrustIndicationModule

---

NetKAN/KerbalSuitcases.netkan

Add KerbalSuitcases

---

NetKAN/RustyTexturesForProceduralParts.netkan

Add RustyTexturesForProceduralParts

---

NetKAN/Saab39Gripen.netkan

Add Saab39Gripen.netkan

---

NetKAN/WW2Warships.netkan

Add WW2Warships

---

NetKAN/ThrustIndicationModule.netkan

Foldername now includes a version number `v1.1`

Folder now has a version number

---

NetKAN/AlternisRealSolarSystem.netkan
NetKAN/BilliardsPlanetPack.netkan
NetKAN/KPlus.netkan
NetKAN/NewHorizons.netkan
NetKAN/OtherWorlds.netkan
NetKAN/OuterPlanetsMod.netkan
NetKAN/SigmaBinary-core.netkan
NetKAN/SigmaJoolRecolor.netkan
NetKAN/SigmaPluronKhato.netkan
NetKAN/SigmaStockRecolor.netkan

* Added AlternisRealSolarSystem
* Added BilliardsPlanetPack
* Added OtherWorlds
* Added more conflicts

Add new packs

---

NetKAN/MagiCore.netkan

Also updated the "homepage" to use the new forum structure.

Update MagiCore KSP Version and License

---

NetKAN/DangerAlerts.netkan

I *think* I figured out this pull request thing...
Closes #2741

Adding DangerAlerts from KerbalStuff

---

NetKAN/B9AnimationModules.netkan

Add B9AnimationModules

---

NetKAN/TrimPlus.netkan

netkan for my new plugin TrimPlus.

add TrimPlus

---

NetKAN/StockRealismRebalances.netkan

Add StockRealismRebalances

---

NetKAN/HangarExtender.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2775

New ksp_version for new release

---

NetKAN/ShipSections.netkan

Just noticed that I messed up the name on the NetKAN file.  This'll fix it.

Update ShipSections NetKAN name.

---

NetKAN/kspboatparts.netkan

Add kspboatparts

---

NetKAN/PossiblePropulsion.netkan

Add PossiblePropulsion

---

NetKAN/X34PersonalTransport.netkan

Add X34PersonalTransport

---

NetKAN/HermesInterplanetarySpacecraft.netkan

Add HermesInterplanetarySpacecraft

---

NetKAN/AntennaRangePatch4OctoSat.netkan

Add AntennaRangePatch4OctoSat

---

NetKAN/BetterCrewAssignment.netkan

Add BetterCrewAssignment

---

NetKAN/TantaresFairingExtension.netkan

Add TantaresFairingExtension

---

NetKAN/HeatResistantSpaceplanePartsHRP.netkan

Add epoch for HeatResistantSpaceplanePartsHRP

---

NetKAN/Asclepius-clouds.netkan
NetKAN/Asclepius.netkan

Resolves https://github.com/KSP-CKAN/CKAN-meta/pull/877

Add epoch and force v for Asclepius and Asclepius-clouds

---

NetKAN/WernhersOldBits.netkan

Add WernhersOldBits

---

NetKAN/WinterKerbol.netkan

Add WinterKerbol

---

NetKAN/SaruPlanetPack.netkan

Add SaruPlanetPack

---

NetKAN/StarTrekTOSSpaceSuits.netkan

Modder has gone from 1.2 to 0.4

Add Epoch to StarTrekTOSSpaceSuits.netkan

---

NetKAN/LanderControl.netkan

Add LanderControl

---

NetKAN/BearPodMKI.netkan

Add BearPodMKI

---

NetKAN/B9-PWings-Fork.netkan

Adding compatibility fork of B9AerospaceProceduralParts. Tested locally

Add B9-Pwings-Fork.netkan

---

NetKAN/B9.netkan
NetKAN/B9AerospaceProceduralParts.netkan
NetKAN/MK2KSPIIntegration.netkan
NetKAN/Mk3HypersonicSystems.netkan
NetKAN/RP-0.netkan

Merge after #2827 
Jenkins will fail because this mod isn't added yet.

Use new mod, part of #2827

---

NetKAN/ChineseLunarLanderWithRover.netkan

Add ChineseLunarLanderWithRover

---

NetKAN/Radialstackdecoupler.netkan

Add Radialstackdecoupler

---

NetKAN/RP-0.netkan

@Schnobs combined your request with the 1.0.5 change

RP-0 Upgrade to 1.0.5, require AsteroidDay, other changes

---

NetKAN/ContractConfigurator-KerbinSpaceStation.netkan

Closes https://github.com/KSP-CKAN/NetKAN/issues/2836

Mod getting a new `name` on next release.

---

NetKAN/AmazingCurveEditor.netkan
NetKAN/CrewManifest.netkan
NetKAN/CustomBarnKit.netkan
NetKAN/GCMonitor.netkan
NetKAN/KlockheedMartian-Gimbal.netkan
NetKAN/MechJeb2.netkan
NetKAN/ModularFlightIntegrator.netkan
NetKAN/ModuleManager.netkan
NetKAN/SmokeScreen.netkan

Add AmazingCurveEditor, CrewManifest, CustomBarnKit, GCMonitor, KlockheedMartian-Gimbal, MechJeb2, ModularFlightIntegrator, ModuleManager and SmokeScreen.
The ones I'm not sure about are:
* KlockheedMartian-Gimbal as this file already exists
* MechJeb2 as all the releases are downloaded from curse but @Sarbian began using Jenkins for the last 2 - 3 releases.

Add Sarbian's mods

---

NetKAN/BearPodMKI.netkan

Author now uses 1 instead of I

Update BearPod Mk1

---

NetKAN/AlternisKerbolRekerjiggered.netkan
NetKAN/BilliardsPlanetPack.netkan
NetKAN/ToySolarSystem.netkan

**AlternisKerbolRekerjiggered**
* Add ModuleManagers as a dependency
* Update `min_version` to `1:beta-05-2`
* Add conflicts
**BilliardsPlanetPack**
* Update conflicts
**ToySolarSystem**
* Update conflicts

Update Planet packs

---

NetKAN/KerbalMechanics.netkan

Expand range for current version.

Update KerbalMechanics.netkan + x_netkan_override

---

NetKAN/OuterPlanetsMod.netkan

the latest update (1.9) of OPM now higly recommends SigmaBinary

OuterPlanetsMod update

---

NetKAN/NavUtilities.netkan

See http://forum.kerbalspaceprogram.com/index.php?/topic/77062-102-navutilities-ft-hsi-amp-instrument-landing-system-v051-rc-1-june-2015/&page=9#comment-2313380

Updated NavUtilites compatible version.

---

NetKAN/Kronkus.netkan

Update Kronkus.netkan - Force v

---

NetKAN/GAP.netkan

Add Giving Aircraft a Purpose (GAP)

---

NetKAN/ProceduralParts.netkan

Add install stanza, filter source for ProceduralParts

---

NetKAN/KerbalAircraftExpansion.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/2863

Add epoch to KerbalAircraftExpansion

---

NetKAN/KerbalKrashSystem.netkan

Add Kerbal Krash Systems - fixed Kerbalstuffbot submission

---

NetKAN/Super100ShootingStarSuper67LittleStarCommandPods.netkan

Add Super100ShootingStarSuper67LittleStarCommandPods.netkan (fixed KerbalStuff submission) 

---

NetKAN/UKS.netkan
NetKAN/USI-Kolonization.netkan
NetKAN/USI-MKSLite.netkan

Updated UKS, MKS-Lite, and Kolonization for RoverDudes mods (fixes broken installs)

---

NetKAN/AtmosphereAutopilot.netkan

Hi!
AtmosphereAutopilot is a flight control system designed to replace the stock SAS.
Website: http://forum.kerbalspaceprogram.com/index.php?/topic/124417-105
Please add it to CKAN!

Add AtmosphereAutopilot

---

NetKAN/KerbalObjectInspector.netkan

Only the licence string needed fixing here, so I'm going to go ahead and merge.
Fixes #2894

Add Kerbal Object Inspector (fixed kerbalStuffBot submission)

---

NetKAN/KerbodynePlus.netkan

replaces #2972, with suggestions from mod author in #2982

Add Kerbodyne Plus (fixed KerbalStuff submission)

---

NetKAN/SpaceXLandingLegs.netkan

Nice simple parts mod which came very close to having a successful KerbalStuffBot submission
Replaces #2882

Add SpaceXLandingLegs (fixed KerbalStuffBot submission)

---

NetKAN/CrossFeedEnabler.netkan

See https://github.com/KSP-CKAN/NetKAN/pull/2997#issuecomment-179290309

Restrict ksp version compatibility of CrossFeedEnabler

---

NetKAN/Scatterer.netkan

Bumping epoch to catch up to latest version thanks to non-netkan-friendly versioning.

Scatterer epoch bump

---

NetKAN/AutoRove.netkan
NetKAN/DockingcameraKURSstyle.netkan

Minor fixes I spotted in reviewing recent merges. Huge thanks to @politas and @pjf for going through them.
Seeing you guys push some merges fills me with *determination*.

Catchup on old merges

---

NetKAN/NearFuturePropulsionExtras.netkan

Waiting on approval from @lOmicronl either here or in #2975.

Restrict NearFuturePropulsionExtras to ksp 1.0.4 max.

---

NetKAN/RealScaleBoosters.netkan

Waiting on approval from @NecroBones either here or in #2970.

Install stanza for RealScaleBoosters

---

NetKAN/TurboNisu.netkan
NetKAN/TurboNisusPartsPack.netkan

Add Turbo Nisus Parts Pack (fixed KerbalStuff submission)

---

NetKAN/KerbalCitiesPack.netkan
NetKAN/kerbalcitiespack.netkan

Add kerbal cities pack (fixed KerbalStuffBot submission)

---

NetKAN/Aerostats.netkan

Add Aerostats (fixed KerbalStuffBot submission)

---

NetKAN/KASAssembledAreobrakingShield.netkan

Add KAS Assembled Areobraking Shield (fixed KerbalStuffBot submission)

---

NetKAN/RealSolarSystem.netkan

Once this is merged #2950 can be re-examined.

Change RSSTextures to recommends

---

NetKAN/ZPEPropulsionSystem.netkan

Add ZPE Propulsion System (fixed KerbalStuffBot submission)

---

NetKAN/BD-AWP.netkan
NetKAN/BDAdvancedWeaponsPackBDAddon.netkan

Add BD - Advanced Weapons Pack

---

NetKAN/RealSolarSystem.netkan

Revert "Change RSSTextures to recommends"

---

NetKAN/FacilityReset.netkan
NetKAN/FacilityResetfor64bitKSP.netkan

Add FacilityReset (fixed KerbalStuffBot submission with author input)

---

NetKAN/WalkAbout.netkan

Add WalkAbout (fixed KerbalStuffBot submission)

---

NetKAN/HermesInterplanetarySpacecraft.netkan

Fix Hermes Interplanetary Spacecraft

---

NetKAN/KerbalTubes.netkan

Fix Kerbal Tubes

---

NetKAN/StrykersAerospaceandIVAs.netkan

Fix folder structure and new dependencies

Fix StrykersAerospaceandIVAs

---

NetKAN/KerbalTimer.netkan

Add KerbalTimer (fixed KerbalStuffBot submission)

---

NetKAN/BatteryIndicator.netkan

Add Battery Indicator (fixed KerbalStuffBot submission) 

---

NetKAN/PrakasaAeroworks.netkan

Add Prakasa Aeroworks (fixed KerbalStuffBot submission)

---

NetKAN/MasterTechAerospace.netkan

Folder name changed, added dependencies and added suggestion

Fix MasterTechAerospace

---

NetKAN/Impact.netkan

Latest update had no leading 'v'
Fixes KSP-CKAN/CKAN-meta/issues/941

Fix Impact

---

NetKAN/Olympic1ARPIcons.netkan

USI mods now require `CommunityResourcePack`

Update suggested mods

---

NetKAN/nofuel.netkan

Added NoFuel mod as requested by @leocadle in #2943

Added nofuel mod

---

NetKAN/ETTWBImodscompatibilitypatch.netkan
NetKAN/WBIforETT.netkan

Add WBIforETT (fixed KerbalStuffBot submission)

---

NetKAN/KSCShipyard.netkan

Add KSC Shipyard (fixed KerbalStuffBot submission)

---

NetKAN/StockReplacementAssets.netkan

Add Stock Replacement Assets (fixed KerbalStuffBot submission)

---

NetKAN/TheCube.netkan
NetKAN/TheCubetransformableblocksdesignedtofityourstructuralneeds.netkan

Add The Cube (fixed KerbalStuffBot submission)

---

NetKAN/RSSVisualTweaks.netkan
NetKAN/RSSVisualTweaksandScienceDefinitions.netkan

Add RSS Visual Tweaks (fixed KerbalStuffBot submission)

---

NetKAN/TheCube.netkan

Didn't see the "banner" on the forum thread

Fixes #3056

---

NetKAN/NANAWildfire.netkan

Add N.A.N.A. Wildfire (fixed KerbalStuffBot submission) 

---

NetKAN/SnackPartsByWhyrenUPDATED51.netkan
NetKAN/SnackPartsUpdated.netkan

Add Snack Parts Updated (fixed KerbalStuffBot submission)

---

NetKAN/FlatBottomSpaceplaneParts.netkan
NetKAN/RaginCaucasian.netkan

With input from Mod author.
Closes #3020
Closes #3070

Add Flat-Bottom Spaceplane Parts (fixed KerbalStuffBot submission) 

---

NetKAN/DMagicScienceAnimate.netkan

Add DMagicScienceAnimate

---

NetKAN/Strut.netkan
NetKAN/StrutPlus.netkan

Add StrutPlus (fixed KerbalStuffBot submission)

---

NetKAN/BlackRibbon.netkan

Add BlackRibbon

---

NetKAN/RN-MiscParts.netkan
NetKAN/RN-SalyutStations-SoyuzFerries.netkan
NetKAN/RN-Skylab.netkan
NetKAN/RN-SovietProbes.netkan
NetKAN/RN-SovietRockets.netkan
NetKAN/RN-USProbesPack.netkan
NetKAN/RN-USRockets.netkan

-Add file for new misc part mod
-Update old files to be 1.0.5 compatible

RN mod update and add

---

NetKAN/B9-props.netkan
NetKAN/B9.netkan
NetKAN/B9AerospaceHX.netkan
NetKAN/B9AerospaceLegacy.netkan
NetKAN/B9AnimationModules.netkan
NetKAN/B9PartSwitch.netkan

They're all in their respective Github repositories now

External NetKAN files for all B9-related mods

---

NetKAN/kOS.netkan

Update kOS.netkan to point at a netkan file managed by the kOS team.

Update kOS netkan

---

NetKAN/DarkMultiPlayer.netkan

Hopefully I didn't break it :D

Update DarkMultiPlayer's netkan file to spacedock

---

NetKAN/CargoTransportationSolutions.netkan
NetKAN/Olympic1ARPIcons.netkan

Move to SpaceDock

---

NetKAN/NAS.netkan

Update NAS netkan file to SpaceDock

Update NAS to SpaceDock

---

NetKAN/FerramAerospaceResearch.netkan

So as we all now FAR is the alpha and the omega for certain mods, like RO, so lets try and get it working.
I haven't done one of these "in a while" so there's no way I'm merging this on my own until someone who understands the regex and can verify everything works as it should so I'm pinging @dbent

Move FAR from outdated KS to Github

---

NetKAN/ImageViewer.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3121

ImageViewer to spacedock

---

NetKAN/notes.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3119

Notes to SpaceDock

---

NetKAN/JoolBiomes.netkan

Add JoolBiomes (fixed KerbalStuffBot submission)

---

NetKAN/GAP.netkan

Update and rename GAP.kerbalstuff to GAP.netkan

---

NetKAN/WernhersOldBits.netkan

I did this, but my github fu is sorely lacking and I think I may have clicky clicked too quickly somewhere because it wasn't done.  If there's two though, they should be the same.

Spacedocking Wernher's stuff again

---

NetKAN/NMSG.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3122

NMSG to spacedock, updated recommends, hardcode license

---

NetKAN/SolarisHypernautics.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3181

SolarisHypernautics to SpaceDock

---

NetKAN/OScienceLaboratories.netkan

A science mod that includes the testing of Kerbal pee :grinning:

Add OScienceLaboratories, closes #3124

---

NetKAN/ETT.netkan

ETT to SpaceDock

---

NetKAN/Mk2CockpitExpansion.netkan

Mk2CockpitExpansion to Spacedock

---

NetKAN/TMSTACLSRetexture.netkan

Move TMS TAC Retexture to Spacedock

---

NetKAN/Chatterer.netkan

Move Chatterer to Spacedock

---

NetKAN/RustyStarRockets.kerbalstuff
NetKAN/RustyStarRockets.netkan

Move Rusty Star Rockets to SpaceDock

---

NetKAN/KSABetterFairings.netkan

KSA Fairings

---

NetKAN/VersatileToolboxSystem.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3217

Add VersatileToolboxSystem

---

NetKAN/KSAIVAUpgrade.netkan

Update KSA IVA Upgrade

---

NetKAN/KerbalConstructionTime.netkan

KerbalConstructionTime to spacedock

---

NetKAN/BetterBurnTime.kerbalstuff
NetKAN/BetterBurnTime.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3243

BetterBurnTime to spacedock

---

NetKAN/SimpleFemaleKerbals.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3232

Add SimpleFemaleKerbals

---

NetKAN/Deltaglider.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3126

Deltaglider to spacedock

---

NetKAN/BehemothAerospaceEngineeringLargeParts.netkan

Move Behemoth Aerospace Engineering Large Parts to SpaceDock

---

NetKAN/VersatileToolboxSystem-TACLSPack.netkan
NetKAN/VersatileToolboxSystem-USIPack.netkan
NetKAN/VersatileToolboxSystem-core.netkan

Add VersatileToolboxSystem-core, VersatileToolboxSystem-TACLSPack, VersatileToolboxSystem-USIPack

---

NetKAN/SaruPlanetPack.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3254

SaruPlanetPack to spacedock

---

NetKAN/StandardPropulsionSystems.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3260

StandardPropulsionSystems to spacedock

---

NetKAN/DunaSpaceProgram.netkan
NetKAN/EveSpaceProgram.netkan
NetKAN/LaytheSpaceProgram.netkan

Pinging @GregroxMun and @Sigma88 to let you both know this is being added to CKAN: if you could ping us to let us know any time you add a new space program location it would be highly appreciated.
Closes https://github.com/KSP-CKAN/NetKAN/pull/2940

Add AlienSpacePrograms (Duna, Eve, Laythe)

---

NetKAN/BlacklegIndustries.netkan

Fix BlacklegIndustries

---

NetKAN/KIS.netkan

Last two releases of Kerbal Inventory System has been released on github, so I took the liberty creating this.

Add KIS.netkan

---

NetKAN/PEWPromethiumExperimentalWeaponry.netkan

Move PEW to SpaceDock

---

NetKAN/SixSeatMk3cockpit.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3289

SixSeatMk3cockpit to spacedock

---

NetKAN/SixCrewScienceLab.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3287

SixCrewScienceLab to spacedock

---

NetKAN/HangarGrid.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3282

Add HangarGrid

---

NetKAN/WalkAbout.netkan

WalkAbout to spacedock

---

NetKAN/TMEME-TheMostEssentialModEver.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3288

Add TMEME-TheMostEssentialModEver

---

NetKAN/PhoenixIndustriesCubeSat.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3286

Add PhoenixIndustriesCubeSat

---

NetKAN/PhoenixIndustriesBoosters.netkan
NetKAN/PhoenixIndustriesFlags.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3285

PhoenixIndustriesBoosters to spacedock

---

NetKAN/PhoenixIndustriesCargoResupplySystem.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3284

PhoenixIndustriesCargoResupplySystem to spacedock

---

NetKAN/FantomWorksKAXPartPack.netkan

Move FantomWorks to SpaceDock

---

NetKAN/Muffler.netkan

Closes https://github.com/KSP-CKAN/NetKAN/pull/3305

Add Muffler

---

NetKAN/ZPEPropulsionSystem.netkan

RSR ZPE to Spacedock - closes #3314

---

NetKAN/KSCFloodlight.netkan

KSCFloodlight to spacedock - closes #3308

---

NetKAN/Kosmodrome.kerbalstuff
NetKAN/Kosmodrome.netkan

license is on forum thread + spacedock

Kosmodrome -> spacedock - closes #3307

---

NetKAN/SimpleNuclear-NFT.netkan
NetKAN/SimpleNuclear.netkan

License on forums says `CC-BY-NC-SA-4.0`
Closes #3301

Add SimpleNuclear

---

NetKAN/Mk2Expansion.netkan

The files are in mk2expansion's .zips, we should install them.

Change dependency from IFS-core to IFS proper.

---

NetKAN/RandSCapsuledyne.netkan

RandSCapsule -> Spacedock - closes #3356

---

NetKAN/SpaceXBargeLander.netkan

Add SpaceX Barge Lander

---

NetKAN/TheBlueDrill.netkan
NetKAN/TheBlueScoop.netkan

Update TheBlueDrill and TheBlueScoop

Update BlueTech Parts

---

NetKAN/RP-0.netkan

Localize RP-0 netkan

---

NetKAN/SimpleNuclear-NFT.netkan
NetKAN/SimpleNuclear-NFTBalanced.netkan
NetKAN/SimpleNuclear.netkan

Add SimpleNuclear-NFT-Balanced and conflict with SimpleNuclear-NFT

Add SimpleNuclear NFT Balanced, closes #3344

---

NetKAN/DangIt.netkan

Update DangIt to spacedock

---

NetKAN/SimpleNuclear.netkan

Pushing as soon as Jenkins clears this as we shouldn't have a mod that fails on installation.

Fix conflicting recommends

---

NetKAN/VersatileToolboxSystem-USIPack.netkan

Per [mod author](http://forum.kerbalspaceprogram.com/index.php?/topic/70312-105-versatile-toolbox-system-added-usi-support/&page=2#comment-2433021)

Remove karbonite as dependency

---

NetKAN/xScience.netkan

Hardcoded the `author` for the original author (`Brodrick`) and the maintainer (`Z-Key Aerospace`).

Add xScience

---

NetKAN/SimpleNuclear-NFT.netkan
NetKAN/SimpleNuclear-NFTBalanced.netkan
NetKAN/SimpleNuclear.netkan

A more comprehensive fix to this situation. My last PR (https://github.com/KSP-CKAN/NetKAN/pull/3374) was the fastest/easiest I could do with the time I had available.

Create virtual mod to provide a choice between SimpleNuclear-NFTBalanced and SimpleNuclear-NFT

---

NetKAN/Asclepius.netkan
NetKAN/ContractConfigurator-Asclepius.netkan
NetKAN/Kronkus-clouds.netkan

@MrChumley it'd be awesome to have your input on this. We were just made aware that your mod has CC contracts and it'd be great to offer them to our users in a way you think makes sense. What I'm currently proposing is adding `ContractConfigurator-Asclepius` as a sperate module and essentially treating it in the same way as `Asclepius-clouds`, so it's a recommendation from the base mod and it requires the base mod to be installed as well as `ContractConfigurator`.

Add CC-Asclepius, Kronkus-clouds and modify relationships

---

NetKAN/AutoAsparagus.netkan

Pretty much like #1229, just without typos :)

AutoAsparagus: recommends SmartStage
