KSP-CKAN/NetKAN

NetKAN/Hangar.netkan

The current version of Hangar.dll is linked with the requirement of the local
copy of KSPAPIExtensions.dll in the GameData/Hangar/Plugins/

Corrected Hangar.netkan. Added suggestions and removed KSPAPIExtensions filter as it breaks the installation.

---

NetKAN/RoutineMissionManager.netkan

The netkan file as created by kerbal stuff had wrong install instructions.
This file is works correct and was tested by netkan.exe and ckan.exe utilities.

correct netkan file for routine mission manager

---

NetKAN/PlanetShine-Config-Default.netkan
NetKAN/PlanetShine.netkan

Preparatory work for other mods that tweak the PlanetShine config - Astronomer's Pack is one of them.

Split PlanetShine into core and default config

---

NetKAN/ExtraPlanetaryLaunchpads-RegolithAdaptation.netkan

EPL-Regolith is on Kerbalstuff now. This improves upon the hand-written meta file that fetched its archive from dropbox.

Added EPL Regolith Adaptation

---

NetKAN/EnvironmentalVisualEnhancements-HR.netkan
NetKAN/EnvironmentalVisualEnhancements-LR.netkan
NetKAN/EnvironmentalVisualEnhancements.netkan

So it seems my previous correction of the EVE split was only partially correct. Not only the directories were inverted, but the entire mod was too. It is not the core mod that needs to be split into HR and LR variants, but rather the default configuration.
This PR makes EnvironmentalVisualEnhancements-HR and -LR into default configuration packages in their respective resolutions, renames EnvironmentalVisualEnhancements-Config-Default into EnvironmentalVisualEnhancements and makes it into the core package. The whole thing now finally makes sense.

Environmental Visual Enhancement: Core Mod and Config split, act 2

---

NetKAN/PartMapper.netkan

The spec doesn't have a `beta` status as far as I can tell. This sets it
to `testing` (which is in the spec).

PartMapper: Fix release status beta -> testing

---

NetKAN/RFStockalike.netkan

Had a request on the KSP forum to change the name so it appears next to RealFuels in the program. Seemed like a good idea.

Updating RFStockalike name so it appears near RealFuels in the GUI

---

NetKAN/TestFlight.netkan

This is pulling from GitHub instead of KerbalStuff on purpose.  GitHub is my main distribution, as it is automated.  KerbalStuff releases may or may not always be up to date.

Add TestFlight NETKAN

---

NetKAN/KerbalWeatherSystems.netkan
NetKAN/KerbalWind.netkan

The FAR Wind API currently supports only one client at any time,
so these two must conflict.
Using a provides so it's easy to extend in the future.

KWS must conflict with KerbalWind

---

NetKAN/NearFuturePropulsionExtras.netkan

Adds the ability to install the optional ModuleManager configs bundled
with NearFuturePropulsion for nuclear engines.

NearFuturePropulsion MM patches for nukes

---

NetKAN/EngineIgnitor-Unofficial-Repack.netkan

The repack works just fine in 0.90 as well as 0.25, and remains
identical to the official release, so I've made a new release with
updated AVC info. This PR updates the metadata to use the `find` keyword
for locating the files, removing a rather ugly kludge with a hard-coded
version number.

Updated EngineIgnitor repack

---

NetKAN/Protractor.netkan

And yes, I'm the current maintainer of Protractor, blessed by MrEnigma03. A user asked that I support CKAN, and so here it is! Tested it and it seems just fine. Thank you!
And yes, it is licensed under the CC-0 license. I will add a note as such in my LICENSE file in the new version which I am releasing extremely soon (working on that now, in fact). Probably be there by the time you get to merging this.

Added .netkan file for Protractor.

---

NetKAN/ADIOS.netkan

I'll confirm on the forums that Arachnidek is fine with this change, but he should be since he currently bundles ContractConfigurator and the current NetKAN strips it out.  This changes makes the CKAN install more consistent with a manual install of ADIOS.

ADIOS dependency on ContractConfigurator.

---

NetKAN/Firespitter.netkan

I'm not sure why Firespitter.cfg was filtered out in the first place but it makes KSP start on loadup with firespitter installed through CKAN since FirespitterCore does not contain the .cfg file.
Relevant forum thread [here](http://forum.kerbalspaceprogram.com/threads/113809) and shoutout to @NathanKell who brought it to my attention.
I'm unsure if this will autogenerate a new (fixed) .ckan file, if not can someone trigger that interaction and/or tell me how to?

Fixing firespitter to work through CKAN

---

NetKAN/ControlLock.netkan

The CKAN spec specifies that mods *must* start with a letter. Despite
the fact that `netkan.exe` will process this file, it may not in the
future, and at the moment our bot chokes on the validation phase.
This change renames the identifier to one that's CKAN friendly.
Unfortunately, users who already have the mod installed won't be able to
auto-upgrade with the identifier change, but they can uninstall with the old
identifier and install with the new identifer just fine.

Rename 001ControlLock to just ControlLock

---

NetKAN/KOSMOS-SSPP.netkan

According to a user in the KOSMOS forum thread SSPP works fine in 0.90 so I'm updating it manually to get solar panels available for #939
Filtering out Flags and readme as to not collide with KOSMOS-URM (see #940)

patch KOSMOS-SSPP to work with 0.90

---

NetKAN/KOSMOS-URM.netkan

Version in CKAN-meta is _old_ and it seems to be due to folderstructure having changed in a newer release. This should hopefully fix it.

KOSMOS-URM : file -> find to circumvent new folderstructure

---

NetKAN/ImprovedStrategies.netkan

closes https://github.com/KSP-CKAN/NetKAN/issues/554
This change should make stuff load in the right order for the mod to work based on the issuereport linked above.

Patch ImprovedStrategies metadata

---

NetKAN/AmpYearPowerManager.netkan
NetKAN/KabinKraziness.netkan

KK depends on AmpYear and that's how I found that it seems to have updated it's folderstructure. This commit adds KK and fixes AY metadata.
Supercedes https://github.com/KSP-CKAN/NetKAN/pull/910

Add KabinKraziness.netkan and fix AmpYear metadata

---

NetKAN/EngineIgnitor-Unofficial-Repack.netkan

closes https://github.com/KSP-CKAN/CKAN-meta/issues/337
Since this is a repack by @pjf I'd like him to be able to comment on this PR before we consider merging it. This is the first (only?) unofficial repack I see in CKAN so I'm not sure what the policy are for these.
I can see no reason that this should depend on RealFuels, I assume it is because it is part of RO or something along those lines? I also added the recommended mods from the forum thread for EngineIgnitor as recommends in the metadata.
Proposed changes are based on the issuereport which this PR closes.

Fix metadata of EngineIgnitor-Unofficial-Repack

---

NetKAN/IR-Model-Rework-Utility.netkan

Depends on #951 and requires a solution to https://github.com/KSP-CKAN/NetKAN/issues/932 since it depends on those mods. An alternate route might be to have this install and conflict with `CIT-Util` and `ActiveStruts` since it redistributes them within the .zip.
We'll see once #951 is merged how to resolve this, CIT mods might be back on the market by the time IR-Rework have had their first release.

add Infernal robotics model rework - utility pack

---

NetKAN/CommunityResourcePack.netkan

This seems to be the reason all USI mods are stuck in limbo and I'm tired of being asked about them already so I'm doing a manual fix.
Latest version in CKAN-meta is the one compiled for 1.0 so this will overwrite that and everyone will be happy.

Manual update of CRP ksp_version field

---

NetKAN/InfernalRobotics.netkan
NetKAN/ProceduralFairings.netkan

Their respective githubs have notes saying the newest versions are 1.0 compatible so this is just a matter of changing the hardcoded version.
IR should probably be moved over to KerbalStuff in the .netkan file to resolve this for them forever.

Change version fields on pFairings and IR

---

NetKAN/AntennaRange.netkan

Why this even has a ksp_version field is beyong me, so I'm removing it to let us use the awesome metadata of KerbalStuff.

remove ksp_version field from antennarange

---

NetKAN/RandSCapsuledyne.netkan

Removed an ampersand that's no longer part of the foldername we want to install.

Fixing .netkan for RSCapsuledyne

---

NetKAN/InfernalRobotics.netkan

KS seems to be getting updates faster than Github, KS also has better metadata so I'm undoing my switch over to github for this mod and going back to KS.
Original switch was because it seemed github would deprecate the KS entry and add a new one, this did not happen so there's no reason not to use KS.

InfernalRobotics Github->KS

---

NetKAN/FShangarExtender.netkan
NetKAN/RealismOverhaul.netkan

closes https://github.com/KSP-CKAN/NetKAN/issues/866
This will look interesting for 0.90 users since they will keep the duplication but for users of KSP 1.0 and up this fixes the double Hangar Extender in the modlist.
I choose to keep HangarExtender rather than FSHangarExtender since it was created first. I also updated RO to properly recommend the now correct mod.
notifying @Felger that I've done this since he created the original FShangarExtender which I now deprecate.

Fix duplication of HangarExtender for 1.0 and up

---

NetKAN/OuterPlanetsMod.netkan

DDS loading functionality is now stock in v1.0 and the DDSLoader plugin
will not be updated.
http://forum.kerbalspaceprogram.com/threads/96729?p=1869823#post1869823

Remove DDSLoader dependency from OuterPlanetsMod

---

NetKAN/OPTMk3MiniExpansion.netkan

Based on https://github.com/KSP-CKAN/CKAN-meta/issues/261 I'm hereby locking OPTMk3... to 0.90 so the problem will not move on over to KSP 1.0.
This will have a negative effect on people who have the "wrong" one installed in CKAN and then updates to 1.0 of KSP without clearing their modcache. This crowd have so far not been gigantic and this is one of the few ways I can think of to fix this without horrible breaking stuff for 0.90 users seeing as we lack a means of deprecation.
notifying @TeddyDD and @hakan42 who discussed the original issue.

Hardcode OPTMk3MiniExpansion to 0.90

---

NetKAN/VesselView.netkan

closes #1103 
There is an old handpackaged version of this mod that has a different set of workings to get it working. 
The mod author has chosen to only upload the complete edition to Kerbalstuff and not the broken into smaller pieces versions that only depend on Toolbar or RPM rather than, as in this case, both. I've elected to add the same one to NetKAN in an attempt to fullfill the wishes of the mod author and as such I've repackaged this to use a simpler format than the older handpackaged ones.
The versions available since earlier stop the compatibility at ksp_version_max 0.25 and as such I forsee no conflicts by the above way of working.

Add VesselView.netkan

---

NetKAN/K2CommandPod.netkan

Author did an update of the license on KS and changed it from MIT to something the bot can't read since it's not in CKAN.schema, this fixes it.

Update license for K2CommandPod

---

NetKAN/CryoEngines.netkan

In v0.1.3 dependency on Firespitter was replaced with dependency on
InterstellarFuelSwitch.

Update dependencies for CryoEngines

---

NetKAN/RasterPropMonitor-Core.netkan
NetKAN/RasterPropMonitor.netkan

closes https://github.com/KSP-CKAN/CKAN-meta/pull/434
Basically I set the RPM version numbers to the ones from Kerbalstuff
RPM-Core does not contain a .version file since it does not install the folder which contains it making an older hardcoded value being used instead. A solution for this specificsituation is probably to switch over to using KS hosting which will give us less exact ksp_version fields but will make them consistent for both Core and RPM and preventing this situation from occuring again.

Switch RPM over to KS hosting for ksp_version consistency

---

build.sh

I looked through the build.sh and from what I gather this is the only file I need to change to update the build parameters for Jenkins?
Expected outcome of these changes:
- Jenkins will properly run his tests as if he was on KSP version 1.0.2
- Jenkins "KSP install" will now properly have the `/Ships/@thumbs` folder introduced in KSP 1.0.0
Worries:
- Will the "@" in the foldername be a problem?

Update Jenkins - Help wanted

---

NetKAN/EnvironmentalVisualEnhancements-HR.netkan
NetKAN/EnvironmentalVisualEnhancements-LR.netkan

The current setup seems to have a weird interaction with astronomers pack and tbh I've never seen one like it.
This change will fail the build since the two packs inherently conflict.
This PR will make EVE behave like all other mods who have provide/conflict solutions.

Change provide/conflict fields in EVE to match eachother

---

NetKAN/Firespitter.netkan
NetKAN/FirespitterCore.netkan

Jenkins approved these but it seems they missed some fields required for Github indexing, namely `name` and `abstract`.
See if this solves it!

Figuring out why firespitter isn't indexing

---

NetKAN/FirespitterCore.netkan

I'm going insane about this file.
Missed adding a subfolder in the install-stanza. This'll probably force people to totally reinstall it on the next update of firespittercore which will lead to some backlash. I'm terribly sorry, firespitter was kinda stressed out due to public demand and then changed around between hosts to find the most up to date version and fix the versioning of previous versions.
This is hopefully the last change I'll ever do to firespittercore.

Last (?) update of firespitter

---

NetKAN/KeepFit.netkan

When launching, KeepFit complains that it should now be installed directly in the GameData directory.  This untested change ought to put it where it belongs.

Adjusts KeepFit installation directory.

---

NetKAN/DangIt.netkan

We no longer depend on CrewFiles now that we have switched to the stock XP system.

Update DangIt dependencies for upcoming 1.02 compatible version

---

NetKAN/UniversalStorage.netkan

Because it does, upgrading fails as we try to overwrite an
auto-generated file. This causes it to be ignored.
Closes KSP-CKAN/CKAN#853.

UniversalStorage shouldn't be packaging MiniAVC.xml

---

NetKAN/PortableScienceContainer.netkan

The zip file has a change in the naming scheme, this should fix it.

PortableScienceContainers: Fix install stanza.

---

NetKAN/TarsierSpaceTechnologyWithGalaxies.netkan

The zip file is the latest version does not match the install stanza in the netkan file. Updated to reflect the changes, such that netkan-bot can process it again.

TarsierSpaceTech: Update install stanza to reflect zip file path.

---

NetKAN/RocketWatch.netkan

The zip file contains the version of the mod, thus netkan can't autoindex it when it updates.

Rocketwatch: Fix install stanza to reflect the change in the filename.

---

NetKAN/KWRocketry.netkan

KWRocketry 2.7 includes a new dependency, ModuleAnimateEmissive, that seems
to be only distributed by KWRocketry and is only used by KWRocketry. So
make KWRocketry depend on and provide ModuleAnimateEmissive.
If something else in the future depends on ModuleAnimateEmissive it should
be straightforward to update.
This could really use a `find_regexp` in the `install` stanza.

Update KWRocketry and Add ModuleAnimateEmissive

---

NetKAN/InstellIncorporatedExperimentalEngines.netkan

Suppresses license warning on accepted license, adds missing dependency on FirespitterCore and fixes install stanza. @Dazpoet may be able to answer is the ships part is necessary.
Closes #1182.

Add InstellIncorporatedExperimentalEngines, modified from automated PR.

---

NetKAN/KWRocketry-LegacyFairings.netkan

Adds the legacy (non-procedural) fairings included in the extras portion of the distribution. These fairings require nuFAR to be used properly.
I would like to have used a `find` clause in the `install` stanza, but what I really want is to express:
"*Find* `OldFARFairings`  *Then Find* `KWRocketry`", something like a `find_regexp`: `OldFARFairings/.*/KWRocketry`, which I don't believe exists.

Add KWRocketry-LegacyFairings

---

NetKAN/Firespitter.netkan
NetKAN/FirespitterCore.netkan
NetKAN/FirespitterResourcesConfig.netkan
NetKAN/KerbalAircraftExpansion.netkan

Changes:
- FirespitterCore now use #1227 as a source
- Moved conflicting file Firespitter.cfg from Firespitter to new package
- Updated Firespitter and KAX to depend on new package (FirespitterResourcesConfig)
- addev ksp/avc $vref to Firespitter (instead of hardcoded "ksp_version")
- removed PartCatalog support from Firespitter (it's no longer present in
Firespitter zip archive - version 7.1.2)
- filter some files from KAX (zip file with old textures)
- added missing dependency to KAX (ModuleManager)
This should fix/close:
https://github.com/KSP-CKAN/NetKAN/pull/1217
https://github.com/KSP-CKAN/CKAN-meta/issues/472
https://github.com/KSP-CKAN/CKAN-meta/issues/356
https://github.com/KSP-CKAN/NetKAN/pull/1227
https://github.com/KSP-CKAN/CKAN/issues/859
If you want to test this you can …

Firespitter new core

---

NetKAN/KWRocketry.netkan
NetKAN/ModuleAnimateEmissive.netkan
NetKAN/SolverEngines.netkan

As requested by @NathanKell 
I split out ModuleAnimateEmissive since we have a case of a mod depending on it in KW.
Upcoming version of RealFuels and AJE depends on SolverEngines.
100% handwritten .netkan files so I'm bound to get some errors on the first run through Jenkins

Add SolverEngines and ModuleAnimateEmissive

---

NetKAN/RealFuels.netkan

For some unknown reason our indexer overwrote itself.
After #1404 was merged the bot triggered and built https://github.com/KSP-CKAN/CKAN-meta/commit/4e698cb3440787b67731a8361a90504e4495ecac
Then a while afterwards https://github.com/KSP-CKAN/CKAN-meta/commit/c4895bc8b7644f959bb2dfa06d18fbf9fd438208 came along and ruined everything and leaving us with a borked version.
I'm hoping that pushing this minimal formatting change will force the bot to retrigger and fix what it broke once and for all. This is an extremely suboptimal way of doing this but it's the only one I can come up with while nearly falling asleep in my chair.
Pinging @techman83 who might be able to explain what went wrong here?

RealFuels needs a forced update

---

NetKAN/KSPInterstellarExtended.netkan

KSPI-E needs InterstellarFuelSwitch 1.4 otherwise people vessels might explode/implode

KSPI-E needs InterstellarFuelSwitch 1.4

---

NetKAN/Hangar.netkan
NetKAN/KSPAPIExtensions.netkan

KSPAPIExtensions clashes wildly with how CKAN does things. Reading its [forum thread](http://forum.kerbalspaceprogram.com/threads/81496-0-90-KSPAPIExtensions-V1-7-2-Utilities-for-shared-mod-use-16-Dec?p=1184389&viewfull=1#post1184389) it states that each mod should install it's own version of the .dll and the thread also includes confirmation of this still being the case  [here](http://forum.kerbalspaceprogram.com/threads/81496-0-90-KSPAPIExtensions-V1-7-2-Utilities-for-shared-mod-use-16-Dec?p=1664750&viewfull=1#post1664750).
Right now we have mods both installing and not installing their own version of KSPAPIExtensions which is the worst of both worlds. Mods like NearFuturePropulsion and ExtraplanetaryLaunchpads bundle the .dll while a [single …

Deprecate KSPAPIExt by confining it to 0.90

---

NetKAN/ContractConfigurator-KerbinSpaceStation.netkan

Specifically, the forums state that it depends on Contract Configurator 0.7.12 or higher, but right now it's (hypothetically) possible to meet the dependency with something as low as 0.3.2, as the new "$vref" line allowed it to work on KSP 0.9 as well.

Updates the Kerbin Space Station file.

---

NetKAN/A6Intruder.netkan
NetKAN/F117.netkan
NetKAN/F14CTomcat.netkan
NetKAN/F18ASuperHornet.netkan

Both are tested and working locally on a KSP 0.90 install.
.craft file from F18 not installed since I cannot install to a subfolder of Ships as per the CKAN spec.
BDArmory not a distinct dependency for A6Intruder but it seems you can't do much without it so I've elected to have it as a dependency for it. Text on F18 page is not as outspoken about needing BDArmory which is why it "merely" recommends it.
GPL-3.0 chosen as license for F18 since afaik it's the most restrictive of the 3 listed ones (CC-BY-NC-4.0, GPL-3.0 and WTFPL)

Add the BD crafts from KSCSM

---

NetKAN/AerojetKerbodyne.netkan
NetKAN/RealPlume.netkan

This is adds the `ModuleManager` dependency to `AerojetKerbodyne` and `RealPlume` to compliment KSP-CKAN/CKAN-meta#554.

Add ModuleManager dependencies to AerojetKerbodyne and RealPlume

---

NetKAN/SCANsat.netkan

https://github.com/KSP-CKAN/CKAN-meta/issues/563 pointed out that SCANSat 12.1 wasn't in CKAN and although the problem seems to originate from the [NetKAN-bot outage](https://github.com/KSP-CKAN/NetKAN-bot/issues/13) the removal of the v from the version is bound to cause grief down the road so I'm fixing it here, which should also force-index SCANSats latest version.

Adding a forced v to SCANSat

---

NetKAN/PhoenixIndustriesCargoResupplySystem.netkan

I wonder if this works... if it does it's amazing.
So currently we have https://github.com/KSP-CKAN/CKAN-meta/pull/528 which added a small and large version of this mod. Both versions are now consolidated into a single package so we can catch it with a .netkan rather than handpackaging. Both old mods provide and conflict with this identifier.
I'm not sure if this will provide and upgradepath though or if old users will have to reinstall. Also names of the parts appears to have changed to accomodate for both being in the same package so the update is most probably craftbreaking.

Add PhoenixIndustries...netkan

---

NetKAN/EpicSuits.netkan

Never used this mod or TextureReplacer, but I'm taking for granted that the previous .netkan install paths still hold true, this is just that .netkan with new installs for the new folders, and it's in alphabetical order for simplicity in reading.
"epic suits/EVAtexture.png" install removed (file not present in new zip).
Resolves #1483... probably.

Epic suits update

---

NetKAN/HGR.netkan

depends on #1476 
Reusing identifier and install stanza from CKAN-meta where we currently index an earlier version from when this was only available on curse.

Add HGR.netkan

---

NetKAN/A6Intruder.netkan
NetKAN/A7Corsair2.netkan
NetKAN/AV8HarrierWITHTRUEVTOLFlight.netkan
NetKAN/AircraftIVAHelmet.netkan
NetKAN/EF2000EuroFighter.netkan
NetKAN/F14CTomcat.netkan
NetKAN/F15DCStrikeEagle.netkan
NetKAN/F16FightingFalcon.netkan
NetKAN/F18ASuperHornet.netkan
NetKAN/F22Lightning2OrRaptor.netkan
NetKAN/F35BSTOLStealthMultiroleFighter.netkan
NetKAN/FairchildRepublicA10Warthog.netkan
NetKAN/MIG29Fulcrum.netkan
NetKAN/SukhoiSU27Flanker.netkan

AircraftIVAHelmet depend added to all planes from this author as, according to https://kerbalstuff.com/mod/872/Aircraft%20IVA%20Helmet it's unclear *which* planes actually require it.
Some KS pages for these mods don't explicitly state any dependencies, though from the screenshots they seem to use the same parts, therefore planes with no explicit dependencies will have the "Standard 4" dependencies of FirespitterCore, BDArmory, BahamutoDynamicsPartsPack, and AircraftIVAHelmet.
All mods licensed under WTFPL as per http://kscsm.freeforums.net/thread/20/question-licenses-dependencies-ckan-indexing
Closes #1441 - Depends per KS page
Closes #1442 - Depends per KS page
Closes #1448 - Depends per KS page
Closes #1456 - Filtered cockpit from archive, added depend to AircraftIVAHelmet
Closes #1470 …

Added 10 planes and edited another 5 from LuizChacon.

---

NetKAN/StockBugFixModules.netkan

Now that StockBugFixModules distributes two zip files in its releases, let's be explicit about which one to use.
Also, hardcode `repository` due to KSP-CKAN/CKAN#1075.

Use explicit asset_match for StockBugFixModules

---

NetKAN/RandSCapsuledyne.netkan

CKAN thinks that the 1.5.01 version of this mod is higher than 1.5.1, or atleast it reports the incorrect version as newest.
`ckan compare 1.5.1 1.5.01` and `ckan compare 1.5.01 1.5.1` both give `-1` as output so something if afoot, but this should solve it and stop causing grief to the author.

Bump epoch of RandSCapsuledyne

---

CONTRIBUTING.md

Alternatively, the links can both go to outside sources (http://opensource.org/licenses/MIT and https://creativecommons.org/publicdomain/zero/1.0/legalcode) to future-proof them from any changes in the repo files/structure.

Fixed links

---

NetKAN/ContractConfigurator-KerbinSpaceStation.netkan
NetKAN/ContractConfigurator-UsefulSpaceStations.netkan

Quote from the author on being asked about installing both.
> I wouldn't recommend it - as they are now, CC would complain that you've got 2 contracts with the same name. You could workaround, and make them work together, but there would not be much point.
http://forum.kerbalspaceprogram.com/threads/113642-1-0-2-Severedsolo-s-Space-Station-Contract-Packs?p=2006147&viewfull=1#post2006147

Add conflicts to space station contract packs

---

NetKAN/UKS.netkan

Blizzy's Toolbar is not used by UKS.
Refs:
* http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-%28MKS-OKS%29-%280-30-3%29-2015-05-22?p=1150243&viewfull=1#post1150243
* http://forum.kerbalspaceprogram.com/threads/79588-1-0-2-USI-Kolonization-Systems-(MKS-OKS)-(0-30-3)-2015-05-22/page1003?p=1997534#post1997534

Remove Toolbar dependency for UKS.

---

NetKAN/RSSTextures2048.netkan
NetKAN/RSSTextures4096.netkan
NetKAN/RSSTextures8192.netkan

These have previously been manually indexed but are now up for grabs here on GitHub \o/
Having never used asset_match before I'm not sure these are correct in all ways but "Works on my machine (TM)"
While making these I noticed the ones over in CKAN-meta are rather malformed and also have `"ksp_version" : "any"` so I'll head over there and slap a _max onto them and confine them to 0.90 since these new ones take over from there.
There are no distinct DDS texturepacks anymore since KSP is all about DDS now, I've therefore elected to use the identifiers `RSSTextures*` rather than `RSSTexturesDDS*` and hope that is acceptable for all parties.

Add rss textures

---

NetKAN/FerramAerospaceResearch.netkan

According to KSP-CKAN/CKAN#1174, FAR's releases are sorting funny.
This bumps the epoch so the latest release is considered the latest
release, no matter how funny the version numbers are.
I've also fixed some errant whitespace. :)

Bump FAR epoch number.

---

NetKAN/CivilianPopulation.netkan

CKAN is listing 1.41 (for KSP 0.90) instead of 1.6.2 (for KSP 1.0.2). 1.41 was supposed to be 1.4.1

Add epoch to CivilianPopulation

---

NetKAN/DeadlyReentry.netkan

DR comes with MM 2.6.5, so this makes sure that users actually have
that installed. :)

DeadlyReentry now has a minimum ModuleManager version.

---

NetKAN/TACLS.netkan

This requires KSP-CKAN/CKAN#1197 to be merged to actually function,
but can be safely be merged before then (as `x_netkan_override` is
ignored in the current netkan build).
Part of KSP-CKAN/CKAN#1184.

Latest TACLS works on KSP 1.0.2-1.0.4

---

t/metadata.t

These update the tests run on our PRs to spot common problems with
`x_netkan_override`. It insists that the field, if present:
- Must contain an array of overrides
- All overrides must have a version
- Overrides must have a delete section, an override section, or both.

Basic tests for x_netkan_override

---

NetKAN/Firespitter.netkan
NetKAN/FirespitterCore.netkan

We were doing this for the full FS package, but not the core.
Closes #1675.

Always start FireSpitter versions with `v`.

---

NetKAN/Proton-Bobcat.netkan
NetKAN/SovietEngines.netkan
NetKAN/StripSymmetry.netkan

Final preening of the great metadata clean in KSP-CKAN/CKAN-meta#628.
Note: At least two of these files were produced by @Felger. If the
Proton and Soviet engines are known to work under 1.0.x, let us know
(or send us a PR) and we'll merge that for great justice!

Fix min/max on Proton-Bobcat, SovietEngines, and StripSymmetry

---

NetKAN/Kerbulator.netkan

The author bumped the supported version in the [forum thread](http://forum.kerbalspaceprogram.com/threads/69406-1-0-3-Kerbulator-use-your-own-math!).
Is this how the metadata for the supported version work?

Update Kerbulator to support up to KSP 1.0.4

---

NetKAN/KerbalJointReinforcement.netkan

provide ranged version override of ksp_version for compat marking 1.0.2, 1.0.3, 1.0.4

KerbalJointReinforcment v3.1.4 minmax override

---

NetKAN/KerbalFoundries.netkan

Part of KSP-CKAN/CKAN-meta#628.
Depends upon KSP-CKAN/CKAN#1209 being merged in order for `netkan.exe`
to parse the upstream data.
Resulting output on patched `netkan.exe`:
```
{
"spec_version": "v1.4",
"identifier": "KerbalFoundries",
"license": "GPL-3.0",
"recommends": [
{
"name": "TweakScale"
}
],
"install": [
{
"find": "KerbalFoundries",
"install_to": "GameData"
}
],
"resources": {
"homepage": "http://forum.kerbalspaceprogram.com/threads/84102-WIP-PARTS-PLUGIN-0-23-5-Kerbal-Foundries-wheelpack-anti-grav-repulsors",
"repository": "http://included%20in%20the%20download",
"kerbalstuff": "https://kerbalstuff.com/mod/58/Kerbal%20Foundries%20Wheels%20and%20Repulsors%20ALPHA"
},
"name": "Kerbal Foundries Wheels and Repulsors ALPHA",
"abstract": "Better wheels and anti-gravity repulsors", …
```

KerbalFoundries works on 1.0.2 to 1.0.4

---

NetKAN/DockingPortAlignmentIndicator.netkan

Added min-max 1.0.2-1.0.4 override to netkan file.

DockingportAlignmentIndicator 6.2 KSP Override using min-max

---

NetKAN/CommunityTechTree.netkan

Remove conflict on OpenTree since that now apparently does not [conflict](http://forum.kerbalspaceprogram.com/threads/122571).
Replaces KSP-CKAN/CKAN-meta#654

Remove OpenTree conflict from CommunityTechTree

---

NetKAN/EnginesPlus.netkan

Currently awaiting a response on which license the mod is under.
[Forum thread](http://forum.kerbalspaceprogram.com/threads/127424) indicates CC-BY-ND-4.0 but CC-BY-NC-SA-4.0 is the license in the archive.

Add EnginesPlus.netkan

---

NetKAN/NearFutureProps.netkan

Works in 1.0.4, currently at 1.0.2 and likely will not be rebuilt for it due to no changes needed.
Stockalike Station Parts Expansion depends on this and *is* already updated for 1.0.4 in the CKAN-Meta, so overriding NearFutureProps should make it visible for install via CKAN.  
Already tested and installed on my local test instance via local ckan file installs

NearFutureProps-0.4.2 override ksp min=1.0.2 max=1.0.4

---

NetKAN/RaptorAerospacial-Textures.netkan
NetKAN/Super100ShootingStarCommandPod-heatshield.netkan
NetKAN/Super100ShootingStarCommandPod.netkan
NetKAN/Super67LittleStarCommandPod-heatshield.netkan
NetKAN/Super67LittleStarCommandPod.netkan

Should close #1625, close #1588
5 packs to add 2 parts from 2 KerbalStuff pages. Common files are extracted from Super100 because it seems to be the 'base' (and was up to date at the time of this writing).
```
\---RaptorAerospacial
+---Extras
|       Fairing.dds * Exists in both archives, provided by RaptorAerospacial-Textures
|       Heatshield 2.5.cfg * Only needed for Super67, provided by Super67-heatshield
|       Heatshield.cfg * Only needed for Super100, provided by Super100-heatshield
|       heatshield.dds * Exists in both archives, provided by RaptorAerospacial-Textures
|       Heatshield.mu * Exists in both archives, provided by RaptorAerospacial-Textures
|       
+---Spaces
|   \---IVA_S100 * Only needed for and provided by Super100
|           IVA.dds
|           IVA_S100.cfg …
```

Add Super 67 and 100 command pods

---

NetKAN/SCANsat.netkan

Module Manager is more-or-less required for full SCANsat functionality now, so it should probably go in the depends section.
I'm not sure if that override section is still needed, but I left it as is.

Update SCANsat depends section

---

NetKAN/RemoteTech.netkan
NetKAN/SCANsat.netkan
NetKAN/SDHI-ServiceModuleSystem.netkan
NetKAN/TarsierSpaceTechnologyWithGalaxies.netkan

Less an issue for 1.0.4, but an issue that means there are no releases for 1.0.2.

Force v for RemoteTech.netkan

---

NetKAN/EmDrive-TweakPatch.netkan
NetKAN/EmDrive.netkan

Closes #1596
I used `find_regexp` because I think `Emdrive R1` is likely to change names. The end result of the install isn't pretty `GameData/EmDrive/EmDrive R1` but since this is a parts-only pack there's no reason to think it will create any files that would prevent the `EmDrive R1` folder from being deleted and replaced with `EmDrive R2` down the line.

Add EmDrive

---

.gitignore
t/metadata.t

This is a hacky fix for the version comparison issue. Being that 1.10 is less than 1.2 and 1.4. It works and will do for this time of the evening.

Fix spec 1.10 test

---

build.sh

Currently the build script for Jenkins fails if:
* The PR contains multiple files with inter-dependencies (e.g. https://github.com/KSP-CKAN/NetKAN/pull/1145).
* The KSP version is not the latest (e.g. https://github.com/KSP-CKAN/NetKAN/pull/1420).
This attempts to solve this by:
* Use a local metadata file in the form of master.tar.gz, which contains all .ckan files but the one being tested.
* Create dummy KSP installs matching the min KSP version requested by the .ckan file being tested.
Will depend on the static build of https://github.com/stedolan/jq (Not included in this PR) to extract json identifiers.
Any comments welcome, shell scripting is not my force.
Tested on https://github.com/KSP-CKAN/NetKAN/pull/1420 without error locally. My git-fu is not strong enough to figure out how to …

Build script update

---

NetKAN/RP-0.netkan

The netkan side of CKAN-meta#701.

Extant RP-0 releases should be for KSP 0.90 only.

---

NetKAN/NearFutureElectrical.netkan

changed to Recommends until/unless is changed back.
Per release note comment 0.5.2: 
"Retuned radiator and reactor parts to work with stock radiator system"
Installed and tested, it works without HeatControl.  Verified by user post in forum as well.

NearFutureElectrical-0.5.2 no longer depends on HeatControl-Core

---

NetKAN/SerialIO.netkan

Also forced prepending `v` onto the version due to past version number
inconsistencies.
Closes KSP-CKAN/CKAN#1280.

SerialIO works fine in v1.0.4 (override)

---

NetKAN/NearFuturePropulsionExtras.netkan

Running the existing NearFuturePropulsionExtras.netkan file through netkan.exe revealed a syntax error causing parsing to fail.

Fix syntax error for provides field of NearFuturePropulsionExtras.netkan

---

NetKAN/ProceduralParts.netkan

I've found that Procedural Parts will not run without Module Manager. See Swamp-Ig/ProceduralParts#152

Change ProceduralParts to depend on ModuleManager

---

NetKAN/SigmaBinary-DunaIke.netkan
NetKAN/SigmaBinary-core.netkan

Paging @Sigma88 for input.
`SigmaBinary-core` installs the `GameData` contents and has an abstract which informs users that this mod on its own won't create binary systems.
`SigmaBinary-DunaIke` installs the Duna + Ike binary system to `GameData/Sigma/BinaryExpansion` (would like to know if you prefer a different destination)
In using `SigmaBinary-core` as the idenfitier (seen only to CKAN's code) it would allow for easy creation of an eventual `SigmaBinary` install which includes the core and the default binaries, or can easily accept binaries from other sources. Currently the mod's name (visible to users) is `Sigma Binary` to help people find it and to provide simplicity until such a time as a full `SigmaBinary` install exists.
A question though, do .cfgs like `DunaIke.cfg` conflict …

Add SigmaBinary-core and SigmaBinary-DunaIke

---

NetKAN/DeadlyReentry.netkan

- No longer depends on ModularFlightIntegrator (mentioned in the 7.2.1 release notes)
- Force a 'v' onto the version string, as DR seems to lose them starting with 7.2.0

Deadly Reentry adjustments

---

NetKAN/BULB.netkan

Noticed that https://github.com/KSP-CKAN/CKAN-meta/commit/7a189015ff68eedd3e4a3c00ba9ef4606e451f00 breaks the mod for 1.0.2 users. Opened KSP-CKAN/NetKAN-bot#26 with more information.
The change in this PR simply adds an override to the version which will give us the appropriate compatibility range.

Restore 1.0.2 compatibility for BULB-1.1.2

---

NetKAN/KerbolPlus.netkan

Updated hosting from KerbalStuff (their old page is 404) to github.
Updated KerbolPlus' part of the stanza to reflect folder changes.
I'm trusting that @Dazpoet in #983 knew what he was doing so I didn't touch relationships to other mods or the KittopiaSpace install.

Update KerbolPlus.netkan to use github

---

NetKAN/KerbinSideAirRace.netkan

Resolves KSP-CKAN/CKAN-meta#706 in a non-fragile way at the expense of user resources (to the tune of 18 duplicate textures being loaded)

Alternative to #1916 aka "The Blue Pill"

---

NetKAN/ALCOR.netkan
NetKAN/ALCORIVAPatch.netkan
NetKAN/ASETProps.netkan

Closes #1965, closes #1966 , closes #1967 
Adding the ALCOR IVA as a `depends` to ALCOR because we don't index the VNG plugin, and without either ALCOR IVA or the VNG plugin parts of the capsule will be broken.

Add ALCOR suite of mods

---

NetKAN/RoutineMissionManager.netkan

If there's a way to just have a range of versions, I'd love to know about it.

Add 1.0.4 override for new version of RoutineMissionManager

---

NetKAN/RasterPropMonitor.netkan

I haven't been with the project for very long, and this change seems to date back to #6 so i'd like to get input from someone more senior than me. (@dbent looking your way)
I *think* `VesselView-RasterPropMonitor` was always meant to be `VesselView`. I can say with certainty that there's currently no mod with the ID `VesselView-RasterPropMonitor` but maybe it existed in the past.

Change RasterPropMonitor suggested mods

---

NetKAN/FuelSwitchtoeverytank-default.netkan

According to #1981, these mods shouldn't conflict.

Remove conflict with InterstellarFuelSwitch-Core

---

NetKAN/Telemachus.netkan

Otherwise v1.4.26.0 gets loaded, which is old

Telemachus should have a leading 'v'.

---

NetKAN/BetterBuoyancy.netkan

BB requires it. So the netkan should too.

Make BetterBuoyancy require MM

---

NetKAN/KWRocketry-CommunityFixes-interstage.netkan
NetKAN/KWRocketry-CommunityFixes.netkan
NetKAN/KWRocketry.netkan

And add conflict to netkan of KWRocketry (Community fixes are to be applied to non-netkan version of KWRocketry).
@dbent would love a second set of eyes on this.
Thanks to @TeddyDD whose metadata I basically copy + pasted.
Related issue: https://github.com/KSP-CKAN/CKAN-meta/pull/724
This adds netkans for `CommunityFixes` and `interstage` in case they need updates. This also adds a conflict to `KWRocketry` so that any version other than `2.7.0-community` (which isn't netkan-generated) will have a conflict to the fixes.

Add KWRocketry-CommunityFixes and interstage

---

NetKAN/MacrossValkyrieVf1.netkan

:warning: DO NOT MERGE until netkan+ckan allow installation to `Ships/SPH` :warning: 
Mod has to install to folder name `Y` due to hardcoding of at least one part's mesh.
Related to https://github.com/KSP-CKAN/ckan/pull/1243
Links to mod's [KS page](https://kerbalstuff.com/mod/961/Macross%20Valkyrie%20Vf1%20) and [forum thread](http://forum.kerbalspaceprogram.com/threads/125324-VF1-Work-in-Progress)

[WIP] MacrossValkyrieVf1.netkan

---

NetKAN/ClampOTronAPAS.netkan
NetKAN/DockingTarget.netkan
NetKAN/FederalProductions-Flags.netkan

Closes https://github.com/KSP-CKAN/CKAN-meta/issues/733

Fix `ClampOTronAPAS` and `DockingTarget` both trying to install the same flags.

---

NetKAN/RKE-Kanadarm.netkan

Netkan.exe is currently too insistant on using the embedded AVC file.  This adjusts the versions somewhat.

RKE_Kanadarm works on 1.0.2 - 1.0.4

---

t/metadata.t

Part of #1257 and #1243.
Can be happily merged even before v1.12 has been released, since we can start writing metadata for v1.12 now. :)

Tests: v1.12+ required for `Ships` with path.

---

NetKAN/TarsierSpaceTechnologyWithGalaxies.netkan

Duplicate of and closes #1943. Redone to help Jenkins out.

Transform version to exclude V and v, and force epoch to deal with version inconsistencies.

---

NetKAN/FerramAerospaceResearch.netkan

Strips leading `v` and any codenames from the version number.
Test with all FAR versions currently on Kerbal Stuff:

Edit FAR Version

---

NetKAN/KerbinSide.netkan

Somewhere in the past KerbinSide made a `v0.41.1` release, but all its other releases didn't have a trailing 'v'. It's now up to `1.0.3`, but clients on the `v0.41.1` release won't auto-upgrade to that.
This change bumps the KerbinSide epoch so that existing users will get the upgrades automatically, without having to uninstall and reinstall.
Thanks to Blu3wolf for helping me spot this.

Bump KerbinSide epoch

---

NetKAN/Scatterer.netkan

Some older versions of Scatterer had a leading 'v'. New ones don't.

Scatterer: force leading 'v'.

---

NetKAN/ShipEffects.netkan

See discussion in #2157 for explanation of why the KS page changed.

Update ShipEffects' download source/kref

---

build.sh

Many mods have `ksp_version_max: 1.0.99` and dependencies fail because not all mods have such a high compatibility ceiling. So instead lets use the default ksp version when we hit 1.0.99.

Add case in build script for ksp_version being 1.0.99

---

NetKAN/KopernicusExamples.netkan

We transfered the repository for Kopernicus, seperated the examples from the main plugin.
I will release an update after the changes have been merged (that's why the exaples depend on a Kopernicus 0.3.2).
Cheers
Thomas

[Kopernicus] seperated examples / moved repository

---

NetKAN/NewHorizons.netkan

These are the minimum required changes to allows indexing of `NewHorizons` versions past 1.35.
I'd like to dig into the relationships more but just don't have the time at the moment.
Pinging @Olympic1 in the hopes you can look into it more as you're sorting through the `PlanetPacks` mods.
Closes KSP-CKAN/CKAN-meta#767
Closes #2199 
Edit: I realized after I had done the first two commits that #2199 had all the same changes, so I took @pjf's formatting and added `netkan_epoch` to it.

Update NewHorizons.netkan for new versions

---

NetKAN/RoboBrakes.netkan

NetKAN currently broken, this should fix it and continue working if the folder reverts to 'RoboBrakes'.

Fix 'Module contains no files to install.'

---

NetKAN/ContractConfigurator-MaritimeMissionsandBoatNavigationPlugin.netkan

There is an argument to be made for splitting this into multiple mods, but as the author hasn't split it, I opted to keep it as one module (for now).
For posterity: If this mod is to be split, the contracts should remain under the ID `ContractConfigurator-MaritimeMissionsandBoatNavigationPlugin` with a `name` hardcoded and the plugin should be split into a new .netkan.

Add ContractConfigurator-MaritimeMissionsandBoatNavigationPlugin

---

NetKAN/TrackingStationAmbientlight.netkan

New version disables itself when the other mod is detected

Remove TrackingStationAmbientlight conflict with AmbientLightAdjustment.

---

NetKAN/PersistentThrust.netkan
NetKAN/SolarSailNavigator.netkan

Fix PersistentThrust and SolarSailNavigator, change to pull from Github rather than Kerbalstuff at author's request.  Aware this is redundant to KerbalStuffBot, this is a better netkan overall.

PersistentThrust and SolarSailNavigator

---

NetKAN/EngineerLevelFixer.netkan

I entered a mod the other day, but I didn't realize that I needed to declare it has a ModuleManager dependency or that it has a KSP AVC file.

Fixed EngineerLevelFixer to include it's ModuleManager dependency

---

NetKAN/NyrathsUSAFOrion.netkan

The auto generated NyrathsUSAFOrion.netkan from Kerbal Stuff seems to have been broken first by lack of clear install folders, and secondly by me using a long license description.  And then I think I've muffed the git pull/push fixups to the point neither I nor github have any clue which file is which.
Anyway, this is a fresh netkan file with extra details to match spec where info is available.  I've left x_via in as per the auto, 'cos I'm not sure if that's needed for the version checking.

Replacing Auto NyrathsUSAFOrion.netkan

---

NetKAN/SCANsat.netkan

As stated in #2248 SCANsat now includes this functionality (as of v14.2), so adding a conflict to the current .netkan will update the v14.2 .ckan and onward.
Closes  #2248

Add conflict to ContractConfigurator-ScanSatLite as it's now included in SCANsat

---

NetKAN/Mk2Expansion.netkan

Problem described here - http://forum.kerbalspaceprogram.com/threads/121224-1-04-Mk2-Expansion-v1-6-UDATE-9-24-2015?p=2231443&viewfull=1#post2231443
Don't know if epoch needs to be bumped over that or not.
Tested compatibility with all available on Kerbal Stuff versions, that's why not a version override.

Fixed dir structure error

---

build.sh

This change instructs git/build.sh to only examine files which have changed on the current branch from its most-recent-ancestor of `origin/master`. This is better than the absolute differences, as it means `origin/master` can change as much as it likes and we don't care.
Tested locally. I'm sure there's an issue number for this somewhere, so feel free to edit this PR to include that. :)

build.sh: Evaluate only changes on branch, not absolute diffs

---

NetKAN/QuickHide.netkan

Toolbar is not a dependency since QuickHide v2.00

Updated QuickHide

---

NetKAN/EVAHandrailsPackContinued.netkan
NetKAN/EvaHandrailsKISCompatibility.netkan

Added this as a suggestion to EVAHandrailsPackContinued as KIS is very popular and presenting the patch to users is probably a good choice.
Closes https://github.com/KSP-CKAN/NetKAN/pull/2389

Add EvaHandrailsKISCompatibility

---

NetKAN/Ktolemy.netkan

@Olympic1 part of https://github.com/KSP-CKAN/CKAN-meta/issues/588 but I can tell you up front it should conflict with every other pack. It places Kerbin in the center of the system and has every other planet revolving around it.
Closes https://github.com/KSP-CKAN/NetKAN/pull/2433

Add Ktolemy

---

NetKAN/SigmaOPMExpansion.netkan
NetKAN/SigmaOPMRecolor.netkan
NetKAN/SigmaPluronKhato.netkan

`SigmaOPMExpansion` was split into 3 mods.
`SigmaPluronKhato` are 2 planets, `SigmaOPMRecolor` is a recolor of one of the OPM planets, and "SigmaOPMTilt" I kept under the ID `SigmaOPMExpansion` to provide some kind of upgrade path (`SigmaOPMExpansion` is discontinued and old links are dead).
Branched under the NetKAN repo to allow anyone to modify as needed.
See the referenced issue for any missing details.
Closes https://github.com/KSP-CKAN/NetKAN/issues/2382
@Olympic1 `SigmaPluronKhato` will fall under your planetpack purview. https://github.com/KSP-CKAN/CKAN-meta/issues/588
@Sigma88 let me know if you want modifications to the relationships (if you want them to recommend each other or any others from your suite of mods).

Sigma expansion split

---

NetKAN/KSAIVAUpgrade.netkan

`ASETAvionics` isn't currently a dependency but according to the author it will be in future versions (and rather than the mod breaking later on I'd rather future-proof things now).
Closes  #2477

Add KSAIVAUpgrade

---

NetKAN/SigmaBinary-DunaIke.netkan
NetKAN/SigmaBinary-core.netkan
NetKAN/SigmaJoolRecolor.netkan
NetKAN/SigmaModExpansions.netkan
NetKAN/SigmaRTExpansion.netkan
NetKAN/SigmaStockRecolor.netkan

* `SigmaStockRecolor` was split into `Jool Recolor` (new) and `Eve Recolor` (holds identifier).
* `SigmaRTExpansion` was moved to github and renamed to `Sigma: Antennas` (holds identifier).
* `SigmaModExpansions` was moved to github and renamed to `Sigma: OuterSpaceComms` (holds identifier).
* `SigmaBinary` was split into `SigmaBinary-core` and `SigmaBinary-DunaIke` (both hold there identifier).

Sigma split

---

NetKAN/StockPlus.netkan

Locally this still works (but so does the original) and the hope is that it'll get this mod unstuck from the fail list on http://status.ksp-ckan.org bringing this mod's version to parity with its brother StockBugFixModules

Attempt to fix StockPlus by changing asset match pattern

---

NetKAN/surfacelights.netkan

SufaceMountedLights was created where surfacelights already existed. They're the same mod. Due to SufaceMountedLights being very recently created I'd like to prioritize the existing install base surfacelights has and deprecate SufaceMountedLights.
Merge before https://github.com/KSP-CKAN/CKAN-meta/pull/804

SufaceMountedLights -> surfacelights in order to give an upgrade path to the existing user base.

---

NetKAN/FerramAerospaceResearch.netkan

Newest version of FAR has the config file in the distribution whereas previous versions didn't. This causes an overwrite conflict on upgrade, so filter it out. @pjf

Filter FAR config file

---

NetKAN/StockBugFixModules.netkan
NetKAN/StockPlus.netkan

With pull #2585, Stock Bug Fix Modules and Stock Plus should work up to 1.0.4

Deprecate Stock Bug Fix Modules and Stock Plus

---

NetKAN/ModuleRCSFX.netkan

According to @NathanKell [here](http://forum.kerbalspaceprogram.com/threads/92290-1-0-4-ModuleRCSFX-v4-2-Aug-23-OBSOLETE-IN-1-0-5?p=2295817&viewfull=1#post2295817), this mod is obsolete for 1.0.5.
This pull request caps the max version to 1.0.4.

Deprecate ModuleRCSFX for 1.0.5

---

NetKAN/USI-Core.netkan
NetKAN/USI-EXP.netkan

USI-EXP: As of v0.4.3.0 it doesn't need a dependancy on `ModuleRCSFX` anymore.
USI-Core: As of v0.1.1.0 it depends on `USITools`, `CommunityResourcePack`, `FirespitterCore` and `ModuleManager`.

Update USI mods

---

NetKAN/ActivateWhenShielded.netkan

The author released a new update especially for CKAN. This change caused the mod to not get picked up by our bot because of this change and giving an error on `NetKAN Status`.

New folder structure

---

NetKAN/ModuleAnimateEmissive.netkan

ModuleAnimateEmissive only works till 1.0.4. It was included in the stock version since 1.0.5

Restrict to 1.0.4

---

NetKAN/AdjustableLandingGear.netkan
NetKAN/BahamutoDynamicsPartsPack.netkan
NetKAN/CameraTools.netkan

AdjustableLandingGear and CameraTools work with 1.0.5 according to the KS pages. BahamutoDynamicsPartsPack works fine because it uses the `BDAnimationModules.dll`, the same dll that is used for AdjustableLandingGear.
This dll can be updated by merging in KSP-CKAN/CKAN-meta/pull/831

AdjustableLandingGear

---

NetKAN/SuperHeavyBoostersHistoricalNexus.netkan

I converted my engine and fuel tank configs to stock fuel, with Module Manager config to convert to original fuels.
I *think* this is the only change needed here.  This NetKAN change is after the change in the mod (because it'd be broken if the sequence was reversed), but only slightly after.   I doubt if CKAN references the updated mod just yet (07:40 UMT 22-11-2015).  If someone looks at this pull request in the next couple of hours, it might be best to wait.

Moving to stock + recommend CRP

---

NetKAN/Asclepius.netkan
NetKAN/ForgottenWorlds.netkan
NetKAN/Insystem.netkan
NetKAN/KPlus.netkan
NetKAN/KittopiaTech.netkan
NetKAN/Kopernicus.netkan
NetKAN/NewHorizons.netkan
NetKAN/OuterPlanetsMod.netkan
NetKAN/RealSolarSystem.netkan
NetKAN/TerrestrialPlanetPack.netkan

First step of the Planet Pack overhaul.
* Added KittopiaTech, a visual planet editor plugin for Kopernicus
* Added KPlus
* Added conflicts with other planet packs
* Made the packs only work on a `min_version` of Kopernicus
* Removed the `Provides: PlanetPack` stanza's
* Reformated some files
**NOTE:** For the moment I only added/changed planet packs that are compatible with the current version of Kopernicus (v0.5.2). When a new compatible pack is released, I'll update that file.

PlanetPacks Overhaul - Part 1

---

NetKAN/AlternisKerbolRekerjiggered.netkan
NetKAN/Arkas.netkan
NetKAN/KSP-64k-12HourDay.netkan
NetKAN/KSP-64k.netkan
NetKAN/KerbolPlus.netkan
NetKAN/KopernicusExpansion.netkan
NetKAN/Kronkus.netkan
NetKAN/Ktolemy.netkan
NetKAN/NebiaAndShomma.netkan
NetKAN/RhatssPlanetpack.netkan
NetKAN/SentarExpansion.netkan
NetKAN/SigmaBinary-core.netkan
NetKAN/SigmaOPMExpansion.netkan
NetKAN/SigmaOPMRecolor.netkan
NetKAN/SigmaPluronKhato.netkan
NetKAN/SigmaStockRecolor.netkan
NetKAN/ToySolarSystem.netkan
NetKAN/sidosUraniaSystem.netkan

Second step of the Planet Pack overhaul.
Restricted all planet packs to 1.0.4 that were listed working for 1.0.5. By doing this I also needed to force the packs to use Koperncius 0.4

PlanetPacks Overhaul - Part 2

---

NetKAN/RealSolarSystem.netkan

It's obsolete to do so; RSS includes it itself now.

RSS should no longer suggest the RT2 config

---

build.sh

Function variables are global to the script, we overwrite $f inside the 'inject_metadata' function. Tested with/without changes locally duplicating the issue first and fixing it with below.

Lets test _all_ the changed NetKANs - fixes KSP-CKAN/CKAN#1479

---

NetKAN/B9-props.netkan
NetKAN/B9.netkan

Part of #2748 so that it doesn't need to install the whole `B9` mod but only the `Props` folder.
Filter out the `Props` folder in B9 and depend on `B9-props`. Also removed dependency on `FirespitterCore` and `RasterPropMonitor-Core` because these are required for `B9-props`.

Add B9-props

---

NetKAN/FutureParts.netkan

Before merging, need to that answers from author in https://github.com/KSP-CKAN/CKAN-meta/issues/892 are reflected in the metadata.
Jenkins will fail due to `BDArmory` not having 1.0.5-compatibility.
Closes https://github.com/KSP-CKAN/CKAN-meta/issues/892

Add FutureParts

---

NetKAN/B9-props.netkan

The B9 props pack shows up with the same name as the main B9 pack currently.  This prevents it from being installed by itself and prevents it from being removed once installed (except via command line).  This also reduces confusion when looking at mods to be installed.

Give B9 props a separate name

---

NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids.netkan

Version override mirrors the "if it doesn't crash KSP, it works" policy expressed in #2762. Custom Asteroids is incompatible with Kopernicus after the latter added its own asteroid feature (compatibility may be restored later; is there a way to express that only a specific version of CA has a conflict?). Other changes should be self-explanatory.

Updated Custom Asteroids for 1.2 release.

---

NetKAN/KerbinSide.netkan

Closes #2897
AirRace is separate package at Kerbal Stuff and CKAN
It shouldn't be installed by KerbinSide package.

Filter out AirRace from KerbinSide

---

NetKAN/AdvancedJetEngine.netkan

Latest version has a preceding v after never using one. This will ensure that if it's a mistake or later changes back to having no v that versioning will remain the same.

Force v for AdvancedJetEngine

---

NetKAN/TacFuelBalancer.netkan

Reports seem positive for this continuing to work in 1.0.5

Update TacFuelBalancer ksp version override

---

NetKAN/CryoEngines-SurfaceAttach.netkan
NetKAN/CryoEngines.netkan
NetKAN/CryoTanks.netkan
NetKAN/DeployableEngines.netkan
NetKAN/KerbalAtomics.netkan

Introduces new mod "Kerbal Atomics" by Nertea. Decouples two submodule dependencies that it shares with CryoEngines, to avoid duplicate installs. Updates CryoEngines to latest version. Finally, adds missing optional extra for CryoEngines.

Comprehensive CryoEngines & KerbalAtomics update

---

NetKAN/NearFuturePropulsionExtras.netkan

This optional config file is no longer being shipped with the mod nowadays. Metadata tweaked to only allow it to install in 1.0.4 or prior.

NF Propulsion Extra deprecated in KSP 1.0.5+

---

NetKAN/CryoEngines.netkan

I totally said this in the PR comments, and then failed to apply my
change. The indexer needs this so it doesn't index new CryoEngines
releases as being "old".
For #2957

CryoEngines should keep its epoch!

---

NetKAN/B9-PWings-Fork.netkan

CrossFeedEnabler is stock as of 1.0.5
**Apparently, CrossFeedEnabler mod should not be installed at all in 1.0.5**
Instead they should patch Physics.cfg (as RO does) to enable surface-attach crossfeed.

B9-PWings-Fork: do not depend on CrossFeedEnabler

---

NetKAN/LittleGreenMenFromMars.netkan

Developer is unfamiliar with CKAN, but clearly someone created this very nice complete file for the prerelease LGMFM.  KerbalStuff bot is likely to try creating the netkan file again, but I suspect it'll fail due to having the same name etc.

Little Green Men From Mars: New maintainer and dependencies

---

NetKAN/AlcubierreStandalone.netkan
NetKAN/CommunityResourcePack.netkan
NetKAN/Karbonite.netkan
NetKAN/KarbonitePlus.netkan
NetKAN/KaribouExpeditionRover.netkan
NetKAN/SoundingRockets.netkan
NetKAN/UKS.netkan
NetKAN/USI-ART.netkan
NetKAN/USI-Core.netkan
NetKAN/USI-EXP.netkan
NetKAN/USI-FTT.netkan
NetKAN/USI-LS.netkan
NetKAN/USI-MKSLite.netkan
NetKAN/USI-NuclearRockets.netkan
NetKAN/USI-SRV.netkan
NetKAN/USI-SubPack.netkan
NetKAN/USI-UKS-Shared.netkan
NetKAN/USITools.netkan

The `netkan` indexer can use `.netkan` files from other sites, but it
needs glue files to know where to fetch them from. This hange adds that
glue (and is a pretty good reference if we want to do this for other
folks, too).
Tested locally with AlcubierreStandalone and USI-SRV, but I don't have
any reason to expect any of the glue here is incorrect.
Related: #2996, #3009.

Add glue to index RoverDude's mods from his own metadata

---

NetKAN/Super100ShootingStarSuper67LittleStarCommandPods.netkan

Mod contains two files that conflict with each other. Mod uses an RPM IVA as default but it says in the `Readme.txt`:
> For non-Raster Prop Monitor IVA copy and replace the folders inside "Stock IVA" to the mod location.
So filter out the `StockIVA` and add a dependency for RPM untill the author has fixed this. @politas already mentioned this to the author on the forums.

Filter conflicting files

---

NetKAN/TACLS-Declutter.netkan

Update to point to the GitHub repository instead of the now defunct KerbalStuff.

Update to point to the GitHub repository

---

NetKAN/AlternateResourcePanel.netkan
NetKAN/FirespitterCore.netkan
NetKAN/KerbalAlarmClock.netkan
NetKAN/KerbalJointReinforcement.netkan
NetKAN/RasterPropMonitor-Core.netkan
NetKAN/RasterPropMonitor.netkan
NetKAN/RealChute.netkan
NetKAN/SCANsat.netkan
NetKAN/TextureReplacer.netkan
NetKAN/TransferWindowPlanner.netkan
NetKAN/TweakScale.netkan

These are some cornerstones in terms of dependencies and/or popular mods that should be available sooner rather than later to CKAN users.
Some of the changes are just removing old KS resources (this makes searching for old KS mods that have GitHub repos easier).
Tagging relevant authors to give them a heads up:
@TriggerAu @snjo @BobPalmer @ferram4 @MOARdV @Mihara @StupidChris @DMagic1 @ducakar @pellinor0 @Biotronic

Change from KS to GitHub

---

NetKAN/REPOSoftTech-Agencies.netkan

So people run into problems when trying to install AmpYear since it requires this mod but the latest version pointing to KS is V1.1.1.0 so hopefully this solves that issue.

REPOSoftTech-Agencies add epoch

---

NetKAN/RaginCaucasian.netkan

I don't know why the `identifier` `RaginCaucasian` was chosen.

Mk2.5 Spaceplane Parts to SpaceDock, closes #3198

---

NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids.netkan

This PR moves Custom Asteroids' krefs from KerbalStuff to SpaceDock. In addition, it fixes a mistake I made in the NetKAN file regarding which versions are incompatible with Kopernicus.

Custom Asteroids updates

---

NetKAN/KASAssembledAreobrakingShield.netkan

So this one is a bit odd.. The author uploaded version 1 to spacedock but not (or instead of) version 2 which we have a .ckan for (and a working download as well). Version 2 *is* the superior version per the ksp forum thread
> OK, I just released an update to this mod.
Changelog-
Fixed spelling (Thanks, parameciumkid!)
Converted textures to .dds.
With that in mind, I'm not adding an epoch to this netkan as I think we should be offering v2, however once the author re-releases v2 I think we should have a netkan in place to catch that.
I poked the author in http://forum.kerbalspaceprogram.com/index.php?/topic/129047-105-kas-assembled-aerobraking-shield/ to see what's up.
Closes https://github.com/KSP-CKAN/NetKAN/pull/3280

KASAssembledAreobrakingShield to spacedock

---

NetKAN/SimpleConstruction.netkan

Filtering out `InterstellarFuelSwitch.version` and `InterstellarFuelSwitch.dll` because it depends on InterstellarFuelSwitch-Core which includes these files.

Add SimpleConstruction

---

NetKAN/kRPC.netkan

kRPC 0.2.2 was released with a ```kRPC.version``` file. Adding vref field.

Get kRPC version info from ksp-avc

---

NetKAN/RealFuels.netkan

RealFuels: Remove CrossFeedEnabler

---

NetKAN/ModuleManager.netkan

Fast-tracking to stop people accidentally upgrading to it.

New ModuleManager release is targeted at KSP 1.1

---

NetKAN/RSSeaDragon.netkan

The other PR was closed for being a duplicate, but it was for a different mod's Netkan. Same change, but to a different file.

SeaDragon: remove "quicksearch" recommendation.

---

NetKAN/ModularFlightIntegrator.netkan

`1.1.3.0` should only be compatible with KSP 1.1.0.

Add KSP versions to override for ModularFlightIntegrator

---

NetKAN/CustomBarnKit.netkan
NetKAN/GCMonitor.netkan
NetKAN/ModularFlightIntegrator.netkan

Should fix some issues with their current CKAN listings (1.1 versions
being installed on 1.0.5 etc)

Set CustomBarnKit, ModularFlightIntegrator, and GCMonitor to use AVC version

---

NetKAN/RSSeaDragon.netkan

Probably another case of https://github.com/KSP-CKAN/CKAN/issues/1477 via http://status.ksp-ckan.org/
I ran a test on  a version of the file without the dependency on Hangar, see http://ci.ksp-ckan.org/job/NetKAN/2490/console for results.

Update install stanza for RSSeaDragon

---

NetKAN/NavballUpDefault.netkan

KSP 1.1 changes the way the navball is accessed, so any version older than NavballUpDefault-v0.2 (the latest release) will not work on KSP v1.1

Amended NavballUpDefault due to 1.1 changes

---

NetKAN/CareerManager.netkan

Verbatim copy of https://github.com/bananashavings/CareerManager/blob/febcc185cb345f099a96e62cf5e823948caf8133/CareerManager.netkan
Courtesy ping @bananashavings in case you weren't aware that https://github.com/bananashavings/CareerManager/commit/4f2d10008db7feebc5f631047b472eec9b4d4395 deleted your .netkan.

Copy CareerManager.netkan

---

NetKAN/EVAHandrailsPackContinued.netkan

Per http://status.ksp-ckan.org/ this is broken and from local testing I'm really not sure why it's broken.
Anyone with insight on this? @dbent @techman83
````
1303 [1] WARN CKAN.NetKAN.Transformers.SpacedockTransformer (null) - Could not normalize URL: 
2081 [1] FATAL CKAN.NetKAN.Program (null) - After parsing a value an unexpected character was encountered: C. Path 'DOWNLOAD', line 5, position 3.
````

EVAHandrailsPackContinued

---

NetKAN/Mk2Expansion.netkan

No longer depends on Firespitter or Klockheed Martian Gimbal

Fix Mk2Expansion dependencies

---

NetKAN/BackgroundProcessing.netkan
NetKAN/kOSBFSMultipleArchiveManager.netkan

These two NetKANs were using features not compatible with their listed spec. Identified during updated testing.

Update to compatible Spec v1.16

---

NetKAN/GammaTextures.netkan
NetKAN/MainSailorTextures-Complete.netkan
NetKAN/MainSailorTextures-Essentials.netkan
NetKAN/MainSailorTextures-Fairings.netkan
NetKAN/MainSailorTextures-Historical.netkan
NetKAN/MainSailorTextures-Theta.netkan

Splits out individual packs for those that don't want everything.
PPTextures mods, so KSP version compatibility can be controlled by the dependency's availability.
Closes #3557
Closes KSP-CKAN/CKAN-meta#1045

Add MainSailor's Procedural Parts Texture packs from Spacedock

---

NetKAN/KIS.netkan

As per KSP-CKAN/CKAN-meta#1047, there is an additional credited author for KIS.

Add author to KIS

---

NetKAN/TransferWindowPlanner.netkan

The latest version is marked on github as 1.0.5 compatible and the forum thread for the mod mentions something about UI changes. People are also asking if the mod will get updated/is working so I'm assuming it is not at this time, user ace22 on irc also mentioned it not working. Might have to add ksp_version to the files in CKAN-meta aswell as to ensure that users don't get a really old version instead.

TransferWindowPlanner lacks ksp_version

---

NetKAN/KIEFighter.netkan

Interesting background to this.. the timing of the folder name's change was such that even though a perfectly working .netkan was merged, an update to the mod was issued that broke the .netkan before we ever indexed a version of the mod.

Edit regex to match new folder name in KIEFighter

---

NetKAN/KSPChromaControl.netkan

Copied (with some small revisions) from and closes https://github.com/KSP-CKAN/CKAN-meta/issues/1056. Pinging @Dazpoet to see if there's any precedent on how to handle these types of mods.
I'm also of 2 minds regarding `link2source.txt`. I could see someone making the argument that it's a source and should be filtered, but I could also make the argument that it's in the same vein as a "readme" which we include.

Add KSPChromaControl

---

NetKAN/Taerobee.netkan

According to https://github.com/Tantares/Taerobee/releases the release is only hours old, but we have a version `2.3` indexed as compatible with `1.0.5`. This may be the same file re-released in which case an override would be accurate, but in the event that the file is different users on `1.0.5` end up installing an incorrect version. An epoch allows us to have both `2.3` with individual compatibilities.

Add epoch.

---

NetKAN/DockingPortAlignmentIndicator.netkan

DPAI is not dependent on RPM, it can work standalone and adds a new screen if RPM is installed.

Change Depends on RPM to Recomments

---

NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids.netkan

This config ensures that the upcoming release of Custom Asteroids 1.3 (which among other changes factors the zip file, as requested by two forum users) will not break CKAN, and that the new ModuleManager dependency is recognized right away.
The removal of `$vref` from the population configs is a temporary workaround for KSP-CKAN/CKAN#1674. The line can be restored once a 1.3 zip is on SpaceDock. (I will need to make a second pull request anyway, to upload `CustomAsteroids-Pops-Stock-Stockalike.netkan`; the file cannot be compiled at present due to a "no files to install" error.)

Updated config files for breaking changes in Custom Asteroids 1.3.

---

NetKAN/SpaceshuttleSRB.netkan

Explanation of the regex:
The folder name is currently `Not enuogh Engines`.
Ehe capitalization of the `e` in `enuogh` might change to match `Not` and `Engines` so `[Ee]` catches that.
`enuogh` is presumably a typo of the word `enough` so the 2x `[uo]` means the `u` and `o` can be in either position and it'll still catch. 
Lastly `Engines` might be changed to lower case so `[Ee]` allows for both those possibilities.

Fix install for SpaceshuttleSRB

---

NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan

This is a continuation of #3691 with changes that Netkan couldn't handle until there was a Custom Asteroids 1.3 release on SpaceDock. The files should now build and test cleanly with KSP 1.1.

Remaining Custom Asteroids 1.3 changes

---

NetKAN/TakeCommand.netkan

I've released a new version of TakeCommand for KSP 1.1, and it's now being hosted on SpaceDock so I'd like to get CKAN updated to point at the new location.

Moved TakeCommand from Kerbstuff to SpaceDock

---

NetKAN/ItsTheLittleThings.netkan

Another convoluted regex to cover all kinds of capitalization changes.
In this case the folder went from `Its the little things` to `Its the little Things`
This regex covers all cases of caps changing as well as spaces between words and the addition of an apostrophe `'` to `Its`.
I'm a regex scrub so there are probably 100 more efficient ways to do this.

Fix install for ItsTheLittleThings

---

NetKAN/Mk3HypersonicSystems.netkan

A quick fix to us installing the base `Mk3HypersonicSystems` folder resulting in its dependencies being double-installed. Pushing this through immediately but would appreciate an after-the-fact review from @politas and/or @Dazpoet

Fix install, bump epoch

---

NetKAN/RealSolarSystem.netkan

The KSP-AVC spec isn't really clear on whether KSP versions should
always have three parts. Our code assumes that it does. The RSS .version
version file doesn't. This results in a file being emitted targetting
KSP "1.1." (with a trailing dot) which causes validation to fail.
This override forces the version to "1.1", which will work with both
1.1.0 and 1.1.1 (which is arriving soon).
For @NathanKell.

Fixup RSS / KSP version oddity.

---

NetKAN/PartCommander.netkan

I've released a new version with KSP 1.1 support via SpaceDock and would like to get CKAN updated.  Thanks!

Move PartCommander to SpaceDock

---

NetKAN/InfernalRobotics.netkan

The `ksp_version_strict` field requires at least v1.16 of the CKAN spec.
This updates the .netkan file appropriately.

InfernalRobotics update to v1.16 of the CKAN spec.

---

NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan

This is a fix to a minor issue where installing Custom Asteroids configs would leave the dummy "Standard Setup" folder in GameData. All configs not associated with another mod should go into `GameData/Custom Asteroids/config`.

Fixed configs being installed to wrong folder.

---

NetKAN/SDHI-StrobeOMatic.netkan

This only uses stock part modules, therefore no plugin compatibility issues. Should be able to be updated ASAP.

Update SDHI Strobe-O-Matic compat to KSP 1.1.2

---

NetKAN/RN-SovietSpacecraft.netkan

-Fix naming error in Soviet Spacecraft, it still said salyut, now the
name is correct.

RN naming fix

---

NetKAN/StockNoContracts.netkan
NetKAN/StockPlugins.netkan
NetKAN/StockRT.netkan
NetKAN/StockSCANsat.netkan

Hello, I've added support of KSP-AVC on my mods. I don't know why but at this time, I don't see StockRT on the CKAN list, perhaps something goes wrong? As I can see, my last StockRT update is indexed on the metadata, I don't know what I can do to correct this.
Thanks :)

Added KSP-AVC support of my StockMods

---

NetKAN/SMURFF.netkan

FYI, @Kerbas-ad-astra
I assume SMURFF is compatible with KSP 1.1.2? In which case you'll probably want to update your `.version` file in the repository.

Add SMURFF

---

NetKAN/RN-SovietRockets.netkan

This will add a conflict to `FASA` and add an epoch. The epoch bump will appear to the CKAN client as if there's a new version of `RN-SovietRockets` so users who want to upgrade will have to remove FASA.

Add conflict, bump epoch for RN-SovietRockets

---

NetKAN/AstronikiSunflareforScatterer.netkan
NetKAN/Scatterer-sunflare.netkan

Testing this is a pain. The easiest way I found is to plop the .ckans into a test repo. https://github.com/KSP-CKAN/CKAN-meta/tree/AstronikiSunflareforScatterer_test includes those .ckans with `Scatterer` bumped to kspver 1.1.2

Break sunflare from scatterer, add AstronikiSunflareforScatterer

---

NetKAN/HazardTanksTextures.netkan

Creates a dependency on VensStylePPTextures to fix the problems encountered trying to install both due to a shared file.
Closes KSP-CKAN/CKAN#1675

Update HazardTanks dependencies

---

NetKAN/ContractConfigurator-ContractPack-SCANsat.netkan

Jenkins failure because ksp_version_max is 1.2.0 and dependencies can't be met because of that.

force v for ContractConfigurator-ContractPack-SCANsat

---

NetKAN/KerbalConstructionTime.netkan

Changes required for KCT 1.3.3.7 for KSP 1.1.2

KerbalConstructionTime - depend MagiCore, recommend KRASH

---

NetKAN/SXT.netkan

AFAICT by my testing works just as well in 1.1.2 as in 1.1.0.

SXT compatibility bump

---

NetKAN/LEAForKSP.netkan

Shame this isn't useful for Linux users.

Fix LEAForKSP install

---

NetKAN/CommunityTechTree.netkan

CTT had explicit 1.1.0 metadata from spacedock; this changes current release to min/max to work in 1.1.2. @nertea you might want to update on spacedock too :)

Make CTT 1.1-1.1.2 compatible

---

NetKAN/KSPInterstellarExtended.netkan

Tweakscale 2.2.10 is needed for KSPI-E to work correctly

Updated dependancy Tweakscale

---

NetKAN/InterstellarFuelSwitch-Core.netkan

IFS is heavily integrated with Tweakscale and it relies on very specific functionality from Tweakscale to work correctly when installed

Addded recommendation for Tweakscale with minimum version

---

NetKAN/KSPInterstellarExtended.netkan

InterstellarFuelSwitch 2.0.4 also depends on Tweakscale 2.2.10

InterstellarFuelSwitch 2.0.4 is now recommended

---

NetKAN/PilotAssistant.netkan

All the text shows the author's intent was to make the latest version more generally compatible as "1.1", even though the .version file says "1.1.0". Limiting to released versions to be conservative, though.
I have reached out to the author to get the .version file updated.

Open up KSP compatibility for PilotAssistant

---

NetKAN/InterstellarFuelSwitch.netkan

Interstellar Fuel switcher can optionaly use KSP Interstelar Extended crygenic module for boiloff

Added dependancy to KSPInterstellarExtended

---

NetKAN/CommunityTechTree.netkan

`CommunityTechTree-2.4.0` was manually added to ckan meta and `2.4.0` > `2.4`. This has awkward effects on what CKAN lists as CTT's highest ksp compatibility. An epoch brings all CTT users to the same version with the correct compatibility listed.

CommunityTechTree add epoch

---

NetKAN/EPL-MKSLite-Patch.netkan

I'm open to a better identifier. Without the dashes it's kinda alphabet soup and spelling out EPL makes for another really long ID. *shrug*

Add EPL-MKSLite-Patch

---

NetKAN/KerbinSideGAP.netkan

I've updated dependencies to fit new packages structure that AlphaAsh had introduced.
Am I right, that this affects only further releases of my mod, while current ones (v1.0-v1.2) remains as they are and so they will be still available for KSP 1.0.5 users?

KerbinSideGAP mod dependencies updating

---

NetKAN/KSP-64k.netkan

Set homepage to forum link since both Spacedock and forum thread have a prominent link to kingtiger.co.uk, but kingtiger.co.uk has no link to forum thread, and is outdated. Forum thread has been updated with new release details.
64K - 12 hour & Delta-V ImageViewer optional installs appear to have been dropped.
Closes #4125

Move KSP-64K to Spacedock

---

NetKAN/KWRocketry-CommunityFixes-interstage.netkan
NetKAN/KWRocketry-CommunityFixes.netkan

Change in casing for `GameData`, switch from `file` paths to `find`.
@linuxgurugamer I was under the impression `KWRocketry-CommunityFixes` was discontinued in favour of `KWRocketryRedux` but seeing as you're continuing to issue new releases, should we bump the ksp_version compatibility of `KWRocketry-2.7.0-community`?

Fix install for KWRocketry-CommunityFixes and -interstage

---

NetKAN/SMURFF-Extras-VenStockRevamp.netkan
NetKAN/SMURFF.netkan

SMURFF now comes with optional patches in its `Extras` directory. This adds a package for the only one so far: `SMURFF-Extras-VenStockRevamp`. For future extensibility I figure its best to group the patches by mod/general functionality. If that does not prove to be granular enough we can split them in the future.

Add SMURFF-Extras-VenStockRevamp

---

NetKAN/DarkSideTechnology.netkan

Netkan.exe actually fails to transform this properly but after reading issue 1469 (https://github.com/KSP-CKAN/CKAN/issues/1469) and Program.cs in the CKAN repo I gather that this will actually work in reality. (Or at least I assume so, and that netkan is just being persnickety.)

Add DarkSideTechnology

---

NetKAN/DestructionEffects-SemiContinued.netkan
NetKAN/DestructionEffects.netkan

Following advice [here](http://forum.kerbalspaceprogram.com/index.php?/topic/99088-10xdestruction-effects-flames-and-smoke-on-joint-breaks/&do=findComment&comment=2622536).
Replaces the current DestructionEffects with a pure continuation.
Makes DestructionEffects-SemiContinued a separate, conflicting mod.
The Spacedock release appears to be someone re-releasing the DestructionEffects here without giving credit. (CC-0, so they can do that, but this source seems better.)
Replaces #4192

DestructionEffects fixup

---

NetKAN/NewHorizons.netkan

Update as per [forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/102776-112-kopernicus-new-horizons-v200-14june2016-out-with-the-old-in-with-the-new/#comment-1792426). Newest version is 2.0.0 for KSP 1.1.2

Update New Horizons to KSP 1.1.2

---

NetKAN/Historian-expanded.netkan

Not sure what happened, exactly, but we need the "v" now.
As per [forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1161-13-mar-2016/&do=findComment&comment=2629757)

Historian-expanded add force_v

---

NetKAN/Telemachus-2.netkan

Because it's easier to manage SpaceDock NetKANs than GitHub ones.
Alternative to #4189 .
Odd that this fails checks. O.o Works fine for me.

Update Telemachus to use SpaceDock

---

NetKAN/UKS-Kerbalism-Patch.netkan

Revert "UKS isn't supported on CKAN anymore, so remove it as a dependency."

---

NetKAN/MagiCore.netkan

Can be reverted once https://github.com/magico13/MagiCore/pull/2 is accepted. As of now nothing that depends on MagiCore (KCT, mods that req KCT) will show in CkAN due to this mismatch.
Hopefully @magico13 can get to the PR soon, but I see no harm in doing this until then.

Update MagiCore to work on 1.1.2/3 both

---

NetKAN/DeadlyReentry.netkan

With the release of 7.4.7 for 1.1.3, we don't need the override.

DRE override no longer needed

---

NetKAN/KerbQuakeExtended.netkan

Add my fork of KerbQuake, KerbQuake extended. KerbQuake's original licenses allows for forks, as it uses the [BSD 3-Clause license](https://tldrlegal.com/license/bsd-3-clause-license-(revised)).

KerbQuake extended mod.

---

NetKAN/DMagicOrbitalScience.netkan

For Science doesn't properly interact with Orbital Science experiments. This can lead to simply thinking the experiments can't be run, to preventing experiments from being transmitted while using Remote Tech.

Add For Science to conflicts list for DMagic Orbital Science

---

NetKAN/KSPSerialIOcrossplatform.netkan
NetKAN/SerialIO.netkan

There's a little bit of hairiness here, sorry.
* This mod conflicts with `SerialIO` (the mod it's forked from - I hope to eventually merge them, but this is where we are now). I've gone ahead and updated the netkan for `SerialIO` to reflect this.
* It's functionality equivalent, but a separate implementation, to the `SerialIO-MacLinuxWin`, which existed on kerbalstuff but hasn't been maintained for quite some time and isn't currently listed anywhere. That's why I replaced it in the `SerialIO` conflicts. But didn't want to flat-out remove the netkan for it.
* This mod installs a DLL that's a duplicate of the `PsimaxSerialLibrary` netkan. But, again, that's a listing that hasn't been kept up to date - the package doesn't exist on spacedock at all.
I'm not sure what the policy is on those …

Add KSPSerialIO cross platform fork

---

NetKAN/StockBugFixPlus.netkan

This is my first time editing NetKAN.
The name of the zip, and folder within, changed from "StockBugFixPlus" to "StockBugFixControllerPlus". Should it be handled as I have done, or should the netkan file be renamed?

Update Stock Bug Fix Modules & StockPlus

---

NetKAN/Pledna.netkan

Closes #4444 
The original, while accepted, was incorrect. This one, generated by my new script, properly includes Kopernicus

Updated Pledna, with Kopernicus

---

NetKAN/InfernalRobotics-Sequencer.netkan

SpaceDock hasn't been upgraded since IRS version 0.6.0, but the mod is
up to 1.0.0 on GitHub (and Sequencer versions each require the matching IR version).  I've checked with the mod authors and they've OK'd this update.

Redirect InfernalRobotics-Sequencer from SpaceDock to GitHub

---

NetKAN/LightFixer.netkan

The mod is just a `Config.cfg` which edits Kopernicus using ModuleManager, which is why I added ModuleManager as a hard dependency, rather than getting it transitively through Kopernicus.
Closes #4482

Add LightFixer!

---

NetKAN/KerbalCitiesPack.netkan

This was right when #4464 was checked by Jenkins, but got broken before it was committed.

Fix Installation for KerbalCitiesPack

---

NetKAN/VesselView.netkan

There's an old v0.71 that's messing up the version sorting.

Add Epoch to VesselView

---

NetKAN/ABLaunchers.netkan

Forum thread describes the current release as being ok for all of KSP 1.1
Will fix dependency required by #4599

Add KSP version override for ABLaunchers

---

NetKAN/ProbesPlus.netkan

I looked at the guide and I hope I have the right changes to reflect the change of my mod to the new released version 0.14 . I'd appreciate if someone can help me get my mod updated, or just proofread my code chage. I suggest the name change to "ProbesPlus" because "Coatl Aerospace" is the name of the in-game company for my mods, whereas ProbesPlus is the mod name.
Also, the mod now has a Firespitter dependency. I also don't know what to put in the code to make "Bluedog Design Bureau" a suggested mod. I'll read the guide again.

Update and rename CoatlAerospace.netkan to ProbesPlus.netkan

---

NetKAN/CrowdSourcedScience.netkan

As CrowdSourcedScience is bascially compatible with almost all versions of KSP, this fix should be safe. According to the changelog this is 1.0.2 until 1.1.x
See also DuoDex/CrowdSourcedScience#49 .

Update CrowdSourcedScience to be 1.1.x-compatible

---

NetKAN/AntaresCygnus.netkan
NetKAN/RN-MiscParts.netkan
NetKAN/RN-SPP.netkan
NetKAN/RN-SalyutStations.netkan
NetKAN/RN-Skylab.netkan
NetKAN/RN-SovietProbes.netkan
NetKAN/RN-SovietRockets.netkan
NetKAN/RN-SovietSpacecraft.netkan
NetKAN/RN-USProbesPack.netkan
NetKAN/RN-USRockets.netkan
NetKAN/TextureReplacer.netkan

-Update all mods for ksp 1.2
-Removed all unneeded dependencies, I now only use bahaSP and sometimes
texture replacer for my mods. Firespitter and animated dec are no longer
needed.
- Updated all craft files so they can be installed by default again

RN updated for ksp 1.2

---

NetKAN/AstronikiSunflareforScatterer.netkan
NetKAN/Scatterer-sunflare.netkan
NetKAN/Scatterer.netkan

SVE Sunflare was fixed in #4712, but the original and Astroniki are broken. 
Scatterer users will likely have to uninstall/reinstall to move file ownership.

Scatterer Sunflare configuration has moved

---

NetKAN/ShipEffects.netkan

This is a NetKAN file for a KSP-1.1.3 compatible ShipEffects that is newer than the one presently in the repository.
I am hoping this pull request generates CKAN-meta/ShipEffects/ShipEffects-1.0.5.ckan
After it has been picked up I will do another PR with a new version of ShipEffects.netkan to generate CKAN-meta/ShipEffects/ShipEffects-1.0.7.ckan which is for KSP 1.2.
Confused yet?  I am.

ShipEffects update 1 of 2

---

NetKAN/IndicatorLightsCommunityExtensions.netkan

I think `supports` is the more appropriate relationship here over `recommends` since users installing this mod may not even care or be interested in any of the mods it supports except maybe one or two. It's basically a set of compatibility patches, it doesn't encourage using any particular mod.

Change IndicatorLightsCommunityExtensions relationships from recommends to supports

---

NetKAN/VensStylePPTextures.netkan

Its functionality is far more dependant on Procedural Parts versions, all of which it will work for currently.

Make VensStylePPTextures KSP_version "any"

---

NetKAN/FutureParts.netkan

KSP version compatibilities make the restriction unnecessary.
closes #4898

Future Weapons - remove BDArmory version

---

NetKAN/IXSWarpshipOS.netkan

IXS Warpship OS was not showing up in CKAN anymore. I suspect because it uses the same directory name as its predecessor (Sofia's Warpship mod). Took the opportunity to update dependencies and add KSPInterstellarExtended and the preceding Warpship mod as a conflict.
Summary of the changes:
- Changed mod's directory to be different from its predecessor's (Sofia's Warpship mod)
- Added predecessor's mod as conflicting
- Added KSP Interstellar Extended mod as conflicting, it uses same DLL references.
- Added Fendrin's Spacedock mod as suggestion after removing purely structural spacedock parts from IXSWarpshipOS
- Added Community Resource Pack as a dependency

IXSWarpshipOS not showing up in CKAN client

---

NetKAN/KeridianDynamicsVesselAssembly.netkan

and dependencies
OSE Workshop is not listed at this time since it isn't yet 1.2.1
compatible

Updated file for KeridianDynamics, based on recommendations

---

NetKAN/SVE-HighResolution.netkan
NetKAN/SVE-LowResolution.netkan
NetKAN/SVE-MediumResolution.netkan

The AVC .version files in the current releases have ksp_min as 1.2 and ksp_max as 1.2.1, so for 1.2.2 we're offering the previous release which has been removed from GitHub.

SVE Override broken AVC KSP versions

---

NetKAN/HazardTanksTextures.netkan

KerbalHacks/license.txt which is included in all my mods was preventing the install if the file existed.

Specify install folder to omit the license.txt

---

NetKAN/WarpEverywhere.netkan

this mod is simple, works on 1.2.0/1.2.1/1.2.2 and is likely to not
need recompiles for patch revs of KSP.
Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

allow WarpEverywhere on KSP v1.2.x

---

NetKAN/RealisticAtmospheres.netkan

Turns out there's a bug in the automatic `install` directive code that will cause it to fail if there are no files directly under the mod root (in this case `GameData/RealisticAtmospheres`). Explicitly specify the install directive as a workaround until I get that sorted.

Update Realistic Atmospheres

---

NetKAN/NyrathsUSAFOrion.netkan

For reasons I've yet to determine, this mod's plugin fails to work with the existing folder structure.  Fixing the mod required moving it's install location.  Which, from a netkan point of view is a giant pain in the posterior.

Path Change - USAFOrion

---

NetKAN/KaribouExpeditionRover.netkan
NetKAN/USI-SRV.netkan
NetKAN/USI-SubPack.netkan

> Yup!  Sub pack and Srv-Pack are now part of the expedition pack.  KER is now part of MKS.  So those mods should be removed from CKAN.

Remove RoverDude's merged mods

---

NetKAN/LargeBoatPartsPack-Modern.netkan
NetKAN/LargeBoatPartsPack-WW2.netkan
NetKAN/LargeBoatPartsPack.netkan

There's a weird "version_3.5.1" that's messing with the order.

LargeBoatParts* Epoch Bump

---

NetKAN/kRPC.netkan

Only download the zip with the correct contents. In this case it should download `krpc-0.3.8.zip` and **not** `krpc-python-0.3.8.post1.zip`.
This regex code works, but can it be made simpler?
Fixes #5387

Use regex to find correct kRPC

---

NetKAN/ETT.netkan

Looks like he sometimes forgets to add the "v" to the version number

Added epoch to ETT

---

NetKAN/SemiSaturatableRW.netkan

There's one update to SSRW that works on 1.2.x
Set the upper bounds to 1.2.8 since 1.2.9 seems to be the
1.3.0 pre-release, dunno if you care, but 1.2.99 now seems
inappropriate...

SSRW 1.12 is a 1.2.x release

---

NetKAN/TACLS.netkan

We froze the files in #5330 because RO now uses MM to modify the TACLS config, but the TACLS config wasn't set to install.
Fixes https://github.com/KSP-RO/RealismOverhaul/issues/1621
Fixes https://github.com/KSP-RO/TacLifeSupport/issues/83

Install TACLS config

---

NetKAN/ProceduralParts.netkan

ProcParts has a 1.2.1 release and this expands that to 1.2.x

Proc Parts metadata updates for 1.2.x

---

NetKAN/Telemachus.netkan

Hello,
This is my first CKAN metadata change, and I'm not very familiar with CKAN, so it's likely I botched this change :)
The latest [Telemachus versions](https://github.com/KSP-Telemachus/Telemachus/releases) seem to support KSP 1.2. Will this change on `NetKAN` also update existing metadata on `CKAN-meta`? Or will it only be applied to new versions?

Telemachus for KSP 1.2

---

NetKAN/BlacklegIndustriesMMTantaresTACLS.netkan
NetKAN/Contares.netkan
NetKAN/ContaresCA1CanadianArrow.netkan
NetKAN/ORIONMonkeyBusinessIncParts.netkan
NetKAN/ShadowWorksStockalikeSLSandMore.netkan
NetKAN/SovietConversion.netkan
NetKAN/TantaresFairingExtension.netkan

Use `NewTantares` instead of the old `Tantares`. This should make some mods available in CKAN that were hold off because of this.
[Reference](http://forum.kerbalspaceprogram.com/index.php?/topic/154922-*/&do=findComment&comment=3045504)

Use NewTantares instead of old one

---

NetKAN/BetterBurnTime.netkan
NetKAN/BetterCrewAssignment.netkan
NetKAN/DefaultActionGroups.netkan
NetKAN/IndicatorLights.netkan
NetKAN/IndicatorLightsCommunityExtensions.netkan
NetKAN/VectorRepurposed.netkan

I'm not exactly sure when these licenses were changed. Sometime around October last year, apparently.
@techman83, do we have any way to fix incorrect licenses on files we've mirrored to the Internet Archive?

Update licenses for Snark's mods

---

NetKAN/TooManyOrbits.netkan

Mod is not compatible with 1.3 so overriding back to 1.2

TooManyOrbits to 1.2

---

NetKAN/KerbalSimpit.netkan

Adds my Kerbal Simpit mod.
I couldn't find any docs on what the `x_netkan_license_ok` field is expected to do, but all of the metanetkan entries I've checked have it, and my mod is licensed under simplified BSD so hopefully that's OK too.

Add kerbalsimpit

---

NetKAN/TACLS.netkan

BackgroundResources was mistyped in the dependencies, preventing the install of TACLS.

Fix TACLS dependencies

---

NetKAN/AviationLights.netkan

PR-5529 added an override for 3.13 of Aviation Lights. But as per the author's response at http://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1223-mahia/&do=findComment&comment=3087187 this is incorrect.
I'm not sure if just removing the override at this point will have the desired effect. But figure that changing the override to point to the intended version would work as intended.

Remove incorrect Aviation Lights 3.13 compat override.

---

NetKAN/CryoTanks.netkan

I am not quite sure why this broke, but CryoTanks has its own .version
file and running NetKAN confirms that it is finding the correct one
For reference, the error is this:
```
AVC: Invalid path to remote GameData/KerbalAtomics/Versioning/KerbalAtomics.version, doesn't match any of: GameData/CryoTanks/Versioning/CryoTanks.version,
```

Fix CryoTanks vref

---

NetKAN/NearFutureProps.netkan

again not quite sure why this broke, but NearFutureProps has its own .version
file and running NetKAN confirms that it is finding the correct one

Fix NearFutureProps vref

---

NetKAN/AntaresCygnus.netkan
NetKAN/BDAnimationModules.netkan
NetKAN/RN-MiscParts.netkan
NetKAN/RN-SPP.netkan
NetKAN/RN-SalyutStations.netkan
NetKAN/RN-Skylab.netkan
NetKAN/RN-SovietProbes.netkan
NetKAN/RN-SovietRockets.netkan
NetKAN/RN-SovietSpacecraft.netkan
NetKAN/RN-USProbesPack.netkan
NetKAN/RN-USRockets.netkan

-Remove the changes to 1.3 because of it breaking ckan and my mod/the
game from loading.
@linuxgurugamer This needs to go hand in hand with removing those
metadata files I mentionned in the forum PM. Once all that is deleted I will quickly remove the releases for 1.3.

RN revert changes to 1.3

---

NetKAN/SmartTank.netkan

The maximum version has been reduced to 1.3.0, so there should be no errors this time.

Defer most metadata to external .netkan file

---

NetKAN/FuelEfficientPilots.netkan

Mod details:
name = /mod/1466/FuelEfficientPilots
author = packetshepherd
abstract = Give Pilots better fuel efficiency based on experience
license = CC-BY-NC-SA 4.0
Homepage =
description = Pilots have the ability to get better fuel efficiency through experience, so now your five-star pilot can give you better bang for your buck!

FuelEfficientPilots.netkan

---

NetKAN/MemGraph.netkan

Update MemGraph metadata to correctly reflect compatible versions.
Mod thread link for convenience:
http://forum.kerbalspaceprogram.com/index.php?/topic/139128-12x13-memgraph-1103-with-stutter-reduction/

MemGraph 1.1.0.3 works on both KSP 1.2 and 1.3

---

NetKAN/FerramAerospaceResearch.netkan

Makes KSP-CKAN/CKAN-meta#1288 permanent

FAR Override bad AVC info for 0.15.9

---

NetKAN/TrimIndicator.netkan

A minimalistic add-on displaying trim values inside the control gauges.

Add Trim Indicator

---

NetKAN/AstronomersVisualPack.netkan

Case sensitivity with the identifier for the Scatterer mod was preventing AVP from installing. I changed it in my local registry, and AVP upgraded without issue. This should allow others to upgrade.

Case sensitivity in dependency identifier

---

NetKAN/CommunityTerrainTexturePack.netkan
NetKAN/GPO.netkan

Also extends CTTP KSP compatibility (texture pack only)
Closes #5657

Add GPO from SpaceDock

---

NetKAN/JPL-RSS.netkan

The "v" in the ksp_version_min and _max fields confuses the NetKAN bot. Currently causing "JSON deserialization error" at http://status.ksp-ckan.org/, discovered by making that error more verbose in a local fork of netkan.exe.

Fix JPL-RSS version overrides format

---

NetKAN/KerbalTubes.netkan

I don't quite understand why this is erroring out, but changing `find` to `file` generates a valid `.ckan` file in my testing.
Current [status page](http://status.ksp-ckan.org/) error: "Could not find KerbalTubes entry in zipfile to install"
Example file:
```
Length      Date    Time    Name
---------  ---------- -----   ----
1439  2017-07-31 22:33   KerbalTubes/Parts/Coupling/DockingIrisMax/DockingIrisMax.cfg
```

Switch from find to file

---

NetKAN/SpudMoon.netkan

This mod currently has the wrong Github repo in its $kref, causing "Could not find Spud entry in zipfile to install" on the status page.

Fix repo URL for SpudMoon

---

NetKAN/ReworkedStockSystem.netkan

`.netkan` was hard coded to version 1.0.1, which didn't work so well once version 1.0.2 came out. But there's also a nested `gameData` folder, which looks like it should be the true root of the tree.
Current [status page](http://status.ksp-ckan.org/) error: "Could not find ReSS_V1.0.1 entry in zipfile to install"
Example file:
```
Length      Date    Time    Name
---------  ---------- -----   ----
2074  2017-08-27 15:11   ReSS_V1.0.2/gameData/ReSS/Bop/cfg/Bop.cfg
```

Switch to find_regexp

---

NetKAN/OPTSpacePlaneMain.netkan

This was blocking the version for KSP 1.3 from getting indexed correctly.
Bonus: add resources.spacedock.

OPTSpacePlaneMain: remove ksp_version_min,max; rely on Curse version

---

NetKAN/FASALaunchClampsContinued.netkan

Fixing: ["Could not find FASA entry in zipfile to install"](http://status.ksp-ckan.org/)
This download doesn't contain separate entries for its subdirectories, which I discovered that `find` and `find_regexp` require while investigating problems with #5841. I will probably be submitting an issue or PR about that, but in the meantime this mod has a single consistent root path of FASA, which works well with `file`. Also some minor clean-up of the indentation.
```
Length      Date    Time    Name
---------  ---------- -----   ----
2503  2017-09-18 10:10   FASA/launchclamps/FASA_Launch_Clamp_125/FASA_Launch_Clamp_125.cfg
187403  2017-09-18 10:04   FASA/launchclamps/FASA_Launch_Clamp_125/FASA_Launch_Clamp_125.mu
2414  2017-09-18 10:10 …
```

FASALaunchClampsContinued: find -> file

---

NetKAN/kRPC.netkan

The github asset regex wasn't picking up new versions 0.3.10 and 0.3.11 for the kRPC mod. I've tweaked the regex to fix this.

Fix regex for version numbers for kRPC

---

NetKAN/FASALaunchClampsContinued.netkan

This mod previously shipped a FASA folder, and now it's nested in a GameData folder. This change updates the netkan to account for that.

Update folder path for FASA

---

NetKAN/Historian-expanded.netkan

Historian-expanded is erroring out in the NetKAN-bot after its latest update.
https://github.com/Aelfhe1m/Historian-Expanded/releases/tag/v.1.3.1
> BREAKING CHANGE
>
> Move Historian install folder from GameData/KSEA/Historian to GameData/Historian. If upgrading from Historian version 1.2.8 or earlier then any custom layouts must be copied to the new location and the old folder deleted.
This change updates the netkan metadata accordingly.

Update Historian's install folder

---

NetKAN/WindowShineTR.netkan

The latest version of this mod is on SpaceDock, and the older DropBox download seems to have been removed, as the bot now errors out on this mod. The internal structure of the zip file changed slightly as well.
https://forum.kerbalspaceprogram.com/index.php?/topic/110080-13-windowshine-v15-toroidal-tank-update-2-october-17/

Switch WindowShine from DropBox to SpaceDock

---

NetKAN/DescentMode.netkan

Hello. Please update my netkan file to use KSP-AVC version data instead of hardcoded one. I pushed a prerelease version and it seems to generate a correct .ckan file, and will make it a full release when .netkan is updated, to not break existing 1.2.2 installs

Update DescentMode NetKAN file

---

NetKAN/BackInBlack.netkan
NetKAN/BackInBlackTexturePack.netkan

- Change BackInBlack's dependency from InterstellarFuelSwitch to InterstellarFuelSwitch-Core
- Make BackInBlackTexturePack depend on BackInBlack

Update BackInBlack dependencies (fixes #5946)

---

NetKAN/WindowShineTR.netkan

Ensures post-v12 versions require TextureReplacerReplaced, not TextureReplacer.

Fixes up WindowShine's CKAN

---

NetKAN/EnvironmentalVisualEnhancements.netkan

so you can install a cloud pack not on CKAN (or make your own) without manually removing it

Makes EVE Configs NOT required

---

NetKAN/ExtraPlanetaryLaunchpads.netkan

This mod's download is hosted on the maintainer's custom server, so version updates have to be done manually. This change switches it to version 5.9.0.
https://forum.kerbalspaceprogram.com/index.php?/topic/54284-131-extraplanetary-launchpads-v590/

Update ExtraPlanetaryLaunchpads to 5.9.0

---

NetKAN/SoundTrackEditor.frozen

SoundTrackEditor cannot be installed by CKAN without a spec change, or a change in the mod's installation folders.
Closes #5953

Freeze SoundTrackEditor

---

NetKAN/CAMk3BlockII.netkan

ShuttleLiftingBody is a dependency, and it includes the CA localisations for everything.
closes #5998

Filter localisations from CAMk3BlockII

---

NetKAN/PreciseNode.netkan

PreciseNode lists two authors, but they're combined into one comma-delimited string, and NetKAN supports proper lists of authors.

Split concatenated author names for PreciseNode

---

NetKAN/Toolbar.netkan

Toolbar lists two authors, but they're combined into one comma-delimited string, and NetKAN supports proper lists of authors.

Split concatenated author names for Toolbar

---

NetKAN/Fenrir.netkan

Author confirms that this folder is intentionally removed and will no longer be shipped:
https://forum.kerbalspaceprogram.com/index.php?/topic/166821-wip-fenrir-launcher-pack/&do=findComment&comment=3210124

Remove VAB folder from Fenrir

---

NetKAN/ChineseTianGongScienceSpaceStation.netkan

It was empty in the old downloads anyway, and it's absent in the latest ones.

Remove SPH folder from TianGong

---

NetKAN/HeatControl.netkan

This mod's code is CC-BY-NC-SA-4.0, but its models are All Rights Reserved.
(That is the reason for #6037.)

Update HeatControl's license

---

NetKAN/OuterPlanetsMod.netkan

See https://github.com/KSP-CKAN/CKAN-meta/pull/1306; this pull request sets up a version override in the NetKAN to fix the problem of OPM 2.1 trying to install on the incompatible 1.1.x KSP releases.

Fix ksp_version_min for OPM 2.1

---

NetKAN/DCKDavincisCombatKit.netkan

- The DCK folder is now DCKinc
- The release announcement says only ModuleManager is required, so other depends moved to recommends
- Other supplemental folders added
https://forum.kerbalspaceprogram.com/index.php?/topic/159310-13x-dck-v030-part-textures-rims-transparent-aircraft-armor-energy-shields-stealth-coating-and-other-goodies-for-ksp-stock-bdac-bdmk22-sm_afvs-m2x-kax-ap-badtprops-quiztech-procedural-parts11052017/&do=findComment&comment=3211388

DCK: update directories and dependencies

---

NetKAN/NewTantares.netkan

Version is hard coded to 1.2.2 in the netkan, but this mod has been 1.3 compatible since June:
https://github.com/Tantares/Tantares/releases
It doesn't specify 1.3.0 or 1.3.1, so I went with both.

Update KSP versions for NewTantares

---

NetKAN/DistantObject-default.netkan

DistantObject-default currently installs an empty GameData/DistantObject/PluginData folder, which causes conflicts with DistantObject at uninstallation (see #6065). This pull request removes the empty folder.

Filter empty PluginData folder in DistantObject-default (fixes #6065)

---

NetKAN/DeepFreeze.netkan

DeepFreeze currently recommends three life support mods, TACLS, USI-LS, and Snacks. Of these, TACLS and USI-LS are marked as conflicting; Snacks isn't, but it's supposed to be a simplified life support mod, so a user wanting to install it probably wouldn't want to deal with the complexity of the other two. In GUI, recommendations are checked by default when prompting for optional dependencies, so the user would have to know that they conflict and then uncheck the ones they don't want.
This pull requests moves these life support mods to "suggests". This way the user can choose whether and which to install rather than having them default to checked in the GUI.

DeepFreeze: Conflicting life support recommends to suggests

---

NetKAN/TextureReplacerReplaced.netkan

TRR currently provides itself. This is redundant and confuses the installer; the user is asked to choose between the same mod twice when installing a dependent mod:
This pull requests removes that provides directive.

TextureReplacerReplaced, don't provide yourself

---

NetKAN/IXSWarpshipOS.netkan

- changed suggested SpaceDock to SpaceDockRedeployed
- moved Alcubierre Drive from depends to recommends
- added WarpDrive to recommends
- added suggests CommunityTechTree
- added depends ModuleManager
@bartblommaerts, I apologize, I appear to have messed up #6079 beyond my ability to repair. There was a conflict with master because your branch was out of date, and in the process of resolving the conflicts, I erroneously committed instead of `rebase --continue`ing, then pushed to your branch thinking the changes were ready. But git decided to push unchanged master instead, after which your branch had no changes; GitHub decided this meant it should auto-close your PR, and without an open PR, I can no longer push changes to your branch.
The good news is that I do still have the changes and …

Update required for IXSWarpShipOS release 0.4.0.8

---

NetKAN/GPP.netkan

GPP currently recommends a number of mods that conflict with one another.
Cloud packs:
- GPPCloudsHighRes
- GPPCloudsLowRes
Rescales:
- Rescale-25
- Rescale-32
- Rescale-64
- Rescale-10
- Rescale-10625
Currently if you install GPP from the command line, it installs Rescale x2.5, which should probably be something the user chooses rather than the default. And GUI defaults to installing them all:
This pull request moves these mods from recommends to suggests, so the user can choose which ones they want, if any.
Pinging @Galileo88 for FYI/feedback.

Move GPP's conflicting recommends to suggests

---

NetKAN/GPP.netkan

GPP updated from 1.5.3 to 1.5.88, but the version was hardcoded in the netkan, so the new version overwrote the old.
GPP ships a valid AVC file, though, so we can just $vref it.

Remove version hardcoding for GPP

---

NetKAN/GPPCloudsHighRes.netkan
NetKAN/GPPCloudsLowRes.netkan
NetKAN/GPPSecondary.netkan

These mods are currently installing version 1.5.88 while CKAN displays 1.5.3.
Switching to AVC $vref since the download contains a valid version file.

Use KSP-AVC file for GPP side mods

---

NetKAN/SamBelangerFlags.netkan

@SamBelanger, I really don't want to force people installing Optional Atmospheres to download the nearly 1GB that is DoubleDouble just to get the flags. If you want to have a SamBelanger Flags that is simply v1.0 and doesn't change, you could make a zip file available anywhere and we could point to that. We don't need a GitHub/Spacedock release to scrape for unchanging mods.

Move SamBelangerFlags to Spacedock

---

NetKAN/FASA.netkan

FASA currently depends on TextureReplacer, which is not available for KSP 1.3.1. This causes FASA to be hidden completely for KSP 1.3.1 (see KSP-CKAN/CKAN#1695). However, manual users of FASA report that it works without TextureReplacer, so it's more appropriately marked as an optional dependency:
https://forum.kerbalspaceprogram.com/index.php?/topic/22888-105-fasa-544/&do=findComment&comment=3244692
This PR changes that dependency to a recommendation, so FASA will be available to install without TextureReplacer on KSP 1.3.1.

FASA: Move TR from depends to recommends

---

NetKAN/NewTantaresLV.netkan

This mod is labeled as 1.3.1 compatible starting in late October.
https://github.com/Tantares/TantaresLV/releases

TantaresLV works on KSP 1.3.1

---

NetKAN/FoxDefenseContracts.netkan

Slight structural change in this download, the folder is the same but now it's under a GameData folder.

FoxDefenseContracts got moved into GameData

---

NetKAN/OptionalAtm.netkan

OptionalAtmospheres was recently removed from SpaceDock, and now lives on GitHub. 
@SamBelanger has transferred ownership to @DeltaDizzy.
The download no longer has a KSP-AVC file.
Fixes #6105.

Replace OptionalAtm with OptionalAtmospheresRevamped

---

NetKAN/DeepSpaceSurfaceHabitatUnitPack.netkan

These configs were previously applied unconditionally and incompatible, so we weren't installing them. The author has updated them to use NEEDS clauses, so now we'll install them all.

Add DSSHU life support patches

---

NetKAN/CapsuleCorporationEndeavourMarsBaseCamp.netkan

The previous release had some duplication of directories, that seems to be ironed out now.

CCEMBC removed extra directory

---

NetKAN/InfernalRobotics-LegacyParts.netkan

InfernalRobotics is currently released in a non-functional state, strictly speaking. It consists of a plugin and some parts, but the last time the parts were released was for KSP 1.1.3. Since then, the developers have only been releasing "Core" updates containing just the plugin, including for KSP 1.3.1. Users are expected to assemble the mod themselves by extracting the parts from an earlier release.
In theory, CKAN supports this via the InfernalRobotics-LegacyParts module. However, this package targets an old download file naming scheme (IR-LegacyParts.zip was last released for IR 2.0.0, and after that the naming scheme was changed to IR-version-Final-Full.zip), and was set as only compatible with KSP 1.1 in its netkan. This resulted in frequent confusion for CKAN users, who would …

Make IR parts available

---

NetKAN/KWRocketryRebalanced.netkan
NetKAN/KWRocketryRedux.netkan

These are nearly the same mod, but it's currently possible to attempt to install both:
```
$ ckan install KWRocketryRedux KWRocketryRebalanced
1) KWRocketryRedux-GraduatedPwr (KW Rocketry Redux - Graduated Power Response Configs)
2) KWRocketryRedux-InstantPwr (KW Rocketry Redux - Instant Power Response Configs)
Enter a number between 1 and 2 (To cancel press "c" or "n".): 
2 
About to install...
* KW Rocketry Redux 3.1.4 (cached)
* KW Rocketry Rebalanced 3.2.3 (cached)
* KW Rocketry Redux - Instant Power Response Configs 3.1.4 (cached)
* Module Manager 3.0.1 (cached)
* Simple Adjustable Fairings - KW Rocketry Pack v1.0.1 (cached)
* Simple Adjustable Fairings - Plugin v1.0.1 (cached)
* The Janitor's Closet 0.3.2 (cached)
* Filter Extensions - Plugin 3.0.4 (cached)
* Filter Extensions - …
```

Mark KWRocketryRedux and KWRocketryRebalanced as conflicting

---

NetKAN/PEBKACIndustriesLaunchEscapeSystem.netkan

PEBKACIndustriesLaunchEscapeSystem crashes on KSP 1.2.2, because CKAN installs a 1.3.1-only version of the mod, because the version metadata is too broad, because ksp_version is set to 1.1.3 in the netkan.
Now that's removed.
Fixes the netkan for #6148. CKAN-meta PR to follow for older versions.

Stop hardcoding game version

---

NetKAN/Kethane.netkan

There's a new Kethane out. Its hosting setup requires manual upates.

New version of Kethane

---

NetKAN/KittopiaTech.netkan

KottopiaTech's latest release is for 1.3.0. It doesn't have a KSP-AVC file.

Update game version of KittopiaTech

---

NetKAN/Taerobee.netkan

Taerobee's forum thread says it supports 1.3.1, but we have it as 1.2.2. The latest release is older than KSP 1.3, so I took a look, and it's just a parts/config mod, so it makes sense to mark it compatible with any game version.

Taerobee is just parts, mark it as version independent

---

NetKAN/KerbalWind.netkan

The latest version of KerbalWind is for KSP 1.3, but we have it as 1.1. It doesn't have a KSP-AVC file.

Update game version for KerbalWind

---

NetKAN/RCSLandAid.netkan

RCSLandAid is updated to KSP 1.3, but we have it as 1.2. It has a plugin but no KSP-AVC file.

Update RCSLandAid to game version 1.3

---

NetKAN/KerbCam-Continued.netkan

KerbCam's latest release was built for 1.2 and is reported by its author to work on 1.3, but we have it as 1.1. It doesn't have a KSP-AVC file.

Update KerbCam to KSP 1.2-1.3

---

NetKAN/KerbalLaunchVehicles.netkan

This mod's forum thread says 1.3, but we have it only as 1.3.0. There was a release recently which didn't caution "1.3.0 only", so I think it's safe to say there's no such limitation.
Discovered while investigating #6154.

Mark KerbalLaunchVehicles compatible with 1.3

---

NetKAN/UnchartedLands.netkan

UnchartedLands is marked as 1.3.1 compatible on its forum page, but we have it as 1.3.0. According to discussion on its forum thread, it works with both. It has no KSP-AVC file.

Make UnchartedLands version-independent

---

NetKAN/ConnectedLivingSpace.netkan

As much as a trailing newline is nice, I don't think it was the intended change by @linuxgurugamer in #6127.

Fix CLS revert

---

NetKAN/SCANsat.netkan

Overdrive changes the stock UI in a way that breaks SCANsat and is therefore incompatible with it.

Update SCANsat netkan for Overdrive incompatibility

---

NetKAN/AxisSystem.frozen
NetKAN/RejuvenatedDuna.frozen
NetKAN/rt-config-by-ippo.frozen

Early in my CKAN career, I was eager to eliminate all errors from http://status.ksp-ckan.org/, several of which were due to mods that had been removed from their host sites. In three instances I addressed this by deleting the .netkan files, which I found out in #5975 is a no-no; we should rename them to .frozen instead.
| Pull request | File |
| --- | --- |
| #5842 | AxisSystem.netkan |
| #5843 | RejuvenatedDuna.netkan |
| #5864 | rt-config-by-ippo.netkan |
@Olympic1, next time please tell the clueless new person about freezing. :wink: 
These files are now retrieved from the repo archive and re-added as .frozen as they should have been.

Re-add deleted netkans as frozen

---

NetKAN/PoodsCalmNebulaSkybox.netkan
NetKAN/PoodsDeepStarMap.netkan
NetKAN/PoodsMilkyWaySkybox.netkan

Switching from TextureReplacer to Sigma Replacements: Skybox as a dependency and now listing Distant Object Enhancement as a suggested mod.

Update NetKAN files for Pood's Skyboxes

---

NetKAN/BluedogDB.netkan

This is bundled in the download but wasn't mentioned on the forum thread. As per: 
- https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1226-guiana/&do=findComment&comment=3279133

 Add missing B9PartSwitch dependency to BDB

---

NetKAN/SCANsat.netkan

SCANsat [18.3 no longer conflicts](https://github.com/S-C-A-N/SCANsat/commit/67bb2d30de5e840b8a730aecd1b2361400608566) with Overdrive:
https://github.com/KSP-CKAN/NetKAN/pull/6187#issuecomment-364139701

Remove Overdrive conflict from SCANsat

---

NetKAN/Ballistanks.netkan
NetKAN/JDBallisback.netkan
NetKAN/JDLiquidFuelCell.netkan

These mods all try to install `GameData/JatwaaDemolitionsCo/Resources.cfg`:
- Ballistanks
- JDLiquidFuelCell
- JDBallisback
The contents of the file are different for each mod, so there's no prospect of reconciling them via a common dependency.
This PR marks them all as conflicting.
Fixes #6224.

Add conflict relationships to jatwaa's mods

---

NetKAN/ScienceAlert.netkan

Toolbar is required for ScienceAlert. I think this was added to the thread after it was added to CKAN (and it's still not mentioned on SpaceDock).

Add Toolbar dependency to ScienceAlert

---

NetKAN/CritterCrawler.netkan

See https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1226-guiana/&do=findComment&comment=3298253
`"depends"` is a JSON array of objects, one object per dependency. CritterCrawler had two `"name"` properties in the same object, when it should be two objects.

Split dependency into two objects

---

NetKAN/INSTANTIATOR.netkan
NetKAN/KS3P.netkan

This pull request adds mods by @TheWhiteGuardian to CKAN:
- KS3P, a post-processing visual mod
- INSTANTIATOR, also a visual mod
They are pretty straightforwardly packaged, with an identifier-matching directory containing the files.
The only complication is that INSTANTIATOR includes an example config file that looks like it would not be good to have installed, since it includes statements like "Body = X" that probably are not valid since X is not a planet, so we filter that file out. Modders who need that file can and should download the mod outside of CKAN.
Permission of author:
- https://forum.kerbalspaceprogram.com/index.php?/topic/168992-13x-instantiator/&do=findComment&comment=3303409
- https://forum.kerbalspaceprogram.com/index.php?/topic/168763-13x-ks3p/&do=findComment&comment=3303 …

Add @TheWhiteGuardian's mods

---

NetKAN/KSPLogiRGB-battlemoose.netkan

Folder structure changed slightly, need `find` instead of `file` since GameData isn't in the root of the ZIP anymore.

Fix install stanzas for KSPLogiRGB-battlemoose

---

NetKAN/GPP.netkan
NetKAN/GPPCloudsHighRes.netkan
NetKAN/GPPCloudsLowRes.netkan
NetKAN/GPPSecondary.netkan

GPP had a new release, then replaced the same download URL with a ZIP with an updated KSP-AVC file.
The metadata hash doesn't match the current download, which causes errors at installation, but the netkan bot refuses to re-index the download:
This must mean the original file is still in the bot's cache. This pull request makes whitespace-only changes to the affected netkans, so their CKAN-meta entries will be regenerated by Jenkins.

Force GPP hash recalc

---

NetKAN/EnvironmentalVisualEnhancements.netkan

EVE currently has a hard coded game version in its netkan.
But it has a KSP-AVC file in the download. Now we check it instead.

Use EVE's version file

---

NetKAN/SmokeScreen.netkan

I think Sarbian edits these without the aid of the pull request validation scripts, and this one has a syntax error that's breaking #6324.

Remove extra comma in SmokeScreen.netkan

---

NetKAN/AlphabeticalKerbals.netkan

Addon has been tested and doesn't need to be modified, this is just marking it as compatible now that testing is complete.

Updated AlphabeticalKerbals to KSP version 1.4

---

NetKAN/StockVisualEnhancements.netkan

Scatterer is no longer required

move Scatterer SVE

---

NetKAN/KerbalXMod.netkan

>katateochi  2,892
>Started conversation: Saturday at 10:09 PM
>
>Hey Politas!
>
>Wondering if you could sort something out for me. I've updated the KerbalX mod to work with KSP 1.4.0, but that version is incompatible with KSP 1.3.x. But I've just heard from someone that CKAN updated the KXmod in their 1.3.1 install to the latest version. 
>
>Can you make it so that the 0.1.4 version of the mod is only for KSP 1.4.0, and any older versions of KSP should stick with the 0.1.3 version of the mod?
>KSP <= 1.3.1 - https://github.com/Sujimichi/KerbalXMod/releases/tag/0.1.3
>KSP == 1.4.0 - https://github.com/Sujimichi/KerbalXMod/releases/tag/0.1.4
>
>Thanks! 
>
>Kat

Change KerbalXMod compatibility as per forum PM

---

NetKAN/ShowFPS.netkan

ShowFPS is marked as compatible with all game versions 1.1 and later, but it doesn't work on 1.2.
This pull request sets it to use a proper `$kref` property so the actual version info will be pulled from Curse. This not only fixes the current problem but ensures that any future uploads, if there are any, will work properly.
See KSP-CKAN/CKAN-meta#1333.

Switch ShowFPS to a proper kref

---

NetKAN/DeepSpaceSurfaceHabitatUnitPack.netkan

Two of this mod's optional configs have been removed.

Remove Snacks cfg from DeepSpaceSurfaceHabitatUnitPack

---

NetKAN/ContractConfigurator-AnomalySurveyor.netkan
NetKAN/ContractConfigurator-FieldResearch.netkan
NetKAN/ContractConfigurator-RemoteTech.netkan
NetKAN/ContractConfigurator-Tourism.netkan
NetKAN/ContractConfigurator.netkan
NetKAN/WaypointManager.netkan

Most of the old-style KSP forum links broken and I needed to fix them.  I figured this was a good opportunity to move everything in the netkans into my own repos to make this type of change easier in future.

Move nightingale mods to use mod-owned .netkan files.

---

NetKAN/CustomBarnKit.netkan

@linuxgurugamer noted that this version was showing up as compatible with 1.3.1 even though its .version file says it isn't. Let's try removing the versions from the netkan.
Fixes KSP-CKAN/CKAN#2390.

Remove hard coded versions from CustomBarnKit

---

NetKAN/PicoPort.netkan
NetKAN/REKT.netkan

REKT and PicoPort both install:
- SHED/License
- Several files under SHED/Agencies
This causes a conflict where there shouldn't be one.
Now the install stanzas filter out these conflicting paths.
In addition, we now use PicoPort's .version file, previously ignored.
Fixes #6413.

Filter out conflicting License and Agencies files

---

NetKAN/MkerbIncOxidizerTank.netkan

This line is supposed to find the files changed in a pull request:
https://github.com/KSP-CKAN/xKAN-meta_testing/blob/a5050a2b15e0515863de23895ffb20ad6df2b086/NetKAN/build.sh#L200
It seems to sometimes pull in additional changes. I haven't done a complete investigation, but I saw it once before because a pull request was failing due to a syntax error made by Sarbian to an unrelated file.
Now #6418 is failing due to a different syntax error by Sarbian in this commit:  https://github.com/KSP-CKAN/NetKAN/commit/443a149b0c173453349cdcfb99a89ec8abb253a7
I fixed it in master, but that PR needs to be rebased to get the fix, and git won't let me force-push to Space-Duck's branch. So this pull request does it instead.
Closes #6418.

Add Mkerb Inc. Oxidizer Tank from SpaceDock

---

NetKAN/Snacks.netkan

Snacks has a .version file, but it's currently hard coded to use game version 1.3. This is creating bad metadata for the current version, which is 1.4.1 only.
This pull request updates it to use the .version file. However, the current .version file has KSP_VERSION_MIN without KSP_VERSION_MAX, which indicates compatibility with all future releases. Since that's probably wrong, this pull request also tries to filter out that KSP_VERSION_MIN value.
Fixes #6434

Stop hardcoding game version for Snacks

---

NetKAN/AviationLights.netkan

I'm honestly a little unsure as to how this affects versions previous to v4.0.0 of the mod, which should still be marked as 1.3 compatible only.

Aviation Lights v4.0.0+ now supports KSP 1.4.x - Upping version number.

---

NetKAN/EnvironmentalVisualEnhancements-HR.netkan

As per #6445, `EnvironmentalVisualEnhancements-HR` should not be version-specific. Currently it has a max game version of 1.3.9.
This pull request removes version limits from this module.
Fixes #6445.

Allow any game version for EVE-HR

---

NetKAN/DynamicBatteryStorage.netkan

DynamicBatteryStorage is one of those mods that exists only as a bundled dependency in multiple other mods. Currently it's sourced from KerbalAtomics' download, which hasn't been updated to 1.4. Now it's switched to NearFutureElectrical, which is updated to 1.4. It also will hopefully pull from the right KSP-AVC file now.
Fixes KSP-CKAN/CKAN#2404.

Get newer DynamicBatteryStorage

---

NetKAN/KSPInterstellarExtended.netkan

This mod's $vref is commented out with a note indicating this was done because the version file was invalid. The version file in the current download looks OK to me, so this pull request is a test of whether it's time to uncomment this $vref.

Reactivate KSPIE's version file

---

NetKAN/ExperimentTracker.netkan
NetKAN/OPTSpacePlaneMain.netkan
NetKAN/StoreMyReports.netkan
NetKAN/WaterSounds.netkan

We found out in #6481 that Curse can't auto update anymore, because the API has been asked to shut down.
There are 12 mods with a `"$kref"` on Curse, 4 of which are also hosted elsewhere. This pull request migrates those 4 to their alternate hosts.

Migrate mods with alternate downloads off of Curse

---

NetKAN/RealisticHeatMgmt.netkan

This was removed from SpaceDock, but is still on GitHub. We could freeze it, but if we let the bot index it on GitHub then the version already in CKAN would still work.

Get RealisticHeatMgmt from GitHub

---

NetKAN/AstronomersVisualPack.netkan

Astronomer's Visual Pack follows a non-sequential versioning scheme in its GitHub release versions (51 < 52 < 53 < 6 < 61 < 62 < 63 < 7, etc.), but has a proper Major.Minor.Patch structure in its version file. Since Netkan prefers GitHub release versions by default, this means that v3.63 is currently considered the highest version, even though v3.7 is newer.
This pull request sets `"x_netkan_trust_version_file"` to `true` to make future versions work correctly, and increments the epoch to force the current version to be higher than v3.63.
Fixes #6480.

Fix versioning for AstronomersVisualPack

---

NetKAN/FuelWings.netkan
NetKAN/ModularFuelTanks.netkan

Version 3.2e for Kerbal Space Program 1.4.2
Released on 2018-04-02
Version FuelWings_v3.2d for Kerbal Space Program 1.3.0
Released on 2017-07-04
Fixes #6497.

Add Epoch to FuelWings and Update ModularFuelTanks

---

NetKAN/CapCom.netkan
NetKAN/ContractsWindowPlus.netkan
NetKAN/DMagicOrbitalScience.netkan
NetKAN/PortraitStats.netkan

#6503 pointed out several mods with official support for all of 1.4.x that are only indexed for one game version. They have version files that specify 1.4.0-1.4.8, but they're not being used currently.
This pull request updates these mods to get the compatible versions from their version files.
Fixes #6503.

Use version files for DMagic's mods

---

NetKAN/DMagicScienceAnimate.netkan

This mod has its version hard coded in the netkan because it's hosted on GitHub and there's no version file, and the version is now out of date.
This pull request changes it to a version-specific override so future versions won't have old game versions applied.

Version override for DMagicScienceAnimate

---

NetKAN/KWRocketryRebalanced.netkan

No longer has an extra parent directory for GameData, currently erroring out with "Could not find KWRocketryRebalanced/GameData/KWRocketry entry in zipfile to install"

Fix KWRocketryRebalanced install stanza

---

NetKAN/KerbalRenamer.netkan

This mod is released for specific game versions, but it doesn't have a version file, so the compatible version is stored in its netkan entry. The latest release is for KSP 1.4.3, and this pull request updates the netkan for that.
Fixes KSP-CKAN/CKAN#2446.

Update KerbalRenamer game version

---

NetKAN/DecouplerShroud.netkan

I've added a version file to my mod. The "$vref" line will get the ksp version from that file, correct? And does this affect the current release, or just new ones?

Use version file for DecouplerShroud

---

NetKAN/ThorTech.netkan

#6559 updated this mod's install path, but I thought it had to include the full path. Apparently it only needs the parent directory. That makes sense given that we usually install to GameData.
This is on SpaceDock so it won't pass tests till KSP-CKAN/CKAN#2453 gets resolved.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/168326-131-143-thor-tech-v0962-~-may-10-2018/&do=findComment&comment=3385780

Fix ThorTech's path again

---

NetKAN/RealHeat.netkan

This mod lives on GitHub and has no .version file, so the CKAN team has the pleasure of maintaining its version compatibility manually.
https://github.com/KSP-RO/RealHeat/releases
Fixes #6572.

Update RealHeat game version

---

NetKAN/Kerbalism.netkan

This mod is suffering from bot reversion syndrome; the author replaced the download after the bot cached it, so now the checksums are wrong and [our fixes](https://github.com/KSP-CKAN/CKAN-meta/commit/e5aafca7dcb173abc89a2a9e13e63ed1822dc71c) are [reverted every 3 hours](https://github.com/KSP-CKAN/CKAN-meta/commit/58b549be2e64c73e994880fbfd1c4b501d11df9c#diff-cf1d668dd5b46acd533e4d55ca704640).
As of KSP-CKAN/CKAN#2337, GitHub is immune to this problem. This mod's releases are hosted there as well, so now we'll use GitHub for it instead.

Switch Kerbalism to GitHub

---

NetKAN/ProceduralFairings.netkan

This mod went from v5.0 to 1.4.3.1, necessitating an epoch bump.
In #6547 and #6552, an epoch was added but then removed. The latest version is currently counted as earlier than nearly all other verisons.
Fixes KSP-CKAN/CKAN#2455.

Re-add epoch for ProceduralFairings

---

NetKAN/ReCoupler.netkan

KSP-CKAN/CKAN-meta#1350 is attempting to update this mod to be compatible with all of KSP 1.3 and 1.4, as per [its forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/157131-*). However, it's hosted on SpaceDock and has no version file, so that change would be overwritten by the NetKAN bot on its next pass.
Instead, this pull request puts these changes in an override in the netkan file.
Closes KSP-CKAN/CKAN-meta#1350.

Override ReCoupler compatible versions

---

NetKAN/FullAutoStrut.netkan

This mod has some versions with a 'v' and some without, and it's causing confusion.
This pull request adds the `x_netkan_force_v` property to try to work around this. I haven't used this property before, so I'm not sure it will work, and will be checking the validation output to find out.

Force v for FullAutoStrut

---

NetKAN/CommunityTechTree.netkan

This mod has a version file promising compatibility up to KSP 1.4.9, but we're only using SpaceDock's compatible version of 1.4.2.
This pull request tells Netkan to look at the version file.
Should help with the validation error in #6618.

Use CTT's version file

---

NetKAN/InterstellarFuelSwitch-Core.netkan

This mod ships a valid version file, but it's not used. Currently it only specifies compatibility with the same version as indicated on SpaceDock, but that might change in the future. This pull request updates the netkan to check the version file.

Use IFS's version file

---

NetKAN/FlagPack.netkan

This mod's earliest versions are v1.0 and v1.1, but the latest is just 1.1.1 without the 'v'.
Setting force_v to head off problems.

Add force_v to FlagPack

---

NetKAN/KittopiaTech.netkan

This mod has been erroring out for quite a while, because the author deleted all the releases.
The forum thread explains that they're moved to a new repo, so this pull request makes that change.

Point KittopiaTech to Legacy repo

---

NetKAN/PhotonSailor.netkan

In order to play with the new KSC laser, you need to have acces to several CTT technodes.

Added dependancy on CommunityTechTree to Photon Sailor

---

NetKAN/BetterBurnTime.netkan

BetterBurnTime 1.6.1 originally supported KSP 1.3.1, and as more game versions were released, that same version of BBT remained compatible, so its version on SpaceDock was simply updated, currently at 1.4.4. This meant that while you could have installed it on several previous game versions, it no longer appears as compatible.
This pull request overrides BBT 1.6.1 to support 1.3.1 through all of 1.4.
Fixes #6629.

Support original game versions for BBT 1.6.1

---

NetKAN/KerbalFlightIndicators.netkan

This mod previously had a game version hard coded in the netkan, but its latest release includes a version file. This pull request updates the netkan to use the version file.
Closes KSP-CKAN/CKAN-meta#1352.

Use KerbalFlightIndicators's version file

---

NetKAN/TundraExploration.netkan

* It depends on Kerbal Reusability Expansion, so include that dependency
* Allow installation of example craft
This was done in talks with the author, @damonvv

Couple of fixes for Tundra Exploration

---

NetKAN/RemoteTechRedevAntennas.netkan

[@KSP-TaxiService says](https://github.com/KSP-CKAN/NetKAN/pull/6660#issuecomment-410899718) that this mod supports KSP 1.3 and up. This pull request adds an override to do that (if I got the syntax right).

Make RemoteTechRedevAntennas support 1.3 and 1.4

---

NetKAN/LoadingTipsPlus.netkan

We're not supposed to de-bundle MiniAVC, see #1455. I didn't know that while indexing this mod, and I filtered it. This pull request removes that filter.

Don't filter MiniAVC out of LTP

---

NetKAN/MissionController2.netkan

MissionController has accidentally shipped KSP-AVC's version file in addition to its own, which is making Netkan error out on it. This pull request adds a regex to select the right one.

Specify version file for MissionController

---

NetKAN/DiscordRP.netkan

[DiscordRP says this on Curse](https://kerbal.curseforge.com/projects/discordrp/files/2532403):
However, currently it's filed as 1.4.0 only, and occasionally 1.3 only (see #6622).
Now this mod's compatible game version is overridden to reflect its compatibility with KSP 1.2 through 1.4. This will more accurately reflect the versions on Curse. It also fixes #6622, since Netkan will now discard the value that seems to be fluctuating back and forth.

Override versions for DiscordRP

---

NetKAN/WarpEverywhere.netkan

This mod's latest version is for KSP 1.4.3, but its netkan hard codes compatibility with 1.2.
This pull request removes that hard coding.

Get WarpEverywhere's game versions from SpaceDock

---

NetKAN/RealHeat.netkan

RealHeat's latest release has a version file, so this pull request removes the hard coding of `ksp_version` in favor of a `$vref`.
@rsparkyc, tagging you in case GitHub doesn't send you a notification automatically.
Fixes #6692.

Use RealHeat's .version file

---

NetKAN/KSPInterstellarExtended.netkan
NetKAN/PersistentRotation.netkan

The bot staged an update for KSPI-E :+1:, and a few issues surfaced.
Closes KSP-CKAN/CKAN-meta#1357.
The homepage link is broken, probably from an earlier iteration of the forum.
Now it's updated to point to the current support thread.
The ZIP has a folder by this name, but it's not handled in the netkan either as a dependency or an install stanza. It seems to consist of an engine, tank, and IRSU for a hybrid solid/liquid motor based on aluminüm. As far as I can tell this is not a standalone mod but an integral part of KSPI-E packaged outside the usual WarpPlugin folder.
Now a new install stanza handles this folder.
These mods have folders in the ZIP but aren't listed as dependencies.
Now ToolbarController is recommended and FilterExtensions is suggested, since the forum thread explicitly …

KSPI-E: update homepage, dependencies, and install

---

NetKAN/PartOverhauls.netkan

This pull request makes two changes to `PartOverhauls.netkan`.
1. Add "Porkjet's" to the start of the `name` property because players generally identify this mod with that user name (the `identifier` is unchanged)
2. Remove the `ksp_version_max` property, previously set to 1.3.9. This mod contains only parts, not plugins,  and the [original announcement](https://forum.kerbalspaceprogram.com/index.php?/topic/147582-update-12-pre-release-is-here/) doesn't specify version limitations, so there's no reason to think these will become incompatible. This will make the part overhauls show up for KSP 1.4 again.

Make Porkjet overhaul compatible with all future versions

---

NetKAN/AnimatedDecouplers.netkan

This mod has a .version file, but its netkan currently hard codes a KSP version, which is now out of date.
Now it has a `$vref` instead.
Fixes #6730.

Use AnimatedDecouplers' version file

---

NetKAN/ImpossibleInnovations.netkan

This mod currently says
```
Module contains no files matching: file="GameData/ImpossibleInnovations", file="Ships"
```
It has changed ownership and the format is slightly modified.

Ships folder moved in ImpossibleInnovations, add vref, fix homepage

---

NetKAN/ExtraPlanetaryLaunchpads.netkan

ExtraPlanetaryLaunchpads previously required manual netkan updates for each release, but it has [an online .version file](http://taniwha.org/~bill/EL.version). As of KSP-CKAN/CKAN#2517, we can use that file to find the latest release. A new version of this mod dropped today, and the online .version file was updated.
This pull request updates ExtraPlanetaryLaunchpads to use its online .version file to find new releases.

Use AVC kref for ExtraPlanetaryLaunchpads

---

NetKAN/RemoteTechRedevAntennas.netkan

This mod has a version file, updating the netkan to use it.
Fixes #6783.
@techman83, purging D8C909AA-netkan-RemoteTechRedevAntennas.zip might help prevent future bot problems here, since this download appears to have been modified in-place on SpaceDock.

Vref for RemoteTechRedevAntennas

---

NetKAN/BetterScienceLabsContinued.netkan

Current error:
> Could not find Better Science Labs Continued entry in zipfile to install
The spaces have been removed from the path in the ZIP.

Fix BetterScienceLabsContinued install path

---

NetKAN/OuterPlanetsMod.netkan

Update the NetKAN metadata to point to remotely hosted NetKAN metadata.

OPM - Remote hosting of NetKAN metadata

---

NetKAN/NewTantares.netkan
NetKAN/NewTantaresLV.netkan

Tantares and TantaresLV are hosted on GitHub and don't have version files, so their version compatibility is tracked in their netkan files. The latest releases are compatible with 1.4-1.5 and 1.5 respectively, according to their forum threads. This pull request makes that update.
Fixes #6802.

Update NewTantares game versions

---

NetKAN/ScienceLabInfo.netkan

"—" was showed as "???" in the abstract

ScienceLabInfo abstract

---

NetKAN/CommunityTerrainTexturePack.netkan

Update the NetKAN metadata to point to remotely hosted CTTP NetKAN metadata.

CTTP - Remote hosting of NetKAN metadata

---

NetKAN/Mk3Expansion.netkan

Updates M3X dependency from IFS to B9PS and adds M3X example craft.

Update M3X netkan

---

NetKAN/FerramAerospaceResearch.netkan
NetKAN/FerramAerospaceResearchContinued.netkan

Replaced the restricted assets with different ones so there are no licensing issues. Would like to get this on CKAN so everyone can use one version and not many different recompiles. 
If I was providing backports, how would that work with CKAN? Would I need to create multiple releases one for each KSP version?
Edit: build fails because ModularFlightIntegrator is not found for KSP 1.5 but a version from KSP 1.4.5 works.

New FAR fork

---

NetKAN/ModularFlightIntegrator.netkan

This mod has a vref and a version file specifying 1.5.0 as the minimum.
The hard coded values in the netkan brought that down to 1.4.0, which is bad.
Now the vref stands alone.

Remove hard coded game versions for ModularFlightIntegrator

---

NetKAN/ExtraPlanetaryLaunchpads.netkan

ExtraplanetaryLaunchpads has changed its internal version file from EL.version to ExtraplanetaryLaunchpads.version. This pull request makes that change.

Update EL's version file path

---

NetKAN/IDFlagsandDecals.netkan

Based on KSP-CKAN/CKAN-meta#1384, which is making the same change for already indexed versions.

Add ModuleManager dependency for IDFlagsandDecals

---

NetKAN/KerbalKonstructs.netkan

The author forgot to attach the download to the latest GitHub release. Switch this one to SpaceDock where that's impossible.

Switch KerbalKonstructs to SpaceDock

---

NetKAN/RSSVE-HR.netkan
NetKAN/RSSVE-LR.netkan

https://github.com/KSP-CKAN/NetKAN/pull/5321#issuecomment-439599861:
> I have been getting false "bug reports" about Scatterer not working. **[RSSVE requires specific mod versions that are documented in the RSSVE wiki](https://github.com/PhineasFreak/RSSVE/wiki/Installation)** and not all mod versions will work with it.
When installing this, I also got prompted for several `provides` relationships that look like they should be satisfied by RSSVE.
- Scatterer 2:v0.0320b is now required as per the referenced wiki page
- New provides/conflicts based on inspecting the configs:
- EnvironmentalVisualEnhancements-Config
- Scatterer-config
- Scatterer-sunflare
All changes are made to both RSSVE-HR and RSSVE-LR.
@PhineasFreak, I'd like to check the bug reports you received to confirm that they're …

Require specific Scatterer for RSSVE

---

NetKAN/KSPInterstellarExtended.netkan

- New releases of this mod are coming out at a rapid rate
- The metadata being generated is fine and doesn't need manual review (we haven't had any issues reported that could have been caught that way)
- The author submits netkan PRs from time to time, so we can work with him directly if there are any problems
- The staging mechanism doesn't currently work very well with pull requests; if we need to make an edit (as we did in the first staged PR), it won't be reflected on the bot's branch, so we get the *entire* history of staged releases in each PR, which can't be merged normally without messing things up.
For these reasons, the `x_netkan_staging` property is now turned off for KSPInterstellarExtended.

Stop staging KSPInterstellarExtended

---

NetKAN/AATI-Flags.netkan
NetKAN/AdvancedTextures.netkan
NetKAN/DeclasseVoodooCar.netkan
NetKAN/MilkyWay-Skybox.netkan
NetKAN/PureElectricEngines.netkan
NetKAN/SpaceXLandingPad.netkan
NetKAN/StockalikeUtilityVehicles.netkan
NetKAN/WoodSpaceProgram.netkan

More mods have been added to SpaceDock with CKAN flair. They have to be handled manually due to KSP-SpaceDock/SpaceDock#188.
Previous was #6827.
Fixes #6846.

SpaceDock catch-up 5

---

NetKAN/Landertron.netkan

This mod was almost indexed in #4863, then frozen instead in #4871, then the mod author gave the all-clear in a comment on #5180, but it wasn't actually indexed at that time.
Now it's unfrozen and has a $vref.
Fixes #6864.

Unfreeze Landertron

---

NetKAN/CTTStockRebalance.netkan
NetKAN/Kethane.netkan
NetKAN/SDHI-ServiceModuleSystem.netkan

These mods have out of date metadata.
- CTTStockRebalance was re-uploaded by someone else and marked as compatible with KSP 1.5.1
- Kethane is hosted on taniwha.org and requires manual maintenance of everything
- SDHI-ServiceModuleSystem is on GitHub but has no version file, so it was listed as compatible with the wrong game version
Now they're fixed.

Update manually maintained mods

---

NetKAN/RSSVE-HR.netkan
NetKAN/RSSVE-LR.netkan

Currently, scatterer configs for stock are not installed and RSSVE depends on them. This makes installation of RSSVE broken.

Fix installation of RSSVE

---

NetKAN/KerbinSide.netkan

KerbinSide has several folders split between KerbinSide and KerbinSideCore, and a few that aren't installed by anything.
https://spacedock.info/mod/1347
| Folder | Module |
| --- | --- |
| Centers | *Missing* |
| CoreAssets | KerbinSideCore |
| Flags | KerbinSideCore |
| FreeAssets | *Missing* |
| GroundControl | KerbinSide |
| MainBases | KerbinSide |
Now the Centers and FreeAssets folders are included in KerbinSide.
Fixes #6888.

Add install stanzas for KerbinSide

---

NetKAN/ChakaMonkeyExplorationSystems.netkan

This mod is out for KSP 1.4.3, but one of its dependencies only goes up to KSP 1.1:
This is because AnimatedDecouplers-x86 is now just AnimatedDecouplers. This pull request makes that change.

Switch Chaka to platform neutral version of AnimatedDecouplers

---

NetKAN/RealEngines.netkan

RealEngines' versions are all messed up. There's a v1.x series, and then a 2.0 series without a leading 'v'.
https://github.com/KSP-CKAN/CKAN-meta/tree/master/RealEngines
Adding an epoch.
Fixes KSP-CKAN/CKAN#2622.

Epoch RealEngines

---

NetKAN/DiscordRP.netkan

DiscordRP was having a problem with inconsistent versioning, see #6622. In #6674, we set an override to try to stabilize it. More recently, KSP-CKAN/CKAN#2616 should have created a better solution that made the overrides unnecessary. Now the overrides are removed.

Remove DiscordRP override

---

NetKAN/KerbalChangelog.netkan

Previous releases contained a folder matching the identifier.
The latest one has KerbalChangeLog1.1.4 instead.

Install stanza for KerbalChangelog

---

NetKAN/GravityTurnContinued.netkan

This mod has a hard coded game version of 1.4, but it should be 1.3-1.6.
Replaces KSP-CKAN/CKAN-meta#1394 which tried to do this in CKAN-meta and got overwritten by the bot.

Update compatible versions for GravityTurn

---

NetKAN/MakingHistoryEngineTweaks.netkan

@TykoTek says this mod is no longer necessary as of KSP 1.6.
Fixes #6938.

Set game version range for MakingHistoryEngineTweaks

---

NetKAN/PreciseEditor.netkan

PreciseEditor now has a .version file. this pull request uses it.
Closes #6946.

Add vref to PreciseEditor

---

NetKAN/Kerbalism.netkan

In #6575 we switched Kerbalism from SpaceDock to GItHub, but this mod's GitHub versions are inconsistent in whether they are prefixed with a 'v', so we used `x_netkan_trust_version_file` to make a smooth transition without epochs. Later it was switched back to GitHub.
Now the .version file in the latest release is wrong but the version on SpaceDock is right (see steamp0rt/Kerbalism#306), so `x_netkan_trust_version_file` is removed.

Stop trusting Kerbalism's version file

---

NetKAN/CryoTanks.netkan
NetKAN/DeployableEngines.netkan
NetKAN/DynamicBatteryStorage.netkan
NetKAN/NearFutureProps.netkan

Up until recently, some of Nertea's mods only existed as bundled pieces of other mods, and their netkans had to choose one download as the source. This created a sort of artificial dependency situation, where (for example) KerbalAtomics might not be installable until NearFutureElectrical updated, or vice versa, even though they're technically independent, because they depend on bundled mods that we source from one or the other.
See KSP-CKAN/CKAN#2404 for an example.
Nertea asked on a Discord about opportunities to improve how his mods work with CKAN, and I mentioned this. He has graciously decided to provide standalone releases for these dependencies.
Now the bundled dependencies are sourced from their own independent repositories.
| Mod | Change |
| --- | --- |
| CryoTanks | Change kref …

Source Nertea dependencies from independent repositories

---

NetKAN/MarkIVSpaceplaneSystem.netkan

MarkIVSpaceplaneSystem's .version file got renamed, and some of its dependencies haven't been included in the download for quite a while.

Fix mk4 version file and deps

---

NetKAN/ExtendedInfoSciExp.frozen
NetKAN/ScienceSituationInfo.netkan

- https://spacedock.info/mod/1008 is indexed twice, as ScienceSituationInfo and ExtendedInfoSciExp
- ScienceSituationInfo has the wrong license
- ScienceSituationInfo lists version 1.3.1.2 as 1.3.1.1
- ScienceSituationInfo is missing several versions that are indexed under ExtendedInfoSciExp
Timeline of events:
1. ScienceSituationInfo indexed 2015-10-23, #2445 (#2333)
2. ScienceSituationInfo frozen 2016-02-18, #3107 (#3106)
3. ExtendedInfoSciExp indexed 2016-10-26, #4826
4. ExtendedInfoSciExp epoched 2016-12-31, #5101
5. ScienceSituationInfo unfrozen 2017-02-26, #5290
6. ScienceSituationInfo re-frozen 2017-02-26, #5291
7. ScienceSituationInfo unfrozen 2018-02-15, #6247
- ExtendedInfoSciExp frozen with comment about it being a duplicate
- ScienceSituationInfo no longer hard codes version …

Clean up duplicate science info module

---

NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan

This PR updates versions 1.6+ of stock Custom Asteroids configs to depend on Custom Asteroids 1.6 or later. Previous versions of the configs may also be used with CA 1.6, but new configs may not work with older versions of Custom Asteroids.

Latest CustomAsteroids configs need recent CA version.

---

NetKAN/CustomAsteroids-Pops-OPM-Outer.netkan

This PR registers a new Custom Asteroids config with CKAN. The proper NetKAN file can be found at https://github.com/Starstrider42/Custom-Asteroids-Extras/blob/master/CustomAsteroids-Pops-OPM-Outer.netkan.

Add Custom Asteroids OPM config.

---

NetKAN/Kopernicus.netkan

Kopernicus has a broken link as `resources.homepage`.
I don't know exactly how or why that happened. Maybe another forum migration? Maybe the incident where a moderator's account was compromised and abused to delete threads?
Whatever the cause, it's fixed now.
Fixes #6978.

Fix Kopernicus homepage

---

NetKAN/DebugStuff.netkan

This mod can show collider wireframes. It's hosted on Sarbian's Jenkins.
Sarbian's OK:  https://forum.kerbalspaceprogram.com/index.php?/topic/135726-1x-debugstuff-2018-03-13-see-the-hidden-secrets-of-the-game-objects/&do=findComment&comment=3531852

Add DebugStuff

---

NetKAN/Kopernicus.netkan

Kopernicus had netkan staging enabled in #4794. The rationale was:
> Might want to add any mod with manually set ksp_version to the staging queue so new versions don't get generated for the wrong KSP versions.
Kopernicus has a version file and a $vref as of #5535, so that reasoning no longer applies. This pull request disables staging for that reason.

De-stage Kopernicus

---

NetKAN/MechJeb2.netkan

MechJeb's game version is hard coded in the netkan, which has caused the latest version to be out of date. Now it's updated from 1.5 to 1.6.
#4794 made the point that staging might be a good way to avoid this, since it would allow us to check the game versions before they go live. So now staging is enabled.

MechJeb2 compatibility and staging

---

NetKAN/SDHI-ServiceModuleSystem.netkan

SDHI-ServiceModuleSystem's game compatibility is hard coded in its .netkan, and currently out of date. It's now updated from 1.5 to 1.6.
Similar to #6992, the Netkan bot's staging feature is now enabled for this mod so we can check compatibility before a new version goes live.
Fixes #6993.

SDHI-ServiceModuleSystem compatibility and staging

---

NetKAN/MoarFEConfigs.netkan

This module's folder path changed, and the license on SD says "Creative Commons Zero v1.0 Universal" but is "unknown" in the netkan.

Fix Moar Filter Extension Configs

---

NetKAN/UniversalStorage2.netkan

Apparently this mod has a version file now, but its netkan is only set up to use the version from SpaceDock. Now it has a vref.
Fixes #7004.

Obey UniversalStorage2's version file

---

NetKAN/MainSailorTextures-Fairings.netkan
NetKAN/MainSailorTextures-Theta.netkan

This ain't right:
One of those is MainSailorTextures-Fairings, and another is MainSailorTextures-Theta.
Now they're named that way instead of looking like duplicates of Gamma.

Fix MainSailor module names

---

NetKAN/CryoEngines-LFO.netkan
NetKAN/KerbalAtomics-NFECompatibility.netkan
NetKAN/NearFutureElectrical-DecayingRTGs.netkan
NetKAN/NearFuturePropulsion-LowThrustEP.netkan
NetKAN/NearFuturePropulsionExtras.frozen

I discovered that all the Extras support packages for my mods install to an incorrect location, creating ModuleManager targeting conflicts. They are intended to go in the GameData root. I've changed this for the ones I could track down in this PR.

Move extras to right location

---

NetKAN/OSEWorkShopCont.netkan

OSEWorkShopCont goes up to version 1.2.5 on KSP 1.4.2.
OSEWorkShopReworked is a new fork with versions up to 1.2.9 on KSP 1.6.1.
This pull request marks the former as `replaced_by` the latter.
Part of #7027.
ckan compat add 1.4 1.5 1.6

Add replaced_by to OSE Workshop branches

---

NetKAN/IR-Model-Rework-Core.netkan
NetKAN/IR-Model-Rework-Expansion.netkan
NetKAN/IR-Model-Rework-Utility.netkan
NetKAN/SentarExpansion.netkan

Some modules have `version_min` properties in relationships. The correct property is `min_version`:
https://github.com/KSP-CKAN/CKAN/blob/6b4cd143996f029b94162ec89a2e0cb86f9a7c3f/Core/Types/CkanModule.cs#L37-L42
Noticed during #7056.
This pull request fixes it.

Fix bad min version syntax

---

NetKAN/Atoren.netkan
NetKAN/ThalassaSystem.netkan
NetKAN/TopiaiSystem.netkan

These are the mods added since #7029 (and #7044).

SapceDock catch-up 11

---

NetKAN/DMagicOrbitalScience.netkan
NetKAN/SCANsat.netkan

Some weird SCANsat netkan change seems to have tagged along with this update for some reason, I'm not sure how to get rid of it. It seems to be white space changes and a block for OverDrive, the UI replacement mod. I seem to remember that mod causing issues with SCANsat at some point, but I'm not sure if that is still the case.

DMagic Orbital Science recommendation changed from US1 to US2

---

NetKAN/ContractConfigurator-HistoricMissions.netkan
NetKAN/ContractConfigurator-HistoricMissionsRSS.netkan
NetKAN/FerramAerospaceResearch.netkan
NetKAN/MechJeb2.netkan
NetKAN/MilitaryVehicleChassis.netkan
NetKAN/PlanetWiki-OPM.netkan
NetKAN/RoverFuelTanks.netkan
NetKAN/RoverWheelSounds.netkan
NetKAN/SDHI-ServiceModuleSystem.netkan
NetKAN/SovietConversion.netkan
NetKAN/StockVisualEnhancements.netkan

As of KSP-CKAN/NetKAN-bot#88 we now have the option to set a property `x_netkan_staging_reason` in a netkan to tell metadata maintainers why a module has staging enabled. This property is used as the body of a staged pull request when present.
In several cases, the `comment` property had this information; these are now updated to use `x_netkan_staging_reason` instead.
In other cases the reason for staging could be figured out by checking the pull requests where it was enabled. These now have `x_netkan_staging_reason` added.
RoverWheelSounds now has its game versions updated to match its forum thread.
PlanetWiki-OPM had its reason for staging removed in #4988, so it is now no longer staged.
ckan compat add 1.1

Populate known staging reasons

---

NetKAN/BehemothAerospaceEngineeringLargeParts.netkan
NetKAN/GolderSystem.netkan
NetKAN/SolidPropulsionIndustries.netkan

These are the mods added since #7059.

SpaceDock catch-up 12

---

NetKAN/GravityTurnContinued.netkan

At least one active mod suggests GravityTurn, which was last indexed for KSP 1.0.5.
GravityTurnContinued is more up to date. This pull request marks it as providing GravityTurn so it can be pulled in for such relationships.

Have GravityTurnContinued provide GravityTurn

---

NetKAN/NavballDockAlignIndCE.netkan

At least one active mod suggests NavballDockingIndicator, which was last indexed for KSP 1.0.5.
A newer fork, CommunityNavballDockingIndicator, was available for KSP 1.1. This mod both provides and conflicts with NavballDockingIndicator, so it is considered as an option for relationships involving NavballDockingIndicator.
NavballDockAlignIndCE is the current up to date fork. It previously did not provide or conflict with NavballDockingIndicator. Now it does.

Have NavballDockAlignIndCE provide and conflict with NavballDockingIndicator

---

NetKAN/DiazosLandingHeight.netkan

At least one active mod suggests LandingHeight, which was last updated for KSP 1.3.
DiazosLandingHeight is a fork that is supported through KSP 1.6.1.
Now DiazosLandingHeight provides LandingHeight.
The author field is also converted to a list.

Have DiazosLandingHeight provide LandingHeight

---

NetKAN/CustomAsteroids-Pops-OPM-Reconfig.netkan

This PR adds the OPM-Reconfig.cfg asteroid pack by @HSJasperism as a separate download for Custom Asteroids. It also changes the name of the existing OPM-Outer to clarify the difference between the two.

Add 'OPM-Reconfig' Custom Asteroids config

---

NetKAN/NearFutureConstruction.netkan
NetKAN/NearFutureSolar.netkan

NearFutureSolar and NearFutureConstruction both bundle ModuleManager and list it as required on their forum pages, but it's not a dependency in CKAN. This pull request adds it.
Fixes #7091.

Add missing Near Future dependencies

---

NetKAN/KerbalAtomics-NFECompatibility.netkan
NetKAN/KerbalAtomics-NTRModSupport.netkan
NetKAN/KerbalAtomics-NTRsUseLF.netkan
NetKAN/KerbalAtomics.netkan

Adds two previously non-CKAN enabled mods, and self-hosts all netkan metadata.

Self-host KA netkans, add two new packages

---

NetKAN/SDHI-ServiceModuleSystem.netkan

Latest version of this mod is for KSP 1.7, which we track in the netkan because there's no version file.

Update SDHI-ServiceModuleSystem.netkan's game version

---

NetKAN/ProgressiveColonizationSystem.netkan

If there's a way to make it so that CKAN pulls the max KSP version out of the GitHub release, please point me at it.

Update PKS to KSP 1.7

---

NetKAN/OPTSpacePlaneParts.netkan

The bot reports this error for this mod:
> AVC: Invalid path to remote OPTLegacySpaceplaneParts.version, doesn't match any of: GameData/OPT_Legacy/Version/OPTLegacy.version,
Now it'll use that file.

OPTSpacePlaneParts's version file moved

---

NetKAN/TextureReplacerReplaced.netkan

If you try to install Astronomer's Visual Pack in CmdLine or GUI with KSP 1.3 through 1.7 marked as compatible, it'll prompt you to choose a TextureReplacer equivalent multiple times:
```
$ _build/ckan install AstronomersVisualPack
Too many mods provide Scatterer-sunflare. Please pick from the following:
1) GPO (Gameslinx Planet Overhaul)
2) GPP (Galileo's Planet Pack)
3) Scatterer-sunflare (scatterer - sunflare)
Enter a number between 1 and 3 (To cancel press "c" or "n".):
3
Too many mods provide Scatterer-config. Please pick from the following:
1) GPO (Gameslinx Planet Overhaul)
2) SSRSS-Cont (SSRSS Continued)
3) Scatterer-config (scatterer - default config)
Enter a number between 1 and 3 (To cancel press "c" or "n".):
3
Too many mods provide AVP-Textures. Please pick from the …
```

TextureReplacerReplaced should provide TextureReplacer

---

NetKAN/SpecialMissionProjects.netkan

The mod versions are out of order due to irregular usage of the 'v' in the version strings.
The abstract is now set manually because the generation from spacedock did some weird stuff in previous versions. The new one is copied from the first section of the spacedock description.
I'll open another PR in ckan-meta to fix the .ckan files.

Force v for SpecialMissionProjects versions

---

NetKAN/KerbalJointReinforcementContinued.netkan

This fork has its own forum thread, but the metadata was pointing to the parent fork.

Update KJRContinued forum thread

---

NetKAN/AdvancedFlyByWire-Linux.netkan
NetKAN/AdvancedFlyByWire-OSX.netkan
NetKAN/AdvancedFlyByWire.netkan

There are three Advanced Fly-By-Wire mods, one each for Windows, Mac, and Linux. Their metadata currently isn't very consistent:
| Identifier | Name | Abstract |
| --- | --- | --- |
| AdvancedFlyByWire | Advanced Fly-By-Wire (Windows, x64) | Joystick & controller mod with multiple presets and in-flight controls binding! |
| AdvancedFlyByWire-OSX | ABFW Revived (OSX version) | AFBW is an input overhaul mod. It dramatically enhances the stock input system with a bunch of fixes and many new features. |
| AdvancedFlyByWire-Linux | AFBW Revived (Linux version) | AFBW is an input overhaul mod. It dramatically enhances the stock input system with a bunch of fixes and many new features. |
If you sort by name in CKAN, these all appear in different parts of the list, and ABFW is a misspelling.
| …

Rename ABFW -> AFBW

---

NetKAN/unBlur.netkan

Lets end users fix blurry UI textures in other mods via config, without having to modify or rename installed texture files.

add unBlur

---

NetKAN/KerbalAtomics.netkan

#7105 dropped this mod's epoch, so recent versions have been indexed as older than previous versions:
Now the epoch is restored.

Restore epoch of KerbalAtomics

---

NetKAN/KerbalAircraftExpansion.netkan

Hi.
I'm the New Management for Kerbal Aircraft Expansion, and I want to redirect the CKAN metadata to the new repository on SpaceDock.
I think KAX is, now, relatively bug free and can be reachable by the masses.

Updating KerbalAircraftExpansion to the Lisias' New Management fork.

---

NetKAN/AirlockPlus-Localization.netkan
NetKAN/AirlockPlus.netkan

AirlockPlus ships its localization assets in a separate ZIP. This pull request indexes it.
Came up in discussion of KSP-CKAN/CKAN#2760. Note that this pull request will **not** set the `localizations` property because it's not part of the spec/schema yet.

Add AirlockPlus-Localization

---

NetKAN/OuterPlanetsMod.netkan

We've just transferred ownership of the Git repo so the external URL reference just needs updating. :D

Outer Planets Mod - Change metadata external reference URL

---

NetKAN/WaterLaunchSites.netkan

\-\-\-
Edited by @DasSkelett:
See https://github.com/KSP-CKAN/CKAN/pull/2326
\-\-\-

Water Launch Sites - recommend MakingHistory-DLC

---

NetKAN/TelemachusReborn.netkan

See https://github.com/TeleIO/Telemachus-1/issues/15
Telemachus Reborn is a maintained fork of Telemachus - a mod to access telemetry data from your web browser.
@DanGSun is going to include an AVC .version file in the future.
For the current release, a `x_netkan_override` is used to set the KSP version compatibility.
I had to do some trickery with the `x_netkan_version_edit` regex, because the latest release contains the release name in the Git(Hub) tag:
https://github.com/KSP-CKAN/NetKAN/blob/b72748d63fc7656e5c3ed346be3fe911a4f6a43d/NetKAN/TelemachusReborn.netkan#L11
@HebaruSan, any suggestions to improve the that, or is it okay like this?

Add TelemachusReborn

---

NetKAN/AirlockPlus.netkan

The suggestion has been forgotten to be removed in https://github.com/KSP-CKAN/NetKAN/commit/8456e9ae2dd7ac4c15bf09cfa48255da782c0726.
@cake-pie, can you give a go?

Remove AirlockPlus-Localization suggestion of AirlockPlus

---

NetKAN/Kopernicus-Backport.netkan

See https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1260-baikonur/&do=findComment&comment=3609503
Kopernicus releases additional versions for older game versions on a separate repo.
https://github.com/Kopernicus/Kopernicus-Backport/releases
Currently they're all missing from CKAN, so anyone using Kopernicus on an older version will have an out of date copy of the mod. This pull request adds a netkan that checks the backport repo and indexes its releases under the Kopernicus identifier. A `x_netkan_version_edit` property is used to replace "backport" in the version string with "release", to prevent this from causing problems with the version sort.

Add Kopernicus-Backport

---

NetKAN/KerbalJointReinforcementNext.netkan

#7101 indexed KerbalJointReinforcementNext with a `provides` property containing `KerbalJointReinforcement`, because this module is a successor module and might be preferred by some users who, say, install a craft module recommending KJR. This has caused two problems so far:
- In #7203 a RealismOverhaul team member reported that KJRNext providing KJR causes issues for them:
> Also I would like to point out KJR NEXT should NOT be able to provide for KJR. RO/RSS does not support next at all. It has known issues with the RO/RSS suite of mods, in fact both RO and KJR Continued conflicts with next yet ckan seems to be allowing people to install it with these mods.
- In #7210 we discovered that it's very difficult, if even possible, for IRNext to conflict with old KJR and KJRContinued without …

Remove KJR provides from KJRNext

---

NetKAN/InfernalRoboticsNext.netkan

first try... the release is not yet online... can you still test it if it's ok? we plan to upload the release in about 4 hours
and, other question... some parts are under the "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License" and some under "MIT License" ... should/can we name all 3 of them? or put this in a description?

Internal Robotics Next

---

NetKAN/AirlockPlus.netkan

Since #7131 and #7200 are clearly going nowhere fast due to continued inertia, this is intended to provide some kind of workable interim arrangement so as to stop holding up my releases.
For now I will be bundling Harmony for manual installs in a manner similar to what I laid out in https://github.com/KSP-CKAN/NetKAN/issues/7131#issuecomment-484625693 which follows the generally established convention for bundling Module Manager.
In this compromise approach, CKAN can take that bundled dll and put it in the mod folder instead of GameData to prevent collision between multiple mods that bundle Harmony in this way. This is effectively the same as the "suggestion" in #7131 that all mods that require Harmony to include their "own" copy of it.
For reasons already discussed in #7131 this is not …

Use Harmony bundled with AirlockPlus

---

NetKAN/ModularFuelTanks.netkan

This module has to be updated manually.
Note that #7086 created bad data that needs to be cleaned up; the version was changed without updating the download URL, so CKAN was telling users that 5.11.0 was 5.12.1. The version constraint as of that PR is probably wrong as well (seems to depend on changes in 1.6, and a later version is only supported up to 1.7, so an open ended interval starting with 1.4 doesn't make sense at either end). Another pull request in CKAN-meta will fix that next...

Update MFT to 5.12.3

---

NetKAN/EnvironmentalVisualEnhancements.netkan

themaster402/AstronomersVisualPack#2 noted that AVP doesn't show as compatible unless you have KSP 1.4 marked as compatible. This is because it depends on EVE, which hasn't been updated since 1.4.
Users on EVE's forum thread reported that it works fine on KSP 1.6 and 1.7. I submitted WazWaz/EnvironmentalVisualEnhancements#18 to update the version file to reflect this, and that change was accepted. This may be interpreted as agreement that EVE's current release is supported up to KSP 1.7. This pull request adds an override to make that change in CKAN's metadata.

Override latest EVE compatibility up to 1.7

---

NetKAN/Kerbalism-Config-Default.netkan
NetKAN/Kerbalism.netkan

`file` requires the specified path to start at the root.
`find` looks in subfolders.
This release of Kerbalism put the relevant folders inside `GameData`, but the netkan used `file`. This was not known at the time of #7228 because the new release was not available yet. Now it's fixed.

Fix Kerbalism install stanzas

---

NetKAN/SSRSS-Cont.netkan
NetKAN/SSRSS-Rescale.netkan

SigmaDimensions and SSRSS-Rescale seem to be the same mod. They have identical `$kref`s and `install` stanzas. Unsurprisingly this causes problems if you try to install both.
The reason for this is not clear but it does seem to be deliberate; see #5435:
> Added SSRSS-Rescale as a 'fake' SigmaDimensions
Now SSRSS-Rescale is marked as conflicting with SigmaDimensions.
Fixes #7235.

Add conflict with SigmaDimensions to SSRSS-Rescale

---

NetKAN/Kerbalism-Config-RO.netkan

The 0.1 version of this mod contained `GameData/KerbalismConfig`.
The 0.1.1 version just contains `KerbalismConfig` in the root of the ZIP.
http://status.ksp-ckan.space/
| NetKAN | Last Checked | Last Inflated | Last Indexed | Last Error ▾ |
| --- | --- | --- | --- | --- |
| Kerbalism-Config-RO | an hour ago | an hour ago | N/A | Could not find GameData/KerbalismConfig entry in zipfile to install |

Remove GameData from Kerbalism RO config install stanza

---

NetKAN/SuperfluousNodes.netkan

This forum thread says:
https://forum.kerbalspaceprogram.com/index.php?/topic/181663-17-superfluous-nodes-06-plethora-of-extra-nodes-for-stock-parts/
Now those are reflected in the netkan.

Add dependencies and recommendations to SuperfluousNodes

---

NetKAN/KSPFrenchTranslation.netkan

This mod is a French translation, but the config file labels it with the "en-us" locale. Maybe this was because French was not in the game's language list at the time, so it had to be faked?
Now it's hard coded in the netkan.

Mark French translation as French translation

---

NetKAN/SDHI-SharedAssets.netkan

The sumghai/SDHI_SharedAssets repository contained releases of Agencies files used by SDHI_ServiceModuleSystem and SDHI_StrobeOMatic. This repo has been deleted, and its CKAN module is erroring out currently.
The files are still in both of those modules. Now we extract them from SDHI_ServiceModuleSystem.

Switch SDHI-SharedAssets to main SDHI repo

---

NetKAN/StationScienceContinued.netkan

This mod's versions had a 'v' prefix, which was dropped in the latest release:
Since all versions without a 'v' prefix are considered less than all versions with a 'v' prefix, this caused this override to improperly fire:
https://github.com/KSP-CKAN/NetKAN/blob/43bebe54e30dca1129eea99c100eeda9191d59d9/NetKAN/StationScienceContinued.netkan#L26-L33
Which caused `ksp_version_max` to be set to 1.2.2, while `ksp_version_min` was 1.6.0. When the max is less than the min, the module is compatible with nothing.
Now all of this mod's versions will start with 'v', fixing the above.
Fixes #7262.

force_v for StationScienceContinued to avoid override

---

NetKAN/DeepFreeze.netkan

DeepFreeze bundles BackgroundResources in its latest version, which has triggered a conflict with that module. Now we handle this via a proper dependency.
Fixes #7276.

Add DeepFreeze dependency on BackgroundResources

---

NetKAN/xScience.netkan

See KSP-CKAN/CKAN#2823; this module was generating 'vV' in its versions on CKAN thanks to `x_netkan_force_v`. Now that flag will replace 'V' with 'v' instead, but that means that newer versions will be counted as older because they lack the 'V'.
An epoch is added to address this.

Epoch xScience due to vV

---

NetKAN/AirParkContinued.netkan

This module had an out of order release for KSP 1.3.1 (which is still somewhat popular among RSS players), and we need to add an epoch to make room to fix it:

Epoch AirParkContinued

---

NetKAN/AstronomersVisualPack.netkan

This module had an out of order release, which was epoched in KSP-CKAN/CKAN-meta#1477:
However, that simply pushed it to the front of the line, avove other newer versions:
**Two** epochs were needed. Now we have them.

Bump AVP epoch

---

NetKAN/AircraftCarrierAccessories.netkan

This mod had its `version` property hard coded in #5194, which has completely messed it up. The author has released **eleven** versions since then, from 1.2.5 through 1.5.1, but instead of being indexed normally, they've all been re-indexed under the 1.2.4 version:
https://github.com/KSP-CKAN/CKAN-meta/commits/master/AircraftCarrierAccessories/AircraftCarrierAccessories-1-1.2.4.ckan
:cry: 
Now the hard coding is removed.

Remove hard coding of ACA version

---

NetKAN/AutomatedAerialRefueling.netkan

This mod had an out of order release by dropping the 'V' prefix:

Epoch AutomatedAerialRefueling

---

NetKAN/AviationLights.netkan

This mod had an out of order release a while back by omitting its 'v' prefix.
Now it has an epoch to make room for the needed fixes.

Epoch AviationLights

---

NetKAN/ComfortableLanding.netkan

This mod was unnecessarily epoched in #6588, and then later released a version in need of an epoch:
Now the epoch is bumped again to make room for fixing this.

Bump ComfortableLanding epoch

---

NetKAN/ESLDJumpBeacons.netkan

This mod had an out of order release due to inconsistent 'v' prefixing.

Epoch ESLDJumpBeacons

---

NetKAN/KerbalAircraftExpansion.netkan

This mod dropped its 'v' when it switched authors:

Bump KerbalAircraftExpansion epoch

---

NetKAN/ChakaMonkeyExplorationSystems.netkan

With apologies to our Aussie teammates, "That's not a chaotically versioned mod; ***this*** is a chaotically versioned mod":
Properly epoching this would make a good college admissions or job interview question. Try it yourself before checking out my answer:
<details><summary>My plan for epoching ChakaMonkey</summary>
- 3:Chaka_Monkey_161_B
- 3:1.4.3.a
- 2:Chaka_143
- 1:Chaka_Monkey_Evolution_1.3.1_X
- 1:1.3_X
- 1:1.3_Collectors_Edition
- Chaka_Monkey_Exploration_Systems_1.2.2.X
- Chaka_Monkey_Exploration_Systems_1.2.2
- Chaka_Monkey_Exploration_Systems_1.1.3
- 1.1_BETA
</details>
ckan compat add 1.4 1.5

Epoch ChakaMonkey to make room for fixes
