NetKAN/GPO.netkan
Erroring on http://status.ksp-ckan.org/ .
The main folder name changed.
=> GPO's folder is called GPO now

NetKAN/LoadingTipsPlus.netkan
JPLRepo's cool mod to add loading tips.
Author's permission:
https://forum.kerbalspaceprogram.com/index.php?/topic/142840-131-loadingtipsplus-v15-7th-oct-2017/&do=findComment&comment=3246923
=> Add LoadingTipsPlus

NetKAN/ScottManleyHeadPack.netkan
Author is inactive, so I'm adopting this one.
=> Add Scott Manley Head Pack

NetKAN/ExtrasolarPlanetsBeyondKerbol-stock.netkan
Update Extrasolar's paths and dependencies
=> Extrasolar path changes, dependencies

NetKAN/CrowdSourcedScience.netkan
Moving CrowdSourcedScience to use external metadata.
=> Self-maintain CrowdSourcedScience

NetKAN/Kerbalized-SpaceX.netkan
Author wants to use SpaceDock as per KSP-CKAN/CKAN-meta#1314.
=> Switch Kerbalized-SpaceX to SpaceDock

NetKAN/NorthKerbinDynamics.netkan
Latest download uses just "NKD"
=> North Kerbin Dynamics changed path again

ISSUE_TEMPLATE.md
There have been a few issues filed for NetKAN that required follow-up questions for clarification. This pull request copies the issue template from CKAN to NetKAN, with modifications, to encourage issue reports to include relevant info in the first draft.
=> Borrow updated issue template from CKAN repo

NetKAN/NiceMKseriesBody.netkan
This mod now has a [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/169385-131-nice-mkseries-body-nmb-v10-201819/), and it recommends a few mods.
=> Add recommendations as per forum thread

NetKAN/ModularFuelTanks.netkan
[MFT is updated for 1.3.1](https://forum.kerbalspaceprogram.com/index.php?/topic/58235-131-modular-fuel-tanks-v5100/).
=> Add new MFT update

NetKAN/RecycledParts.netkan, NetKAN/RecycledPartsMk2KISContainers.netkan, NetKAN/RecycledPartsMk2SolarBatteries.netkan
Added additional netkans to allow individual selection of
Mk2 KIS Containers and
Mk2 Solar Batteries
updated RecycledParts with id for Mk2SolarBatteries
=> Recycled Parts updates

NetKAN/PoodsCalmNebulaSkybox.netkan, NetKAN/PoodsDeepStarMap.netkan, NetKAN/PoodsMilkyWaySkybox.netkan
I need Module Manager as a dependency also. *facepalm*
=> Update NetKAN files for Pood's Skyboxes #2

NetKAN/LCAproject.netkan
Latest download omits GameData folder and Ships folder.
=> Update LCAproject's install stanzas

NetKAN/SpeedUnitAnnex.netkan
As per @yalov's comment in #6173.
=> Add conflicts to SpeedUnitAnnex

NetKAN/BluedogDB.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1226-guiana/&do=findComment&comment=3280756
=> Add NFP dependency to BDB

NetKAN/SigmaReplacements-MenuButtons.netkan
latest entry of SigmaReplacements
=> Add SigmaReplacements: MenuButtons

NetKAN/AlphaMensaeMobileLauncher.netkan
As per 
https://forum.kerbalspaceprogram.com/index.php?/topic/171145-alphamensaes-saturn-mobile-launcher-standalone-bdb-version-20feb18/&do=findComment&comment=3300297
=> Add KJR rec

NetKAN/VostokContinued.netkan
This pull request indexes [Vostok Continued](https://forum.kerbalspaceprogram.com/index.php?/topic/162231-13-vostok-continued/). It's a parts mod, looks like no dependencies or special version requirements.
=> Add Vostok Continued

NetKAN/RealEngines.netkan
Path in ZIP no longer matches identifier.
=> Add install stanza for RealEngines

NetKAN/GPO.netkan
Added sigmareplacements: Skybox. Moved download to github in accordance to a version file.
=> Moved install to Github, added version file

NetKAN/GPO.netkan
Moved scatterer to dependency, as it was not working when it was in "suggested".
=> GPO - Scatterer moved

NetKAN/GPO.netkan
Updated to provide scatterer sunflare and requires scatterer config.
=> GPO - Provides scatterer sunflare.

NetKAN/MSP3000.netkan
This is a part mod that adds a materials science bay with the shape and mass of a mystery goo.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3324094
=> Add MSP-3000 Material Science Pod

NetKAN/RN-SalyutStations.netkan, NetKAN/RN-SovietProbes.netkan, NetKAN/RN-SovietRockets.netkan, NetKAN/RN-SovietSpacecraft.netkan, NetKAN/RN-USProbesPack.netkan, NetKAN/RN-USRockets.netkan
-Update my mods to use reflection plugin instead of texture replacer.
=> RN update mods to use RP instead of TR

NetKAN/KSPLogiRGB-battlemoose.netkan
This mod previously had an extra folder outside its GameData. Now it's all self contained.
=> Remove outdated install stanza from KSPLogiRGB-battlemoose

NetKAN/KerbalConstructionTime.netkan
Also removed suggestion of Toolbar
=> Update KCT to recommend ScrapYard

NetKAN/SigmaReplacements-Descriptions.netkan, NetKAN/SigmaReplacements-Heads.netkan, NetKAN/SigmaReplacements-MenuButtons.netkan, NetKAN/SigmaReplacements-MenuScenes.netkan, NetKAN/SigmaReplacements-Navigation.netkan, NetKAN/SigmaReplacements-SkyBox.netkan, NetKAN/SigmaReplacements-Suits.netkan, NetKAN/SigmaReplacements-Textures.netkan
Add a new mod: SigmaReplacements-MenuScenes
Purged all KSP forum references.
=> Update Sigma Replacements

NetKAN/SpacetuxSA.netkan
This mod currently suffers from "Could not find spacetux entry in zipfile to install"
This pull request updates the license and install stanza.
=> Fix spacetux

NetKAN/Chrononaut.netkan
As per PM on forum. It's a mod that reloads models without having to reload the game, to make the lives of part modders easier.
=> Add Chrononaut

NetKAN/PVFMFlags.netkan
=> Add PVFMFlags

NetKAN/Kerbalism.netkan
Mod got accidentally deleted from spacedock by author. Changing kref to new page.
=> Kerbalism New kref

NetKAN/RocketdyneF-1.netkan
-update this file for 1.3.1, it does work
=> RN update f1 for ksp 1.3.1

NetKAN/KSCSwitcher.netkan, NetKAN/RocketdyneF-1.netkan
-this was just updated for 1.3.1 pending the ro/rss update
=> RN update kscswitcher for ksp 1.3.1

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
Hoping this works better than #6428 since it include the files that one halted on. I recall the bot handling these things better now so I no longer need to stage PRs like this?
closes #6428
=> Scatterer fix

NetKAN/ImprovedChaseCamera.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3343949 , this mod has been adopted and is now on GitHub with a .version file.
=> Switch ImprovedChaseCamera to new fork

NetKAN/ExtraPlanetaryLaunchpads.netkan
This mod requires manual updates for each release.
=> New ExtraPlanetaryLaunchpads

NetKAN/PlanetShine-Config-Default.netkan, NetKAN/PlanetShine.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3349087
Updated:
- New $kref
- New author added to array
- New forum link
- New repository link
- License set to Apache-2.0
=> New PlanetShine maintainer

NetKAN/B9-PWings-Fork.netkan
@jrodrigv has taken over maintenance of B9 Procedural Wings.
Fixes KSP-CKAN/CKAN#2403.
=> New maintainer for B9 Procedural Wings

NetKAN/NewTantares.netkan, NetKAN/NewTantaresLV.netkan
Beale added support for `1.4.x`.
https://github.com/Tantares/Tantares/releases
https://github.com/Tantares/TantaresLV/releases
=> Update Tantares & TantaresLV for 1.4

NetKAN/QuizTechAeroPackContinued.netkan
QuizTechAeroPackContinued
Could not find Ships/SPH entry in zipfile to install
=> Remove Ships install stanza from QuizTech

NetKAN/MakingHistoryEngineTweaks.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1251-broglio/&do=findComment&comment=3364731
=> Add MakingHistoryEngineTweaks

NetKAN/RN-SalyutStations.netkan, NetKAN/RN-SovietProbes.netkan, NetKAN/RN-SovietRockets.netkan, NetKAN/RN-SovietSpacecraft.netkan, NetKAN/RN-USProbesPack.netkan, NetKAN/RN-USRockets.netkan
-Change reflection plugin to Textures Unlimited, this will be the new
dependency from now on
=> RN change dependency to TU

NetKAN/RocketEmporium.netkan
This is a parts mod, indexing as per forum PM from author
=> Add KSPKatten's RocketEmporium

NetKAN/ElonsRoadsterStarman.netkan
This mod's packaging has changed. The folder now contains version info, so hopefully a regex will work for the long term.
=> Update starman folder

NetKAN/KspCraftOrganizer.netkan
KspCraftOrganizer release now includes .version file
=> KspCraftOrganizer now includes .version file

NetKAN/ThorTech.netkan
This mod has had some changes in its dependencies, and the default install stanza omits a parent folder that's supposed to be there.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/168326-131-143-thor-tech-v0962-~-may-10-2018/&do=findComment&comment=3382838
=> Fix ThorTech install stanza and dependencies

NetKAN/ETT.netkan
This mod used to ship a GameData folder, but not in the latest release.
=> Update ETT path

NetKAN/SpaceLaunchSystemPartPack.netkan
This mod used to have a craft folder, and the latest release doesn't.
The forum thread also says TexturesUnlimited is recommended.
=> Update SLSPP install stanza and recommendations

NetKAN/ElonsRoadsterStarman.netkan
Previous versions of this mod had a craft file, but the latest version does not.
=> ElonsRoadsterStarman no longer has a craft file

NetKAN/ConstellationEssentials.netkan
=> Add ConstellationEssentials

NetKAN/Kerbalism.netkan
https://github.com/steamp0rt/Kerbalism/pull/55
=> Add ClickThroughBlocker as a dependency for Kerbalism

NetKAN/Kerbalism.netkan
Reverts KSP-CKAN/NetKAN#6591
turns out CTB doesn't work for Kerbalism due to it's nature....
=> Revert "Add ClickThroughBlocker as a dependency for Kerbalism"

NetKAN/ScottManleyHeadPack.netkan
This mod has been updated for 1.4 by a new maintainer.
=> New Scott Manley Head Pack branch

NetKAN/ExtraPlanetaryLaunchpads.netkan
This mod requires manual updates for new versions.
=> New ExtraplanetaryLaunchpads release

NetKAN/PhotonSailor.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1251-broglio/&do=findComment&comment=3406789
=> Add PhotonSailor

NetKAN/newReactionWheels.netkan
The structure of this mod's ZIP file has changed.
=> Update folder of newReactionWheels

NetKAN/TundraExploration.netkan, NetKAN/TundraTechnologies.netkan
=> Add Tundra Technologies

NetKAN/KSPDev-LogConsole.netkan
The mod's repository has migrated.
=> Migrate the mod repository

NetKAN/RemoteTechRedevAntennas.netkan
Hi, I would like to add a new part package of RemoteTech Redev (2) to the CKAN list for third-party modders to refer without getting into license issues.
Thank you.
=> Add RemoteTechRedevAntennas.netkan

NetKAN/PolishFlagPack.netkan
* Updated version of the mod
* Updated license information
=> Update Polish Flag Pack version to 1.2

NetKAN/CommNetAntennasExtension.netkan
After passing thorough the netkan,  in CKAN - "File/install from .ckan" do nothing
=> add CommNetAntennasExtension

NetKAN/SurveyTransponder.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/111834-14-survey-transponder-052a/
=> add Survey Transponder

NetKAN/Moca.netkan
This just appeared on SpaceDock after I finished #6686.
=> Add Moca Vehicle

NetKAN/KerbalRenamer.netkan
this is my first NetKAN PR, so please let me know if I did something wrong, but this should be similar to what was just don for RealHeat here https://github.com/KSP-CKAN/NetKAN/pull/6693
=> update KerbalRenamer to use .version file for versioning

NetKAN/RSSTextures2048.netkan, NetKAN/RSSTextures4096.netkan, NetKAN/RSSTextures8192.netkan
-update version to support ksp 1.4.x
=> RN update rss textures version

NetKAN/RemoteTechRedevAntennas.netkan
Hi,
Due to 3rd-party mods detecting RemoteTech folder and running RemoteTech patches, I renamed the main folder to RemoteTechRedev to avoid mod conflicts.
I already pushed a new release to Github and Spacedock.
Do reach me if you have any question or clarification
=> Amend metadata for RemoteTech-Antennas

NetKAN/ExtraPlanetaryLaunchpads.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/54284-145-extraplanetary-launchpads-v620/&do=findComment&comment=3459445
=> New version of ExtraPlanetaryLaunchpads

NetKAN/CommNetAntennasExtension.netkan
After adding MM to mod's archive I need this "install" directive in the file, right?
=> CommNetAntennasExtension - "install"

NetKAN/CommNetConstellation.netkan
Hi there,
I would like to add conflicts and suggestions for CommNet Constellation.
Thanks!
=> Add conflicts and suggestions for CommNet Constellation

NetKAN/VariantPersist.netkan
- https://spacedock.info/mod/1983/VariantPersist
(Effectively this is "SpaceDock catch-up 3," successor to #6705, but there are fewer new mods this time.)
=> Add VariantPersist

NetKAN/Kerbalism.netkan
because i'm more likely to update the spacedock lol
=> Changes Kerbalism to use spacedock

NetKAN/TweakScale.netkan
New Version
New Management
New Download Site
I'm the new Maintainer for TweakScale.
Thanks
=> Updating TweakScale:

NetKAN/Mk2Expansion.netkan
Updates M2X dependency following switch from IFS to B9PS
=> Update m2X Netkan

NetKAN/PSA-Greenhouse.netkan
This mod's zip format has changed.
=> Update install folder for PSA-Greenhouse

NetKAN/SciFiVisualEnhancements.netkan
This mod is an EVE texture pack and was requested by a user on its thread.
As per https://forum.kerbalspaceprogram.com/index.php?/topic/151190-14sci-fi-visual-enchancements-v-14-high-performance-alt-to-sve/&do=findComment&comment=3481223
I forgot to add `provides` and `resources`...
=> Add SciFiVE

NetKAN/RealisticAtmospheres.netkan
#6838 created a netkan called "RealisticAtmo", which was a duplicate of the existing RealisticAtmospheres entry.
This pull request updates the existing entry instead.
=> Switch RealisticAtmospheres to GitHub kref

NetKAN/DunaDirect.netkan, NetKAN/LandOJunk.netkan, NetKAN/NGC3371-Skybox.netkan
KSP-SpaceDock/SpaceDock#188 remains unfixed, so here's another round of manually indexed mods that requested CKAN support on SpaceDock. Previous was #6788.
=> SpaceDock catch-up 4

NetKAN/TalisarParts.netkan
This is a parts mod featuring contributions by our very own @Olympic1. It's released by taniwha, so we have manual maintenance of all versioning info in the netkan.
Replaces KSP-CKAN/CKAN-meta#1388.
=> Add TalisarParts

NetKAN/RadarAltitude.netkan
@Marginal, Could you add .version file to your archive/repo ? 
Example: [SpeedUnitAnnex.version](https://github.com/yalov/SpeedUnitAnnex/blob/master/SpeedUnitAnnex.version)
=> add RadarAltitude to CKAN

NetKAN/SimplexTechTree.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1254-kennedy/&do=findComment&comment=3504571
Several MM cfgs that modify the tech tree.
=> Add Simplex tech tree

NetKAN/Kerbalism.netkan
Latest download has no GameData folder.
=> Fix kerbalism vref

NetKAN/DistantObject-RealSolarSystem.netkan, NetKAN/DistantObject-default.netkan, NetKAN/DistantObject.netkan
#6895 added force_v for DistantObject, but the config modules are sourced from the same repo and so need the same workaround.
=> Force v for DistantObject configs

NetKAN/SurfaceExperimentPack.netkan
Latest version of this mod supposedly has a .version file (CobaltWolf/Surface-Experiment-Pack#40 got merged, but I haven't checked it myself yet). This PR updates the netkan to use it.
=> vref for SEP

NetKAN/Decalc-o-mania.netkan, NetKAN/GregroxMultiColorSuitsPack.netkan, NetKAN/KerbalKristmasPack.netkan, NetKAN/KerbinElectric.netkan, NetKAN/KolyphemusSystemContinued.netkan, NetKAN/MakingLessHistory.netkan, NetKAN/MorimeeSystem.netkan, NetKAN/NagasakiVehiclesPack.netkan, NetKAN/ParkingBrake.netkan, NetKAN/PhoenixIndustriesSpaceTug.netkan, NetKAN/SN1006-Dark-Skybox.netkan, NetKAN/SN1006-Light-Skybox.netkan, NetKAN/SN1006-Unedited-Skybox.netkan, NetKAN/TALRadiallyAttachedExperimentalDataStorageContainer.netkan, NetKAN/USIKolClassSuitsRedux.netkan, NetKAN/WesternVehicles.netkan
These are the mods added since #6850.
=> SpaceDock catch-up 6

NetKAN/ExceptionDetectorUpdated.netkan, NetKAN/StockalikeStructures.netkan
These are the mods added since #6960.
=> SpaceDock catch-up 7

NetKAN/SciFiVisualEnhancements.netkan
This mod had a folder missing, now it's back and we install it.
https://forum.kerbalspaceprogram.com/index.php?/topic/151190-16sci-fi-visual-enchancements-v-15-high-performance-alt-to-sve/&do=findComment&comment=3527711
ckan compat add 1.4
=> Fix SciFiVE install

NetKAN/ScienceSituationInfo.netkan
There's a new LGG adopted branch of this mod, but we only have the original. (A duplicate and various other issues were cleaned up in #6957 and KSP-CKAN/CKAN-meta#1403).
This PR switches to the new one.
Part of the fix to #6980.
=> Switch ScienceSituationInfo to new branch

NetKAN/Kerbalism.netkan
removes Ven's Stock Revamp supports, add UKS conflict
=> Updates Kerbalism.netkan

NetKAN/MoarFEConfigs.netkan
=> Fix folder name

NetKAN/BOPN.netkan, NetKAN/UnKerballedStart.netkan
These are the mods added since #6985.
=> SpaceDock catch-up 9

NetKAN/Kethane.netkan
This mod's metadata is manually maintained. A new version is out for KSP 1.6.
=> New version of Kethane

NetKAN/FilterExtensions.netkan
I reached out to LGG and he gave me the OK to add
=> Add MoarFEConfigs as recommended

NetKAN/Milkyway-Skybox-SpaceEngine.netkan
=> Add Milkyway-Skybox-SpaceEngine

NetKAN/StationalConstructs.netkan, NetKAN/VarutaSystem.netkan
These are the mods added since #7007.
=> SpaceDock catch-up 10

NetKAN/PlanetDunope.netkan
This was the only new SpaceDock mod I found on the latest pass.
=> Add Planet Dunope

NetKAN/xScience.netkan, NetKAN/xScienceContinued.netkan
Taking over for Z-Key Aerospace due to inactivity
=> [x] Science! Continued

NetKAN/xScience.netkan
=> xScience replaced_by: xScienceContinued

NetKAN/JDiminishingRTG.netkan, NetKAN/ReStock.netkan, NetKAN/ReStockPlus.netkan
Two new mods, pulling their metadata from our repo.
=> Adds indexing for Restock and Restock+

NetKAN/KerbalKrashSystem.netkan
=> Updated versoin for KerbalKrashSystem

NetKAN/KerbalKrashSystem.netkan
=> KerbalKrashSystem

NetKAN/SimplexPropulsion.netkan
Some MM patches to change some properties of fuels and engines.
As per https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1254-kennedy/&do=findComment&comment=3562582
=> Add SimplexPropulsion

NetKAN/InnerLock.netkan, NetKAN/MiporiaPlanetPack.netkan, NetKAN/RedOnion.netkan
These are the mods added since #7066.
@HebaruSan is on holiday, so I tried my best.
=> Spacedock catch-up 13

NetKAN/NearFutureElectrical-Core.netkan, NetKAN/NearFutureElectrical-DecayingRTGs.netkan, NetKAN/NearFutureElectrical.netkan
Switching as with others to self-hosted netkans.
=> Near Future Electrial netkan updates

NetKAN/EVAHandrailsPackContinued.netkan, NetKAN/KerbalKrashSystem.netkan
=> Evahandrails

NetKAN/Kerbalism.netkan
=> Revert "Add B9PartSwitch to Kerbalism deps"

NetKAN/HangerExtenderExtended.netkan
As per https://forum.kerbalspaceprogram.com/index.php?/topic/162790-151-hangar-extender-extended/&do=findComment&comment=3579676
=> Rename Hanger to Hangar

NetKAN/RedOnion.netkan
Thanks @HebaruSan for pointing it out.
=> Make `Install` property of RedOnion lower case

NetKAN/TundraExploration.netkan, NetKAN/TundraTechnologies.netkan
These mods' author has requested several changes:
- Fix the licenses (we had the wrong one)
- Different depends and recommends
Fixes #7125.
=> Fix Tundra's relationships and licenses

NetKAN/KSCExtended.netkan, NetKAN/TundraSpaceCenter.netkan
Some custom space center assets.
Fixes #7133. Fixes #7134.
=> Add TundraSpaceCenter and KSCExtended

NetKAN/CommunityTechTree.netkan, NetKAN/CryoTanks-Core.netkan, NetKAN/CryoTanks.netkan, NetKAN/DeployableEngines.netkan, NetKAN/DynamicBatteryStorage.netkan, NetKAN/HeatControl.netkan, NetKAN/KerbalAtomics-NFECompatibility.netkan, NetKAN/KerbalAtomics-NTRModSupport.netkan, NetKAN/KerbalAtomics-NTRsUseLF.netkan, NetKAN/KerbalAtomics.netkan, NetKAN/NearFutureLaunchVehicles.netkan, NetKAN/NearFutureProps.netkan
Propagate more items to self-hosted versions for better control.
**Modified:**
- CommunityTechTree
- HeatControl
- CryoTanks
- DeployableEngines
- DynamicBatteryStorage
- KerbalAtomics
- KerbalAtomics-NFECompatibility
**New:**
- CryoTanks-Core
- KerbalAtomics-NTRModSupport
- KerbalAtomics-NTRsUseLFO
=> More self-hosted NetKans

NetKAN/HyperPropulsionSciFiEnginePack.netkan, NetKAN/XensPlanetCollectionRevived.netkan
These are the mods added since #7136.
ckan compat add 1.4 1.6
=> SpaceDock catch-up 15

NetKAN/VesselMoverContinued.netkan
=> Switch VesselMoverContinued to new fork

NetKAN/StationPartsExpansionRedux.netkan
=> Self-host SSPXr netkan

NetKAN/CryoEngines-LFO.netkan, NetKAN/CryoEngines-NFAero.netkan, NetKAN/CryoEngines.netkan
This should be getting to the end of these. Moves to self hosting and adds a previously un-indexed mod.
=> CryoEngines and related extras

NetKAN/DockingCamKURS.netkan
Used to be OLDD, now DockingCamCKURS.
=> Update DockingCamKURS install folder

NetKAN/AutoAGL.netkan
This mod automates switching the altimeter mode.
=> Add AutoAGL

NetKAN/KerbalJointReinforcementNext.netkan
Another KJR fork. Currently only release is marked as a pre-release, so tests will fail and require a rebuild once that's fixed.
Fixes #7180.
=> Add KJRNext

NetKAN/NearFutureConstruction.netkan, NetKAN/NearFutureSolar-Core.netkan, NetKAN/NearFutureSolar.netkan
Changes the last 3 NF CKAN packages to self-hosted versions.
=> Move to self-hosted for last NF mods

NetKAN/BetterLoadSaveGame.netkan
I've switched to use a version range since my mod works with all versions in this range.
=> Update supported version range for BetterLoadSaveGame

NetKAN/InnerLock.netkan
See https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1260-baikonur/&do=findComment&comment=3606503
This mod has another folder that should be installed. This pull request adds it.
=> Add missing InnerLock install stanza

NetKAN/Science-Full-Reward.netkan, NetKAN/Science-Full-Transmit.netkan
As suggested in [#7217](https://github.com/KSP-CKAN/NetKAN/pull/7217), I have forked NMSG and am resubmitting it for any version.
Simultaneously, I am updating my other (very similar) mod to install to any version since that seemed like a good idea and really shouldn't cause any trouble.
Closes #7217.
=> Fork NMSG and update my own

NetKAN/NMSG.netkan
Suggest the new fork as an upgrade path.  I'm not sure if this is required or even recommended, but I figured I'll propose it and see what happens.
=> NMSG replaced_by Science-Full-Reward

NetKAN/SuperfluousNodes.netkan
ModuleManager patches to add more attachment nodes to certain parts.
=> Add Superfluous Nodes

NetKAN/NewTantares.netkan
This mod is hard coded to KSP 1.4-1.5 in its netkan, which is now 4 versions out of date:
https://github.com/Tantares/Tantares/releases
=> Update NewTantares game version

NetKAN/MiporiaPlanetPack.netkan
This mod no longer includes License_Miporia.txt.
=> Remove Miporia license stanza

NetKAN/AllYAll.netkan
This mod had an out-of-order release in late May:
This pull request adds an epoch so we can fix that.
=> Epoch AllYAll

NetKAN/ResearchBodies.netkan
=> Bump ResearchBodies epoch

NetKAN/CapsuleCorporationEndeavourMarsBaseCamp.netkan
=> Bump epoch for CapsuleCorporationEndeavourMarsBaseCamp

NetKAN/CraftImport.netkan
This module had an out of order release:
=> Epoch CraftImport

NetKAN/MNWSModernNavalWeaponSystem.netkan
This mod had an out of order release, and we need an epoch to make room for the fixes:
=> Epoch MNWS

NetKAN/CAMk3BlockII.netkan
This mod had an out of order release recently.
=> Epoch CAMk3BlockII

NetKAN/ChineseTianGongScienceSpaceStation.netkan
This module had an out of order release a while back, currently shown as newest. Now it has an epoch to make room for the fixing.
=> Epoch ChineseTianGongScienceSpaceStation

NetKAN/CivilianPopulation.netkan
This mod had an epoch long ago, but it was dropped when #5740 unfroze it, so now most of its versions are out of order:
Now the epoch is back.
=> Restore CivilianPopulation's epoch

NetKAN/Corvus125mTwoKerbalPod.netkan
This mod had an out of order release and needs an epoch to make room for the fix.
=> Epoch Corvus125mTwoKerbalPod

NetKAN/DecoupleWithControl.netkan
This mod had an out of order release a while ago, so now it has an epoch to make room for fixing it.
=> Epoch DecoupleWithControl

NetKAN/EvaFollower.netkan
This mod had an out of order release.
=> Epoch EvaFollower

NetKAN/ExplodiumBreathingEngines.netkan
This mod had an out of order release.
=> Epoch ExplodiumBreathingEngines

NetKAN/KerbalCitiesPack.netkan
This mod had an out of order release.
=> Epoch KerbalCitiesPack

NetKAN/KerbalField.netkan
This mod had an out of order release.
=> Epoch KerbalField

NetKAN/KerbalField.netkan
This one is way more complicated than I thought:
I think we need:
| Epoch | Version |
| --- | --- |
| 3 | V2.4.1 |
| 3 | 2.4 |
| 2 | V2.3 |
| 2 | 2.2 |
| 2 | 2.1 |
| 1 | V2.0f1 |
| 1 | V2.0 |
| - | V1.0 |
=> Double bump KerbalField epoch

NetKAN/TrimIndicators.netkan
=> TrimIndicators

NetKAN/KerbinCup.netkan, NetKAN/Mk2Essentials.netkan
Curse's download links have changed.
=> Update KerbinCup download link

NetKAN/Kethane.netkan
This mod's metadata are manually maintained.
New release with version `0.10.2` is compatible to KSP 1.7,
see [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/119480-17-kethane-plugin-and-parts-0102-now-with-background-scanning/).
=> Update Kethane Mining for new release

NetKAN/TiltEm.netkan
This mod adds axial tilt!!
https://github.com/LunaMultiplayer/TiltEm/releases
https://forum.kerbalspaceprogram.com/index.php?/topic/179281-172-tiltem-planetary-axial-tilt-v120-25-oct-2018/&do=findComment&comment=3475191
=> Add TiltEm

NetKAN/TundraExploration.netkan
Listed as a dependency in [the forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/166915-17x-tundra-exploration-v1501-july-17th-restockalike-spacex-falcon-9-dragon-v2-and-starship/)
=> Add RetractableLiftingSurface dependency to TundraExploration

NetKAN/AnimatedDecouplers.netkan
Reported functional in [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/170880-16x-animated-decouplers-142/&do=findComment&comment=3582147)
=> AnimatedDecouplers compatibility bump

NetKAN/KeyNode.netkan
=> Epoch for lost 'v' prefix

NetKAN/ShangshengOrbital.netkan
=> Force 'v' for ShangShengOrbital

NetKAN/Kerbalism-Config-Default.netkan, NetKAN/Kerbalism.netkan
* New download location (Github)
* Updated the meta data: homepage, authors
* Updated list of recommended / conflicting mods
=> Kerbalism metadata update

NetKAN/RealTimeClock2.netkan
Some funny versioning going on again.
=> Force 'v' for RealTimeClock2

NetKAN/CommunityPartsTitles.netkan, NetKAN/CommunityPartsTitlesExtrasCategory.netkan, NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
=> Community Part Titles, separating Extras

NetKAN/PicoPortShielded.netkan
=> Add DockingPortDescriptions suggestion to PicoPortShielded

NetKAN/MADLAD.netkan
A user has requested this mod to be added:
https://forum.kerbalspaceprogram.com/index.php?/topic/185536-17x-madlad-mod-assembly-dll-loading-anomaly-detector-11-100819/&do=findComment&comment=3689586
If the author agrees, this PR will accomplish that.
=> Add MADLAD

NetKAN/KKL.netkan
Removed plugin, added recommendations
=> v1.2 "Land on Mün"

NetKAN/RationalResourcesParts.netkan
Requested by @JadeOfMaar on Discord.
=> Add RationalResourcesParts

NetKAN/BluedogDB.netkan
=> Add $vref to ksp-avc to BluedogDB

NetKAN/DebugStuff.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/135726-18-debugstuff-2019-10-22-see-the-hidden-secrets-of-the-game-objects/&do=findComment&comment=3697940
=> DebugStuff game version, staging

NetKAN/AlternisKerbolRekerjiggered.netkan
This mod's metadata says KSP 1.3.0 but the forum thread says 1.7.3.
The forum thread wasn't in the metadata.
=> Fix Alternis game version, staging, homepage

NetKAN/PilotAssistant.netkan
See https://forum.kerbalspaceprogram.com/index.php?/topic/184277-17-pilot-assistant-atmospheric-piloting-aids-1134-may-6/&do=findComment&comment=3696099
=> Switch PilotAssistant to new fork

NetKAN/ProceduralParts.netkan
=> Switch to jrodrigv fork

NetKAN/DoubleTapBrakes.netkan
=> Add DoubleTapBrakes

NetKAN/VenStockRevamp-Core.netkan, NetKAN/VenStockRevamp-NewParts.netkan, NetKAN/VenStockRevamp.netkan
=> Switch VensRevamp to new fork

NetKAN/ProgressiveColonizationSystem.netkan
The version number is in the ZIP file, in GameData\ProgressiveColonizationSystem\ProgressiveColonizationSystem.version
https://github.com/SteveBenz/ProgressiveColonizationSystem/blob/master/src/ProgressiveColonizationSystem/GameData/ProgressiveColonizationSystem/ProgressiveColonizationSystem.version
=> Update PKS for 1.8 and to use version number supplied in the deployment

NetKAN/BDArmoryContinued.netkan, NetKAN/BDModularMissileParts.netkan
=> Add BDModularMissileParts

NetKAN/MaterialExtensionsForRealChute.netkan
License changed shortly after indexing:
https://forum.kerbalspaceprogram.com/index.php?/topic/189812-wip-material-extensions-for-realchute/&do=findComment&comment=3707670
I also changed the install stanza again to include the license file.
Should be more future proof.
=> New License + Changed install stanza

NetKAN/PlanetShine-Config-Default.netkan, NetKAN/PlanetShine.netkan
I've updated PlanetShine for KSP 1.8 and higher. You can find the new forum post containing my reasons for the change in authorship [here](https://forum.kerbalspaceprogram.com/index.php?/topic/189071-18x-planetshine-0262-oct-19-2019/). If I've done anything incorrectly, let me know.
=> Updated author for PlanetShine

NetKAN/Historian-expanded.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/138848-181-historian-expanded/&do=findComment&comment=3710890
=> Bump Historian-expanded epoch

NetKAN/AstronomersVisualPack.netkan, NetKAN/B9-PWings-Fork.netkan, NetKAN/B9-PWings-Modified.netkan, NetKAN/ConnectedLivingSpace.netkan, NetKAN/ContractConfigurator-KerbinSpaceStation.netkan, NetKAN/ContractConfigurator-Tourism.netkan, NetKAN/ContractParser.netkan, NetKAN/ContractsWindowPlus.netkan, NetKAN/CryoEngines-LFO.netkan, NetKAN/CryoEngines-NFAero.netkan, NetKAN/CryoEngines.netkan, NetKAN/CryoTanks-Core.netkan, NetKAN/CryoTanks.netkan, NetKAN/DeflatableHeatShield.netkan, NetKAN/DockingPortDescriptions.netkan, NetKAN/KerbalHeatShield.netkan, NetKAN/Konstruction.netkan, NetKAN/MoreHeat.netkan, NetKAN/ProgressiveColonizationSystem.netkan, NetKAN/RCSLandAid.netkan, NetKAN/RealismOverhaul.netkan, NetKAN/RealismOverhaulCraftFiles.netkan, NetKAN/RealisticHeatMgmt.netkan, NetKAN/RemoteTechRedevAntennas.netkan, NetKAN/RemoteTechStockConfigs.netkan, NetKAN/SpaceY-Lifters.netkan, NetKAN/UKS.netkan, NetKAN/USIKolClassSuits.netkan, NetKAN/USIKolClassSuitsRedux.netkan, NetKAN/VentralDrill.netkan
Successor to #7545. Thirty more of these.
=> Tag fourth group of mods

NetKAN/ASETAgency.netkan, NetKAN/ASETAvionics.netkan, NetKAN/ActsEW.netkan, NetKAN/AllYAll.netkan, NetKAN/AntaresCygnus.netkan, NetKAN/AtmosphereAutopilot.netkan, NetKAN/AutomatedScienceSampler.netkan, NetKAN/BluedogDB.netkan, NetKAN/ChopShop.netkan, NetKAN/ColorCodedCans.netkan, NetKAN/DarkMultiPlayer.netkan, NetKAN/DestructionEffects.netkan, NetKAN/EVAEnhancementsContinued.netkan, NetKAN/EVAHandrailsPackContinued.netkan, NetKAN/FASA-RCS.netkan, NetKAN/FASA.netkan, NetKAN/FASALaunchClampsContinued.netkan, NetKAN/GravityTurnContinued.netkan, NetKAN/Hangar.netkan, NetKAN/Impact.netkan, NetKAN/JSIAdvancedTransparentPods.netkan, NetKAN/KEI.netkan, NetKAN/LargeBoatPartsPack-Modern.netkan, NetKAN/LargeBoatPartsPack-WW2.netkan, NetKAN/LargeBoatPartsPack.netkan
=> Tag tenth group of mods

NetKAN/LithobrakeExplorationTechnologies.netkan, NetKAN/LoadingScreenManager.netkan, NetKAN/ModActions.netkan, NetKAN/NavballDockAlignIndCE.netkan, NetKAN/NewTantares.netkan, NetKAN/NewTantaresLV.netkan, NetKAN/PortraitStats.netkan, NetKAN/Protractor.netkan, NetKAN/RaginCaucasian.netkan, NetKAN/RecoveryController.netkan, NetKAN/RestockRigidLegs.netkan, NetKAN/SETI-BalanceMod.netkan, NetKAN/SETI-Contracts.netkan, NetKAN/SETI-RemoteTech.netkan, NetKAN/ScienceRelay.netkan, NetKAN/ShipManifest.netkan, NetKAN/SmartParts.netkan, NetKAN/Snacks.netkan, NetKAN/SoundingRockets.netkan, NetKAN/Strategia.netkan, NetKAN/TakeCommandContinued.netkan, NetKAN/ToadicusToolsContinued.netkan, NetKAN/UbioWeldContinued.netkan, NetKAN/VesselView-UI-RasterPropMonitor.netkan, NetKAN/VesselView-UI-Toolbar.netkan, NetKAN/VesselView.netkan
=> Tag eleventh group of mods

NetKAN/AutoAsparagus.netkan, NetKAN/BetterCrewAssignment.netkan, NetKAN/MADLAD.netkan, NetKAN/ModularFlightIntegrator.netkan, NetKAN/QuickBrake.netkan, NetKAN/QuickContracts.netkan, NetKAN/QuickCursorHider.netkan, NetKAN/QuickExit.netkan, NetKAN/QuickFineControl.netkan, NetKAN/QuickGoTo.netkan, NetKAN/QuickHide.netkan, NetKAN/QuickIVA.netkan, NetKAN/QuickMute.netkan, NetKAN/QuickRevert.netkan, NetKAN/QuickSAS.netkan, NetKAN/QuickScroll.netkan, NetKAN/QuickSearch.netkan, NetKAN/QuickStart.netkan, NetKAN/SmartTank.netkan, NetKAN/SmokeScreen.netkan, NetKAN/TestFlight.netkan, NetKAN/TestFlightConfig-KerbalAtomics.netkan, NetKAN/TestFlightConfig-NFPropulsion.netkan, NetKAN/TestFlightConfig-NFSpacecraft.netkan, NetKAN/TestFlightConfig-Stock-S42.netkan, NetKAN/TestFlightConfigLibrary.netkan, NetKAN/TestFlightConfigStock.netkan
=> Tag thirteenth group of mods

NetKAN/CustomAsteroids-Pops-OPM-Outer.netkan, NetKAN/CustomAsteroids-Pops-OPM-Reconfig.netkan, NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan, NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan, NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan, NetKAN/CustomAsteroids.netkan, NetKAN/CustomBiomes-Data-Stock.netkan, NetKAN/CustomBiomes.netkan, NetKAN/DecouplerShroud.netkan, NetKAN/KAS.netkan, NetKAN/KerbinRoverOffRoadVehicles.netkan, NetKAN/LayeredAnimations.netkan, NetKAN/PersistentThrust.netkan, NetKAN/RecycledParts.netkan, NetKAN/RecycledPartsAtomicAge.netkan, NetKAN/RecycledPartsFTmNAtomicRockets.netkan, NetKAN/RecycledPartsFTmNImprovedAtomicRockets.netkan, NetKAN/RecycledPartsFarscape.netkan, NetKAN/RecycledPartsLVNClusters.netkan, NetKAN/RecycledPartsMk2Essentials.netkan, NetKAN/RecycledPartsMk2KISContainers.netkan, NetKAN/RecycledPartsMk2Lightning.netkan, NetKAN/RecycledPartsMk2SolarBatteries.netkan, NetKAN/RecycledPartsOrgamiFoldableAssets.netkan, NetKAN/RecycledPartsRSCapsuledyne.netkan, NetKAN/RecycledPartsSpareParts.netkan, NetKAN/RecycledPartskal9000.netkan, NetKAN/SAVE.netkan, NetKAN/SmartStage.netkan, NetKAN/TimeControl.netkan
Successor to #7563.
ckan compat add 1.5
=> Tag seventeenth group of mods

NetKAN/BAMCont.netkan, NetKAN/CivilianPopulation.netkan, NetKAN/ColorfulFuelLines.netkan, NetKAN/ComfortableLanding.netkan, NetKAN/ControlLock.netkan, NetKAN/CorrectCoL.netkan, NetKAN/CriticalTemperatureGauge.netkan, NetKAN/EvaFuelCont.netkan, NetKAN/HangarGrid.netkan, NetKAN/HarderSolarSystem-1x.netkan, NetKAN/HarderSolarSystem-2x.netkan, NetKAN/HarderSolarSystem-3x.netkan, NetKAN/HarderSolarSystem-4x.netkan, NetKAN/HarderSolarSystem-generic.netkan, NetKAN/IXSWarpshipOS.netkan, NetKAN/KerbalXMod.netkan, NetKAN/KramaxAutopilotContinued.netkan, NetKAN/LaunchNumbering.netkan, NetKAN/MK12PodIVAReplacementbyASET.netkan, NetKAN/Mk1CabinHatch.netkan, NetKAN/PartCommanderCont.netkan, NetKAN/PhoenixIndustriesEVASuit.netkan, NetKAN/PhoenixIndustriesSpaceTug.netkan, NetKAN/PoodsMilkyWaySkybox.netkan, NetKAN/ProceduralAirships.netkan, NetKAN/SETI-ProbeControlEnabler.netkan, NetKAN/StorkDeliverySystem.netkan, NetKAN/WindowShineTR.netkan, NetKAN/WorldStabilizer.netkan, NetKAN/unBlur.netkan
=> Tag eighteenth group of mods

NetKAN/Kerbalism.netkan
=> Kerbalism: remove conflict with DynamicBatteryStorage

NetKAN/Backports/Kopernicus.netkan, NetKAN/IR-Model-Rework-Core.netkan, NetKAN/IR-Model-Rework-Expansion.netkan, NetKAN/IR-Model-Rework-Utility.netkan, NetKAN/KerBalloons.netkan, NetKAN/LudicrousPropulsionSystems.netkan, NetKAN/RocketdyneF-1.netkan, NetKAN/SpaceDock.netkan, NetKAN/SpaceShuttleEngines.netkan
Successor to #7597.
This should be the last group of non-erroring netkans!
=> Tag forty-third group of mods

NetKAN/CareerModePartCostNullifer.netkan, NetKAN/ContractConfigurator-KerbalAcademy.netkan, NetKAN/DiscordRP.netkan, NetKAN/Graphotron.netkan, NetKAN/HyperEdit.netkan, NetKAN/KerbalOccupationColors.netkan, NetKAN/KerbinCup.netkan, NetKAN/WoodSpaceProgram.netkan
Successor to #7598. These are the mods that raise errors when you try to inflate them. If the errors ever get fixed, then they'll be tagged.
=> Tag mods with indexing errors

NetKAN/SimplexTechTree.netkan
This tech tree mod is not compatible with other tech tree mods.
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1266-leonov/&do=findComment&comment=3722387
=> Conflicts for Simplex

NetKAN/KSTS.netkan
KSTS had tags, #7611 blew them away. Now they're restored.
=> Restore KSTS's tags

NetKAN/KRnD.netkan
#7635 blew away KRnD's tags. Now they're restored.
=> Restore KRnD's tags

NetKAN/AutomatedScienceSampler.netkan, NetKAN/CraftHistory.netkan, NetKAN/KerboKatzSmallUtilities-DailyFunds.netkan, NetKAN/KerboKatzSmallUtilities-DestroyAll.netkan, NetKAN/KerboKatzSmallUtilities-FPSLimiter.netkan, NetKAN/KerboKatzSmallUtilities-FPSViewer.netkan, NetKAN/KerboKatzSmallUtilities-KerbalScienceExchange.netkan, NetKAN/KerboKatzSmallUtilities-ModifiedExplosionPotential.netkan, NetKAN/KerboKatzSmallUtilities-PhysicalTimeRatioViewer.netkan, NetKAN/KerboKatzSmallUtilities-RecoverAll.netkan, NetKAN/KerboKatzSmallUtilities.netkan, NetKAN/KerboKatzUtilities.netkan
These repos got moved, which sometimes causes a GitHub API rate limit problem.
=> Xarun -> KerboKatz

NetKAN/LessRealThanReal.netkan
Fixes #7660, which was submitted by the mod author.
=> Add LessRealThanReal

NetKAN/RSSTextures2048.netkan, NetKAN/RSSTextures4096.netkan, NetKAN/RSSTextures8192.netkan
Updated version compatibility due to changes in RSS.
=> Updated 1.8 compatibility

NetKAN/Spectra.netkan
A folder is removed in the latest Spectra
=> Remove planetshine config install stanza from Spectra

NetKAN/NSSC.netkan
ZIP file used to contain NSSC, now NotSoSimpleConstruction
=> Fix NSSC install path

NetKAN/BeyondHome.netkan
See KSP-CKAN/CKAN-meta#1815, new release has new compatibility.
=> Update BeyondHome compatibility

NetKAN/AVP-8kTextures.netkan
#7701 for 8k, needed for KSP-CKAN/CKAN-meta#1817.
=> Update compat for AVP-8kTextures

NetKAN/ASETProps.netkan, NetKAN/DE-IVAExtension.netkan
This is a set of IVAs for stock pods using RPM and ASET.
https://forum.kerbalspaceprogram.com/index.php?/topic/186715-18x-de_ivaextension-for-all-the-stock-pod-ivas/
Permission from author:
=> Add DE_IVAExtension

NetKAN/GravityTurnContinued.netkan
See https://forum.kerbalspaceprogram.com/index.php?/topic/148448-14177-gravityturn-continued-automated-efficient-launches/&do=findComment&comment=3741917
=> Set GravityTurnContinued to KSP 1.9 compatible

NetKAN/ChayrolDesignOrg.netkan
Fixes #7710 
ckan compat add 1.5
=> Add ChayrolDesignOrg

NetKAN/ModActions.netkan
#7732 switched this module to a new fork, and the hard coded version is now out of date.
See KSP-CKAN/CKAN-meta/pull/1856.
=> Vref for ModActions

NetKAN/FASA.netkan
=> RN FASA switch texture plugins

NetKAN/KerbalKomets.netkan
#7758 added this mod without tags. Now it has them.
=> Tag KerbalKomets

NetKAN/RealExoplanets.netkan
=> Add RealExoplanets

NetKAN/B9-PWings-Fork.netkan
=> Add suggestions to B9-PWings-Fork

NetKAN/OhScrap.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3755887
=> Switch OhScrap to new fork

NetKAN/CivilianPopulation.netkan
Hard coded version info for mod with version file
=> vref for CivilianPopulation

NetKAN/RealChute.netkan
https://github.com/StupidChris/RealChute
is now
https://github.com/ChrisViral/RealChute
=> Update RealChute repo

NetKAN/IntakeAirDrainIt.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3760390
=> Fix IntakeAirDrainIt license

NetKAN/GravityTurnContinued.netkan
=> Update resources for GravityTurnContinued

NetKAN/SimpleConstruction.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/191424-ksp-181-simpleconstruction-stock-rocket-building-version-40232020-02-10/&do=findComment&comment=3762448
=> Add recommendations for SimpleConstruction

NetKAN/LessSimpleISRU.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/192738-18-19less-simple-isru-for-modded-fuels-v01-electrolysis-sabatier-and-more/&do=findComment&comment=3763190
=> Fix LessSimpleISRU license

NetKAN/NewTantares.netkan
=> Update NewTantares compatibility

NetKAN/RSSTextures16K.netkan
=> Add RSSTextures16K

NetKAN/AutoAsparagus.netkan
Now depends on ToolbarController and ClickThroughBlocker
=> Add required dependencies

NetKAN/LessSimpleISRU.netkan
Latest release note says a version file was added
https://forum.kerbalspaceprogram.com/index.php?/topic/192738-18-19less-simple-isru-for-modded-fuels-v02-electrolysis-sabatier-and-more-added-rss-and-nfc-integration/&do=findComment&comment=3770123
=> Add vref for LessSimpleISRU

NetKAN/MoreTerraWorlds.netkan
This mod's folder structure has changed.
=> Fix MoreTerraWorlds install

NetKAN/BlacklegIndustriesMMTantaresTACLS.netkan
This repo's user has been renamed.
=> Update BlacklegIndustriesMMTantaresTACLS kref

NetKAN/TantaresAndBDBNowinColors.netkan
=> Fix install for TantaresAndBDBNowinColors

NetKAN/AlternateResourcePanel.netkan
@zer0Kerbal asked to adopt this mod, but @TriggerAu intends to still maintain it. We switched the kref in #7840, now it's switched back.
Fixes #7863.
=> Revert AlternateResourcePanel to original fork

NetKAN/ModularLaunchPads.netkan
There are some other goodies in this ZIP file. Now we'll install the example craft files.
ckan compat add 1.9.1
=> ModularLaunchPads craft files

NetKAN/PAWRangeBuff.netkan
=> Add PAWRangeBuff

NetKAN/ModularFuelTanks.netkan
This mod isn't on a host that can be queried for updates.
Previous was #7592 and #7223.
=> Update ModularFuelTanks to 5.13.1

NetKAN/Spectra.netkan
Removed versioning override, set mod to be compatible with all KSP versions after 1.1.2.
=> Update Spectra.netkan versioning

NetKAN/ASETProps.netkan
=> Update ASETProps RPM dep version

NetKAN/AirplanePlus.netkan, NetKAN/AutoLoadGame.netkan, NetKAN/BonVoyage.netkan, NetKAN/CEDA-Aethon-ITS.netkan, NetKAN/CelestialBodyScienceEditor.netkan, NetKAN/ChakaMonkeyExplorationSystems.netkan, NetKAN/ContractConfigurator-ContractPackHistoricalProgression.netkan, NetKAN/ContractConfigurator-KSI.netkan, NetKAN/ContractRewardModifier.netkan, NetKAN/CorrectCoL.netkan, NetKAN/DavonSupplyMod.netkan, NetKAN/DeepSkyCore.netkan, NetKAN/DraggableNavball.netkan, NetKAN/ESLDJumpBeacons.netkan, NetKAN/EVATransfer.netkan, NetKAN/ExceptionDetectorUpdated.netkan, NetKAN/FanRadiator.netkan
This was one of my major motivations for KSP-CKAN/CKAN#3045.
Now a bunch of mods with version files will use them. There are many more left. Some may need to be removed if it doesn't work out.
=> Add vrefs to first group of mods with version files

NetKAN/FlexibleDocking.netkan, NetKAN/FlightPlan.netkan, NetKAN/GAP.netkan, NetKAN/HideEmptyTechNodes.netkan, NetKAN/IONRCS.netkan, NetKAN/IXSWarpshipOS.netkan, NetKAN/InterstellarFuelSwitch.netkan, NetKAN/JanitorsCloset.netkan, NetKAN/K2CommandPodCont.netkan, NetKAN/KEI.netkan, NetKAN/Kaboom.netkan, NetKAN/LLL-Extras.netkan, NetKAN/ManeuverNodeEvolved.netkan, NetKAN/ODFC-Refueled.netkan, NetKAN/OneWindow.netkan, NetKAN/OrbitalColony.netkan, NetKAN/Overdrive.netkan, NetKAN/PersistentRotation.netkan, NetKAN/PlanetaryDiversity.netkan, NetKAN/QuantumStrutsContinued.netkan, NetKAN/RedOnion.netkan, NetKAN/RemoteTech.netkan, NetKAN/ResonantOrbitCalculator.netkan, NetKAN/RosterManager.netkan, NetKAN/ScienceRelay.netkan, NetKAN/SensibleScreenshot.netkan
=> Add vrefs to second group of mods with version files

NetKAN/KWSKerbalWeaponsSystem.netkan, NetKAN/KerbalModsOverhaul.netkan, NetKAN/LCAproject.netkan, NetKAN/ModularRocketSystemsLITE.netkan, NetKAN/MoonReorganizer.netkan, NetKAN/NAS.netkan, NetKAN/OPTUSILifeSupportPatch.netkan, NetKAN/PL-IRC.netkan, NetKAN/PL-KSat.netkan, NetKAN/ShipSaveSplicer.netkan, NetKAN/SpaceBus.netkan, NetKAN/StockishProjectOrion.netkan, NetKAN/TheRATPack.netkan, NetKAN/ThorTech.netkan, NetKAN/TooManyOrbits.netkan, NetKAN/TreeToppler.netkan, NetKAN/VesselView-UI-RasterPropMonitor.netkan, NetKAN/VesselView-UI-Toolbar.netkan, NetKAN/VesselView.netkan, NetKAN/WhoAmI.netkan, NetKAN/WorldStabilizer.netkan, NetKAN/Wwwwwwwww.netkan, NetKAN/notes.netkan, NetKAN/xScience.netkan
Next pass of #7913.
This should be the last group without metanetkans, though there are several left that show the warning because of a version file in a mod they bundled rather than a real version file.
=> Add vrefs to third group of mods with version files

NetKAN/ZZZRadioTelescope.netkan
This PR does what I surmise KSP-CKAN/NetKAN#7916 was intended to do.
https://forum.kerbalspaceprogram.com/index.php?/topic/160243-12-131-141-151-161-17-19-triple-z-radio-astronomy-telescope/&do=findComment&comment=3788627
=> Add depends for ZZZRadioTelescope

NetKAN/PayToPlay.netkan
=> Add PayToPlay

NetKAN/KourageousTourists.netkan
First successful notification of a newly added version file (see KSP-CKAN/CKAN#3045)!
=> Get KourageousTourists compat info from version file

NetKAN/SuperBattery.netkan
- https://spacedock.info/mod/2368/SuperBattery
- https://github.com/baddzse233/SuperBatteryMod
Fixes #7853.
=> Add SuperBattery

NetKAN/ContractConfigurator-ExplorationPlus.netkan
=> Fix ExplorationPlus install path

NetKAN/CriticalTemperatureGauge.netkan
=> CriticalTemperatureGauge does not depend on anything now

NetKAN/GroundEffect.netkan
A mod that enhances stock aerodynamics.
https://forum.kerbalspaceprogram.com/index.php?/topic/178169-ground-effect-development-thread/&do=findComment&comment=3567275
=> Add GroundEffect

NetKAN/WalkAbout.frozen
=> Revert "Walkabout"

NetKAN/EnduranceReconfig.netkan
=> Add EnduranceReconfig missing depends

NetKAN/PersistentThrust.netkan
Replaces #7971.
https://spacedock.info/mod/2450/Persistent%20Thrust
=> New fork for PersistentThrust

NetKAN/PersistentThrust.netkan
(Should have been done in #7972.)
=> Update homepage link for "Persistent Thrust"

NetKAN/AGExt.netkan, NetKAN/AllYAll.netkan, NetKAN/B9HXReconfig.netkan, NetKAN/BetterTimeWarpCont.netkan, NetKAN/KerbalTubes.netkan, NetKAN/SOS.netkan, NetKAN/TweakScaleCompanion-ReStockPlus.netkan, NetKAN/WalkAbout.netkan
Some mods may have been missed during the initial mass-tagging. Others were frozen during that and unfrozen later without tags. Still others had them deleted in #7729 or #7734.
Now all these modules have tags.
=> Tag untagged modules

NetKAN/NodeSplitter.netkan
#7980 added this mod without tags.
Now it has them.
=> Tags for NodeSplitter

NetKAN/SSTOProject.netkan
=> Update SSTOProject relationships

NetKAN/VesselSwitcher.netkan
=> VesselSwitcher compatibility

NetKAN/Bumblebee.netkan
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2097
=> Update Bumblebee max KSP version to 1.10

NetKAN/TestLite.netkan
=> Update TestLite compatibility

NetKAN/MechJeb2.netkan, NetKAN/ModuleManager.netkan, NetKAN/SmokeScreen.netkan
Mechjeb2 required a rebuild and the other mods seems to work as is
=> Update my mods for KSP 1.10

NetKAN/SpaceXLegs.netkan
This mod apparently just added a version file.
=> vref for SpaceXLegs

NetKAN/SciFiVisualEnhancements.netkan
See #8037, this is the other netkan with no author.
=> Add author for SciFiVisualEnhancements

NetKAN/LunaMultiplayer.netkan
So I've got a request by the author of DarkMultiplayer to get LunaMultiplayer indexed on CKAN :P
Permission is given by @gavazquez / Dagger as seen in the screenshot below:
This needs https://github.com/LunaMultiplayer/LunaMultiplayer/pull/344 to be merged first, and a new release which includes the version file.
https://github.com/LunaMultiplayer/LunaMultiplayer/releases
=> Add LunaMultiplayer

NetKAN/DockRotate.netkan
This mod has been releasing backports and has a clean versioning history.
=> Allow out of order releases for DockRotate

NetKAN/NearFutureAeronautics.netkan
=> Index NearFutureAeronautics

NetKAN/PatentPurchase.frozen
=> Remove 'plugin' tag

NetKAN/CrowdSourcedScience.netkan
Moved the tags to the self-hosted netkan
=> CrowdSourcedScience - Moved tags

NetKAN/GroundEffect.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/183500-13-110-ground-effect/&do=findComment&comment=3839781
https://forum.kerbalspaceprogram.com/index.php?/topic/183500-13-110-ground-effect/&do=findComment&comment=3839787
=> Fix GroundEffect install, compatibility

NetKAN/EnvironmentalVisualEnhancements.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/149733-18-environmentalvisualenhancements-180-2/&do=findComment&comment=3835958
~~Note this is pending and needs to be confirmed with the author. I just want to investigate whether it will work. Notably the version file is missing.~~
=> New maintainer for EnvironmentalVisualEnhancements

NetKAN/Kopernicus.netkan
I'm sure everyone's heard of the new Kopernicus authors by now - everybody except for CKAN, that is.
=> Update Kopernicus authors

NetKAN/Kopernicus.netkan
Sorry for not including this in #8099, totally forgot that there's a new thread.
=> Update Kopernicus URL

NetKAN/AirlineKuisine.netkan, NetKAN/RationalResources.netkan
From forum PM:
> Howdy, guys. I have 2 more updates to throw in.
> 
> Airline Kuisine
> ```json
> {
>     "supports": [
>         { "name": "ClassicStockResources" },
>         { "name": "CommunityResourcePack" },
>         { "name": "CommunityTechTree" },
>         { "name": "ConnectedLivingSpace" },
>         { "name": "Kerbalism" },
>         { "name": "KIS" },
>         { "name": "Pathfinder" },
>         { "name": "Snacks" },
>         { "name": "TacLifeSupport" },
>         { "name": "USI-LS" },
>         { "name": "WildBlueTools" }
>     ],
>     "suggests": [
>         { "name": "Mk2Expansion" },
>         { "name": "Mk3Expansion" }
>     ],
> }
> ```
> 
> Rational Resources
> ```json
> {
>     "supports": [
>         { "name": "BeyondHome" },
>         { "name": "CryoTanks" },
> …
```
=> Relationship updates for JadeOfMaar's mods

NetKAN/SDHI-ServiceModuleSystem.netkan
See KSP-CKAN/CKAN-meta#2149, this mod's hard coded compatibility has changed.
=> Update SDHI-ServiceModuleSystem compatibility

NetKAN/SSTOProject.netkan
See KSP-CKAN/CKAN-meta#2150 and Monniasza/SSTO-Project#1, this mod now has a version file.
This PR adds a vref.
=> vref for SSTOProject

NetKAN/EnvironmentalVisualEnhancements.netkan
Successor to #8097, there's a new forum thread:
- https://forum.kerbalspaceprogram.com/index.php?/topic/196289-environmental-visual-enhancements-maintenance-releases/
=> New homepage for new EVE fork

NetKAN/NorthKerbinDynamicRenewed.netkan
=> Fix NKDR install

NetKAN/HumanStuff.netkan
Some suit textures take up 1 GB??????
=> Vref for HumanStuff

NetKAN/RCSBuildAid.netkan
This mod used to be in hiatus.
Changed download from curse to github and added a conflict to the fork of this mod.
=> RCSBuildAid v1.0

NetKAN/DestructionEffects.netkan
=> Update DestructionEffects homepage

NetKAN/AltimeterAutoHide.netkan
I have added a .version file with the latest release
=> Add vref to AltimeterAutoHide

NetKAN/Oddiseo.netkan
Based on the netkan file in the mod's repo. Note, the repo has no releases, so this won't work at first.
Fixes #8172.
=> Add Oddiseo

NetKAN/BluedogDB.netkan
Relationship updates requested by one of the maintainers of BluedogDB.
Fixes #8185.
=> BluedogDB updates

NetKAN/KerbalAnimationSuiteCont.netkan
=> ModuleManager dep for KerbalAnimationSuiteCont

NetKAN/BluedogDB.netkan
=> Update BluedogDB relationships

NetKAN/Xingyun2.netkan
Just like #8205, another mod with a checked CKAN badge we didn't get a PR for. Investigations running...
https://spacedock.info/mod/2559/Xingyun-2%20Satellite
https://forum.kerbalspaceprogram.com/index.php?/topic/197878-110-xingyun-2-satellite-2020112/
=> Add Xingyun2

NetKAN/BeyondHome.netkan
See #8219 
BeyondHome comes with its own planet textures for Parallax
=> Make BeyondHome provide Parallax-Textures

NetKAN/KylandersFlagPack.netkan
This mod has the CKAN badge but we didn't get a PR.
- https://spacedock.info/mod/2577/kylander%27s%20flag%20pack
- https://forum.kerbalspaceprogram.com/index.php?/topic/198065-all-ksp-versions-kylelanders-flag-pack/
=> Add KylandersFlagPack

NetKAN/PartOverhaulIntegration.netkan
=> Add PartOverhaulIntegration

NetKAN/AntaresCygnus.netkan, NetKAN/RN-MiscParts.netkan, NetKAN/RN-SalyutStations.netkan, NetKAN/RN-Skylab.netkan, NetKAN/RN-SovietProbes.netkan, NetKAN/RN-SovietRockets.netkan, NetKAN/RN-SovietSpacecraft.netkan, NetKAN/RN-USProbesPack.netkan, NetKAN/RN-USRockets.netkan
These have been fixed to no longer conflict so it can be removed.
=> RN remove old conflicts

NetKAN/MinmusSpaceCenter.netkan
Fixes #8256.
Also took a look at other new mods with the CKAN badge that didn't get a webhook-created PR and found SLS Part Pack, but not including that because it's a rogue re-upload by someone other than the author.
=> Add MinmusSpaceCenter

.github/workflows/inflate.yml, .travis.yml
See KSP-CKAN/xKAN-meta_testing#61.
This is HebaruSan/NetKAN#1 except with the master branch, the test data removed, and debugging output turned off.
=> Inflate with GitHub Action

NetKAN/LessRealThanReal.netkan
Closes KSP-CKAN/CKAN-meta#2191.
=> Update LessRealThanReal compatibility

NetKAN/KerbalInventoryForAll.netkan
This mod has the CKAN badge but didn't get an automatic PR, and the author asked about it on Discord.
___
ckan compat add 1.10
=> Add KerbalInventoryForAll

NetKAN/CommunityTechTree.netkan, NetKAN/CryoEngines-LFO.netkan, NetKAN/CryoEngines-NFAero.netkan, NetKAN/CryoEngines.netkan, NetKAN/HeatControl.netkan, NetKAN/KerbalAtomics-NFECompatibility.netkan, NetKAN/KerbalAtomics-NTRModSupport.netkan, NetKAN/KerbalAtomics-NTRsUseLF.netkan, NetKAN/KerbalAtomics.netkan, NetKAN/NearFutureConstruction.netkan, NetKAN/NearFutureElectrical-Core.netkan, NetKAN/NearFutureElectrical-DecayingRTGs.netkan, NetKAN/NearFutureElectrical.netkan, NetKAN/NearFutureExploration.netkan, NetKAN/NearFutureLaunchVehicles.netkan, NetKAN/NearFuturePropulsion-XenonHETs.netkan, NetKAN/NearFuturePropulsion.netkan, NetKAN/NearFutureSolar-Core.netkan, NetKAN/NearFutureSolar.netkan, NetKAN/NearFutureSpacecraft-OrbitalLFOEngines.netkan, NetKAN/NearFutureSpacecraft.netkan
To be merged after I finish the migration for these mods.
=> Migrate NFT repos

NetKAN/BeamedPowerPlugin-Realistic.netkan, NetKAN/BeamedPowerPlugin.netkan
Let's see how much of a difference it makes.
=> Vref for BeamedPowerPlugin

NetKAN/MarkIVSpaceplaneSystem.netkan, NetKAN/NearFutureAeronautics.netkan, NetKAN/StationPartsExpansionRedux-Metal.netkan, NetKAN/StationPartsExpansionRedux.netkan
=> NF updates

NetKAN/TechTreeKompacted.netkan
Has CKAN badge on SD but no PR. Author confused why not indexed yet on thread.
- https://spacedock.info/mod/2600/TechTree%20Kompacted?ga=%3CGame+3102+%27Kerbal+Space+Program%27%3E
- https://forum.kerbalspaceprogram.com/index.php?/topic/199096-111x-techtree-kompacted-13/
=> Add TechTreeKompacted

NetKAN/TestLite.netkan
Not expecting much of a change. Related to KSP-CKAN/CKAN-meta#2194.
=> Vref for TestLite

NetKAN/KiwiTechTree.netkan
Compatibility with KSPIE happened on @sswelm  's side.
=> Remove KSPIE Incompatibilty

NetKAN/GroundEffect.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/183500-13-111-ground-effect/
=> GroundEffect is compatible with 1.11

NetKAN/Cressida.netkan
=> Add Cressida

NetKAN/SpaceXSuits.netkan
=> Add SpaceXSuits

NetKAN/MechJeb2.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/154834-111x-anatid-robotics-mumech-mechjeb-autopilot-2110-12th-january-2021/
Closes KSP-CKAN/CKAN-meta#2228.
=> Update MechJeb2 compatibility

NetKAN/DreskillerBase.netkan
- https://forum.kerbalspaceprogram.com/index.php?/topic/199396-dreskiller-base-planet-pack-111-a-starkiller-base-for-ksp/&do=findComment&comment=3911163
Fixes #8319.
=> Add DreskillerBase

NetKAN/BetterCrewAssignment.netkan
A new version of this mod just came out, and if we set a version min override now, then any future updates on SpaceDock will only set the max, as desired.
=> New override for a Snark mod

NetKAN/GrannusExpansionPack-Rescale.netkan, NetKAN/GrannusExpansionPack.netkan
GEP_JNSQ has been replaced by GEP_Rescale.
=> Add GrannusExpansionPack-Rescale

NetKAN/VultureSystem.netkan
Has CKAN badge but no PR.
https://spacedock.info/mod/2628/%5B1.9.1%2B%5D%5BKopernicus%5D%20The%20Vulture%20System%20-%20A%20new%20star%20system.
=> Add VultureSystem

NetKAN/TheBlueDrill.netkan, NetKAN/TheBlueScoop.netkan
These mods originally released for 1.10.1 and recently had their SpaceDock compatibility updated to 1.11.
=> Pin TheBlue* min compat

NetKAN/LionheadAerospaceCircularSolarPanels.netkan
This just updated compatibility. It was originally for KSP 1.5.1.
=> Lionhead min compat

NetKAN/KSPSecondaryMotion.netkan
Another SpaceDock mod with rolling compatibility, originally for KSP 1.10.1.
=> Pin min compat for KSPSecondaryMotion v0.1.1

NetKAN/PlanetWiki.netkan
Another SpaceDock long-termer, this time starting with KSP 1.9.1.
=> Pin PlanetWiki 1:4.1 min compat

NetKAN/Kopernicus.netkan
@R-T-B is starting a new thread because @prestja is not active at the moment:
- https://forum.kerbalspaceprogram.com/index.php?/topic/200143-181-1111-kopernicus-stable-branch-last-updated-febuary-7th-2021/
=> New Kopernicus homepage

NetKAN/CParts.netkan
Has CKAN badge but no PR.
https://spacedock.info/mod/2638/CParts
=> Add CParts

NetKAN/LionheadAerospaceCircularSolarPanels.netkan
https://spacedock.info/mod/2641/Lionhead%20Aerospace%20Circular%20Solar%20Panels
=> Update SD kref for LionheadAerospaceCircularSolarPanels

NetKAN/PlanningNode.netkan
=> Add PlanningNode

NetKAN/StockWaterfallEffects.netkan
=> Add StockWaterfallEffects

NetKAN/KerbalChangelog.netkan
I'm in the process of adopting this mod, but I want to take it slowly in case the author comes back.
- https://github.com/HebaruSan/KerbalChangelog
=> Switch KerbalChangelog to new fork

NetKAN/CRE.netkan
Closes KSP-CKAN/CKAN-meta#2295.
=> Update CRE compatibility

NetKAN/CRE.netkan
This mod has a forum page, but it wasn't in the metadata.
=> Homepage for CRE

NetKAN/OPTSpacePlaneMain.netkan
Looks like this was not new, but might as well fix it.
___
ckan compat add 1.10
=> MM dep for OPTSpacePlaneMain

NetKAN/SciFiVisualEnhancements-WeimaranersTweaks.netkan
A mod on SpaceDock that started compatible with 1.9.1 and has been updated to successive versions since.
=> Pin min compat of SciFiVisualEnhancements-WeimaranersTweaks

NetKAN/OuterKerbin.netkan
Another one on SpaceDock with rolling compatibility, this time back to 1.7.3.
=> Pin min compat of OuterKerbin

NetKAN/Heracleitus.netkan
A mod on SpaceDock with rolling compatibility, starting on 1.11.1.
=> Pin Heracleitus min compat

NetKAN/CommunityAgenciesRevivalProject.netkan, NetKAN/DarkMultiPlayer.netkan
A few more mods on SD with rolling compatibility.
=> Pin min compat of CARP and DMP

NetKAN/ModularLaunchPads.netkan
Yes, I probably will attempt to automate this at some point. Not yet.
=> Pin min compat of ModularLaunchPads

NetKAN/AATI-Flags.netkan
This one's pretty old and still having its compatibility rolled forward.
=> Pin AATI-Flags min compat

NetKAN/CustomAsteroids-Pops-OPM-Outer.netkan
=> MM dep for CustomAsteroids-Pops-OPM-Outer

NetKAN/KSPBugReport.netkan
Bug reporting plugin, homepage : https://github.com/KSPModdingLibs/KSPBugReport
=> Add new plugin : KspBugReport

NetKAN/KSPArtemisSuit.netkan
A mod on SpaceDock originally uploaded for KSP 1.10.1, now compatible with 1.11.2.
=> Pin KSPArtemisSuit min compat

NetKAN/MOISTUnderwaterTechnologies.netkan, NetKAN/PlanetaryStationCores.netkan, NetKAN/PureElectricEngines.netkan, NetKAN/SinkEmAll.netkan
Some of these mods have been on SpaceDock for quite some time.
=> Pin min compat of Jatwaa's mods

NetKAN/OutOfGalaxySkybox.netkan, NetKAN/RN8474-8300-Skybox.netkan
More mods on SpaceDock with rolling compatibility.
=> Pin min compat of LOL221's mods

NetKAN/Benjee10Suits.netkan
chris-kerbal asked me to index this mod by @benjee10 using a metanetkan.
I've made them aware of the usual problems that could arise from using metanetkans.
Anyway:
* [Forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/201382-111-benjee10s-historical-kerbal-suits-custom-space-suits-space-helmets-apollo-aces-sokol-more-initial-release-v100/)
* [NetKAN](https://github.com/benjee10/Benjee10_Suits/blob/master/CKAN/Benjee10Suits.netkan)
* [Version file](https://github.com/benjee10/Benjee10_Suits/blob/master/GameData/Benjee10_Suits/Version/Benjee10Suits.version)
There's a pending PR by myself to fix some smaller issues in the netkan and version file:
https://github.com/benjee10/Benjee10_Suits/pull/2
=> Add Benjee10Suits

NetKAN/MANGO.netkan
=> MM dep for MANGO

NetKAN/PRUNES.netkan
Another SD mod missed by the bug that KSP-SpaceDock/SpaceDock#337 fixed / is fixing.
- https://spacedock.info/mod/2679/Potentially%20Really%20Useful%20New%20Editor%20Sorter%20%28PRUNES%29
- https://forum.kerbalspaceprogram.com/index.php?/topic/201227-1112-fruitkocktail-a-collection-of-mini-life-improvement-mods-with-fruit-based-acronyms-as-names-new-mod-added-prunes/
=> Add PRUNES

NetKAN/TweakScale.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/179030-144/&do=findComment&comment=3949978
(Assuming, of course, I didn't messed up something as usual! :) )
=> Adding KSP-Recall as a dependency, as requested by DasSkellet on forum.

NetKAN/FishyAntiMissileSpam.netkan
This mod just went from two folders with versionless names to one volder with the version in it.
=> Update FishyAntiMissileSpam install

NetKAN/OldPartsRedux.netkan
TriggeredSnake/OldPartsRedux#1 got merged. :tada:
=> Vref for OldPartsRedux

NetKAN/KerbinPlacePack.netkan
=> Update KerbinPlacePack deps

NetKAN/KerbinPlacePack.netkan
Author deleted and re-uploaded to rename the mod.
Folder in ZIP is misspelled, anticipated to be fixed in a future release.
___
=> Update kref for KerbinPlacePack

NetKAN/KerbinPlacePack.netkan
=> MM dep for KerbinPlacePack

NetKAN/GRAPES.netkan
CKAN badge without auto-PR:
https://spacedock.info/mod/2691/Gas%20Repairs%20And%20Probably%20Expensive%20Snacks%20%28GRAPES%29
=> Add GRAPES

NetKAN/PlanetOrigins.netkan
Planet pack with CKAN badge without PR.
https://spacedock.info/mod/2689/Planet%20Origins
=> Add PlanetOrigins

NetKAN/FelineUtilityRovers.netkan
Thanks to Nils277/FelineUtilityRovers#52.
=> vref for FelineUtilityRovers

NetKAN/KerbalSpacePonies.netkan
Mod on SD with rolling compatibility
=> Pin min compat of KerbalSpacePonies

NetKAN/KerbinPlacePack.netkan
___
ckan compat add 1.8 1.9 1.10
=> New dep for KerbinPlacePack

NetKAN/AlcubierreStandalone.netkan, NetKAN/CommunityCategoryKit.netkan, NetKAN/CommunityResourcePack.netkan, NetKAN/Karbonite.netkan, NetKAN/Konstruction.netkan, NetKAN/MalemuteRover.netkan, NetKAN/SoundingRockets.netkan, NetKAN/UKS.netkan, NetKAN/USI-ART.netkan, NetKAN/USI-Core.netkan, NetKAN/USI-EXP.netkan, NetKAN/USI-FTT.netkan, NetKAN/USI-LS.netkan, NetKAN/USI-NuclearRockets.netkan, NetKAN/USITools.netkan
The BobPalmer/CKAN repo got moved to UmbraSpaceIndustries/CKAN, which is causing the bot to exceed the API rate limit.
Now the netkans are updated.
=> Update moved metanetkans

NetKAN/BetterTimeWarpCont.netkan
Another minor one related to #8488.
=> Update BetterTimeWarpCont kref

NetKAN/BargainRocketsCont.netkan
Another one related to #8488, with a renamed repo.
=> Update BargainRocketsCont kref

NetKAN/StandardPropulsionSystems.netkan
=> vref for StandardPropulsionSystems

NetKAN/VertikalSpeedIndicator.netkan
=> Add VertikalSpeedIndicator

NetKAN/BoosterGuidance.netkan
Hi @oyster-catcher, we had a request on the CKAN Discord to add this mod to CKAN.
Would it be OK with you if we did that?
- https://spacedock.info/mod/2587/BoosterGuidance
- https://github.com/oyster-catcher/BoosterGuidance
- https://forum.kerbalspaceprogram.com/index.php?/topic/198760-181-1101-boostguidance-v101/
=> Add BoosterGuidance

NetKAN/ComfortableLanding.netkan
=> Vref for ComfortableLanding

NetKAN/Telemagic.netkan
=> Telemagic no longer has crafts, now has a version file

NetKAN/KerbalMiniShuttle.netkan
New version, the craft moved into the VAB, and a new folder is added.
=> Update KerbalMiniShuttle install

NetKAN/CompletelyNonAggressiveRocketry.netkan
=> Add CompletelyNonAggressiveRocketry

NetKAN/USSDiscovery.netkan
Mod on SD with CKAN badge without PR
=> Add USSDiscovery

NetKAN/BirthOfTime.netkan, NetKAN/BreakingGroundPropellerRebalance.netkan, NetKAN/PLUM.netkan
These have the CKAN badge on SD but no PR
https://spacedock.info/mod/2724/Parachutes%3F%20Let%27s%20Use%20Maths%21%20%28P.L.U.M.%29?ga=%3CGame+3102+%27Kerbal+Space+Program%27%3E
https://forum.kerbalspaceprogram.com/index.php?/topic/201227-1112-fruitkocktail-a-collection-of-mini-life-improvement-mods-with-fruit-based-acronyms-as-names-new-mod-added-plum/
https://spacedock.info/mod/2726/Birth%20Of%20Time%20Planet%20Pack
https://forum.kerbalspaceprogram.com/index.php?/topic/202202-birth-of-time-planet-pack/
https://spacedock.info/mod/2725/Breaking%20Ground%20Propeller%20Rebalance
https://forum.kerbalspaceprogram.com/index.php?/topic/202185-breaking-ground-turboshaft-fuel-tech-rebalance-v10-111x-forever-probably/
=> Add recent mods from SpaceDock

NetKAN/ImprovedTreeEnginePlacement.netkan
=> Install ImprovedTreeEnginePlacement extras

NetKAN/KSP-PartVolume.netkan
=> MM dep for KSP-PartVolume

NetKAN/CrusoeSpaceIndustriesTechTree.netkan, NetKAN/WorkingUnderwaterLite.netkan
Two more mods on SD with CKAN badges and no PR.
https://spacedock.info/mod/2749/Working%20Underwater%20Lite
https://forum.kerbalspaceprogram.com/index.php?/topic/202336-working-underwater-lite/
https://spacedock.info/mod/2748/CSI%20Tech%20Tree
https://forum.kerbalspaceprogram.com/index.php?/topic/202292-wip111x-csi-tech-tree/
=> Add CSITechTree and WorkingUnderwaterLite

NetKAN/No-Texture-Atlas-5.netkan, NetKAN/No-Texture-CST-100.netkan
Some SD mods with the CKAN badge and no PR. Author has pledged to never add textures.
https://spacedock.info/mod/2710/ksp%20no%20textur%20cst%20100%20mod
https://forum.kerbalspaceprogram.com/index.php?/topic/201964-18x-ksp-no-textur-cst-100-mod/
https://spacedock.info/mod/2712/no%20texture%20atlas%205
https://forum.kerbalspaceprogram.com/index.php?/topic/201982-no-texture-atlas-5-mod-18x/
=> Add No Texture mods

NetKAN/GreenKerbs.netkan, NetKAN/JNSQ-RealDate.netkan
Two mods on SD yadda yadda... One suit pack and one calendar display config.
https://spacedock.info/mod/2757/Greenkerbs%20V1
https://spacedock.info/mod/2755/JNSQ%20Real%20Date
https://forum.kerbalspaceprogram.com/index.php?/topic/202434-111x-jnsq-real-date-10/
___
=> Add JNSQ-RealDate and GreenKerbs

NetKAN/BenjisHardwiredLogic.netkan
CKAN badge on SD w/o PR. An interesting alternative to stock staging.
https://spacedock.info/mod/2759/Benji%27s%20Hardwired%20Logic
https://forum.kerbalspaceprogram.com/index.php?/topic/202506-1101-1112-benjis-hardwired-logic-v111/
https://github.com/ErinaceusLinnaeus/BenjisHardwiredLogic
=> Add BenjisHardwiredLogic

NetKAN/WorkingUnderwaterLite.netkan
=> WorkingUnderwaterLite no longer has a SPH folder

NetKAN/DMTanks-AeroRTG.netkan, NetKAN/DMTanks-CargoBays.netkan, NetKAN/DMTanks-Fuselage.netkan, NetKAN/DMTanks-SphericalTanks.netkan
Same as #8565 but for the DMTanks mods.
Now merging KSP-CKAN/CKAN#3390 will not degrade the quality of these mods' repository links.
=> Hard code DMTanks repo links

NetKAN/AutoHibernate.netkan
ZIP structure no longer works with default stanza:
Now we look for `GameData/AutoHibernate`.
=> Fix AutoHibernate install

NetKAN/StockWaterfallEffects.netkan
=> StockWaterfallEffects no longer conflicts with ReStock

.github/workflows/inflate.yml
Requires https://github.com/KSP-CKAN/xKAN-meta_testing/pull/76, see that link for more information.
=> Pass PR URL instead of body to xKAN-meta_testing action

NetKAN/TantaresSAF.netkan
=> Add TantaresSAF

NetKAN/Helvica.netkan
Mod on SD with rolling compatibility, but the minimum is earlier than the initial version we got from SD:
=> Pin Helvica min compat

NetKAN/InterstellarRedistributable.netkan, NetKAN/KSPInterstellarExtended.netkan, NetKAN/PhotonSailor.netkan
Interstellar_Redist.dll should be placed in the GameData folder
=> Fixes missing DLL file issue

NetKAN/B9-PWings-Fork.netkan
The new B9PW fork is finally ready for prime time.
=> New B9PW fork

NetKAN/ModularLaunchPads.netkan
While checking up on that I noticed that several of the relationhips had changed.
=> Compat and dep updates for ModularLaunchPads

NetKAN/StarshipLaunchExpansion.netkan
#8662's text had required and recommended mods, but I only noticed them after merging. Now they're added.
___
=> Fix StarshipLaunchExpansion relationships

NetKAN/xScienceContinued.netkan
#8676 switched this mod to a new fork, which has some dependencies that weren't added to the netkan. Now they are.
=> Fix xScienceContinued dependencies

NetKAN/DavonSupplyMod.netkan
Chaned to yaml
Changed recommends to depends
=> Changed recommends to depends

NetKAN/DeadlyReentry.netkan
Made a new thread after the repo move.
=> Retarget Deadly Reentry forum link

NetKAN/RealSolarSystem.netkan
Convert RSS over to using a locally-managed (on RSS repo) netkan
=> Use metanetkan for RSS

NetKAN/GemstoneLV.netkan
Fixes #8709.
(Waiting for the spec version error to tell me what value is needed for `as`...)
=> Add GemstoneLV

NetKAN/SimpleLogistics.netkan
- update spacedock link now that have access to original posting
- update recommends -> suggests
- update suggests
- add supports
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2435
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2434
=> Update SimpleLogistics.netkan 🦞 🇸🇽 🍭 

NetKAN/StationPartsExpansionRedux-IVAs.netkan
Adds a new mod. This shouldn't be merged until the netkan file in the repository dev branch has been merged to master
=> Add SSPX IVAs

NetKAN/CanaveralPads.netkan
=> Add missing dependencies for CanaveralPads

NetKAN/AlarmEnhancements.netkan
https://github.com/severedsolo/AlarmEnhancements
https://forum.kerbalspaceprogram.com/index.php?/topic/204404-112x-alarm-enhancements-101-18082021-automatic-alarms-and-better-naming-of-alarms/
=> Add Alarm Enhancements

NetKAN/Headlines.netkan
Fixes #8745.
~~Inflation will fail initially because there are only pre-releases available.~~
=> Add Headlines

NetKAN/AirParkContinued.netkan
New dependency on ModuleManager
=> Added missing dependency for AirPark

NetKAN/Headlines.netkan
See #8771, the author requests:
- Min compat of 1.8
- Two new depends
Closes #8771.
=> Headlines compatibility and relationships

NetKAN/Headlines.netkan
=> ModuleManager dep for Headlines

NetKAN/VesselNotes.netkan
Follow-up of https://github.com/KSP-CKAN/NetKAN/pull/8795
* Pull resources from SpaceDock
* Remove default install stanza
* Reorder keys
=> Clean up VesselNotes.netkan

NetKAN/RationalResources.netkan, NetKAN/RationalResourcesCompanion.netkan, NetKAN/RationalResourcesKerbalism.netkan, NetKAN/RationalResourcesKerbalismRF.netkan, NetKAN/RationalResourcesParts.netkan
See https://forum.kerbalspaceprogram.com/index.php?/topic/184875-rational-resources-120-oct-04-2021-kerbalism-realfuels/&do=findComment&comment=4039744
~~Asked a clarifying question about the `provides` property mentioned in the request.~~
=> RationalResources updates

NetKAN/DARTRange.netkan
- https://github.com/Galileo88/DART-Project
- https://forum.kerbalspaceprogram.com/index.php?/topic/205456-1120-dart-range-challenge-100-01-nov-2021/
This mod includes custom forks of several plugins. We have assurances from the authors that they won't conflict with the standard plugins. :crossed_fingers:
=> Add DARTRange

NetKAN/DARTRange.netkan
=> DARTRange authors

NetKAN/PhoenixIndustries.netkan
SD mod originally uploaded with 1.11 compat, updated to 1.12 in https://github.com/KSP-CKAN/CKAN-meta/commit/4474d60e4318d017a30493155647113bda26f089
=> Pin PhoenixIndustries min compat

NetKAN/EnvironmentalVisualEnhancements.netkan
Latest release dropped the GameData folder.
=> Fix EnvironmentalVisualEnhancements install

NetKAN/GrondsMicrometeoriteShield.netkan
=> Fix GrondsMicrometeoriteShield install

NetKAN/GrondsMicrometeoriteShield.netkan
=> MM dep for GrondsMicrometeoriteShield

NetKAN/ShipManifest.netkan
@PapaJoesSoup is planning a new release of this mod shortly and contacted me via forum PM.
See #7756 for previous change.
Forum thread says that previous maintainer has already been contacted and agreed to changing it back.
=> Switch ShipManifest back to PapaJoesSoup repo

NetKAN/AtomicTechIncJunkyards.netkan
=> Fix AtomicTechIncJunkyards install

NetKAN/MoreServos.netkan, NetKAN/SLOTH.netkan, NetKAN/ServoController.netkan
- <https://forum.kerbalspaceprogram.com/index.php?/topic/186546-breaking-ground-mini-mods/>
- <https://github.com/Angel-125/ServoController>
- <https://github.com/Angel-125/SLOTH>
- <https://github.com/Angel-125/MoreServos>
=> Add Breaking Ground mini mods

NetKAN/KerbalMiniShuttle.netkan
Now installs `MKShuttle` to `GameData`.
=> Fix KerbalMiniShuttle install

NetKAN/AtomicTechIncJunkyards.netkan
Closes KSP-CKAN/CKAN-meta#2526.
=> Update AtomicTechIncJunkyards license

NetKAN/ASSET-Mk1.netkan
=> MM dep for ASSET-Mk1

NetKAN/UnKerballedStart.netkan
Please update the CKAN listing if this works
=> Relationship updates for UnKerballedStart

NetKAN/KerwisChinaAerospacePack.netkan
This is #8867, #8823, and #8794 for mod version 1.1. We might want to help the author of this mod make a version file.
=> Pin KerwisChinaAerospacePack compat

NetKAN/Scatterer.netkan, NetKAN/SimplexPropulsion.netkan, NetKAN/WorldWarMaritimeShips.netkan
These would have been included in #8943, but they're part of the hooks-only pass from KSP-CKAN/NetKAN-Infra#40, so they were only inflated a few hours ago.
=> Fix more spec versions

NetKAN/AdjustmentTool.netkan
Fixes #8952.
- https://github.com/ktchen14/AdjustmentTool
=> Add AdjustmentTool

NetKAN/SimpleContractDisplay.netkan
Follow-up of #8958, they have been missed there.
=> Add missing dependencies to SimpleContractDisplay

NetKAN/StockWaterfallEffects.netkan
Closes KSP-CKAN/CKAN-meta#2565.
=> Update StockWaterfallEffects compat

NetKAN/StarshipExpansionProject.netkan
A few more of these have been added to the thread:
___
=> Add recommendations for StarshipExpansionProject

NetKAN/Sandcastle.netkan
Setting `resources.remote-avc` while Angel-125/Sandcastle#1 is in progress.
=> Add Sandcastle

NetKAN/VaporVent.netkan
=> MM dep for VaporVent

NetKAN/KerBalloons.netkan
=> MM dep for KerBalloons

NetKAN/KerbalFlightIndicators.netkan
=> Switch KerbalFlightIndicators to PapaJoesSoup fork

NetKAN/PlanetShine-Config-Default.netkan, NetKAN/PlanetShine.netkan
=> Switch PlanetShine to PapaJoesSoup fork

NetKAN/Mk-X.netkan
=> MM dep for Mk-X

NetKAN/PhotoRealisticVisualEnhancement-64k.netkan, NetKAN/PhotoRealisticVisualEnhancement.netkan
See #9014, the author @SpaceODY requested this mod to be added, then later closed the request with plans to set things up differently.
https://github.com/SpaceODY/PRVE
=> Add PhotoRealisticVisualEnhancement

NetKAN/SRBWaterfallEffects.netkan
=> Fix SRBWaterfallEffects install

NetKAN/StagedAnimation.netkan
This is what I get for not using a .version
=> Update StagedAnimation ksp max version

NetKAN/DepthMask.netkan, NetKAN/StockDepthMaskConfig.netkan
So people aren't confused if they install DepthMask and don't see anything change.
Also mark Stock depth masks as incompatible with restock, since those patches won't work with it
Hope this is ok @kingnoob1377, I only just learned about your mod
=> Suggest stock configs for ModuleDepthMask

NetKAN/MechJeb2.netkan
With an override because I already released a patch and want to make sure all is ok
=> Mechjeb 2.14 version for KSP 1.12.x only

NetKAN/PhotoRealisticVisualEnhancement-64k.netkan, NetKAN/PhotoRealisticVisualEnhancement.netkan
Closes KSP-CKAN/CKAN-meta#2683.
___
=> Update PRVE compat

NetKAN/VollmetallAlternativePropulsionSystem.netkan
https://github.com/KSP-CKAN/CKAN-meta/commit/8ac5c5bccb1ac0442d6952c42f1e30ebe8ccc542
=> Add depends for VollmetallAlternativePropulsionSystem

NetKAN/ElephantEngine.netkan
The folder structure has changed.
=> Update ElephantEngine install path

NetKAN/RationalResourcesELCRP.netkan
Requested by author here:
https://forum.kerbalspaceprogram.com/index.php?/topic/184875-rational-resources-140-apr-28-2022-kerbalism-realfuels/&do=findComment&comment=4124090
https://spacedock.info/mod/2201/Rational%20Resources
=> Add RationalResourcesELCRP

NetKAN/GalaxiesUnbound-AlienWorlds.netkan, NetKAN/GalaxiesUnbound-AlphaCentauri.netkan, NetKAN/GalaxiesUnbound-Core.netkan, NetKAN/GalaxiesUnbound-EpsilonEridani.netkan, NetKAN/GalaxiesUnbound-Lich.netkan, NetKAN/GalaxiesUnbound-Luhman16.netkan, NetKAN/GalaxiesUnbound-Parts.netkan, NetKAN/GalaxiesUnbound-Sirius.netkan, NetKAN/GalaxiesUnbound-StellarAdventures.netkan, NetKAN/GalaxiesUnbound-TauCeti.netkan, NetKAN/GalaxiesUnbound-TeegardensStar.netkan, NetKAN/GalaxiesUnbound-Trappist-1.netkan, NetKAN/GalaxiesUnbound-WorldsofFire.netkan
Requested by a user on Discord, author sounds enthusiastic:
- https://forum.kerbalspaceprogram.com/index.php?/topic/198895-110x-111x-galaxies-unbound-a-stellar-odyssey-102-3-11-jan-2021/
- https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey
- ~~<https://spacedock.info/mod/2620/Galaxies%20Unbound:%20A%20Stellar%20Odyssey>~~
SpaceDock has these as one big ZIP with nested ZIPs, luckily GitHub has them as separate top level assets, so that's where we're getting it.
=> Add GalaxiesUnbound and friends

NetKAN/FoxDefenseContracts.netkan
=> MM dep for FoxDefenseContracts

NetKAN/J20R.netkan
(That's the only file in the ZIP)
=> MM dep for J20R

NetKAN/DeepFreeze.netkan
=> Require BackgroundResources for DeepFreeze

NetKAN/FlyingSaucers.netkan
=> Craft installs for FlyingSaucers

NetKAN/SigmasRSSTUFXProfiles.netkan
=> Fix SigmasRSSTUFXProfiles install

NetKAN/NightShift.netkan
Adds a Day/Night cycle to the Vehicle Editors
https://github.com/coldrifting/NightShift
https://forum.kerbalspaceprogram.com/index.php?/topic/208470-112x-night-shift-auto-daynight-cycle-in-the-vabsph-version-080-initial-release/
=> Add Night Shift Mod

NetKAN/NeistAirReupdated.netkan
https://spacedock.info/mod/3034/NeistAir%20Reupdated
https://forum.kerbalspaceprogram.com/index.php?/topic/208435-neistair-reupdated-updated-by-kerbmario-112x/
Fixes #9163.
=> Recommend FilterExtensions for NeistAirReupdated

NetKAN/RFA-One.netkan
https://spacedock.info/mod/3044
Fixes #9174.
=> Add RFA-One

NetKAN/NeistAirReupdated.netkan
=> MM dep for NeistAirReupdated

NetKAN/ROCapsules.netkan
We've had a remote netkan for a while but apparently no one ever PR'd NetKAN to update to point to it... :(
=> ROCapsules use remote netkan

NetKAN/DraggableAltimeter.netkan
=> Vref for DraggableAltimeter

NetKAN/Kopernicus.netkan
=> Add Kopernicus dependency on Harmony2

NetKAN/SRBWaterfallEffects.netkan
=> Fix SRBWaterfallEffects install yet again

NetKAN/SRBWaterfallEffects.netkan
=> Add TUFX as a dependency for SRBWE

NetKAN/ROHeatshields.netkan
We finally got around to releasing this, adding the netkan.
___
- https://github.com/KSP-RO/ROHeatshields
=> Add ROHeatshields to CKAN

NetKAN/MoldaviteMachines.netkan, NetKAN/MoldaviteMachinesKerbalism.netkan
=> MoldaviteMachines updates

NetKAN/Spectra-JoolShineOnLaythe.netkan, NetKAN/Spectra-KerbinLaytheSnow.frozen, NetKAN/Spectra-MinmusGeysers.frozen, NetKAN/Spectra-MinmusScatterer.frozen, NetKAN/Spectra-VibrantSunsets.netkan
#9249 missed two mods. Now they're updated.
=> Fix Spectra add-on installs

NetKAN/DeployableInventory.netkan
Mod descriptors: inventory - Mods that use stock inventory system
- https://github.com/yalov/DeployableInventory
- https://forum.kerbalspaceprogram.com/index.php?/topic/209148-112-deployable-inventory-beta-2022-08-01/
=> Add DeployableInventory

NetKAN/Targetron.frozen
=> Revert "Adopting of Targetron"

NetKAN/Targetron.netkan
=> Vref for Targetron

NetKAN/Buffalo2.netkan, NetKAN/Sandcastle.netkan, NetKAN/WildBlueCore.netkan
Adds WildBlueCore and Buffalo 2 to CKAN.
=> Buffalo2 and WildBlueCore NetKAN Additions

NetKAN/StarilexMk1NeedleIVA.netkan
@Ailex01, the author of this mod hosted on GitLab, requested to have it added to CKAN.
- https://gitlab.com/Ailex-/starilex-mk1-iva/
- https://forum.kerbalspaceprogram.com/index.php?/topic/209466-1123-starilex-intra-vehicular-solutions-mki-pod-needle/
~~KSP-CKAN/CKAN#3661 must be merged before this because it's adding the ability to index mods from GitLab. Inflation will fail till that happens.~~
Fixes #9325.
=> Add Starilex Mk1 Needle IVA

NetKAN/Buffalo2.netkan
=> Adds sample craft to Buffalo 2

NetKAN/KerbinSideRemasteredTLA.netkan
=> Add MM dep for KerbinSideRemasteredTLA

NetKAN/KerbalKountries.netkan
@CTD37 has asked for this mod to be indexed.
- https://github.com/CTD37/Kerbal-Kountries
- https://forum.kerbalspaceprogram.com/index.php?/topic/209768-kerbal-kountries-kerbalized-nations-and-agencies/
Fixes #9338.
=> Add Kerbal-Kountries

NetKAN/KcalbelohSystem.netkan
- https://forum.kerbalspaceprogram.com/index.php?/topic/203753-wip-112x-kcalbeloh-system-planet-pack-beta-13-a-journey-to-a-black-hole-jul-10-2022/
- https://github.com/jcyuan06/Kcalbeloh-System
Fixes #9330.
=> Add KcalbelohSystem

NetKAN/APPLE.netkan, NetKAN/FIG.netkan, NetKAN/GRAPES.netkan, NetKAN/LIME.netkan, NetKAN/MANGO.netkan, NetKAN/ORANGE.netkan, NetKAN/PEAR.netkan, NetKAN/PLUM.netkan, NetKAN/PRUNES.netkan, NetKAN/VertikalSpeedIndicator.netkan
I wanted to list the mods from #8555, but they're missing their original author.
Now both authors are listed.
=> Add FruitGoose as author to FruitGoose's mods

NetKAN/BuildingBlocker.netkan
I'm the author.
- https://github.com/HebaruSan/BuildingBlocker
- https://forum.kerbalspaceprogram.com/index.php?/topic/209927-112-building-blocker-v010/
=> Add Building Blocker

NetKAN/kOS-Astrogator.netkan
=> Add kOS-Astrogator.netkan

NetKAN/CustomCategories.netkan
Create and edit part categories in the VAB and SPH editors
=> Add Custom Categories

NetKAN/TourismExpanded.netkan
- https://github.com/phillo3/TourismExpanded
- https://forum.kerbalspaceprogram.com/index.php?/topic/210022-1123contract-pack-tourism-expanded/
Fixes #9370.
=> Add TourismExpanded

NetKAN/TourismExpanded.netkan
This is the bot-friendly version of KSP-CKAN/CKAN-meta#3111.
=> Update TourismExpanded name

NetKAN/SIMPLEXResources.netkan
Based on metadata submitted by @Qazerowl, who noted that the author intended to add this mod:
- https://spacedock.info/mod/2045/SIMPLEX%20Resources
- https://forum.kerbalspaceprogram.com/index.php?/topic/181056-1123-and-prior-simplex-resources-112/
Fixes #9380.
=> Add SIMPLEXResources

NetKAN/BluedogDB.netkan
Will merge once the update appears at:
https://spacedock.info/mod/442/Bluedog%20Design%20Bureau
___
=> Add BluedogDB deps

NetKAN/ShuttleOrbiterConstructionKitRecolored.netkan
- <https://forum.kerbalspaceprogram.com/index.php?/topic/195154-111x-shuttle-orbiter-construction-kit-recolored-version-13/>
- <https://spacedock.info/mod/2461/Shuttle%20Orbiter%20Construction%20Kit%20Recolored>
- <https://github.com/Invaderchaos/SOCK-Recolored>
Author gave the go-ahead via Discord PM:
Fixes #9392.
=> Add ShuttleOrbiterConstructionKitRecolored

NetKAN/EuropeanSpaceAgencyRocketKit.netkan
The structure of this ZIP has changed.
=> Update EuropeanSpaceAgencyRocketKit install

NetKAN/kOS-KerbalEngineer.netkan
See https://github.com/markjfisher/kOS-KerbalEngineer for mod, adds very small interface to KerbalEngineer
___
=> Add netkan for kOS-KerbalEngineer

NetKAN/LunarTransferPlanner.netkan
- https://github.com/KSP-RO/LunarTransferPlanner
Fixes #9407.
=> Add LunarTransferPlanner

NetKAN/BDArmoryExtended.netkan
- https://github.com/BrettRyland/BDArmory-Extended
Fixes #9412 (submitted by the author, @BrettRyland is just hosting).
=> Add BDArmoryExtended

NetKAN/DepthMask.netkan
I'm about to push a new version of DepthMask with a more standard distribution layout, so this is to update the NetKAN to match
- https://forum.kerbalspaceprogram.com/index.php?/topic/185353-111-112-moduledepthmask-portable-holes-for-your-parts/
- https://github.com/drewcassidy/KSP-DepthMask
- https://spacedock.info/mod/2943/ModuleDepthMask
=> Update DepthMask netkan file in preparation for next patch

NetKAN/WernhersOldBits.netkan
- This mod was looking for its folder in the root of the ZIP, but in the latest ZIP it's contained within a `GameData` folder
- While investigating I noticed there's a version file now, so a vref is added
=> Fix WernhersOldBits install

NetKAN/ShuttlePathfinderOrbiterConstructionKit.netkan
- https://forum.kerbalspaceprogram.com/index.php?/topic/210184-112xwipspock-shuttle-pathfinder-orbiter-construction-kit-stockalike-nuclear-shuttle-pathfinder-from-fam-v020/
- https://github.com/rogerwang86/SPOCK
[Author approval here.](https://github.com/KSP-CKAN/NetKAN/issues/9429#issuecomment-1312310081)
Fixes #9429.
=> Add ShuttlePathfinderOrbiterConstructionKit

NetKAN/NeidonPlus.netkan
#9446 updated the install for the 0.2.1 release, but now it's changed back.
=> Fix NeidonPlus install again

NetKAN/BDArmoryExtended.netkan
=> MM dep for BDArmoryExtended

NetKAN/KASAS1LoadingScreens.netkan
=> Update KASAS1LoadingScreens install

NetKAN/PlanetsideExplorationTechnologies.netkan
- <https://forum.kerbalspaceprogram.com/index.php?/topic/201439-112x-bg-planetside-exploration-technologies-surface-bases-nasa-mmsev-wind-turbines-more-v102/>
- <https://spacedock.info/mod/2681/Planetside%20Exploration%20Technologies>
- <https://github.com/benjee10/Benjee10_MMSEV>
Fixes #9386.
=> Add PlanetsideExplorationTechnologies

NetKAN/PlanetsideExplorationTechnologies.netkan
=> Move BreakingGround-DLC from depends to recommends for PlanetsideExplorationTechnologies

NetKAN/KARE.netkan, NetKAN/TeaKettleRCS.netkan
- <https://forum.kerbalspaceprogram.com/index.php?/topic/205810-1122-kare-11-dec-20-2022/&do=findComment&comment=4211920>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/204633-1122-tea-kettle-rcs-12-dec-22-2022/&do=findComment&comment=4211921>
=> Add recommends for two of JadeOfMaar's mods

NetKAN/SpaceY-Lifters.netkan
This mod's ZIP structure has changed.
=> Fix SpaceY-Lifters install

NetKAN/HyperDriveMod.netkan
<https://www.curseforge.com/kerbal/ksp-mods/simplehyperdrive>
Inspired by KSP-CKAN/CKAN-meta#3150.
=> Mark HyperDriveMod as version independent

NetKAN/Kerbulator.netkan
Closes KSP-CKAN/CKAN-meta#3166.
=> Update Kerbulator compatibility

NetKAN/HLS-Project.netkan
The folder structure has changed.
___
=> Fix HLS-Project install

NetKAN/ASETAgency.netkan
This mod has been adopted by a new maintainer.
- <https://spacedock.info/mod/3248/ASET%20Consolidated%20Agency>
- ~~<https://github.com/StoneBlue/ASET-Consolidated-Agency>~~ (deleted, or not public, or not created yet?)
=> Switch ASETAgency to new fork

NetKAN/RestockWaterfallExpansion.netkan
=> Added conflicts per @AtomicTech's  request

NetKAN/StarshipExpansionProject.netkan, NetKAN/StarshipExpansionProjectIVA.netkan
(author)
Reflecting the mod's most recent update, I would like to update the netkan to reflect the new state of the mod
note: on "recommends" section there is a new netkan specifically for the IVA portion of the mod, which will be PR shortly after this one
- <https://spacedock.info/mod/2959/Starship%20Expansion%20Project%20-%20SEP>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/206555-1101-112x-starship-expansion-project-sep-v101-january-30th-2022/>
- <https://github.com/Kari1407/Starship-Expansion-Project>
=> Update StarshipExpansionProject Metadata

NetKAN/MinmarKerbinRings-New.netkan
=> Fix MinmarKerbinRings-New install

NetKAN/AviationLights.netkan
- <https://spacedock.info/mod/3208>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/211781-*/>
- <https://github.com/net-lisias-ksp/AviationLights/>
See https://forum.kerbalspaceprogram.com/index.php?/topic/173305-112x-aviation-lights-v413-29-january-2023-available-for-adoption/&do=findComment&comment=4225479
=> Aviation Lights changed ownership.

NetKAN/EveOptimizedEngines.netkan
- <https://github.com/OhioBob/Eve-Optimized-Engines>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/136342-1122-eve-optimized-engines-v302/>
Fixes #9593.
Hi @OhioBob, we have been requested to add EveOptimizedEngines to CKAN. We only add mods to CKAN if it's OK with the author. Is this OK with you?
=> Add EveOptimizedEngines

NetKAN/FuelMyShip.netkan
- <https://github.com/SumGuyTwitches/FuelMyShip>
No license is mentioned, so it defaults to All Rights Reserved. Clarification requested.
Requested by author. Fixes #9592.
=> Add FuelMyShip

NetKAN/Kerbalism-FarFutureTechnologies.netkan, NetKAN/Kerbalism-SystemHeat.netkan
- <https://github.com/judicator/KerbalismSystemHeat>
Fixes #9607.
Hi @judicator, we have been requested to add Kerbalism SystemHeat to CKAN. We only add mods to CKAN if it's OK with the author. Is this OK with you?
=> Add Kerbalism-SystemHeat

NetKAN/VesselView.netkan
=> Remove VesselView dep on JSIPartUtilities

NetKAN/BDArmoryMultiplayer.netkan
- <https://github.com/jrodrigv/BDAMultiplayer>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/184167-191-bdarmory-continued-v134-bdarmory-multiplayer-09042020/>
This mod finally has a non-prerelease release.
Fixes #8634 (contains author approval).
=> Add BDArmoryMultiplayer

NetKAN/HUDReplacer.netkan
- <https://github.com/UltraJohn/HUDReplacer>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/216056-*>
Fixes #9651.
=> Add HUDReplacer

NetKAN/KcalbelohSystem.netkan
Requested by author in https://github.com/KSP-CKAN/NetKAN/pull/9657#issuecomment-1504675424
=> VertexMitchellNetravaliHeightMap dep for KcalbelohSystem

NetKAN/TUFX.netkan
getting this ready for the next release
=> TUFX now depends on shabby

NetKAN/RasterPropMonitor-Core.netkan, NetKAN/RasterPropMonitor.netkan
-switch to spacedock
-remove certain suggestions
-add DE_IVA and freeiva as recommendations
-copy all suggestions/recommendations to rpm-core
=> Update RPM metadata

NetKAN/ActiveStruts.frozen, NetKAN/ActiveStruts.netkan, NetKAN/CameraControllerNext.netkan, NetKAN/DockingFunctions.netkan, NetKAN/DockingPortNext.netkan, NetKAN/IR-ActiveStruts.netkan, NetKAN/IR-ConnectionSystem.netkan
IR-ActiveStruts
- <https://github.com/meirumeiru/IR-Active-Struts>
IR-ConnectionSystem
- <https://github.com/meirumeiru/IR-ConnectionSystem>
CameraController-Next
- <https://github.com/meirumeiru/CameraController-Next>
DockingFunctions
- <https://github.com/meirumeiru/DockingFunctions>
DockingPort-Next
- <https://github.com/meirumeiru/DockingPort-Next>
=> Add ActiveStruts, IR-ConnectionSystem, CameraController-Next, DockingFunctions, and DockingPort-Next

NetKAN/RealFuels.netkan
=> Update RealFuels.netkan to target new home of repo

NetKAN/NeptuneCamera.netkan
Fixes #9708.
Closes KSP-CKAN/CKAN-meta#3191.
=> Vref for NeptuneCamera

NetKAN/SRBWaterfallEffects.netkan
=> Update SRBWaterfallEffects install

NetKAN/RoverPack.netkan
=> Update RoverPack install

NetKAN/ChineseModPatches.netkan
- <https://github.com/tinygrox/KSP_Chinese_Patches>
Fixes #9684.
=> Add Chinese Mod Patches

NetKAN/WaterDrinker.netkan
- <https://github.com/Tantares/WaterDrinker/releases>
- <https://forum.kerbalspaceprogram.com/topic/218027-1125-waterdrinker-stockalike-propeller-engines-0308072023/>
Fixes #9724.
=> Add WaterDrinker

NetKAN/ChineseModPatches.netkan
=> Fix ChineseModPatches install

NetKAN/KcalbelohSystem.netkan
https://github.com/jcyuan06/Kcalbeloh-System/releases
___
=> asset_match for KcalbelohSystem

NetKAN/MinorPlanetSampling.netkan
- <https://github.com/DeltaDizzy/MinorPlanetSampling>
- <https://forum.kerbalspaceprogram.com/topic/218820-110-112x-minor-planet-sampling-v10-8-august-2023/>
Fixes #9754.
=> Add MinorPlanetSampling

NetKAN/SciFiVisualEnhancements.netkan
This mod was updated a while ago but is hosted on dropbox and so the netkan has to be updated manually. Thanks to @DeltaDizzy for letting us know on Discord.
<https://forum.kerbalspaceprogram.com/topic/151190-1122sci-fi-visual-enchancements-v-16-high-performance-alt-to-sve/?do=findComment&comment=4061180>
=> New release of SciFiVisualEnhancements

NetKAN/BluedogDB.netkan
=> Switch BluedogDB to GitHub

NetKAN/ScrapYard.netkan
https://github.com/zer0Kerbal/ScrapYard
https://spacedock.info/mod/1746/ScrapYard%20(SYD)
=> Add missing dependency for ScrapYard

NetKAN/TundraExploration.netkan
Changed "depends" & "recommends"
=> Updated TundraExploration.netkan

NetKAN/PersistentThrustNavigator.netkan
An adoption and significant rewrite/rebranding of SolarSailNavigator (see #1165, #1376, #8477).
- https://github.com/JarredEagley/PersistentThrustNavigator
- https://forum.kerbalspaceprogram.com/topic/107676-*/?do=findComment&comment=4152274
TODO:
Fixes #9488.
___
ckan compat add 1.10
=> Add PersistentThrustNavigator

NetKAN/StockAlarmClockDisabler.netkan
- <https://forum.kerbalspaceprogram.com/topic/219015-112x-stock-alarm-clock-disabler/>
- <https://github.com/UltraJohn/StockAlarmClockDisabler>
Fixes #9773.
=> Add StockAlarmClockDisabler

NetKAN/Trajectories.netkan
https://spacedock.info/mod/396/Trajectories#changelog
=> Add ToolbarController depends for Trajectories

NetKAN/BetterScreenMessages.netkan
- <https://forum.kerbalspaceprogram.com/topic/219077-112x-better-screen-messages/>
- <https://github.com/UltraJohn/BetterScreenMessages>
Fixes #9777, which has a pending follow-up question about the `settings.cfg` file.
=> Add BetterScreenMessages

NetKAN/PerSaveScreenshots.netkan
- <https://forum.kerbalspaceprogram.com/topic/219192-112x-per-save-screenshots-v10-1-september-2023/>
- <https://github.com/DeltaDizzy/PerSaveScreenshots>
Hey @DeltaDizzy, I made a folder to avoid cluttering people's GameData with more loose DLLs. Is that OK?
```
- GameData/PerSaveScreenshots/PerSaveScreenshots.dll
```
Fixes #9787.
=> Add PerSaveScreenshots

NetKAN/CameraControllerNext.netkan, NetKAN/InfernalRoboticsNext.netkan, NetKAN/KerbalJointReinforcementNext.netkan
CameraControllerNext: website added
- <https://forum.kerbalspaceprogram.com/topic/219271-cameracontroller-next/>
- <https://github.com/meirumeiru/CameraController-Next>
InfernalRoboticsNext: recommendation for CameraControllerNext added
=> website added, recommendation added

NetKAN/AstraRocket3TransporterErector.netkan
This mod's folder structure changed.
- <https://spacedock.info/mod/2896/Astra%20Rocket%203.0%20Transporter%20Erector%20(beta)>
- <https://forum.kerbalspaceprogram.com/topic/205673-112x-astra-launch-essentials-v110-beta-stockalike-astra-rocket-30-transporter-erector-mod/>
=> Update AstraRocket3TransporterErector install

NetKAN/PayloadRetentionSystemNext.netkan
https://github.com/meirumeiru/PayloadRetentionSystem-Next
=> new mod "Payload Retention System - Next"

NetKAN/FreeIva.netkan
heisenberg, deepfreeze, nearfuturelaunchvehicles
=> Add new supported mods to FreeIva.netkan

NetKAN/kOSPropMonitor.netkan
https://spacedock.info/mod/3473
I had asked permission to adopt this one years ago and forgot about it.  I reached out to dsonbill again more recently but he's pretty much vanished.
=> Point kOSPropMonitor at JonnyOThan's fork

NetKAN/SSTOProjectLPG.netkan
=> Vref for SSTOProjectLPG

NetKAN/BakerOperatingSystem.netkan
- https://github.com/SelfAwareMatter/BakerOS
- https://spacedock.info/mod/3052/Baker%20Operating%20System
This mod's ZIP structure chagned.
=> Update BakerOperatingSystem install

NetKAN/TundraExploration.netkan, NetKAN/TundraTechnologies.netkan
Updated both TundraExploration & TundraTechnologies with new dependencies/recommendations. (I hope I wrote everything correctly!)
=> Tundra mods netkan update

NetKAN/KOSHUD.netkan
=> Vref for KOSHUD

NetKAN/StarshipExpansionProjectIVA.netkan
=> MM dep for StarshipExpansionProjectIVA

NetKAN/RationalResourcesNuclearFamily.netkan, NetKAN/RationalResourcesRCSFamily.netkan
add b9partswitch as dependency
add any_of (classicstockresources, communityresourcepack) as dependency
remove classicstockresources from suggested
=> Update dependencies of RationalResources addons

NetKAN/Scatterer-config.netkan
This is #9865 for `Scatterer-config`.
=> Improve Scatterer-config's abstract

NetKAN/NavBallAdjustor.netkan
=> Navballadjustor

NetKAN/NavBallAdjustor.netkan
=> Vref for NavBallAdjustor

NetKAN/SaveConfirmationSound.netkan
=> Vref for SaveConfirmationSound

NetKAN/BluedogDB-CommunityCategoryKit.netkan, NetKAN/BluedogDB-Methalox.netkan, NetKAN/BluedogDB-RealNames.netkan
Fix #9885 
ckan compat add 1.12 1.11
=> Update BDB submodules to point at github instead of spacedock

NetKAN/ASETAvionics.netkan, NetKAN/ASETProps.netkan, NetKAN/B9-props.netkan, NetKAN/DE-IVAExtension.netkan, NetKAN/FreeIva.netkan, NetKAN/HabTechProps.netkan, NetKAN/KSAIVAUpgrade.netkan, NetKAN/MK12PodIVAReplacementbyASET.netkan, NetKAN/Mk1LanderCanIVAReplbyASET.netkan, NetKAN/Mk3ShuttleMidDeckIVARefurbished.netkan, NetKAN/NearFutureProps.netkan, NetKAN/ProbeControlRoomRecontrolled.netkan, NetKAN/QuickIVA.netkan, NetKAN/RasterPropMonitor-Core.netkan, NetKAN/RasterPropMonitor.netkan, NetKAN/Reviva.netkan, NetKAN/StarilexMk1NeedleIVA.netkan, NetKAN/StarshipExpansionProjectIVA.netkan, NetKAN/StationPartsExpansionRedux-IVAs.netkan, NetKAN/TDProps.netkan, NetKAN/ThroughTheEyesOfaKerbal.netkan, NetKAN/VesselView-UI-RasterPropMonitor.netkan, NetKAN/VexarpIVA.netkan, NetKAN/kOSPropMonitor.netkan
A `first-person` tag has just been added to https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags .
Now this tag is added to mods where it applies, as far as I can tell.
Fixes part of #9859, but we have other pieces to take care of after this.
=> Add first-person tag to known IVA mods

NetKAN/RationalResourcesParts.netkan
FYI to @JadeOfMaar and @JonnyOThan.
=> Update RationalResourcesParts relationships

NetKAN/BetterRocketDesigns.netkan
- <https://github.com/Bloodsucker/ksp-better-rocket-designs>
The latest ZIP as of when I tested was missing a folder for the mod, so the validation tools will probably fail. There was a pre-release that looked better which has since disappeared, so I assume it's still being worked on.
Fixes #9928.
=> Add BetterRocketDesigns

NetKAN/BetterRocketDesigns.netkan
=> Set name for BetterRocketDesigns

NetKAN/PrecursorsPlanetPack.netkan
- <https://spacedock.info/mod/2869>
- <https://github.com/WyattPetula/Precursors>
=> Update PrecursorsPlanetPack kref to GitHub

NetKAN/RocketMotorMenagerie.netkan
<https://forum.kerbalspaceprogram.com/topic/202266-112x-rocket-motor-menagerie-v110-stockalike-engine-pack/>
Fixes #9952.
=> Update RocketMotorMenagerie compatibility

NetKAN/SpaceY-Expanded.netkan
dependency is listed on curseforge
=> SpaceY-Expanded: add dependency on SpaceY-Corp

NetKAN/RSS-Adapter.netkan
- <https://github.com/Globul-Art/RSS_Adapter>
Hoping to figure out a clearer, more concise abstract.
Fixes #9949.
=> Add RSS-Adapter

NetKAN/RSS-Adapter.netkan
Updates from author as per https://github.com/KSP-CKAN/NetKAN/issues/9949#issuecomment-2002810911
=> Update RSS-Adapter relationships

NetKAN/FlyByWireSASMode.netkan
It points the ship towards a marker you control!
- <https://github.com/gotmachine/FlyByWireSASMode>
Fixes #9988.
=> Add FlyByWireSASMode

NetKAN/AlternisKerbolRekerjiggered.netkan
User name changed, repo moved to: <https://github.com/WhirligigGirl/Alternis-Kerbol-Rekerjiggered>
Noticed due to KSP-CKAN/CKAN-meta#3255.
=> Update AlternisKerbolRekerjiggered kref

NetKAN/EasyRobotics.netkan
- <https://github.com/gotmachine/EasyRobotics>
Does something for Breaking Ground robotics.
Fixes #10003.
=> Add EasyRobotics

NetKAN/RealChute.netkan
- Added dependency to [ClickThroughBlocker](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ClickThroughBlocker.netkan)
- Added dependency to [ToolbarController](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ToolbarController.netkan)
- ModuleManager moved to recommendation; MM patches are optional and not required for the mod to function
=> RealChute 1.4.9.0 update

NetKAN/ContractConfigurator-Constellations.netkan
This mod has added a version file.
=> Vref for ContractConfigurator-Constellations

NetKAN/CelestialHarmony.netkan
A new planet pack.
- <https://github.com/ProximaCentauri-star/Celestial-Harmony>
~~Need to resolve question at https://github.com/KSP-CKAN/NetKAN/issues/10024#issuecomment-2132296852 before merging.~~
Fixes #10024.
=> Add CelestialHarmony

NetKAN/KSP-AutoLoad.netkan
A new mod to auto-load save games at startup.
- <https://github.com/dazoe/KSP-AutoLoad>
Fixes #9982.
=> Add KSP-AutoLoad

NetKAN/EasyISP.netkan
A MM patch that increases specific impulse.
- <https://github.com/Tempus-superest/EasyISP>
Fixes #9983.
=> Add EasyISP

NetKAN/SRBWaterfallEffects.netkan
This mod has a new home according to the author.
- <https://github.com/dangaffa/RSMP>
Fixes #10038.
=> Unfreeze and update SRBWaterfallEffects

NetKAN/KerbinSideRemasteredTLA.netkan
- <https://forum.kerbalspaceprogram.com/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1332-laplace-ksp-2-support/?do=findComment&comment=4400436>
=> Remove unavailable dependency from KerbinSideRemasteredTLA

NetKAN/Bureaucracy.netkan
@R-T-B has adopted Bureacracy with @severedsolo's blessing.
- <https://github.com/R-T-B/Bureaucracy>
- <https://forum.kerbalspaceprogram.com/topic/191192-112x-bureaucracy-monthly-budgets-reimagined-17-01072024-under-new-management/?do=findComment&comment=4403263>
=> Switch Bureaucracy to new adopting fork

NetKAN/QuackPack.netkan
- <https://github.com/jamespglaze/QuackPack>
- <https://spacedock.info/mod/3136/QuackPack>
- <https://forum.kerbalspaceprogram.com/topic/210155-112x-kopernicus-quackpack-v120-an-inner-system-expansion/>
=> Update QuackPack dependencies

NetKAN/RustyStarShipyards.netkan
The other mod from #9522 had the same problem as in #10091. Now it's also fixed.
=> Fix RustyStarShipyards install

NetKAN/AvalanchePlumes.netkan
=> Avalanche: Add suggestions

NetKAN/ColdJsHeliCarrier.netkan
@ColdJ-KSP Let me know if this looks good
=> ColdJsHeliCarrier: add suggested mods

NetKAN/ROEngines.netkan, NetKAN/ROLib.netkan, NetKAN/ROSolar.netkan, NetKAN/ROTanks.netkan
Recommend RP-1, not RP-0 Legacy
=> Recommend/Suggest RP-1

NetKAN/B9-PWings-Fork.netkan
This is an update to add two test craft files to the stock craft.
This is dependent on the next version of PWings, which will be uploaded soon.  Please do not merge this, I'll do it once the new files are available
=> Install craft files for Pwings

NetKAN/ColdJsMilitaryPlanesF16.netkan
See https://github.com/KSP-CKAN/NetKAN/pull/9957#issuecomment-2282334702
=> Make ColdJsMilitaryPlanesF16 depend on ColdJsMilitaryPlanes

NetKAN/MinimalMainMenu.netkan
- <https://github.com/coldrifting/MinimalMainMenu>
- <https://forum.kerbalspaceprogram.com/topic/225747-112x-minimalmainmenu>
=> Add MinimalMainMenu

NetKAN/TundraExploration.netkan
I've changed the dependencies from Tundra Exploration so that it needs SmokeScreen.
___
ckan compat add 1.11 1.12
=> Changed dependencies TundraExploration.netkan

NetKAN/RecolorCollection-ExtraDockingPorts.netkan, NetKAN/RecolorCollection-MissingHistory.netkan, NetKAN/RecolorCollection-NearFuturePropulsion.netkan, NetKAN/RecolorCollection-NearFutureSpacecraft.netkan
- <https://github.com/ZZetho/TU_ExtraDockingPorts>
- <https://github.com/ZZetho/TU_MissingHistory>
- <https://github.com/ZZetho/TU_NearFuturePropulsion>
- <https://github.com/ZZetho/TU_NearFutureSpacecraft>
- <https://forum.kerbalspaceprogram.com/topic/225485-112x-recolour-collection>
Fixes #10120.
=> Add Recolor Collection

NetKAN/VABOrganizer-SheepDog.netkan
This is supplemental config for the mod from #10174.
- <https://github.com/Sheepdog2142/SDVABO_Support>
- <https://forum.kerbalspaceprogram.com/topic/225797-wip-sdvabo-vab-organizer-support-mod/>
Fixes #10178.
~~This will fail to inflate until [a release is created](https://github.com/Sheepdog2142/SDVABO_Support/releases).~~
Then it might fail if the spelling of the folder gets fixed in the meantime.
=> Add SheepDog's VAB Organizer configs

NetKAN/VABOrganizer-SheepDog.netkan
This mod's folder has changed since #10184.
=> Fix VABOrganizer-SheepDog install

NetKAN/Resurfaced.netkan
=> Recommend Deferred for Resurfaced

NetKAN/MassEffectDrive.netkan
- <https://github.com/Lucaspec72/Mass-Effect-Drive-Mod-KSP>
- <https://forum.kerbalspaceprogram.com/topic/218243-112x-mass-effect-drive-mod/>
Fixes #10209.
=> Add MassEffectDrive

NetKAN/Mk1LanderCanIVAReplbyASET.netkan
<https://spacedock.info/mod/3241/ASET%20Consolidated%20Stock%20Replacement%20IVAs>
=> Mk1LanderCanIVAReplbyASET depends on ASETAvionics

NetKAN/AviationLights.netkan, NetKAN/DistantObject-default.netkan, NetKAN/DistantObject.netkan, NetKAN/GPOSpeedPump.netkan, NetKAN/HooliganLabsAirships.netkan, NetKAN/KSP-Recall.netkan, NetKAN/KerbalAircraftExpansion.netkan, NetKAN/KourageousTourists.netkan
All of these are available on [archive org](https://archive.org/details/kspckanmods) anyway.
Thankyou.
=> Preventing the use of github by CKAN due development cycle constraints.

NetKAN/TweakScale-Redist.netkan, NetKAN/TweakScale.netkan
I missed these two from my last pull requests (see #10216). Trying to run things on working hours is not exactly the best way to do some things...
=> Removing github hosting from lisias' mods. Part2.

NetKAN/SterlingSystemsAgency.netkan, NetKAN/SterlingSystemsElectrics.netkan, NetKAN/SterlingSystemsElectricsFuelCell.netkan, NetKAN/SterlingSystemsElectricsPhotoVoltaic.netkan, NetKAN/SterlingSystemsEngines.netkan, NetKAN/SterlingSystemsEnginesAntimatter.netkan, NetKAN/SterlingSystemsEnginesFission.netkan, NetKAN/SterlingSystemsEnginesFusion.netkan, NetKAN/SterlingSystemsEnginesThermalNozzle.netkan, NetKAN/SterlingSystemsTankage.netkan, NetKAN/SterlingSystemsThermals.netkan, NetKAN/SterlingSystemsThermalsExotic.netkan, NetKAN/SterlingSystemsThermalsPower.netkan, NetKAN/SterlingSystemsUtilities.netkan, NetKAN/SterlingSystemsUtilitiesConstruction.netkan, NetKAN/SterlingSystemsWorldPower.netkan
New group of mods from @JadeOfMaar, indexing requested by author on Discord.
- <https://github.com/JadeOfMaar/SterlingSystems>
- <https://forum.kerbalspaceprogram.com/topic/219609-1125-sterling-systems-v0402-aug-14-2024/>
___
=> Add SterlingSystems family

NetKAN/Distantskies.netkan
https://forum.kerbalspaceprogram.com/topic/222840-v07-distant-skies-1125/?do=findComment&comment=4403122
Locally confirmed that you get kopernicus errors without these mods.
=> Distantskies: depends on kopernicus expansion and VertexMitchellNetravaliHeightMap

NetKAN/KerbalInfinity.netkan
per spacedock, locally confirmed too
=> KerbalInfinity depends on VertexMitchellNetravaliHeightMap

NetKAN/LazyPainter.netkan
Added `LazyPainter.version` at `GameData/LazyPainter/LazyPainter.version`.
Contents:
```
{
"NAME": "LazyPainter",
"URL": "https://raw.githubusercontent.com/Halbann/LazyPainter/master/GameData/LazyPainter/LazyPainter.version",
"DOWNLOAD": "https://github.com/Halbann/LazyPainter/releases",
"VERSION": {
"MAJOR": 0,
"MINOR": 3,
"PATCH": 1,
"BUILD": 0
},
"KSP_VERSION": {
"MAJOR": 1,
"MINOR": 12,
"PATCH": 5
},
"KSP_VERSION_MIN": {
"MAJOR": 1,
"MINOR": 10,
"PATCH": 0
}
}
```
=> Added a .version file to LazyPainter

NetKAN/NGC5679-Skybox.netkan
- <https://github.com/LittleBitMoreKSP/NGC-5679-Skybox>
- <https://forum.kerbalspaceprogram.com/topic/224646-ngc-5679-skybox-112x/>
Fixes #10243.
=> Add NGC5679-Skybox

NetKAN/RecolorCollection-ExtraDockingPorts.netkan, NetKAN/RecolorCollection-MissingHistory.netkan, NetKAN/RecolorCollection-NearFutureAeronautics.netkan, NetKAN/RecolorCollection-NearFutureLaunchVehicles.netkan, NetKAN/RecolorCollection-NearFuturePropulsion.netkan, NetKAN/RecolorCollection-NearFutureSpacecraft.netkan
- <https://github.com/ZZetho/TU_NearFutureAero>
- <https://github.com/ZZetho/TU_NearFutureLaunchVehicles>
- <https://forum.kerbalspaceprogram.com/topic/225485-112x-recolour-collection/>
Fixes #10237.
=> Add two more RecolorCollection mods

NetKAN/RSSOrigin-Less-Primary.netkan, NetKAN/RSSOrigin-Less-Secondary.netkan
- <https://github.com/Qazerowl/RSS-Origin-Less>
The releases have independent Primary and Secondary assets containing different planets.
Fixes #10254.
Fixes #10255.
=> Add RSSOrigin-Less

NetKAN/RealAntennas.netkan
There's a pre-release waiting. Ping me on discord once you're ready to merge it and I'll change the release status.
- <https://github.com/KSP-RO/RealAntennas>
=> Add new RealAntennas dep

NetKAN/StarshipExpansionProject.netkan
SEP might consider moving the Spaces folder inside the normal location in GameData.  the StarshipExpansionProjectIVA.netkan already can handle this, but we need to exclude it from this one.
=> StarshipExpansionProject: filter Spaces in case they move it

NetKAN/ContractConfigurator.netkan
=> Revert "ContractConfigurator: add dependencies on harmony and modulemanager"

NetKAN/BarkingOwl.netkan, NetKAN/ContractConfigurator-PlanesWithPurposes.netkan, NetKAN/KSPTOTConnect.netkan, NetKAN/ModuleAnimateDualGenerics.netkan, NetKAN/SmallRockets.netkan, NetKAN/kOSPropMonitor.netkan
This is a follow-up to #10308 addressing a few modules that got missed.
There will be inflation errors, so we'll have to settle for confirming that the inflation looks right for the modules that succeed.
=> Deduplicate properties

NetKAN/StarshipExpansionProject.netkan, NetKAN/StarshipExpansionProjectIVA.netkan
Heya, here’s the updated the SEP and SEP_IVA netkan files to remove relationships that are to be defined in internal .ckan files with the next pre-release at https://github.com/Kari1407/Starship-Expansion-Project/releases.
This pre-release is expected to go live in ~4 hours so if this would be merged after that, that’d be fantastic.
Thanks in advance.
=> Update StarshipExpansionProject NetKAN

NetKAN/ABCORS.netkan
changed abcors to pull from spacedock
=> changed abcors to pull from spacedock

NetKAN/TourismOverhaul.netkan
See https://github.com/KSP-CKAN/NetKAN/pull/10332#issuecomment-2564684058, this mod now depends on Strategia.
=> Strategia dep for TourismOverhaul

NetKAN/TourismOverhaul.netkan
Strategia is now optional for this mod.
Fixes #10352.
=> Update TourismOverhaul relationships

NetKAN/NodeHelper.netkan
Added missing dependency for toolbarController
=> Added missing dependency

NetKAN/kOS.netkan
this has always been a pain to maintain, let's just do it here.
=> kos: remove metanetkan

NetKAN/RocketSoundEnhancement-Config-Default.netkan, NetKAN/RocketSoundEnhancement.netkan
I've had like 3 separate people fail to install the config recently
=> RocketSoundEnhancement: require a config and make the default one provide it

NetKAN/Astrogator.netkan, NetKAN/ExtraDockingPorts.netkan, NetKAN/PrakasaAeroworks.netkan, NetKAN/SpaceY-Corp.netkan, NetKAN/WarpDrive.netkan, NetKAN/kOS.netkan
- ExtraDockingPorts
- PrakasaAeroworks
- SpaceY-Corp
- WarpDrive
- kOS
=> Add MM dependencies to several mods where they are missing

NetKAN/TheOutpost.netkan
The author has requested removal of this dependency:
- <https://forum.kerbalspaceprogram.com/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1332-laplace-ksp-2-support/?do=findComment&comment=4450744>
=> Remove CountryDoggosRandomKKBits dep from TheOutpost

NetKAN/OCCULT.netkan
=> Add OCCULT

NetKAN/OuterPlanetsMod.netkan, NetKAN/ScattererOPM.netkan
This mod aims to replace the outdated Pood's OPM-VO mod for OPM (see #5354).
- <https://github.com/AnisDjerrab/Scatterer-OPM>
=> add scattererOPM CKAN

NetKAN/RocketSoundEnhancement-Config-Default.netkan, NetKAN/RocketSoundEnhancement.netkan
ensou04 got dropped when we moved to the org unfortunately.
tempted to label this "fix relationships" :p
=> update RocketSoundEnhancement authors

NetKAN/ASETAvionics.netkan
- <https://github.com/FirstPersonKSP/ASET_Avionics>
- <https://spacedock.info/mod/3239/ASET%20Consolidated%20Avionics%20Pack>
=> ASETAvionics: transfer to FirstPersonKSP org

NetKAN/AutoVesselRenamer.netkan
- <https://forum.kerbalspaceprogram.com/topic/227614-1125-auto-vessel-renamer-100-no-more-vessels-with-the-same-name-08-april-2025/>
- <https://github.com/matteo-passeri/KSP-1.12.5-MOD___Auto-Vessel-Renamer>
Closes KSP-CKAN/CKAN-meta#3338 (submitted to the wrong repo).
=> Add AutoVesselRenamer

NetKAN/AutoVesselRenamer.netkan
The mod from #10484 was just uploaded at <https://spacedock.info/mod/3857/Auto%20Vessel%20Renamer>.
=> SpaceDock kref for AutoVesselRenamer

NetKAN/KerbalChecklists.netkan
=> Make KerbalChecklists depend on ClickThroughBlocker

NetKAN/RationalResources.netkan, NetKAN/RationalResourcesAluminium.netkan, NetKAN/RationalResourcesBlacksmith.netkan, NetKAN/RationalResourcesCompanion.netkan, NetKAN/RationalResourcesELUtilities.netkan, NetKAN/RationalResourcesJetFamily.netkan, NetKAN/RationalResourcesKerbalism.netkan, NetKAN/RationalResourcesKerbalismRF.netkan, NetKAN/RationalResourcesNuclearFamily.netkan, NetKAN/RationalResourcesParts.netkan, NetKAN/RationalResourcesRCSFamily.netkan, NetKAN/RationalResourcesSSPXRTanks.netkan, NetKAN/RationalResourcesSquad.netkan, NetKAN/RationalResourcesTACLS.netkan
Another mod author is giving up on updating SpaceDock due to the status 0 errors.
(I tried it myself, and it is indeed hopeless.)
=> Make RationalResources hosting GitHub-only

NetKAN/WasdMainMenu.netkan
- <https://spacedock.info/mod/3846/WasdMainMenu>
- <https://github.com/averageksp/WasdMainMenu>
=> Add GitHub hosting for WasdMainMenu

NetKAN/BAMCont.netkan, NetKAN/BOMPs.netkan, NetKAN/BOSSContinued.netkan, NetKAN/BargainRocketsCont.netkan, NetKAN/BetterLoadSaveGame.netkan, NetKAN/BetterScienceLabsContinued.netkan, NetKAN/BetterTimeWarpCont.netkan, NetKAN/BigBen.netkan, NetKAN/BobsPanicBox.netkan, NetKAN/BurstAtomicThrust.netkan
#7734 switched several of LGG's mods from SpaceDock to GitHub.
This PR multi-hosts them on both, to see whether it works.
=> Multi-host several of LGG's mods

NetKAN/OPXFinalFrontierRibbons.netkan
- <https://github.com/arbsoup/OPXFinalFrontierRibbons>
- <https://forum.kerbalspaceprogram.com/topic/227896-*>
Fixes #10548.
=> Add OPXFinalFrontierRibbons

NetKAN/KolonyConstructs.netkan
=> Update KolonyConstructs dependencies, multi-host

NetKAN/KerbalChecklists.netkan
Apparently this mod has a version file now.
=> Vref for KerbalChecklists

NetKAN/KerbalColonies.netkan
=> Remove two dependencies as not needed 

NetKAN/KerbalColonies.netkan
Thinking about what I have done.. I think it is better to change it from suggests (weak recommendation) to recommends (strong recommendation). Since you can't really do anything with only the Core and the Dev Team asked me if I could change it to that.
Their Plan is to have multiple configs so having it changed to recommends will be much better now.
=> Changed suggests to recommends (Kerbal Colonies Core)

NetKAN/TheScatteredDisk.netkan
- <https://github.com/axolliam/the_scattered_disk>
Fixes #10568.
=> Add The Scattered Disk

NetKAN/KerbalColonies.netkan, NetKAN/KerbalColoniesExtraplanetaryLaunchpadsConfig.netkan
The repos for KerbalColonies have moved or been renamed.
Now we reference the current URLs.
=> Update KerbalColonies krefs

NetKAN/ETT.netkan
<https://spacedock.info/mod/199/Engineering%20Tech%20Tree>
As per this mod's author via Discord:
=> New conflict for ETT

NetKAN/BoBSSPXTURecolor.netkan
- Added missing author to SSPX TU Recolor
=> Add Missing Author to SSPX TU Recolor

NetKAN/B9PartSwitch.frozen, NetKAN/B9PartSwitch.netkan
Unfreezes the mod and use the new fork ~~by Linuxgurugamer~~ on KSPModStewards
- <https://github.com/KSPModStewards/B9PartSwitch>
=> Unfreeze B9PartSwitch and switch to KSPModStewards fork

NetKAN/Blueshift.netkan
=> Add FireflyAPI dep to Blueshift

NetKAN/ChemicalExotics.netkan
ChemicalExotics has been merged into the download of ChemicalPropulsion, under its Extras folder.
=> Extract ChemicalExotics from ChemicalPropulsion

NetKAN/SterlingSystemsKerbalism.netkan
Adds Sterling Systems Kerbalism by JadeOfMaar
=> Add Sterling Systems Kerbalism

NetKAN/kOS-Computer.netkan, NetKAN/kOSComputer.netkan
https://forum.kerbalspaceprogram.com/topic/228209-kos-computer/
https://github.com/sinucep/kOS-Computer
fixes #10612
=> Add kOS-Computer

NetKAN/1ThousandSpecialPlanetPack-Textures.netkan
This mod's ZIP file structure has changed.
=> Update 1ThousandSpecialPlanetPack-Textures install path

NetKAN/KerbalJointReinforcementContinued.netkan
This mod is known to prevent KJR from working.
=> Add AnimatedAttachment to KerbalJointReinforcementContinued conflicts

NetKAN/PromisedWorldsDebdeb.netkan
- Changed the name from `Promised Worlds Core` to `Promised Worlds Debdeb`
=> Fix name in the PromisedWorldsDebdeb.netkan

NetKAN/PromisedWorldsCore.netkan, NetKAN/PromisedWorldsDebdeb.netkan
See #10704 for previous.
- New dependencies
- New install instructions
=> Fix installation for Promised Worlds

NetKAN/PromisedWorldsCore.netkan, NetKAN/PromisedWorldsDebdeb.netkan
The latest versions of the PromisedWorlds mods have version files.
=> Vrefs for PromisedWorlds

NetKAN/KerbalColonies.netkan, NetKAN/KerbalColoniesExtraplanetaryLaunchpadsConfig.netkan, NetKAN/KerbalColoniesIndustrialProcesses.netkan
Adding generic identifiers for KC configs and config expansions
=> Update KC metadata

NetKAN/TweakScale.netkan
=> Adding TweakScale Companion as Recomendation.

NetKAN/BonVoyage.netkan
Evidence on Forum.
https://forum.kerbalspaceprogram.com/topic/172447-ksp-1123-bon-voyage-141-2022-10-02/#findComment-3323818
- <https://spacedock.info/mod/3979>
- <https://github.com/net-lisias-ksp/BonVoyage>
Thank you.
=> Moving BonVoyage to Lisias's ownership

NetKAN/BetterDres.netkan
Change "Proxmia" to "Proxima" in the mod's title
Fixes #10738
=> Fix Proxima's Better Dres typo

NetKAN/PromisedWorldsCore.netkan
Soon the ScaledDecorator dependency will be bundled in Promised Worlds
Don't merge this for now.
- <https://github.com/PromisedWorlds/PromisedWorlds>
=> Handle bundled ScaledDecorator dep in Promised Worlds

NetKAN/PromisedWorldsCore.netkan, NetKAN/PromisedWorldsDebdeb.netkan
Changed Promised Worlds to Promised Worlds Core
and changed Promised Worlds to Promised Worlds Debdeb
=> Fix names in the Promised Worlds netkans

NetKAN/SCANsat.netkan
<https://github.com/KSPModStewards/SCANsat/releases/tag/21.0>
=> Work around SCANsat dropping v prefix on GitHub

NetKAN/PWLMPBases.netkan
- Added `Promised Worlds Dev Team` as authors
=> Changed author from Promised Worlds to Promised Worlds Dev Team in the LMPPW_Bases mod

NetKAN/PromisedWorldsCore.netkan
- Added KSPCommunityFixes as a dependency to Promised Worlds
=> Add KSPCommunityFixes as a dependency to Promised Worlds

NetKAN/CosmicSerenity-Anubis.netkan, NetKAN/CosmicSerenity-Core.netkan
Changes for @ProximaCentauri-star 's Cosmic Serenity 2.0 (fixes #10772 ):
- Add Cosmic Serenity - Anubis
- Add KSP Community Fixes as a dependency of Cosmic Serenity - Core
- Have Core recommend Cosmic Serenity - Anubis
=> Update metadata for Cosmic Serenity 2.0
