NetKAN/TestFlight.netkan, NetKAN/TestFlightConfigStock.netkan
These modules both try to install a zero-byte `Config\ignore.txt` file that shouldn't be there, see KSP-RO/TestFlight#191.
This prevents them from installing, since they depend on each other:
```
About to install...
* TestFlight 1.10.0.0 (cached)
* TestFlight Config Stock 1.10.0.0 (cached)
Module "TestFlight" successfully installed
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
If this problem re-occurs, then it maybe a packaging bug.
Please report it at:
https://github.com/KSP-CKAN/NetKAN/issues/new
Please including the following information in your report:
File           : GameData/TestFlight/Config/ignore.txt
Installing Mod : TestFlightConfigStock 1.10.0.0
Owning Mod     : TestFlight
CKAN Version   : v1.26.2
Your GameData has been …
```
=> Fix TestFlight installation

NetKAN/LaserDist.netkan
This module has a `$vref` and a `ksp_version` property. The latter has caused all of its versions to be stamped with a min version of 1.1.2 even though the forum thread just says 1.7.3.
Now the `$vref` shall reign supreme.
=> Remove redundant hard coded game version from LaserDist

NetKAN/TweakScale.netkan
See https://forum.kerbalspaceprogram.com/index.php?/topic/179030-14-tweakscale-under-lisias-management-2431-2019-0725/&do=findComment&comment=3642572 and subsequent; the default install stanza was finding `Extras/TweakScale` instead.
=> Updating TweakScale to cope with more than one folder on the package.

NetKAN/B9-PWings-Modified.netkan
B9-PWings-Modified says to use B9-PWings-Fork
https://forum.kerbalspaceprogram.com/index.php?/topic/126997-pluginsee-active-fork-b9-procedural-parts-modified/
Now CKAN will say the same thing thanks to the `replaced_by` property.
In addition, its game version range is incorrect. Its version file only has a min of 1.1.0, but  the max formerly went up to 1.1.2. I believe this was sourced from the remote version file, which I think was shared with B9-PWings-Fork. Later when that mod released new versions, the remote version file would have been updated and the max version was removed:
https://github.com/KSP-CKAN/CKAN-meta/commit/e5278aebe665ac82e880f944322a3650a912c513#diff-4d6fd65d832feab68871bca806c2bae1
Now it's back via an override.
Fixes #7329.
=> Fix B9-PWings-Modified versions and mark replaced

NetKAN/AJEExtendedConfigs.netkan
Another interesting versioning system...
My plan is to epoch all new versions (including the latest) twice,
and this weird `202` version once. Should get it sorted.
Also put a `x_netkan_force_v` in, so future capital `V` get converted to lower ones.
=> Epoch AJEExtendedConfigs

NetKAN/Spectra.netkan
Latest version is missing a `v`.
=> Force 'v' for Spectra

NetKAN/BonVoyage.netkan
Typo in latest version:
`0.5.0_-_Come_all_you_young_sailormen_listen_to_me`, most likely should be
`0.15.0_-_Come_all_you_young_sailormen_listen_to_me`
=> Epoch BonVoyage

NetKAN/TestFlightConfig-KerbalAtomics.netkan, NetKAN/TestFlightConfig-NFPropulsion.netkan, NetKAN/TestFlightConfig-NFSpacecraft.netkan, NetKAN/TestFlightConfig-Stock-S42.netkan, NetKAN/TestFlightConfigLibrary.netkan, NetKAN/TestFlightConfigStock.netkan
This PR adds `.netkan` files for the major TestFlight config packs in Starstrider42/TestFlight-Configs. 
Local testing shows that while the dependency metadata allows/forbids the correct combinations of mods, the conflict between `TestFlightConfig-Stock-S42` and the original `TestFlightConfigStock` is not handled consistently -- the latter sometimes displays on the relationship tab as "not indexed" (despite being blocked correctly), and CKAN won't let you switch between the two config packs without uninstalling TestFlight first. 😲 I'm not sure if that's a bug in CKAN's dependency resolution or in the `.ckan` files.
=> Add netkan files for new TestFlight configs.

NetKAN/KopernicusExpansionContinued-CometTail.netkan, NetKAN/KopernicusExpansionContinued-Common.netkan, NetKAN/KopernicusExpansionContinued-EVAFootprints.netkan, NetKAN/KopernicusExpansionContinued-EmissiveFX.netkan, NetKAN/KopernicusExpansionContinued-ProceduralGasGiants.netkan
KopernicusExpansionContinued is ten separate downloads for various features, indexed in #7247. Four of them install `KEX-Common.dll`, so if you try to install them together, you get a conflict for that file:
```
File : GameData/KopernicusExpansion/Plugins/KEX-Common.dll
Installing Mod : KopernicusExpansionContinued-EmissiveFX release-1.7.1-5
Owning Mod: KopernicusExpansionContinued-CometTail
CKAN Version : v1.26.4
```
Now `KopernicusExpansionContinued-Common` is added to install just that one file, and the other modules depend on this new module and skip installing the file themselves.
Fixes #7378.
=> KopernicusExpansionContinued-Common

NetKAN/Kerbalism-Config-ScienceOnly.netkan
A configuration pack that disables everything Kerbalism - everything but the science feature.
This has been requested quite a few times on the forum.
=> Added Kerbalism Science-Only configuration pack

NetKAN/CommunityDeltaVMaps.netkan
In #6686 we indexed CommunityDeltaVMaps, but this was a third party re-upload to SpaceDock. Another third party attempted the same with a new re-upload in #7390, possibly just to update the compatibility? It wasn't explained.
Now the original repo is used, and the compatibility is updated to match the forum thread's info of 1.3+. This way the authorship will be accurate, new versions will be detected, and the compatible game versions will be correct.
https://forum.kerbalspaceprogram.com/index.php?/topic/87463-13-community-delta-v-map-26
=> Use original repo and version info for CommunityDeltaVMaps

NetKAN/BlacklegIndustriesMMTantaresTACLS.netkan, NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan, NetKAN/OinkersSkybox.netkan, NetKAN/VersatileToolboxSystem-TACLSPack.netkan, NetKAN/VersatileToolboxSystem-USIPack.netkan
See KSP-CKAN/CKAN#2880, `install_to` paths that are not normalized can trigger a problem with repeating notifications of changed metadata in GUI.
This PR fixes several such values. There should still be a separate code fix to avoid this problem in the future, and probably another PR in CKAN-meta to fix any .ckan files that aren't addressed by this PR.
=> Normalize install_to paths

NetKAN/CustomPreLaunchChecks.netkan, NetKAN/KerbalKonstructs.netkan
Three versions ago, KerbalKonstructs added a new bundled mod in its download. This PR indexes it and adds it as a dependency. We will need an additional PR in CKAN-meta for two older KK versions.
=> Add CustomPreLaunchChecks, a KerbalKonstructs dependency

NetKAN/Firespitter.netkan, NetKAN/FirespitterCore.netkan, NetKAN/FirespitterResourcesConfig.netkan
@sarbian reports on Discord that Firespitter 7.13 is not built for KSP 1.8 (which includes a Unity upgrade and therefore mostly breaks compatibility across the board), but this commit marked the max KSP version as 1.8.9 back in August:
https://github.com/snjo/Firespitter/commit/d6ec90eb76f09a03a1858db85f745a1ad789018f
If we can confirm this, these overrides will set it back to 1.7.
=> Override Firespitter 7.13's max KSP version to 1.7

NetKAN/TestFlight.netkan, NetKAN/TestFlightConfigStock.netkan
Project itself is under the KSP-RO group which means that multiple people have write access to that repo. Recently people have wrongly thought that I'm the author of that mod. I find it better to give credits to the actual author of the mod who has done most of the work.
=> Update Author for TestFlight

NetKAN/ChakaMonkeyExplorationSystems.netkan
ChakaMonkeyExplorationSystems depends on KJR (original/Continued).
A user in the forum reported, that this keeps him from installing it together with InfernalRoboticsNext, which depends on KJRNext:
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1264-orion/&do=findComment&comment=3687555
A `"any_of": ["KerbalJointReinforcement", "KerbalJointReinforcementNext"]` relationship should solve this.
Rudolf Meier (the author of KJRNext) wrote, that CMES _should_ work with KJRNext, but he didn't test it.
Neither did I find anything about using it with KJRNext in CMES' forum thread.
And there's no answer by YANFRET yet.
@HebaruSan, can we still change the metadata? Or should we wait for a comment by YANFRET?
=> Allow KJRNext to drop in for KJRorig/cont for ChakaMonkeyExplorationSystems

NetKAN/DMagicScienceAnimate.netkan
DMagicScienceAnimate v0.22 is a recompile for 1.8 and does not work with previous ksp versions. This can be expected to be the case for all following versions of the mod.
=> DMagicScienceAnimate 1.8 demarcation

NetKAN/ProjectManager.netkan
ProjectManager v2.3 is a recompile for 1.8 and does not work with previous ksp versions. This can be expected to be the case for all following versions of the mod.
=> ProjectManager 1.8 demarcation

NetKAN/PartOverhaulsSETI.netkan, NetKAN/SETI-BalanceMod.netkan, NetKAN/SETI-CareerChallenge.netkan, NetKAN/SETI-CustomBarnKit.netkan, NetKAN/SETI-ProbeControlEnabler.netkan, NetKAN/SETI-RebalanceMaterialsGoo.netkan, NetKAN/SETI-RemoteTech.netkan, NetKAN/UnmannedBeforeManned.netkan, NetKAN/UnmannedBeforeMannedChallenge.netkan
With KSP-CKAN/CKAN#2915's newly strict validation of metanetkans, several mods have new errors:
> New inflation error for SETI-RemoteTech: spec_version v1.4+ required for install with 'find'
> New inflation error for SETI-CareerChallenge: spec_version v1.4+ required for install with 'find'
> New inflation error for SETI-RebalanceMaterialsGoo: spec_version v1.4+ required for install with 'find'
> New inflation error for PartOverhaulsSETI: spec_version v1.4+ required for install with 'find'
> New inflation error for Ringworld: spec_version v1.18+ required for license 'Unlicense'
> New inflation error for UnmannedBeforeMannedChallenge: spec_version v1.4+ required for install with 'find'
> New inflation error for UnmannedBeforeManned: spec_version v1.4+ required for install with 'find'
> New …
=> Fix spec_versions

NetKAN/DecalStickers.netkan
This mod currently has an error on the status page.
> Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
This is in reference to its version file. However, this mod does not have its own version file; rather, netkan is finding the version file of an embedded copy of Firespitter. (And the file contents are a 75 KB HTML document instead of a version file, hence the error.)
=> Remove DecalStickers' vref

NetKAN/ContractConfigurator-SCANsat.netkan, NetKAN/ControlLock.netkan, NetKAN/CoolRockets.netkan, NetKAN/EasyVesselSwitch.netkan, NetKAN/ExceptionDetector.netkan, NetKAN/KScale2.netkan, NetKAN/LayeredAnimations.netkan, NetKAN/NavBallsToYou.netkan, NetKAN/ReflectionPlugin.netkan, NetKAN/StockNoContracts.netkan, NetKAN/StockPlugins.netkan, NetKAN/StockRT.netkan, NetKAN/StockSCANsat.netkan
As noted in #4131, several mods are released under the Unlicense and should be marked that way. Now they are (and their `spec_version` is updated to `v1.18`).
In some cases, the Unlicense in fact was not used, so those are skipped or updated to their actual license. A few mods are switched from a `download` property to a `$kref`, have their `homepage` updated, etc.
Note that the Unlicense is just a specific version of public domain (it's one of the built-in choices on GitHub). Technically a mod released into the public domain and a mod using the Unlicense have the same terms and conditions. Since CKAN supports both `public-domain` and `Unlicense` as license values, I have opted to set any mod that specifically mentions "unlicense" as `Unlicense` and leave those simply stating "public …
=> Set Unlicense for applicable mods

NetKAN/DeepSpaceSurfaceHabitatUnitPack.netkan
The config files moved to a subfolder of `GameData/DSSHU` in the latest release, and as a result they were also picked up by the standard `"find":       "GameData/DSSHU"`, thus they were installed twice in the end.
=> Remove install stanzas for DSSHU config files

NetKAN/B9-PWings-Fork.netkan
B9 Pwings Fork is currently targeting Rafterman82's fork for 1.7.3 but jrodrigv (the previous dev/maintainer) has updated the upstream fork for 1.8.1
=> Revert B9 PWings back to 'jrodrigv' fork.

NetKAN/NewPolandBall.netkan
The NetKAN files conflict with each other on Windows machines, which leads to weird behaviour.
Give this one a new identifier.
Closes #7507
Changing the identifier of a mod should normally be avoided, but since this mod doesn't have too many downloads and no special relationships or anything, it should be mostly fine.
=> Rename PolandBall to NewPolandBall

NetKAN/BurnTogetherContinued.netkan, NetKAN/DestructionEffects.netkan, NetKAN/DistantObject-default.netkan, NetKAN/DistantObject.netkan, NetKAN/FerramAerospaceResearchContinued.netkan, NetKAN/GravityTurnContinued.netkan, NetKAN/HangarExtender.frozen, NetKAN/KerbalEngineerRedux.netkan, NetKAN/KerbalFlightIndicators.netkan, NetKAN/MapResourceOverlay.netkan, NetKAN/NehemiahEngineeringOrbitalScience.netkan, NetKAN/PilotAssistant.netkan, NetKAN/PlanetShine-Config-Default.netkan, NetKAN/PlanetShine.netkan, NetKAN/RCSLandAid.netkan, NetKAN/Science-Full-Reward.netkan, NetKAN/SemiSaturatableRW.netkan, NetKAN/TWR1.netkan, NetKAN/VenStockRevamp-Core.netkan, NetKAN/VenStockRevamp-NewParts.netkan, NetKAN/VenStockRevamp.netkan, NetKAN/VesselMoverContinued.netkan, NetKAN/VesselSwitcher.netkan
After KSP-CKAN/CKAN#2922 we include owners of parent repos on GitHub as authors, which makes some of the manually maintained author lists in netkans redundant. This PR removes them.
=> Prune redundant author lists

NetKAN/CrewLight.netkan
The leading `v` has been lost in the transition to @linuxgurugamer as new maintainer.
Epoch all new versions to maintain proper version sorting.
=> Epoch CrewLight

NetKAN/ChattererExtended.netkan
See KSP-CKAN/CKAN-meta#1537, this mod relies on Chatterer to perform its version-specific functions, and in theory it should be fine to support it on any version. This PR creates an override for that, so we can close that other PR while we decide whether this is a good idea.
Watch here to see if the author responds:
https://forum.kerbalspaceprogram.com/index.php?/topic/160545-142-chatterer-extended-more-kerbalized-chatter-for-chatterer-v06/&do=findComment&comment=3698839
=> Make ChattererExtended indefinitely compatible

NetKAN/Backports/Kopernicus.netkan, NetKAN/KSPInterstellarExtended.netkan
In KSP-CKAN/CKAN#2824 and KSP-CKAN/NetKAN-Infra#102, we are automating version "epoch" management so that mod versions will be interpreted in chronological order.
This is undesirable for a few mods, specifically those that sometimes intentionally release a lower version of a mod after a later version, for example to backport fixes to earlier game versions.
Now the following mods have `x_netkan_allow_out_of_order` set to true because they have a history of intentional/valid out of order releases:
- `Backports/Kopernicus`
- `KSPInterstellarExtended`
This will ensure that these mods will not be auto-epoched.
Note that this property is not in the spec yet, but it will be after KSP-CKAN/CKAN#2824 is merged. It is important to set it before then, though, to prevent backports from accidentally …
=> Set x_netkan_allow_out_of_order for backporting mods

NetKAN/KerbalJointReinforcementNext.netkan
This mod triggered the auto-epoch code, see KSP-CKAN/CKAN-meta#1561. The "Latest release" on GitHub is not the highest version:
Inflating the module produces v4.0.15, and we already have v4.1.15 indexed, so it looks like we have found a version in need of an epoch (see KSP-CKAN/CKAN#2824). This discussion addresses how this might happen:
- https://stackoverflow.com/questions/22822586/swap-latest-release-on-github
If this mod author is in the habit of manually manipulating git tags without paying special care to their timestamps **and** intends to release backports, this is likely to recur. Therefore this pull request excludes this mod from auto-epoching by setting `x_netkan_allow_out_of_order`.
Closes KSP-CKAN/CKAN-meta#1561.
=> Add x_netkan_allow_out_of_order for KerbalJointReinforcementNext

NetKAN/KerbalowAerospace.netkan, NetKAN/UnKerballedStart.netkan
These modules both intentionally released out of order versions. One was done to allow CKAN to index a (presumably missed) version:
The other is a backport:
This indicates that these authors understand how versioning works and are prepared to use it in creative ways to achieve specific goals. Therefore this PR disables auto-epoching for these modules.
Closes KSP-CKAN/CKAN-meta#1577.
Closes KSP-CKAN/CKAN-meta#1588.
=> Turn off auto-epoching for KerbalowAerospace and UnKerballedStart

NetKAN/BetterTimeWarpCont.netkan
This mod is maintaining two parallel release streams, so auto-epoching isn't needed.
Closes KSP-CKAN/CKAN-meta#1591.
=> Disable auto-epoch for BetterTimeWarpCont

NetKAN/DeployableBatteries.netkan
This mod releases intentional out of order backport versions, so auto-epoch isn't needed.
Closes KSP-CKAN/CKAN-meta#1592.
=> Disable auto-epoch for DeployableBatteries

NetKAN/GrannusExpansionPack-CommNet.netkan, NetKAN/GrannusExpansionPack-JNSQ.netkan, NetKAN/GrannusExpansionPack-Primary.netkan, NetKAN/GrannusExpansionPack.netkan
This is a planet pack with some optional components, originally grew out of GPP, now available in standalone mode but also with JNSQ compatibility.
Permission requested here, monitor for responses:
https://forum.kerbalspaceprogram.com/index.php?/topic/169664-173-grannus-expansion-pack-v111-7-dec-2019/&do=findComment&comment=3715014
Note Galileo88/Galileos-Planet-Pack/issues/59, which currently makes a functional GPPSecondary+GEP_Primary install impossible. Need GPPSecondary updated to actually install its needed files.
=> Add Grannus Expansion Pack

NetKAN/Kerbalism.netkan
A user on the CKAN Discord reported that Kerbalism showed this message on launch:
Sure enough, Kerbalism has code to check the loaded assemblies and look for specific ones it doesn't like:
https://github.com/Kerbalism/Kerbalism/blob/155d2b02c947c285163b116ca0b1aa5f2dc84736/src/Kerbalism/System/Settings.cs#L20
Kerbalism string | CKAN identifier | CKAN conflict?
--- | --- | ---
BackgroundResources | BackgroundResources | No
BackgroundProcessing | BackgroundProcessing | No
DynamicBatteryStorage | DynamicBatteryStorage | No
KolonyTools | UKS | Yes
TacLifeSupport | TACLS | Yes
Snacks | Snacks | Yes
USILifeSupport | USI-LS | Yes
Now the missing ones are added to the metadata. And tags are added.
=> Update Kerbalism conflicts and tags

NetKAN/Kerbalism-Config-Default.netkan, NetKAN/Kerbalism.netkan
Kerablism mod conflicts depend on what Kerbalism is configured to do. This moves the mod conflict definitions where they belong.
See also https://github.com/KSP-CKAN/NetKAN/pull/7546
=> Updated Kerbalism mod conflicts

NetKAN/Astrogator.netkan, NetKAN/Ringworld.netkan, NetKAN/SmartTank.netkan
Since #5234, #5717, and #6036, my mods have used metanetkans hosted on the mods' repos.
I think this sets a bad example for others who might look at them to see how to index a mod. Hosting a netkan directly in the main NetKAN repo has several advantages:
- I can run recursive grep searches to get basic info about them
- Easier maintenance by the CKAN team when we need to make a similar change to many mods at once
- Probably a slight performance improvement for netkan since one network call is cut out
- Automated validation scripts for pull requests when making changes
(And of course I can edit the main repo just as easily as my own nowadays, but that's not the case for most mod authors.)
Now my mods no longer use metanetkans, and they also have tags added.
Note that two of them are still …
=> Tag and de-metanetkan HebaruSan's mods

NetKAN/Mk2Essentials.frozen
This mod is hosted on CurseForge.
It uses a direct download link instead of asking querying API for it, which seems to be the reason why it still worked until a few days ago, whereas all other CurseForge mods stopped working a long time ago.
The mod [author announced](https://forum.kerbalspaceprogram.com/index.php?/topic/89875-104-mk2-essentials/&do=findComment&comment=3124227) that he no longer wants to maintain this mod a long time ago, and there is also a replacement for it by LGG. Very unlikely that we will ever see a new release.
He also changed the license to MIT, see the linked comment and the [mod page on CF](https://www.curseforge.com/kerbal/ksp-mods/mk2-essentials).
I changed it in the netkan too despite it being frozen, to reflect the last state before freezing.
=> Freeze Mk2Essentials

NetKAN/CLLS.netkan, NetKAN/KRnD.netkan, NetKAN/KSPDev-LogConsole.netkan, NetKAN/KSTS.netkan, NetKAN/KerbalSimpit.netkan, NetKAN/KerbalSports.netkan, NetKAN/LTechContinued.netkan, NetKAN/PlaneMode.netkan, NetKAN/ROEngines.netkan, NetKAN/RadioFreeKerbin.netkan, NetKAN/RecoverAll.netkan, NetKAN/SASS-DRP.netkan, NetKAN/SASS-ER.netkan, NetKAN/SASS-NH.netkan, NetKAN/SASS-OPM.netkan, NetKAN/SASS-RevJ.netkan, NetKAN/SASS-RevSS.netkan, NetKAN/SASS-SE.netkan, NetKAN/SASS-Saru.netkan, NetKAN/SASS-StockalikeNeptune.netkan, NetKAN/SASS-UL.netkan, NetKAN/StockalikeSolarSystem.netkan, NetKAN/surfacelights.netkan
Successor to #7575.
I was mildly concerned that metanetkans represent a loophole through which we might get odd or misspelled tags cluttering the tag list. This PR tags the remaining metanetkan modules in the main repo to discourage that.
OuterPlanetsMod is excluded because it is already setting tags, accurately. After this it will be the only mod tagged in a metanetkan.
=> Tag twenty-fourth group of mods

NetKAN/KerbalStats.netkan, NetKAN/ModularFuelTanks.netkan, NetKAN/SurveyTransponder.netkan, NetKAN/TalisarParts.netkan
taniwha.org is back up, and some of his mods are updated for KSP 1.8:
- https://forum.kerbalspaceprogram.com/index.php?/profile/57176-taniwha/
This PR makes the necessary manual updates. Exceptions:
- EarlyBird has a remote version file, but it's wrong, so [I pointed this out on the thread](https://forum.kerbalspaceprogram.com/index.php?/topic/162477-18-early-bird-020/&do=findComment&comment=3720010)
- ExtraPlanetaryLaunchpads is already updated in https://github.com/KSP-CKAN/CKAN-meta/commit/36fef24583eb739fdf225bb185c94869c1261604
- Kethane is still being worked on
Side changes:
- `download` replaced with `$kref` of type `http`
- Tags added
=> Manual updates for 1.8 for taniwha's mods

NetKAN/STMsFFRibbonPackExpeditionRibbons.netkan, NetKAN/ScienceRolesFinalFrontierRibbonPack.netkan
New inflation error for ScienceRolesFinalFrontierRibbonPack: Could not find GameData/STMRibbons entry in zipfile to install
New inflation error for STMsFFRibbonPackExpeditionRibbons: Could not find GameData/STMRibbons entry in zipfile to install
The ZIP for these mods used to have a GameData folder, now it doesn't.
GameData removed from install stanzas.
=> Fix ribbon mods install paths

NetKAN/ChakaMonkeyExplorationSystems.netkan
Spiritual successor to KSP-CKAN/CKAN-meta#1738.
ChakaMonkeyExplorationSystems currently depends on RasterPropMonitor-Core, however it uses RasterPropMonitorBasicMFD internally which is only provided by the full RasterPropMonitor module. Now it depends on that. Will update the historical versions afterwards.
=> Update RPM depends for ChakaMonkeyExplorationSystems

NetKAN/ASETProps.netkan, NetKAN/MK12PodIVAReplacementbyASET.netkan
In KSP-CKAN/CKAN-meta#1739, I updated the .ckans for these modules to reflect their actual compatibility based on their release dates and forum threads.
The bot reverted this in https://github.com/KSP-CKAN/CKAN-meta/compare/72936b2300...1465b9931e.
Now there's an override to make it stick.
=> Override some ASET compatibilities

NetKAN/SXTContinued.netkan
A user pointed out that this mod isn't on archive.org, which was a problem during SD's recent outage.
https://forum.kerbalspaceprogram.com/index.php?/topic/190040-161-173-rp-1-realistic-progression-one-v12/&do=findComment&comment=3723520
This is because the license is CC-BY-NC-SA-4.0, but we have it as "unknown". Now it's fixed and should go to archive.org.
=> Set SXTContinued license

NetKAN/Ariane6-RealFuels.netkan
Ariane6 and Ariane6-RealFuels share a `$kref` and don't override `name`.
Now Ariane6-RealFuels has a custom `name` and `abstract`.
=> Rename one of the modules currently called Ariane 6

NetKAN/ThrottleControlledAvionics.netkan
This mod errors out currently with an API rate limit exceeded message:
As usual with GitHub rate limit errors, little is known and much is mysterious, so we can only speculate. However, I noticed that if you open the path to the repo where the metanetkan is located:
https://github.com/qfeys/ThrottleControlledAvionics
It redirects to:
https://github.com/allista/ThrottleControlledAvionics
So allista must have changed his GitHub username at some point, and the API is accounting for that. Maybe GitHub doesn't like having to perform that redirection, and counts it against us somehow?
Now this module is updated to use the newer path for the metanetkan.
(I found no other occurrences of "qfeys" in NetKAN.)
=> Update username for ThrottleControlledAvionics metanetkan

NetKAN/Telemachus.netkan
See #7627; this module also has a rate limit error, and if you open its repo:
http://github.com/richardbunt/Telemachus
It redirects to:
https://github.com/KSP-Telemachus/Telemachus
This makes me think I might be on to something with this redirection hypothesis.
Now the kref uses the newer username.
=> Update username for Telemachus kref

NetKAN/KerbalOccupationColors.netkan
This mod has always had a broken .version file with a KSP_VERSION_MIN of 1.99999.99999. Its netkan started out in #7384 with an override to fix this, but it has an inflation error again now because a new version came out that doesn't match the override.
It doesn't look like Starwaster/Kerbal-Occupation-Colors#2 will be merged anytime soon, so this PR extends the override to cover the latest release. I didn't want to presume that future versions will be broken, so we'll have to continue extending the override if they are.
Also the override is wrong, it changes ksp_version_min and then deletes it. We'll fix that as well, and have to update the previous .ckan later.
=> Extend KerbalOccupationColors compatibility override

NetKAN/ManeuverD.netkan
@sarbian just pushed this module to master without a pull request, and thus with no validation. It has this inflation error:
```
Could not match version ManeuverD-1.0.0.0.zip with find pattern ^ManeuverD-(?<version>\d+\.\d+\.\d+)\.zip$
```
http://status.ksp-ckan.space/
The version has four pieces and the regex is only matching three.
Now it will match the fourth piece.
=> Fix ManeuverD version regex

NetKAN/ODFC-Refueled.netkan
ODFC-Refueled conflicts with OFDC, but it's supposed to be ODFC.
Aren't acronyms grand?
And ODFC-Refueled now `provides` ODFC as well, so depending mods don't need to be updated.
Closes #7640.
Closes #7641.
=> Fix misspelled conflict

NetKAN/ProceduralParts.netkan
In #7497 we switched to a new fork of ProceduralParts by the RealismOverhaul team. The RO team is unfortunately focusing on 1.7.3 backports due to Kopernicus limitations. Unfortunately the fork from #7487 had already indexed a version for KSP 1.8, which places an upper limit on the versions that those backports can use.
Since this mod is going to be releasing backports for the foreseeable future, it now won't be auto-epoched.
=> Turn off auto-epoching of ProceduralParts

NetKAN/RasterPropMonitor-Core.netkan, NetKAN/RasterPropMonitor.netkan
~~We're creating RasterPropMonitor-Legacy as part of a plan to fix an issue with how RPM is organized. The problem is this folder:~~
- `JSI/RPMPodPatches/BasicMFD`
This folder contains the multi-function display prop. But props should be in `JSI/RasterPropMonitor/Library/Props`.
The RasterPropMonitor-Core module is supposed to include the plugin and props, while RasterPropMonitor installs the IVAs. But RasterPropMonitor-Core only installs the `JSI/RasterPropMonitor` directory, so the MFD prop is in RasterPropMonitor instead.
The B9 and Deltaglider modules use the current paths of the MFD files directly, so the files cannot simply be moved without breaking these mods.
Now the `JSI/RPMPodPatches/BasicMFD` folder is installed by RasterPropMonitor-Core and excluded from RasterPropMonitor. …
=> New RPM fork

NetKAN/RasterPropMonitor.netkan
https://github.com/KSP-CKAN/NetKAN/pull/7608#issuecomment-577273818
The latest RPM download unintentionally included files from JSIPartUtilities, so those modules now conflict if you try to install both.
Now RasterPropMonitor won't install the files from JSIPartUtilities.
=> Filter JSIPartUtilities files out of RPM install

NetKAN/ALCORIVAPatch.netkan
ALCORIVAPatch is an IVA for ALCOR. Not much point in installing it without ALCOR.
Now it depends on ALCOR.
This will also allow us to test the fix in #7647.
=> Make ALCORIVAPatch depend on ALCOR

NetKAN/AlternisKerbolRekerjiggered.netkan, NetKAN/AutomatedScienceSampler.netkan, NetKAN/ContractConfigurator-CareerEvolution.netkan, NetKAN/CoolRockets.netkan, NetKAN/CraftHistory.netkan, NetKAN/CustomBulkheadProfiles.netkan, NetKAN/DMagicScienceAnimate.netkan, NetKAN/DebugStuff.netkan, NetKAN/Interkosmos.frozen, NetKAN/KerboKatzSmallUtilities-DailyFunds.netkan, NetKAN/KerboKatzSmallUtilities-DestroyAll.netkan, NetKAN/KerboKatzSmallUtilities-FPSLimiter.netkan, NetKAN/KerboKatzSmallUtilities-FPSViewer.netkan, NetKAN/KerboKatzSmallUtilities-KerbalScienceExchange.netkan, NetKAN/KerboKatzSmallUtilities-ModifiedExplosionPotential.netkan, NetKAN/KerboKatzSmallUtilities-PhysicalTimeRatioViewer.netkan, NetKAN/KerboKatzSmallUtilities-RecoverAll.netkan, NetKAN/KerboKatzSmallUtilities.netkan, NetKAN/KerboKatzUtilities.netkan, NetKAN/Kerbulator.netkan, NetKAN/MechJeb2.netkan, NetKAN/ModuleManager.netkan, NetKAN/NewTantares.netkan, NetKAN/NewTantaresLV.netkan, NetKAN/ProjectManager.netkan, NetKAN/RoverWheelSounds.netkan, NetKAN/SDHI-ServiceModuleSystem.netkan, NetKAN/SDHI-StrobeOMatic.netkan, NetKAN/SeparatorDestroyer.netkan
These netkans had staging enabled due to hard coded compatibility info.
After KSP-CKAN/CKAN#2970, the Inflator will do this automatically, so it no longer needs to be in the metadata.
=> Remove manual staging for hard coded compatibility

NetKAN/BDArmoryContinued.netkan
The authorship has changed from PapaJoesSoup to jrodrigv about a year ago.
The repository is still the same, but the forum thread has changed.
SpaceDock is also no longer used, so I removed that link. The thumbnail link still works fine, so I kept it.
=> Update BD Armory Continued forum thread

NetKAN/BeyondHome.netkan
This mod's metanetkan was just deleted in https://github.com/Gameslinx/BeyondHomePlanetMod/commit/0f3949be15c71dd507ad7e0e5789b6df3e571fa3.
The author seems enthusiastic about CKAN:
Now the metadata from the last copy of the metanetkan is copied into the netkan, restoring the mod. Note that the compatibility is likely to change from 1.7.3 to 1.8.1 with the next release, so we'll hold off on merging this till then to be sure.
=> De-meta BeyondHome

NetKAN/RSSTextures2048.netkan, NetKAN/RSSTextures4096.netkan, NetKAN/RSSTextures8192.netkan
The README.txt says:
```
Real Solar System Texture pack (DDS Edition) for KSP 1.3.1+ (RSS-Kopernicus)
```
Currently we have it as 1.3.0–1.7.
Now the lower bound is 1.3.1 and the upper bound us unlimited.
=> Update RSS-Textures compatibility

NetKAN/Spectra.netkan
A number of issues have arisen with respect to Spectra:
- It depends on EVE, Scatterer, TextureReplacer, and Kopernicus, but in principle a user could choose to install without those other mods and still get some value out of it
- It provides configs for EVE and Scatterer, but this is not reflected in the metadata
- It has a functional conflict with GreenSkullRevived (both attempt to install an EVA visor for TextureReplacer), but this is not discovered until you try to install both and get an error message
See also:
- https://forum.kerbalspaceprogram.com/index.php?/topic/159443-181-no-kopernicus-spectra-v123-visual-compilation-21th-march-19/&do=findComment&comment=3725981
- https://github.com/KSP-CKAN/NetKAN/issues/7662#issuecomment-582543252
- Now EVE, Scatterer, TextureReplacer, and …
=> Fix Spectra's relationships

NetKAN/SpaceplaneCorrections.netkan
The override limits it to KSP 1.3. This is long outdated, the SpaceDock entry now says 1.8.1.
This PR removes the override, so the version is pulled from SpaceDock. There's no AVC file present to use.
Not closing #7672 yet, there's another point open.
=> Remove version override for SpaceplaneCorrections

NetKAN/JNSQ-RibbonPack.netkan
#7264 added JNSQ, but if you install it alongside FinalFrontier, you'll get 263 errors like this:
```
[ERR 20:25:03.335] FF: cannot find image file '/media/DataTrove/Games/KSP-1.8.1/KSP_Data/../GameData/Nereid/FinalFrontier/Ribbons/Edna/SphereOfInfluence.png'
[ERR 20:25:03.337] FF: cannot find image file '/media/DataTrove/Games/KSP-1.8.1/KSP_Data/../GameData/Nereid/FinalFrontier/Ribbons/Edna/OrbitCapsule.png'
[ERR 20:25:03.337] FF: cannot find image file '/media/DataTrove/Games/KSP-1.8.1/KSP_Data/../GameData/Nereid/FinalFrontier/Ribbons/Edna/EvaSpace.png'
[ERR 20:25:03.338] FF: cannot find image file '/media/DataTrove/Games/KSP-1.8.1/KSP_Data/../GameData/Nereid/FinalFrontier/Ribbons/Edna/EvaOrbit.png'
[ERR 20:25:03.339] FF: cannot find image file …
```
=> Add JNSQ-RibbonPack

NetKAN/AlternateResourcePanel.netkan, NetKAN/BananaForScale-large.netkan, NetKAN/BananaForScale-small.netkan, NetKAN/BoxSat-prototypes.netkan, NetKAN/BoxSat.netkan, NetKAN/EntchenFlag.netkan, NetKAN/FMRS.frozen, NetKAN/HGR-Props.frozen, NetKAN/HGR.netkan, NetKAN/HullcamVDS.frozen, NetKAN/KSPTips.frozen, NetKAN/KerbalAdventure.frozen, NetKAN/KerbalAlarmClock.netkan, NetKAN/Mk2Essentials.frozen, NetKAN/PartWizard.frozen, NetKAN/ShipManifest.netkan, NetKAN/StationScience.netkan, NetKAN/StationScienceContinued.netkan, NetKAN/TransferWindowPlanner.netkan
I plan a feature in the client to display more resources in the mod info panel.
I wanted to see which resource types are actually used in the wild, and saw that there are `x_curse` and `x_preview` additional to `curse` and `x_screenshot`.
`curse` is proper part of the spec, `x_screenshot` not entirely (it's not mentioned in the list of allowed resources, but occurs in other places), but widely used. The spec could also need an update.
CKAN-meta has more to offer, a PR for it will follow.
I replaced every `x_curse` with `curse` and `x_preview` with `x_screenshot`.
before:
```
843 "homepage"
245 "repository"
59  "bugtracker"
17  "x_curse"
17  "kerbalstuff"
11  "x_screenshot"
9   "manual"
8   "spacedock"
8   "license"
3   "x_preview"
```
after:
```
843 "homepage"
245 "repository"
59 …
```
=> Clean up resource properties

NetKAN/KerbalFoundriesContinued.netkan
The latest KerbalFoundriesContinued adds a dependency on TexturesUnlimited. Now this is reflected in its netkan.
=> Add missing dep for KerbalFoundriesContinued

NetKAN/SmokeScreen.netkan
SmokeScreen is compatible with both KSP version 1.8 and 1.9
=> SmokeScreen - set compatibility with 1.8 and 1.9

NetKAN/AVP-2kTextures.netkan, NetKAN/AVP-4kTextures.netkan
See KSP-CKAN/CKAN-meta#1812 and KSP-CKAN/CKAN-meta#1813, these modules have a min game version of 1.2, but the forum thread says 1.8. Now the netkans are updated to match.
=> Update AVP textures to 1.8 compat

NetKAN/Spectra.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/159443-12-181-spectra-v124-visual-compilation-10th-february-20/&do=findComment&comment=3740161
> I found that Scatterer did not load properly with Spectra when I installed Scatterer from CKAN, but it did work when I installed manually.
https://forum.kerbalspaceprogram.com/index.php?/topic/159443-12-181-spectra-v124-visual-compilation-10th-february-20/&do=findComment&comment=3741753
> Spectra and Scatterer have been behaving weird with me when I installed via CKAN
Currently Spectra provides Scatterer-config as of #7663, but it does not actually contain complete configs. Instead it uses a ModuleManager patch to modify the default configs. So when CKAN installs Spectra without Scatterer-config, some things are missing.
Now …
=> Spectra shouldn't provide Scatterer-config

NetKAN/WindowShineTR.netkan
The GameData folder is gone, and the dependency is back to TextureReplacer.
A few fields are removed so they can be sourced from SpaceDock.
=> Fix WindowShineTR for new release

NetKAN/Kerbulator.netkan
See KSP-CKAN/CKAN-meta#1842, compatibility of this module is out of date.
=> Update Kerbulator compat

NetKAN/UNDOCKINATOR.netkan
Hard dependency added in Undockinator 1.1.  Previous versions don't need it.
=> Add ToolbarController and CTB dependency to UNDOCKINATOR

NetKAN/SmartActuation.netkan
GitHub does that when you rename a repo or move it to another user name.
Now the current user name is used.
=> Update kref for SmartActuation

NetKAN/BeyondHome.netkan
@Gameslinx made me aware of this problem on the /r/KerbalSpaceProgram Discord.
> "BeyondHome.netkan" says it provides a scatterer config but it needs to recommend the Scatterer config
Essentially, BH depends on scatterer being fully installed (Not just the DLL, the configs and sunflares too) to work, but saying that I provide a config causes CKAN to ignore scatterer's configs and sunflares
Looking at BH's code, this is indeed the case. It provides the sunflares for the added suns, but [only modifies](https://github.com/Gameslinx/BeyondHomePlanetMod/blob/ee77c403349218de1de47b6e3b2e4dcf32cf7fa3/GameData/BeyondHome/scatterer/config/Sunflares/Sunflares.cfg#L127-L144) the one for the stock sun.
The included `config.cfg` is [commented …
=> Don't provide Scatterer-sunflare and Scatterer-config with BeyondHome

NetKAN/PersistentRotation.netkan
The outer `PersistentRotation` folder is absent in the latest release.
Now we just look for `GameData/PersistentRotation`.
~~Also it has a version file, so a vref is added.~~
=> Fix PersistentRotation install

NetKAN/SpacedocksRedeployed.netkan
ZIP file structure changed, and there's a version file, and it uses ModuleManager syntax in some of the cfg files.
=> Fix SpacedocksRedeployed install

NetKAN/TestFlightConfig-Stock-S42.netkan
This PR marks the latest version (0.2.0) of the `TestFlightConfig-Stock-S42` config pack as compatible with KSP 1.9.
=> Increment KSP version for stock TF pack.

NetKAN/InfernalRoboticsRealismOverhaul.netkan
```
GameData/MagicSmokeIndustries/Parts/Legacy/IR_Gantry/gantrynorm.dds
Installing Mod : InfernalRoboticsRealismOverhaul 2.2.0
Owning Mod: InfernalRobotics-LegacyParts
CKAN Version   : v1.27.0
Your GameData has been returned to its original state.
Error during installation!
An unknown error occurred, please try again!
```
Now there's an explicit conflict relation between these mods.
Fixes #7747.
=> Conflict with InfernalRobotics-LegacyParts

NetKAN/ScottManleyHeadPack.netkan
The GitHub API does this when we access a repo that has moved.
Click here:
- http://github.com/messierr/SMHPContinued
It goes here:
- https://github.com/heirloom27/SMHPContinued
Now the current repo name is used.
=> Update ScottManleyHeadPack repo

NetKAN/SolarScience.netkan
Folder structure changed.
Also we can pull the homepage from SpaceDock.
And it has a version file now.
=> Fix SolarScience install

NetKAN/RoutineMissionManager.netkan
#7778 replaced this mod's license with `"x_netkan_license_ok": true,` for unspecified reasons.
Now the license is back.
=> Undelete RoutineMissionManager's license

NetKAN/SimpleLogistics.netkan
While investigating a hash mismatch for this mod...
https://forum.kerbalspaceprogram.com/index.php?/topic/191045-181-simplelogistics-2032-deployable-serenity-2020-03-20/&do=findComment&comment=3759431
... I noticed it has a version file but no vref. Now a vref is added, which also ought to update the hash.
=> vref for SimpleLogistics

NetKAN/LongMarch11CZ11.netkan, NetKAN/LongMarch5CZ5.netkan, NetKAN/Wanhu-Common.netkan
These mods were somehow included in the initial commits of #7749 and #7767, in what looks like a SpaceDock bug, see KSP-SpaceDock/SpaceDock#249. I removed them from those PRs so the primary mod of each could be indexed.
- https://spacedock.info/mod/2351/LongMarch-5%EF%BC%88CZ-5%EF%BC%89
- https://spacedock.info/mod/2362/LongMarch-11%EF%BC%88CZ-11%EF%BC%89
Now they have their own PR.
=> Add Long March mods from SpaceDock

NetKAN/BeyondHome.netkan, NetKAN/Scatterer-sunflare.netkan
Scatterer overrides the sunflare based on config in the `scatterer/config/Sunflares` folder.
The established way to provide a custom sunflare was to replace this folder, including one or more .cfg files defining `Scatterer_sunflare` config nodes. CKAN handles this by splitting the default sunflare into its own `Scatterer-sunflare` module, which is added to the `provides` list of any modules containing their own sunflares (see #3950). The user is then prompted to choose a sunflare when installing Scatterer.
Some mods instead choose to patch the default config nodes with ModuleManager. This only works if the default `Scatterer-sunflare` module is installed, which won't be the case if such a mod provides `Scatterer-sunflare` (see #7741).
Now the user is prompted to select a sunflare, but it …
=> Force default sunflare for BeyondHome

NetKAN/GPO.netkan
This is #7741 and #7794 for another mod by the same author, since it contains two files that assume a sunflare config is already installed:
GameData\GPO\scatterer\config\Sunflares\UrsaMinor
```
@Scatterer_sunflare:NEEDS[GPO]
{
```
GameData\GPO\scatterer\config\Sunflares\UrsaMinor\Ursa_L\Sun.cfg
```
@Scatterer_sunflare:NEEDS[GPO]
{
```
Might need to apply #7794 historically, depending on how up to date this is.
=> Sunflare fix for GameslinxPlanetOverhaul

NetKAN/HyperDriveMod.netkan
The first release of this mod installed into a folder called `HYPERMOD 2.4  10k SPECIAL`.
Now it's just the identifier, so we can use the default install stanza.
Also the author wants KER and TweakScale recommended, fixes #7806.
=> Fix install for HyperDriveMod

NetKAN/ProjectManager.netkan
KSP-CKAN/CKAN-meta#1889 has ProjectManager 2.4 compatible with KSP 1.8, but the release announcement says it's for 1.9.
=> Update ProjectManager compatibility

NetKAN/LithobrakeExplorationTechnologies.netkan
#2034 indexed this module with a dependency that isn't reflected on the forum thread, SpaceDock page, README, bundled mods, etc.
Now it's removed.
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3767463
https://forum.kerbalspaceprogram.com/index.php?/topic/117527-12-14-lithobrake-exploration-technologies-04-2016-10-12/&do=findComment&comment=3647761
=> Remove FirespitterCore depends from LithobrakeExplorationTechnologies

NetKAN/InfernalRoboticsNext.netkan
This mod's version file says it's compatible with KSP 1.4.0 and up, which is kind of impossible for a plugin, and consequently users have been reporting problems with it on recent versions on the forum thread. The author hasn't been responsive.
So far only one user has a specific recollection about the mod's actual compatibility: it worked up until Breaking Ground was released, which was with KSP 1.7.1. So now we will set the upper bound of compatibility to 1.6.
https://forum.kerbalspaceprogram.com/index.php?/topic/184787-infernal-robotics-next/&do=findComment&comment=3767687
FYI to @meirumeiru in case he's still active.
=> Override InfernalRoboticsNext max compat to 1.6

NetKAN/ColorCodedCans.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3769391
Confirmed; CCC uses MM patches to change the meshes of stock parts, which ReStock and Vens also do. Now it conflicts with those mods.
=> ColorCodedCans conflicts with mods that change stock tanks

NetKAN/AntaresCygnus.netkan, NetKAN/KKsDeltaPack.netkan, NetKAN/RN-MiscParts.netkan, NetKAN/RN-SalyutStations.netkan, NetKAN/RN-Skylab.netkan, NetKAN/RN-SovietProbes.netkan, NetKAN/RN-SovietRockets.netkan, NetKAN/RN-SovietSpacecraft.netkan, NetKAN/RN-USProbesPack.netkan, NetKAN/RN-USRockets.netkan
-Make ROxxx mods that change parts in the base mods conflict. These
should never be installed at the same time as they change the part names
of the existing meshes. This will break saves and craft files. You can
use one or the other, but not both sets of mods at once. It is already
set to conflict with ROcraftFiles, I just needed to make the cahnges
here also.
=> RN KK fix conflicts

NetKAN/BetterTimeWarpCont.netkan
#7734 removed the dependencies for BetterTimeWarpCont. Now they're back.
Fixes #7849.
=> Restore BetterTimeWarpCont dependencies

NetKAN/ModularLaunchPads.netkan
This mod has some missing dependencies:
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3776365
The forum thread also recommends KSCExtended:
https://forum.kerbalspaceprogram.com/index.php?/topic/173008-19x18x17x-modular-launch-pads-v208-launch-clamps-evolved-mix-and-match-parts-for-complete-launch-infrastructure-15-feb-2020/
ckan compat add 1.9.1
=> ModularLaunchPads dependencies

NetKAN/TantaresAndBDBNowinColors.netkan
https://forum.kerbalspaceprogram.com/index.php?/topic/168885-19x-tantares-and-bdb-now-in-colors/&do=findComment&comment=3777816
=> Remove outdated TantaresAndBDBNowinColors depends

NetKAN/Spectra.netkan
In #7663, we tried to set up Spectra's relationships to reflect its Scatterer config and sunflare files. However, this was wrong, because Spectra does **not** provide a full config as in #3950, but instead patches the default config as in #7741.
In #7706 we fixed that problem for the Scatterer-config side of things.
The sunflare relationship is still set up as if Spectra provided a full sunflare config, but instead it patches the default sunflare config, which then doesn't work.
Now Spectra uses the approach we started in #7794 to pull in the default sunflare.
(Replaces KSP-CKAN/CKAN-meta#1905.)
=> Force default Scatterer-sunflare for Spectra

NetKAN/ProbeControlRoom.netkan
A user reports that this mod's compatibility is too broad:
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1270-bussard/&do=findComment&comment=3779968
Now it's overridden to just the major version it was compiled for.
We can remove this if icedown/KSP-ProbeControlRoom#7 gets merged.
=> Override ProbeControlRoom compatibility

NetKAN/AstronomersVisualPack.netkan
In #6494 we stopped using this mod's GitHub version numbers because they were non-sequential, and started using the version file instead because they were forced to be more reasonable.
Now we have a release with an outdated version file, see themaster402/AstronomersVisualPack#16. Instead of being indexed on its own, 4.0.3 has replaced 4.0.2 and will need cleanup.
https://github.com/KSP-CKAN/CKAN-meta/commit/548803b3c76a0198d12b5dd2b234ccb702710ee5
With auto-epoching, we can now handle non-sequential versions more smoothly. This PR reverts to using the GitHub release version numbers.
=> Use GitHub version numbers for AstronomersVisualPack

NetKAN/CommNetAntennasConsumptor.netkan, NetKAN/CommNetAntennasInfo.netkan
Both mods had a backport recently:
https://github.com/KSP-CKAN/CKAN-meta/pull/1911
https://github.com/KSP-CKAN/CKAN-meta/pull/1910
They seem to have a reasonable and stable version history so far, so I think we can allow out of order releases for backports.
=> Allow OOO releases for CommNetAntennasInfo/-Consumptor

NetKAN/InterstellarFuelSwitch-Core.netkan, NetKAN/InterstellarFuelSwitch.netkan
InterstellarFuelSwitch bundles TweakScale and references it in code:
https://github.com/sswelm/KSP-Interstellar-Extended/blob/413b6815dfefad3023d9d3eca22da269464767db/FuelSwitch/InterstellarFuelSwitch.cs#L8
Discord user Aivech reports this exception on loading:
```
[ERR 18:40:41.076] AssemblyLoader: Exception loading 'InterstellarFuelSwitch': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
at System.Reflection.Assembly.GetTypes () [0x00000] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
at AssemblyLoader.LoadAssemblies () [0x000e6] in <2c9e31d65a604d1980fb0cb89728fc1e>:0 
Additional information about this exception: …
```
=> Add TweakScale depends to InterstellarFuelSwitch-Core

NetKAN/InterstellarFuelSwitch-Core.netkan
#7883 made TweakScale a depends, but I didn't notice it was already a recommendation.
Now the recommendation is removed.
=> Remove TweakScale rec from InterstellarFuelSwitch-Core (now a dep)

NetKAN/Spectra.netkan
I updated Spectra used this time to fix its NetKAN. I moved minor mods from Recommends to Suggests (added suggests), removed PlanetShine-config from Provides (No longer providing), removed GreenSkullRevived and PlanetShine-config from Conflicts (no longer conflicting), and removed Scatterer-sunflare-default from Depends (no longer depends).
I hope this looks in order, the file did not have suggests before this change, I added it from scratch based on the NetKAN of other mods. The goal is for all the mods in "recommends" to be auto-ticked when you install, and the mods in "suggests" to not.
I also reworked x_netkan_override. This might be set up incorrectly, though it doesn't matter as much as the rest. The current release of Spectra (1.3) is backwards compatible all the way to KSP version …
=> Sort and fix Spectra NetKAN Provides/conflicts/depends/suggests/rec

NetKAN/CEDA-Aethon-ITS.netkan
I thought this wasn't indexed, but apparently it's SpaceXLegs.
=> CEDA-Aethon-ITS recommendation

NetKAN/HooliganLabsAirships.netkan
There's a GameData folder now.
=> Fix HooliganLabsAirships install

NetKAN/ASETAvionics.netkan
This mod's forum thread announces no game version limitations, since in principle it's just data files that are used by other mods. It has such limits in the metadata because it's on SpaceDock. However, the mod version dependencies have changed.
=> Make ASETAvionics compatible with all game versions

NetKAN/ASETProps.netkan
See #7908, these are also just data files that can be used on any game version where the dependencies are available.
There is a "plugin", but it's an oddity with no code or references, supposedly just so ModuleManager can print out the version number. Should be version independent.
=> Make ASETProps compatible with all game versions

NetKAN/PlanetWiki.netkan
> Could not find GameData/planetwikiv[0-9]*.ksp entry in zipfile to install
The mod has a very inconsistent file naming scheme. What has been `planetwikiv4.ksp` is now `PlanetWiki_v4.1.ksp`.
To save us from even more future fix-ups, I decided to go with a "just get everything that looks like it could belong to the mod"-regex:
`"GameData/.*\\.ksp"`
Since it also completely broke the version ordering with the previous release (ironically named `making_CKAN_happy`), I epoched it.
I also moved the mod contents into its own `GameData/PlanetWiki` subfolder for installation.
=> Fix PlanetWiki find regex and epoch, move contents to own folder

NetKAN/SpaceXLaunchVehicles.netkan
A new folder was added at some point and isn't being installed, which makes the mod not work correctly. Also the readme recommends several mods.
Now the install is complete and the recommended mods are updated.
=> Fix SpaceXLaunchVehicles install and recommends

NetKAN/SeparatorDestroyer.netkan
See https://github.com/KSP-CKAN/CKAN-meta/pull/1922
The compatibility history in CKAN is a bit messed up and not matching SpaceDock's data.
I suspect they are like this:
| Mod version | KSP range |
| ----------- | --------- |
| 1.0.0.0     | 1.2.2 - 1.3 |
| 1.0.0.1     | 1.3 - 1.7 |
| 1.0.2.0     | 1.8.0     |
This PR removes the hardcoded `ksp_version` so netkan pulls it from SpaceDock for the latest and future versions. A CKAN-meta PR will follow changing the two older versions to how I listed it above.
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/1922
=> Remove hardcoded ksp_version from SeparatorDestroyer

NetKAN/LanderCanMk12.netkan
Forum user Krzeszny [made us aware](https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1272-chandrasekhar/&do=findComment&comment=3789751) of a [comment from the mod author](https://forum.kerbalspaceprogram.com/index.php?/topic/165240-181-landercan-mk12-v20/&do=findComment&comment=3789564) about wrong relationships:
> I'm not sure how it ended up on CKAN, and have even less of a clue on why it should be depended on anything other than module manager.
I suspect they have been correct for version 1.0 which bundled `JSIPartUtilities` and `Mk1CockpitIVAReplbyASET`, but the mod no longer bundles them:
This PR removes these two relationships and only keeps the ModuleManager one.
---
[SpaceDock …
=> Remove outdated LanderCanMk12 dependencies

NetKAN/JanitorsCloset.netkan, NetKAN/KerbalActuators.netkan
Next pass of #7936.
Most of the remaining warnings are caused by syntax errors.
=> Add ModuleManager depends for sixth pass of mods using MM syntax

NetKAN/SciRev.netkan, NetKAN/WhirligigWorld.netkan
This mod's dependencies have changed since it was indexed in #7116.
- KopernicusExpansion dependencies are removed (will need historical updates back to 0.12)
- SciRev dependency is added (will need historical updates back to 0.10.0)
I have a PM in progress to see if there are any other known issues.
@StollD, is it OK with you if we index SciRev in CKAN?
=> Update Whirligig World dependencies

NetKAN/CollisionFXReUpdated.netkan
> GameData directory found within GameData: GameData/CollisionFXReUpdated/GameData/CollisionFXReUpdated
This mod needs a custom install stanza, because the latest release changed the folder structure from `CollisionFX-ReUpdated/GameData/CollisionFXReUpdated` to `CollisionFXReUpdated/GameData/CollisionFXReUpdated`, so the default stanza is now ambiguous.
After adding the new install stanza, the inflations now throws a warning:
> WARN CKAN.NetKAN.Transformers.AvcTransformer (null) - Error parsing remote version file https://forum.kerbalspaceprogram.com/index.php?/topic/193803-19x-collisionfx-reupdated-100-12thmay2020//: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
I wanted to do a PR to fix this but the [GitHub …
=> Fix CollisionFXReUpdated install stanza

NetKAN/CST100Starliner.netkan
The ZIP contains a `Ships` folder with one craft file in it, with no VAB or SPH subfolder.
Metadata:
```json
"find":       "Ships",
"install_to": "Ships",
"as":         "VAB"
```
| Mod version | Ships folder path in ZIP |
| --- | --- |
| 2.0 | `/CST-100 Starliner/Ships/` |
| 2.1 | `/Ships/` |
The `as` property isn't allowed if the install stanza is trying to install just `Ships` in the root of the ZIP. The reason for this is a bit fishy but also somewhat complex to sort out.
We could monkey with the C# code (and still may), but that won't help users trying to install this with the current client. So now we match the file instead of the folder.
=> Fix CST100Starliner install

NetKAN/WhirligigWorld.netkan
We didn't have it as providing an EVE config. I took a look and it really does create a bunch of EVE_* nodes, not just patch existing ones.
Also it edits the default Scatterer sunflare, so we need that workaround as well.
=> Mark WhirligigWorld as providing EVE config

NetKAN/KScale2.netkan, NetKAN/OPTSpacePlaneMain.netkan, NetKAN/SSRSS-Rescale.netkan, NetKAN/newReactionWheels.netkan
These mods have vrefs but no version files. Now the vrefs are removed.
The other mods with this error:
- Have a version file but the extension isn't all lowercase (`.VERSION` or `.Version`)
- Amusingly these also have glaring syntax errors, so skipping the file is helping them
- Used to have a version file but dropped it and hopefully will bring it back
=> Remove unnecessary vrefs

NetKAN/RealFuels-Stock.netkan, realfuels-stock
Tested on 1.8.1, It should do following, install RealFuels-Stock with its dependencies MM and RF the mod provides RealPlumeConfigs & RealFuels-Engine-Configs, on install it recommends RealPlume, but conflicts with RealPlume-Stock and the old RFStockalike.
=> Add RealFuels-Stock to CKAN

NetKAN/SpaceXLaunchVehicles-StockSize.netkan, NetKAN/SpaceXLaunchVehicles.netkan
This mods has multiple `Ships/VAB/` folders in the zip, one in the zip root for "normal" installations, and one under `Rescaled` for real-sized crafts.
Both can potentially get matched by the `"find": "Ships/VAB"` stanza.
While the current CKAN version seems to always pick the correct one, I found out about this because I am currently using a ckan.exe compiled from the branch of https://github.com/KSP-CKAN/CKAN/pull/3064.
That one tries to install both folders, which fails because there are identically named files in them.
Change the `"find": "Ships/VAB"` to a `"file": "Ships/VAB"` to make it unambiguous and only install the stock-sized crafts.
I think this needs a historic backport too.
=> Make sure the right Ships/VAB folder is installed for SpaceXLaunchVehicles

NetKAN/BluedogDB.netkan, NetKAN/DiRT.netkan, NetKAN/SpearofLonginus.netkan, NetKAN/StockPlugins.netkan
After KSP-CKAN/CKAN#3064, we have a variety of new errors to address.
This PR fixes the ones that have an extra folder with the same name as the main one to install.
Historical versions of this fix should be done before v1.28.0 is released.
=> Filter duplicate folders

NetKAN/KWSKerbalWeaponsSystem.netkan
This is a follow-up to #7969, there was never any need to use a regexp here because `find` matches whole folder names. I just didn't know what I was doing in #6019.
This change should also be applied historically before the full release of v1.28.0.
=> Fix KWS install

NetKAN/RecycledPartsAtomicAge.netkan, NetKAN/RecycledPartsFarscape.netkan, NetKAN/RecycledPartsRSCapsuledyne.netkan
RecycledParts contains 3 crafts.
Craft file | Modded parts | Mod
:-- | :-- | :--
A Nuke Cruiser-Skalou-03.craft | NuclearJetEngine | RecycledPartsAtomicAge
Farscape 1.craft | MNZFarscape MNZFarscapeWingLH MNZFarscapeWingRH MNZFARENG MNZFarscapeGearNose MNZFarscapeGearLH MNZFarscapeGearRH | RecycledPartsFarScape
Farscape (Hetch).craft | MNZFarscape MNZFarscapeWingLH MNZFarscapeWingRH MNZFARENG MNZFarscapeGearNose MNZFarscapeGearLH MNZFarscapeGearRH | RecycledPartsFarScape
Currently RecycledPartsRSCapsuledyne installs the craft files, even though it doesn't provide the modded parts they need. Now that's removed.
Currently RecycledPartsAtomicAge doesn't install any craft files, even though that's what A Nuke Cruiser-Skalou-03.craft is for. Now it installs that file.
Currently …
=> Fix RecycledParts craft installs

NetKAN/Stock-Scatter-Collider-Enabler-Patch, NetKAN/StockScatterColliderEnablerPatch.netkan
I think the NetKAN file I have remotely hosted is correct. If not, please let me know here and I'll rectify it before this merge.
https://raw.githubusercontent.com/Poodmund/Stock-Scatter-Collider-Enabler-Patch/master/CKAN/SSCEP.netkan
=> Add SSCEP NetKAN metadata to the index

NetKAN/TestLite.netkan
I was browsing [RP-0's mod recommendations wiki], and it mentions a few mods that aren't in CKAN, such as "TestLite", a replacement for TestFlight tailored to the needs of RP-0.
- https://github.com/KSP-RO/RP-0/wiki/TestLiteVsTestFlight
Now TestLite would be available in CKAN, and RP-0 can update their metanetkan to suggest it.
~~**NOTE**: Author permission not yet acquired, submitting this mostly to check out the validation to confirm whether it will work. Please do not merge unless/until @ec429 gives us the go-ahead.~~
Once this is merged, we can start a PR to add it here:
- https://github.com/KSP-RO/RP-0/blob/master/RP-0.netkan
[RP-0's mod recommendations wiki]:  https://github.com/KSP-RO/RP-0/wiki/Recommended-Extra-Mods
=> Add TestLite

NetKAN/Spectra.netkan
The TextureReplacer and KSPRC folders are removed in the latest release, and the release announcement says Kopernicus is no longer needed.
=> Fix Spectra install

NetKAN/MissionController2.netkan
The folder is renamed in the latest release.
=> Fix MissionController2 install

NetKAN/ResourceMonitors.netkan
This is the only mod with the `flight` tag. If we want to have this tag, we need to analyze the existing mods and figure out which ones belong in it.
Now it's removed.
=> Remove flight tag from ResourceMonitors

NetKAN/Grannus-RibbonPack-FromGEP.netkan, NetKAN/Grannus-RibbonPack-FromGPP.netkan, NetKAN/GrannusExpansionPack.netkan
GPP and GrannusExpansionPack can't be installed together even though that's what GrannusExpansionPack was designed for.
Both modules install ribbons for Grannus, a CelestialBody that they share.
- Grannus-RibbonPack-FromGEP installs the ribbons from GEP
- Grannus-RibbonPack-FromGPP installs the ribbons from GPP
- GrannusExpansionPack no longer installs the ribbons itself
- GrannusExpansionPack recommends Grannus-RibbonPack, which both of the ribbon pack modules provide
- Galileo88/Galileos-Planet-Pack#64 will make the same filtering and relationship changes to GPP
This way a user installing GPP can install the ribbons from GPP, a user installing GEP can install the ribbons from GPP, a user installing both GPP and GEP can pick randomly, and nobody has to download a 300+ MB mod they're not …
=> Split out Grannus ribbons

NetKAN/StockishProjectOrion.netkan
This mod doesn't have its own version file. We were using the one from its bundled copy of CommunityResourcePack.
Also now installing its ships.
=> Remove StockishProjectOrion vref

NetKAN/EarlyBird.netkan
EarlyBird's netkan has not `author` specified, and since it has a `#/ckan/ksp-avc/` kref it doesn't autogenerate it.
Now I added "taniwha" as author.
=> Add author to EarlyBird

NetKAN/AQSS.netkan
Similar to #8025, no other mod has this tag, let's not start new categories by accident.
=> Remove utility tag from AQSS

NetKAN/KerbalConstructionTime.netkan
https://github.com/linuxgurugamer/KCT/commit/d076e1b7d5608340a199d6b50348e38856e54477#diff-591541463655671910e84e570d967cd4
Now the missing dependency is added. FYI to @linuxgurugamer.
=> Add SpaceTuxLibrary depends to KerbalConstructionTime

NetKAN/DSEV.netkan, NetKAN/Heisenberg.netkan, NetKAN/MOLE.netkan
#8057, #8058, and #8060 indexed these mods with incorrect install paths (missing the WildBlueTools parent folder). Now they're fixed. As well the license is set to reflect that the assets are All Rights Reserved, and the relationships are updated to match the ZIPs and forum threads.
=> Fix new Angel-125 installs

NetKAN/OPTReconfig.netkan, NetKAN/OPTSpacePlaneMain.netkan, NetKAN/OPTSpacePlaneParts.netkan
This is kind of a successor to #8081. Request from author:
> 7 hours ago, JadeOfMaar said:
> Hey LGG. Someone just pointed out that OPT Reconfig is dependent on Legacy. That needs to change. Related, I'd like these changes to happen too, including add/update of abstract, update of tags for Legacy, and if possible, changes to name (not identifier). Legacy's CKAN/SpaceDock name is absurdly long.
> 
> (Unlisted items, like Reconfig's conflicts, don't need to be touched.)
> 
> Reconfig
> ```json
>     "depends": [
>         { "name": "ModuleManager" },
>         { "name": "B9PartSwitch"  }
>     ],
>     "recommends": [
>         { "name": "CommunityResourcePack" },
>         { "name": "OPTSpacePlaneMain" }
>     ],
>     "supports": [
>         { "name": "ClassicStockResources" },
> …
```
=> Update OPT relationships

NetKAN/KSP-Recall.netkan
Yep, now it work around the heading drifting of parked crafts on KSP 1.8 and newer :) 
(does not fixes the drift induced by the wheels and landing legs - yet)
=> Updating the description of the Add'On. Stating the current need of Module Manager 4.0.2 at minimum.

NetKAN/KopernicusExpansionContinued-CometTail.netkan, NetKAN/KopernicusExpansionContinued-Common.netkan, NetKAN/KopernicusExpansionContinued-EVAFootprints.netkan, NetKAN/KopernicusExpansionContinued-EmissiveFX.netkan, NetKAN/KopernicusExpansionContinued-ModularNoise.netkan, NetKAN/KopernicusExpansionContinued-ProceduralGasGiants.netkan, NetKAN/KopernicusExpansionContinued-ReentryEffects.netkan, NetKAN/KopernicusExpansionContinued-RegionalPQSMods.netkan, NetKAN/KopernicusExpansionContinued-VertexHeightDeformity.netkan, NetKAN/KopernicusExpansionContinued-VertexHeightMap.netkan, NetKAN/KopernicusExpansionContinued-Wormholes.netkan
#7247 indexed these modules with no compatibility set, even though they're almost all plugins. Now they don't work.
Now they're set to KSP 1.7, based on the release numbering:
=> Set compatibility for Kopernicus Expansion Continued

NetKAN/TestFlight.netkan
@JonnyOThan made me aware of another user having problems running KSP with RealismOverhaul and TestFlight installed. Apparently TestFlight includes a `TestFlightContracts.dll`, depending on `ContractConfigurator.dll`, since version 1.3 for KSP 0.90.
* https://github.com/KSP-RO/TestFlight/commit/639e90583e8ca3c4f79d8527566e3d8fc2c6ed1f#diff-4485773c9a03724d0df8939c3c71534d
* https://forum.kerbalspaceprogram.com/index.php?/topic/99043-122-testflight-v180-01-may-2017-bring-flight-testing-to-ksp/&do=findComment&comment=1934467
```
158 [WRN 14:18:14.760] AssemblyLoader: Assembly 'TestFlightContracts' has not met dependency 'ContractConfigurator' V1.0.0
```
I wonder why no one ever complained about that before, but I guess TestFlight usually gets installed with RO, and RP-1 (and maybe also …
=> Add ContractConfigurator dependency to TestFlight

NetKAN/EnduranceSpaceExplorationSystem.netkan
See JPLRepo/Endurance#37, the version file syntax error has been fixed on GitHub but not SpaceDock, due to replacing a release being more difficult on SpaceDock. This PR switches the kref so we can see how different the resulting metadata would be and whether it could work.
=> Try switching EnduranceSpaceExplorationSystem kref to GitHub

NetKAN/EnduranceSpaceExplorationSystem.netkan
This got lost in #8134 because it was pulled from SD. Now it's in the netkan.
=> Restore EnduranceSpaceExplorationSystem homepage

NetKAN/ULAVulcan.netkan
The directory layout changed in the latest release of ULAVulcan:
```
New inflation error for ULAVulcan: GameData directory found within GameData:
```
=> Fix ULAVulcan install

NetKAN/NextStarIndustries.netkan
NSI has a version file since a v2.3.0: https://github.com/NextStarIndustries/Next-Star-Industries/blob/master/GameData/NSI/NextStarIndustries.version
It is even a valid one without syntax errors or anything! Which you can't really say of the versioning system, expect yet another epoch soon...
=> Add vref to NextStarIndustries

NetKAN/AECS-Motion-Suppressor.netkan
This mod's abstract has a bunch of ZERO WIDTH NO-BREAK SPACE characters in it:
Now they're removed.
=> Fix AECS-Motion-Suppressor abstract

NetKAN/MissingRobotics.netkan
@linuxgurugamer notified me that this mod had been marked with the CKAN badge on SpaceDock, but we never got a PR for it.
- https://spacedock.info/mod/2557/Missing%20Robotics
- https://forum.kerbalspaceprogram.com/index.php?/topic/197841-missing-robotics/
=> Add MissingRobotics

NetKAN/Parallax-StockTextures.netkan, NetKAN/Parallax.netkan
Parallax 1.1.0(-PRE) just released and includes textures for stock planets now, while previously only BeyondHome had textures for Parallax.
https://spacedock.info/mod/2539/Parallax
Parallax now depends on the virtual module `Parallax-Textures`. A dependency on Kopernicus is also added to Parallax itself now, it was previously pulled in by BeyondHome:
A new module, `Parallax-StockTextures`, providing `Parallax-Textures`, is introduced. It installs the `Parallax_StockTextures` folder into GameData.
BeyondHome also provides `Parallax-Textures` (moved into separate branch to reduce disk usage).
___
=> Add Parallax-StockTextures and create texture dependency system

NetKAN/Kerbulator.netkan
See https://github.com/KSP-CKAN/CKAN-meta/pull/2174 and https://github.com/KSP-CKAN/CKAN-meta/pull/2175
This PR updates the compatibility of Kerbulator, epoch should be taken care of automatically.
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2174
=> Update Kerbulator compatibility to 1.10

NetKAN/BDArmoryContinued.netkan, NetKAN/Buffalo.netkan, NetKAN/FlatBtmShtlSys.netkan, NetKAN/FuelTanksPlus.netkan, NetKAN/MS-SRBs.netkan, NetKAN/ModularRocketSystem.netkan, NetKAN/RetroFuture.netkan
Follow-up after KSP-CKAN/CKAN#3207.
Oddiseo needs them where they are:
```
craftURL = ContractPacks/Oddiseo/Vessels/Damaged Oddiseo tourist orbiter.craft
```
Same for ContractConfigurator-AnomalySurveyor:
```
craftURL = ContractPacks/AnomalySurveyor/Monolith/Monolith.craft
```
Potentially a common pattern for contract packs, might want to account for that in future.
=> Install craft files to Ships folder

NetKAN/AircraftCarrierAccessories.netkan, NetKAN/DunaDirect.netkan
#8242 for the webhooks-only crowd.
DunaDirect's craft file is in a Mission, which is not supposed to be under Ships, so that's another thing we can improve about this warning. Subassemblies can't be installed yet, see KSP-CKAN/CKAN#2804.
=> More craft file install fixes

NetKAN/PhoenixIndustries.netkan
> CHANGELOG
> v1.6
> -Complete overhaul of EVA Suit textures - they now work with the stock suit switcher and do not require Texture Replacer.
=> PhoenixIndustries no longer needs TextureReplacer

NetKAN/Pathfinder.netkan
```
About to install:
* Pathfinder v1.36.1 (cached)
* Buffalo v2.9.0 (cached)
Module "Pathfinder" successfully installed
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
If this problem re-occurs, then it may be a packaging bug.
Please report it at:
https://github.com/KSP-CKAN/NetKAN/issues/new/choose
Please include the following information in your report:
File      : Ships/SPH/Guppy.craft
Installing Mod : Buffalo v2.9.0
Owning Mod: Pathfinder
CKAN Version   : v1.29.2
Your GameData has been returned to its original state.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: …
```
=> Don't install Buffalo's Ships folder as part of Pathfinder

NetKAN/B9-PWings-Fork.netkan
#8144 had an undisclosed dependency:
- https://forum.kerbalspaceprogram.com/index.php?/topic/175197-13x14x15x16x17x18x19x-b9-procedural-wings-fork-go-big-or-go-home-update-40-larger-wings/&do=findComment&comment=3893680
=> Current B9-PWings depends on FAR

NetKAN/CryoTanks-Core.netkan, NetKAN/CryoTanks.netkan, NetKAN/DeployableEngines.netkan, NetKAN/DynamicBatteryStorage.netkan, NetKAN/Kronometer.netkan, NetKAN/NearFutureProps.netkan
A bunch of Nertea's mods have been moved to:
- https://github.com/post-kerbin-mining-corporation
And Kronometer is now under Kopernicus.
This is causing API rate limit errors in Discord.
=> Update references to migrated repositories

NetKAN/NewTantaresLV.netkan
GitHub-hosted mod without version file - hardcoded game version.
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2187
ckan compat add 1.10
=> Update NewTantaresLV compat to 1.11

NetKAN/DiRT.netkan
The current release is a backport, so we've been getting a lot of auto-epoching pull requests. So far this mod has no real epochs.
- https://github.com/KSP-CKAN/CKAN-meta/pull/2180
- https://github.com/KSP-CKAN/CKAN-meta/pull/2183
- https://github.com/KSP-CKAN/CKAN-meta/pull/2186
- https://github.com/KSP-CKAN/CKAN-meta/pull/2188
=> Turn off auto-epoching for DiRT

NetKAN/DeepFreeze.netkan
According to a comment by the author in JPLRepo/DeepFreeze#96, this mod bundles a DLL it doesn't need (BackgroundResources). We have this as a dependency as of #7277 because it's bundled.
Now BackgroundResources is recommended instead of required.
Fixes #8271.
=> Allow DeepFreeze without BackgroundResources

NetKAN/ModuleManager.netkan
Sarbian confirms 1.11 compatibility:
https://github.com/KSP-CKAN/NetKAN/pull/8279#issuecomment-751136250
> @HebaruSan Yes it is ok. I will be able to do it sometime tomorrow but feel free to do it before if you have the time.
=> Update ModuleManager compatibility to 1.11

NetKAN/LunaMultiplayer.netkan
LunaMultiplayer got a new release for KSP 1.11 yesterday, however the version file hasn't been updated in time to reflect this. It has only been updated _after_ the release was already published.
So the included version file still says `VERSION: 0.26.0` and `KSP_VERSION: 1.10`, while the remote version file says `VERSION: 0.27.0` and `KSP_VERSION: 1.11`. Due to the version mismatch CKAN doesn't consider the remote version file for compatibility data now, and still has 1.10 in its metadata.
Additionally, LMP is version locked and not backwards compatible, so users installing the mod new or updating it will end up with a non-functional version on KSP 1.10.
Users on KSP 1.11 won't see any version as compatible at all.
So this PR overrides the `ksp_version` to `1.11` (which the updated …
=> Override compat of LMP 0.27.0 to KSP 1.11 and remove vref

.github/workflows/manual_inflate.yml
Currently the Inflator is driven by the Scheduler and Webhooks. Sometimes it would be nice to have the option to trigger it manually, for example if a mod author wishes to upload several consecutive releases to GitHub in a short period.
I have created a simple new GitHub Action based on xKAN-meta_testing. It uses parts of NetKAN-Infra to submit one identifier for inflation:
- https://github.com/HebaruSan/inflate-netkan
Now a new option "Inflate a chosen module" appears in the Actions list of the NetKAN repo:
If you click it, a "Run workflow" dropdown is available:
If you click that, you can type an identifier and click Run workflow:
This will trigger the action, which checks out the NetKAN and CKAN-meta repos and uses them to submit a request to the queue for the Inflator to process …
=> Manually triggerable inflate Action

NetKAN/TweakScale.netkan
Previous versions are still licensed under the WTFPL (un)license.
=> Updating licensing terms for TweakScale.

NetKAN/ContractConfigurator-PlanesWithPurposes.netkan
Another mod that didn't get caught by the webhook, but noticed via a Reddit post about it.
* [SpaceDock](https://spacedock.info/mod/2601/Planes%20With%20Purposes)
* [Forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/199185-111x-planes-with-purposes-pwp/)
* [GitHub repo](https://github.com/TudorAerospace/PWP) (if I find some time I might try to explain to the author how to use Git)
Abstract:
>  The purpose of this mod is to encourage people to use planes more, as they are quite useless when not built as SSTOs. 
Description:
> Hello! This is my first mod. The purpose of this mod is to make Aircraft useful.
It adds a couple of contracts that will ,well, make aircraft useful.
The mod is by no means finished or bug free, so please report any bugs encountered on the mod's …
=> Add ContractConfigurator-PlanesWithPurposes

NetKAN/KSCExtended.netkan
KSCExtended depends on KerbinSideRemastered since version 2.0:
https://forum.kerbalspaceprogram.com/index.php?/topic/181556-18x-ksc-extended-v22-expanding-your-ksc-in-style/&do=findComment&comment=3718738
It also recommends KSCHarbor now.
=> Add KerbinSideRemastered to KSCExtended's dependencies

NetKAN/ContractConfigurator-PlanesWithPurposes.netkan
Since version 1.3 this mod comes with its ContractConfigurator files in a `ContractPacks/PWP` folder instead of `ContractPacks/` directly.
Its config files also depend on being installed at this path (yes, even the older versions with the incorrectly packaged zip). I'm going to copy the change like this to 1.3, and adjust the `as` in 1.2.
=> Fix PlanesWithPurposes install stanza

NetKAN/AntennaSleep.netkan, NetKAN/AttitudeAdjuster.netkan, NetKAN/AutoAGL.netkan, NetKAN/BetterBurnTime.netkan, NetKAN/BetterCrewAssignment.netkan, NetKAN/DefaultActionGroups.netkan, NetKAN/IndicatorLights.netkan, NetKAN/IndicatorLightsCommunityExtensions.netkan, NetKAN/MissingHistory.netkan, NetKAN/SimpleFuelSwitch.netkan, NetKAN/Snarkiverse.netkan, NetKAN/VABReorienter.netkan, NetKAN/VariantPersist.netkan, NetKAN/VectorRepurposed.netkan
Several mods on SpaceDock have quite broad actual/intended compatibility and narrow in-metadata compatibility, because the minimum compatible version is not stored anywhere, and SpaceDock provides only the current/latest game version.
Before KSP-CKAN/CKAN#3265 is merged, this PR will fail to validate because these overrides won't work.
Once that PR is merged, this PR will set the minimum compatibility to the original compatibility of the current release of each of these mods, as determined programmatically during investigation of #8291.
Fixes #8291.
=> Minimum compatible version overrides for Snark's mods

NetKAN/ExtraPlanetaryLaunchpads.netkan
[This mod] lists an optional mod in its "required" list:
[This mod]: https://forum.kerbalspaceprogram.com/index.php?/topic/54284-18-110-extraplanetary-launchpads-v683/
But apparently it's **really** optional:
Originally switched the other way in #4883 "as per forum thread", presumably referring to the above "required" list; I could find no specific discussion of it on [the EL thread in the days leading up to Nov 4, 2016]. There's a gap in the record of forum posts on the CKAN threads; [pjf's thread] ends in July 2016, and [politas's thread] starts in January 2017, so if it was mentioned there, it's gone now.
[the EL thread in the days leading up to Nov 4, 2016]: https://forum.kerbalspaceprogram.com/index.php?/topic/54284-18-110-extraplanetary-launchpads-v683/page/170/
[pjf's thread]: …
=> Move KIS back to Extraplanetary Launchpads's recommends list

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
This mod from SpaceDock lacks a version file but has broader compatibility than SpaceDock can represent:
As of KSP-CKAN/CKAN#3265, we can handle this with overrides.
=> Extend current Scatterer compatibility back to KSP 1.9

NetKAN/WarpEverywhere.netkan
This is a very broadly compatible mod, apparently from 1.4.3 to the present. The SD entry has been updated to be compatible with 1.11.0.
Closes KSP-CKAN/CKAN-meta#2237.
=> Override min game version for WarpEverywhere

NetKAN/BuranEnergia.netkan, NetKAN/KSPRescueContractFix.netkan, NetKAN/PitchPerfect.netkan
These mods have the CKAN badge but no auto PR:
- https://spacedock.info/mod/2623/%5B1.8-1.10%5D%20Buran%20Energia%20Mod%20%28Rebalanced%20and%20Fixed%29?ga=%3CGame+3102+%27Kerbal+Space+Program%27%3E
- https://spacedock.info/mod/2622/KSP%20Rescue%20Contract%20Fix
- https://spacedock.info/mod/2616/Pitch%20Perfect
RVE-Extended was examined and not indexed:
- It depends on Principia, which we can't index due to system dependencies
- Its installation instructions suggest that it overwrites files
___
=> Add mods from SpaceDock

NetKAN/CustomAsteroids-Pops-OPM-Outer.netkan, NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan, NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan, NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan
Old configs continue to work with CA 1.6+, while new configs (version 1.9+) require CA 1.9+ and KSP 1.10+. The `x_netkan_override` blocks ensure continuity in behavior until Custom Asteroids 1.9 and CA-OPM 1.2 are actually released (tested by running `netkan` locally).
`CustomAsteroids.netkan` itself requires no updates for the new release; its versioning will be handled through Spacedock/AVC metadata.
=> Update Custom Asteroids dependencies for data configs.

.github/workflows/inflate.yml
`ckan.exe`'s cache entries are only readable by the user that creates them (whereas `netkan.exe`'s are readable by everyone, due to differences in how these files are created):
```
$ ll -n downloads-ckan/ downloads-netkan/ 
downloads-ckan/:
insgesamt 64K
-rw------- 1 1000 1000 62K Jan 25 01:14 E9582E0A-ModuleManager-4.1.4.zip
downloads-netkan/:
insgesamt 72K
-rw-rw-r-- 1 1000 1000 62K Jan 25 01:15 E9582E0A-netkan-ModuleManager.zip
-rw-rw-r-- 1 1000 1000  40 Jan 25 01:15 E9582E0A-netkan-ModuleManager.zip.sha1
-rw-rw-r-- 1 1000 1000  64 Jan 25 01:15 E9582E0A-netkan-ModuleManager.zip.sha256
```
GitHub's cache action somehow doesn't run with sufficient permissions to access all files (!), even though it runs in a nice safe sandbox, see actions/cache#133. (And the exact requirements and best …
=> Cache permissions workaround

NetKAN/kRPC-MechJeb.netkan
Fixes #7963.
https://github.com/Genhis/KRPC.MechJeb/releases
___
ckan compat add 1.5
=> Add kRPC-MechJeb

NetKAN/SpaceLink.netkan
SpaceLink 1.0 has been updating its compatibility for every release since KSP 1.2.2, which has meant that while it works on all of those versions, we only have it as working with the latest game version at any given time.
Now the min game version is pinned to 1.2.2.
=> Make SpaceLink compatible with its full game version ramge

NetKAN/CommunityPartsTitles.netkan, NetKAN/CommunityPartsTitlesExtrasCategory.netkan, NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
The latest release of the CommunityPartsTitles set of mods removed the `GameData` folder of the zip and put `002_CommunityPartsTitles` at the root.
=> Fix CommunityPartsTitles install

NetKAN/Kopernicus.netkan
With https://github.com/KSP-CKAN/CKAN/pull/3279 we got the possibility to index multiple release assets from GitHub, taking the version number out of the file name.
@R-T-B planned to upload one Kopernicus release with multiple assets for different KSP versions  (like he already does for his [bleeeding edge repo](https://github.com/R-T-B/Kopernicus/releases)).
In fact, he already did so once, but reverted so CKAN can index it (see https://github.com/KSP-CKAN/CKAN-meta/pull/2248).
This PR adds the new `version_from_asset`, with a regex matching the current zip naming scheme. Judging from https://github.com/KSP-CKAN/CKAN-meta/pull/2248, it should stay the same when he switches to multiple assets again.
A `x_netkan_version_edit` prepends `release-` to match the current versioning.
Inflating …
=> Enable multi-asset indexing for Kopernicus

NetKAN/Kopernicus.netkan
See https://github.com/KSP-CKAN/CKAN-meta/pull/2251, follow-up to #8338 
Since in the current version format for Kopernicus the KSP version comes before the release counter, we will always get a out-of-order auto-epoch for the assets for older KSP versions.
And apparently also for every other asset in the same release, because they share the `TransformOptions`.
We don't want that, so let's enable `x_netkan_allow_out_of_order` here.
Alternative would be swapping the release counter and the KSP version part in the version, but I think in this case it's nicer to keep the current format, which also helps users identifying the zip belonging to the version on CKAN if they want to have a look or something.
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2251
Closes …
=> Allow out of order releases for Kopernicus

NetKAN/JX2Antenna.netkan, NetKAN/ManhattanAirport.netkan, NetKAN/ModularLaunchPads.netkan, NetKAN/SteeringTweaker.netkan
Follow-up to #8309, apparently my search skipped mods with co-authors.
___
=> Min version overrides for SpaceDock mods

NetKAN/AdvancedFlyByWire-Linux.netkan, NetKAN/AdvancedFlyByWire-OSX.netkan, NetKAN/AirlockPlus.netkan, NetKAN/DockingCamKURS.netkan, NetKAN/PicoPort4AllSizes.netkan
KSP-CKAN/CKAN#3286 found five mods with multi-asset releases on GitHub:
In most cases it's a harmless warning we can suppress by specifying `asset_match`.
For AFBW-OSX, the wrong file is being inflated since #7729, and clean-up will be required.
=> Select the right asset

NetKAN/NeptuneCamera.netkan
Hardcoded compatibility, v3.0 is compatible with KSP 1.11
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2258
=> Update NeptuneCamera compat to 1.11

NetKAN/SSRSS-Rescale.netkan
Install moved from `GameData/Sigma/Dimensions` to `GameData/SigmaDimensions`.
=> Fix SSRSS-Rescale install

NetKAN/NewTantares.netkan
New update v24.0 is compatible with KSP 1.11
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2291
=> Update NewTantares compatibility

NetKAN/CommunityPartsTitlesExtrasCategory.netkan, NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
The file has been renamed from `category_hide_cck.cfg` to `category_hide_cck_parts.cfg`.
The filter for CommunityPartsTitlesExtrasCategory needed to be adjusted as well.
=> Fix CommunityPartsTitlesExtrasNoCCKDup install

NetKAN/BeyondHome.netkan
Forum thread says this:
According to comments from the author the restriction should go away with the next release of BeyondHome. But we'll get a staging PR for it anyways, since it has hardcoded KSP compatibility with a max of 1.10.
There's a small bug in the client, it installs the correct version of Parallax but then offers to upgrade it. The upgrade will abort due to the unsatisfied dependency though.
=> Force Parallax 1.0.1 for BeyondHome

NetKAN/Ceteras-Suit-Pack.frozen, NetKAN/CustomDesignSpacesuits-Steampunk.frozen, NetKAN/GregroxMultiColorSuitsPack.netkan, NetKAN/GregroxsColoredEVAIVASuits.frozen, NetKAN/KSPArtemisSuit.netkan, NetKAN/MilitarySuitTextures.frozen, NetKAN/PartlyColoredSuits.netkan, NetKAN/PhoenixIndustriesEVASuit.frozen, NetKAN/ShuttleEVASuit.netkan, NetKAN/SpaceXSuits.netkan, NetKAN/SteampunkColorCodedSpaceSuits.frozen, NetKAN/USIKolClassSuits.frozen, NetKAN/USIKolClassSuitsRedux.netkan
There are a bunch of mods adding new suits to the game, previously using TextureReplacer ans since 1.10 (I think) the built-in feature.
They didn't really fit into any of the existing mod types, they aren't really parts, nor configs.
We've already got `parts` and `flags`, `suits` should complement the list nicely.
As discussed on Discord, we are tagging those mods with `[ "suits", "graphics", "crewed" ]` now, which should cover the categories users likely expect to find them under.
=> Add 'suits' tag to suit mods

NetKAN/CommunityPartsTitles.netkan, NetKAN/CommunityPartsTitlesExtrasCategory.netkan
In the course of #8394, the folder paths of CommunityPartTitles's ZIP were updated to include a `GameData/` prefix, but only one of its three netkans were updated.
Now the other two are updated.
=> Fix CommunityPartTitles installs

NetKAN/KSPW00tNow.netkan
This mod has the CKAN badge on SD but no PR.
https://spacedock.info/mod/2630/KSPW00tNow
It uses the MPL-2.0 license which the current client doesn't support, so it will need to wait till CKAN v1.30.0 is released.
https://github.com/KSP-CKAN/CKAN/commit/85ac317f9512a8e4706fb1ace06b5a8553a465b3
It also bundles Harmony and so may need to be considered for #8288.
=> Add KSPW00tNow

NetKAN/Kerbalism-Config-RO.netkan
Our friends at the KSP-RO Discord informed me that this mod provides its own life support, so it should conflict with TACLS, at least. Looking at the default Kerbalism config, there are already conflicts for several such mods:
https://github.com/KSP-CKAN/NetKAN/blob/908306929b12c8891046e6871545674086535787/NetKAN/Kerbalism-Config-Default.netkan#L23-L30
Now the ones that I was able to confirm are for life support are added here as well.
FYI to @siimav and @Standecco.
=> Make Kerbalism-Config-RO conflict with life support mods

NetKAN/NewTantares.netkan, NetKAN/NewTantaresLV.netkan, NetKAN/Tantares.frozen, NetKAN/TantaresLV.frozen, NetKAN/TantaresSP.netkan
See the conversation above and below [this comment](https://forum.kerbalspaceprogram.com/index.php?/topic/73686-111x-tantares-stockalike-soyuz-and-mir-2402122021/&do=findComment&comment=3937912) on the Tantares thread.
In early 2017, the SpaceDock entries for `Tantares` and `TantaresLV` stopped receiving updates, while releases were still published in the GitHub repo.
After [an issue](https://github.com/KSP-CKAN/NetKAN/issues/5295) from a user who seemed close to the project, [new netkans have been added](https://github.com/KSP-CKAN/NetKAN/pull/5317) for those two mods, with the identifiers `NewTantares` and `NewTantaresLV`. Ideally only the kref should've been changed instead of creating two completely new modules, but well.
Shortly after the original netkans have been frozen. Some time …
=> Fix Tantares mods

NetKAN/NewTantares.netkan, NetKAN/NewTantaresLV.netkan, NetKAN/TantaresSP.netkan
Got a request from Beale to give the Tantares mods more explanatory names, since people seem to get confused about which one is which:
I've pointed to the abstract which already contains the keywords to help distinguish them, but they still think a more detailed mod name should help, so why not.
=> Less confusing names for Tantares mods

NetKAN/Kerbalism.netkan
This release treats Harmony2 as an external dependency instead of bundling it.
https://github.com/Kerbalism/Kerbalism/releases/tag/3.13
Now the provides relationship is replaced with a depends. No filter is added because the DLL isn't in the ZIP at all.
Closes KSP-CKAN/CKAN-meta#2319.
=> Update Kerbalism's Harmony relationships

NetKAN/NewTantaresLV.netkan, NetKAN/TantaresSP.netkan
Both mods now include version files (and even valid on first try! :tada:), so let's remove the hardcoded version range.
The third Tantares mod should follow soon.
=> Add vrefs for Tantares SP and Tantares LV

NetKAN/ManeuverD.netkan
(From KSP-CKAN/CKAN#3326.)
This mod bundles Harmony, but we didn't know about it.
See KSP-CKAN/NetKAN#8288 for why that's bad.
Now it's marked as providing Harmony1 and has staging enabled.
This way it won't be installed alongside Harmony2, and we'll get notifications if it's ever updated.
=> Mark ManeuverD as bundling Harmony1

NetKAN/KSPBurst-Lite.netkan, NetKAN/KSPBurst-NOOP.netkan, NetKAN/KSPBurst.netkan
Replaces #8418 due to some commit weirdness, and GitHub locking the PR closed and no abillity to force-push to the previous commit.
Quick links:
* https://github.com/KSPModdingLibs/KSPBurst
* https://forum.kerbalspaceprogram.com/index.php?/topic/201112-18-111-kspburst-burst-compiler-for-kerbal-space-program/
KSPBurst is a library providing the Burst compiler tool. Some mods plan to use it in the future to make use of [Unity Jobs](https://docs.unity3d.com/Manual/JobSystem.html), which requires all job code to be located in a single DLL, so this mod allows mods to dynamically register themselves and compiles all code into a single DLL. At least that's my understanding.
Maintained and submitted by @dkavolis
=> Add KSPBurst

NetKAN/TestFlight.netkan
This mod's releases aren't being indexed because of a mismatched asset_match:
https://github.com/KSP-RO/TestFlight/releases
Now this is removed.
Brought to my attention by @DRVeyl on Discord.
=> Remove TestFlight's asset_match

NetKAN/BarisBridge.netkan, NetKAN/CST100Starliner.netkan, NetKAN/FelineUtilityRovers.netkan, NetKAN/HullBreach.netkan, NetKAN/JackOLantern.netkan, NetKAN/LunaMultiplayer.netkan, NetKAN/ManhattanAirport.netkan, NetKAN/NoCrewRequirementContinued.netkan, NetKAN/OldPartsRedux.netkan, NetKAN/RFStockalike.netkan, NetKAN/ShowAllFuelsContinued.netkan, NetKAN/StreamlineEnginesRCSsandfueltanks.netkan, NetKAN/UnKerballedStart.netkan
After KSP-CKAN/CKAN#3327 we now have a much more reasonable list of vref warnings:
Now these mods have vrefs.
RadioFreeKerbin isn't updated because it has a metanetkan.
___
=> Add vrefs to mods with unused version files

NetKAN/CapsuleCorpKerbalKolonizationProgram.netkan, NetKAN/JamesWebbForKerbal.netkan, NetKAN/LosslessISRU.netkan
27 mods have the "ModuleManager syntax used without ModuleManager dependency" warning.
22 of these have metanetkans and so would have to be fixed by their authors.
ScienceRolesFinalFrontierRibbonPack and STMsFFRibbonPackExpeditionRibbons are false positives; they use a purely custom syntax in files with the .cfg extension.
The remaining 3 are fixed here.
=> Add MM dep for mods with MM syntax

NetKAN/NorthKerbinDynamicRenewed.netkan
This release was originally set as compatible with 1.9.1 on SpaceDock.
=> Pin min compat of NorthKerbinDynamicRenewed

NetKAN/ProceduralFairings-ForEverything.netkan
This video gives a newbie-friendly introduction to installing RSS/RO/RP-1 on KSP 1.8 (since followed up with another video on how to install on KSP 1.11 which doesn't get into this mod):
https://www.youtube.com/watch?v=6glycvICehU
It mostly uses CKAN, but it says you have to manually install `ProceduralFairings-ForEverything`. This is because its `ksp_version_max` is only 1.7 so it doesn't show up as installable with the settings in the video. The remote version file specifies 1.11:
https://github.com/KSP-RO/ProceduralFairings-ForEverything/blob/master/GameData/ProceduralFairings-ForEverything/ProceduralFairings-ForEverything.version
However, the internal version file's URL property is wrong in the latest release, see KSP-RO/ProceduralFairings-ForEverything#12, so that change can't be …
=> Override max compat for ProceduralFairings-ForEverything

NetKAN/OldPartsRedux.netkan
This SpaceDock mod was originally uploaded for KSP 1.8.1. It has a version file, but there's a syntax error, so we just use the SD data. The repo wasn't linked on SpaceDock or I would have submitted TriggeredSnake/OldPartsRedux#1 sooner.
=> Pin min compat of OldPartsRedux

NetKAN/KerbinPlacePack.netkan
A new release is out which no longer uses the old misspelled path.
___
=> Update install for KerbinPlacePack

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
Noticed while working on #8474 
`Scatterer-sunflare` and `Scatterer-config` don't depend on core `Scatterer`.
To my knowledge they do nothing without it being installed as well.
In a case like #8474 where the sunflares are a recommendation, or if a user sees sunflares and wants to install them, they might only select "Scatterer Sunflare" and don't realize that they need Scatterer as well, then wondering why it doesn't work.
I haven't found a reason why they don't have the dependency yet, so I guess it is "because nobody noticed it yet".
So this PR adds `Scatterer` to the dependencies of `Scatterer-sunflare` and `Scatterer-config`.
=> Make Scatterer-sunflare and Scatterer-config depend on Scatterer

NetKAN/TechTreeKompacted.netkan
These mods are no longer conflicting since TechTreeKompacted 1.4:
https://forum.kerbalspaceprogram.com/index.php?/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1300-glenn/&do=findComment&comment=3955463
https://forum.kerbalspaceprogram.com/index.php?/topic/199096-111x-techtree-kompacted-15-stock-ctt-uks-pbc-and-bet-supported/&do=findComment&comment=3905788
=> Remove UnKerballedStart and ProbesBeforeCrew from TechTreeKompacted conflicts

NetKAN/BDArmoryForRunwayProject.netkan
This mod keeps changing between a 'v' prefix and no prefix:
* https://github.com/KSP-CKAN/CKAN-meta/pull/2292
* https://github.com/KSP-CKAN/CKAN-meta/pull/2318
* https://github.com/KSP-CKAN/CKAN-meta/pull/2333
https://spacedock.info/mod/2487/BDArmory%20for%20Runway%20Project
Let's put an end to this and force a `v`, then the author can do whatever they want and we don't have to merge an epoch bump PR every other week.
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2333
=> Force v for BDArmoryForRunwayProject

NetKAN/LFOBalancer.netkan
This user name was changed and we're getting alerted now, probably because the mods from #8488 are keeping us over some kind of limit.
=> Update LFOBalancer kref

NetKAN/CustomPreLaunchChecks.netkan
The spelling got fixed here at some point, and the bot is alerting us because of #8488.
=> Update CustomPreLaunchChecks kref

NetKAN/KSP-Data-Export.netkan
A mod that exports flight data to CSV files. It has the CKAN badge on SpaceDock, but the automated PR did not generate.
https://spacedock.info/mod/2711/KSP%20Data%20Export
https://forum.kerbalspaceprogram.com/index.php?/topic/201967-111x-export-flight-data-to-a-csv-file-mod/
Hi @kna27, this is the pull request to add your mod to CKAN. The metadata validation process will be visible under the "Checks" tab once it begins.
=> Add KSP-Data-Export

NetKAN/KerbalFlightIndicators.netkan
I updated the mod for ksp 1.11.x. Looks like PapaJoe is not active currenlty so I'm pointing the reference back to my repo.
https://github.com/DaMichel/KerbalFlightIndicators
Current thread by Papa Joe: https://forum.kerbalspaceprogram.com/index.php?/topic/172904-kfi
Previous thread by DaMichel: https://forum.kerbalspaceprogram.com/index.php?/topic/72595-kfi
=> Set Kerbal Flight Indicators repo back to DaMichel's

NetKAN/KerbalTelemetry.netkan
This mod has changed its layout in the last release:
> New inflation error for KerbalTelemetry: No files found matching file="GameData" to install!
> * Kerbal Telemetry folder has been moved into the GameData folder to allow users to download mod from CurseForge without moving files and folders around.
The Python server part goes into GameData now as well, so we can install it too.
Why they haven't moved the `Kerbal Telemetry.dll` inside the `Kerbal Telemetry` folder, no idea.
The common top-level folder has a naming I'm not expecting to stay stable (`Kerbal-Telemetry-v2`) , so I'm picking the DLL and the folder out separately.
Let's see how long it takes for this stanza to fail.
The source code for reference:
https://github.com/yagiziskirik/Kerbal-Telemetry/blob/d9da45d6a46b3fbeda7948723a …
=> Fix KerbalTelemetry install

NetKAN/SDHI-StrobeOMatic.netkan
The current version of KSP on January 12, 2021 was 1.11.0.
Noticed while investigating for #8546.
=> Update SDHI-StrobeOMatic compatibility

NetKAN/AtomicTechFlags.netkan, NetKAN/AutoHibernate.netkan, NetKAN/ElectronStrongbackErector.netkan
Three mods on SD with CKAN badge without PR.
- https://spacedock.info/mod/2762/AutoHibernate
https://forum.kerbalspaceprogram.com/index.php?/topic/202694-autohibernate-set-to-auto/
https://github.com/imakegoodmods/AutoHibernate
- https://spacedock.info/mod/2761/Electron%20strong%20back%20erector%20mod%20%28for%20KSP%201.8.x-1.11.x%29
https://forum.kerbalspaceprogram.com/index.php?/topic/202675-electron-strong-back-erector-mod-for-ksp-18x-111x/
- https://spacedock.info/mod/2763/The%20Flags%20of%20Atomictech
https://forum.kerbalspaceprogram.com/index.php?/topic/202723-the-flags-of-atomictech/
As of KSP-SpaceDock/SpaceDock#356 it should not happen anymore.
=> Final SpaceDock catch-up 🤞

NetKAN/RSSTextures16K.netkan
Adding a new author caused KSP-CKAN/CKAN-meta#2342 to be submitted, because the 16K textures are only marked as compatible with 1.8.
The other texture packs use 1.8 as a minimum:
https://github.com/KSP-CKAN/NetKAN/blob/b2dd4e2432d407cf3e64b6db4a08121d39c3caf7/NetKAN/RSSTextures8192.netkan#L9
https://github.com/KSP-CKAN/NetKAN/blob/b2dd4e2432d407cf3e64b6db4a08121d39c3caf7/NetKAN/RSSTextures4096.netkan#L9
https://github.com/KSP-CKAN/NetKAN/blob/b2dd4e2432d407cf3e64b6db4a08121d39c3caf7/NetKAN/RSSTextures2048.netkan#L9
So now this one will, too.
=> Make RSSTextures16K compatible with 1.8+

NetKAN/RealisticPowerDraw.netkan
Confirmed on the thread.
Also confirmed it was not added in #8222.
=> Add missing RealisticPowerDraw depends

.gitattributes, NetKAN/PlanningNode.netkan
As of KSP-CKAN/CKAN#3367, netkans are allowed to use YAML format, however so far none do.
Now PlanningNode uses YAML format. This will give us a test case for YAML to make sure it works.
Also the git attributes are updated to count .netkan files as YAML instead of JSON.
=> Convert PlanningNode netkan to YAML

NetKAN/InterstellarFuelSwitch-Core.netkan, NetKAN/InterstellarFuelSwitch.netkan
See KSP-CKAN/CKAN#3390, I'd like to use the GitHub API to populate `resources.repository` for mods on SpaceDock, but InterstellarFuelSwitch uses a special link to a particular subdirectory of the main KSPInterstellarExtended repo, which we would like to preserve, and which would be truncated to the main repo with that change.
Now IFS's `resources.respository` "deep links" are set in the netkans, so they will be set regardless of how we treat this property in the Inflator.
=> Hard code IFS repo links

NetKAN/PlanetShine.netkan
One of the mods that caused https://github.com/KSP-CKAN/NetKAN-Infra/pull/220
GitHub highlights this syntax error nicely, now that all netkans are marked as YAML (https://github.com/KSP-CKAN/NetKAN/pull/8566), so I think it was a good thing to do in the end.
https://github.com/KSP-CKAN/NetKAN/blob/339d2f3dc336ec880be6b587a352d0e0d809d583/NetKAN/PlanetShine.netkan#L7-L9
=> Fix PlanetShine indentation

NetKAN/AstronomersVisualPack.netkan, NetKAN/EnvironmentalVisualEnhancements-LR.frozen, NetKAN/SciFiVisualEnhancements-WeimaranersTweaks.netkan, NetKAN/SciFiVisualEnhancements.netkan, NetKAN/Spectra.netkan, NetKAN/StockVisualEnhancements.netkan, NetKAN/StrangeNewWorlds.netkan
Just got pinged by the author on the Kopernicus Discord that this mod conflicts with AVP on CKAN, but it shouldn't.
This is due to the `EnvironmentalVisualEnhancements-Config` provides.
This mod only provides EVE configs for its own planets, but not the stock ones, and it doesn't remove the stock planets.
Thus it still needs another set of EVE configs installed alongside (default configs, AVP, ...) to make EVE work to its full extents,
Now the provides is removed, and instead the virtual module `EnvironmentalVisualEnhancements-Config-stock` is added to the recommendations, alongside `EnvironmentalVisualEnhancements`.
Several EVE config packs that provide configs for the stock planet now provide `EnvironmentalVisualEnhancements-Config-stock`.
---
I've also sent the author a notice about …
=> Remove EVE-Config provides from StrangeNewWorlds

NetKAN/LunaMultiplayer.netkan
The new release 0.28.0 now bundles Harmony2 (updated from Harmony1).
It is also released for KSP 1.12.
After talking to the author, we've decided to filter the Harmony DLL, and replace it with a dependency on our indexed `Harmony2` module (the [HarmonyKSP](https://github.com/KSPModdingLibs/HarmonyKSP) "mod").
They author might switch over to bundling HarmonyKSP themself, which would allow us to get rid of the filter, and make sure that both CKAN users and manual installers would have the same distributions of Harmony installed.
Since this wouldn't need a change in our metadata (besides removing the filter stance), I'm going to go ahead with this change already.
Also see https://github.com/LunaMultiplayer/LunaMultiplayer/issues/415
=> Add Harmony2 dependency to LMP, update compatibility

NetKAN/TweakScale.netkan
Version 2.4.5.1of this mods has been reuploaded, but with a different zip layout.
The `Extras` folder is gone, and the contents of the `GameData` directory are now at the root of the zip.
Fixes #8598
=> Fix TweakScale install stanzas

NetKAN/TweakScale.netkan
Reverting #8599 
When I look at what I _think_ is the most recent reupload from TweakScale 2.4.5.1 (file size 288150, matches the one from [GitHub](https://github.com/net-lisias-ksp/TweakScale/releases/tag/RELEASE%2F2.4.5.1)), the layout is as it was in the very initial upload and all previous releases:
Inflation will probably succeed here, but fail for the bot because it has the outdated file in its cache (see [my comment here](https://github.com/KSP-CKAN/NetKAN/issues/8598#issuecomment-869200228)).
However with the failed inflation, it _might_ delete the zip from the cache and download the new one, with some luck.
=> Revert "Fix TweakScale install stanzas (#8599)"

NetKAN/Kerbalism-Config-RO.netkan
See #8602, this config pack no longer bundles the core Kerbalism, and thus no longer contains its version file to get compatibility data from.
> New inflation warnings for Kerbalism-Config-RO: $vref present, version file missing
Instead, we've decided to go with no KSP version restriction (i.e. `any`), and let the core Kerbalism dictate compatibility.
So let's remove the vref, to keep everything tidy.
=> Remove vref from Kerbalism-Config-RO

NetKAN/RSSVE-HR.netkan, NetKAN/RSSVE-LR.netkan
See https://github.com/KSP-CKAN/NetKAN/pull/8595#issuecomment-870532853, that PR used the wrong identifier for DistantObject.
=> Fix RSSVE dependency on DistantObject

NetKAN/DerivativeTextures.netkan
Note the sentence at the bottom:
=> Mark DerivativeTextures compatible with any version

NetKAN/ModuleManager.netkan
As per https://github.com/KSP-CKAN/NetKAN/issues/8618#issuecomment-873410486:
> @sarbian is the latest ModuleManager release okay to be marked as compatible with KSP 1.12?
We got a bunch of 1.12 mods depending on ModuleManager already, would be nice to have them all show up on KSP 1.12 installations.
> It is but I am unable to do the change for a few more days. Feel free to do it,
Closes #8618
=> Update ModuleManager compatibility to 1.12

NetKAN/KSCExtended.netkan
This mod has been adopted by JadeOfMaar, and some of the relationships have changed.
- KerbinSideRemastered is no longer considered a dependency, but only a recommendation ([it fills in an empty space left by KSCExtended](https://forum.kerbalspaceprogram.com/index.php?/topic/203623-111-ksc-extended-30/&do=findComment&comment=4000171)).
- Scatterer and SVE have been removed from the recommendations
- reDirect is also a recommendation, but not indexed on CKAN
- It currently conflicts with GPP, which may change soon.
The author is notified about the incorrect version file `URL`.
=> Update KSCExtended relationships after adoption

NetKAN/SmokeScreen.netkan
Mark the current SmokeScreen as 1.8 to 1.12 compatible.
___
Fixes #8618.
=> SmokeScreen for KSP 1.12

NetKAN/Parallax.netkan
Parallax 1.3.0 released, with compatibility for KSP 1.12 only (as far as the forum thread title tells).
- https://github.com/Gameslinx/Tessellation/releases/tag/1.3.0
- https://forum.kerbalspaceprogram.com/index.php?/topic/197024-112x-parallax-a-pbr-terrain-shader-130/&do=findComment&comment=4000968
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2380
(for ModularFlightIntegrator)
=> Update Parallax compatibility for new release

NetKAN/Parallax.netkan
Per a random Discord conversation with Gameslinx:
This PR marks the latest release, 1.3.0, as compatible with KSP 1.11 - 1.12.
A CKAN-meta PR will also adjust the metadata of the previous 1.2.3 release to have the same range, maybe there's someone who wants to stick to the older release for now, bugs, performance or whatever.
=> Change Parallax min KSP version to 1.11

NetKAN/KerbinSideRemasteredTLA.netkan
Fixup of #8636 
This mod belongs into `GameData/ContractPacks/`, as it is in the zip. Also the ships belong where they are in the zip, they are part of the contracts, _not_ user-playable ships: `craftURL = "ContractPacks/KerbinSideRemasteredTLA/Assets/Ships/" + @/wreckCraft`.
=> Fix KerbinSideRemasteredTLA install location

NetKAN/InterstellarRedistributable.netkan
It should be available for install from any KSP version starting from KSP 1.8.1
Closes https://github.com/KSP-CKAN/CKAN-meta/pull/2386
=>  hard code minimum KSP version Interstellar Redistributable

NetKAN/RadioFreeKerbin.netkan
See #8641, a metanetkan with hard-coded `download` property has downsides and isn't necessary when the mod is hosted on GitHub or SpaceDock (or both!). This one even has a version file.
=> De-meta RadioFreeKerbin metanetkan with hardcoded download

NetKAN/RadioFreeKerbin.netkan
I removed the vref in #8642 to see if it would help with a validation error. It didn't, and I forgot to add it back in.
This data is probably redundant with the internal ckan, but the possibility of updating the remote version file slightly tips the balance in favor.
=> Vref for RadioFreeKerbin

NetKAN/GPP.netkan, NetKAN/GPPCloudsHighRes.netkan, NetKAN/GPPCloudsLowRes.netkan, NetKAN/GPPSecondary.netkan, NetKAN/GPPTextures.netkan
See https://github.com/Galileo88/Galileos-Planet-Pack/pull/69:
The compatibility data for GPP, GPPClouds*, GPPSecondary and GPPTextures are a mess:
This was due to hardcoded compatibility in the metanetkans.
I've had the PR open for several months, but got not a single person of the Galileo team to look at it, even after several pings on the PR itself, or the forum thread. Several team members have been active both on the GitHub repo and the forum thread in the meantime. Maybe they are purposefully ignoring us, I don't know.
In any case, since this is a live problem, with a worse impact than our average "forgot a comma in the version file" upstream issues and causes people to have broken installs, with several people messaging me about this in the last few months, I decided to de-meta …
=> De-meta GPP mods

NetKAN/GPP.netkan
Small fixup of #8644, I've accidentally put the `Grannus` filter for the Grannus Ribbon Pack on the wrong install stanza.
See
- https://github.com/Galileo88/Galileos-Planet-Pack/pull/64/files#diff-d9450be21cc6728de2fae4bd2b2976d5ad9504f3e9cee4fac255d80ca21e4c7c
- https://github.com/KSP-CKAN/NetKAN/pull/8024/files#diff-bef12baee87f4df2076d36570c2f62aa003bb27ba62601dbf0186e741864bf70
for reference
=> Move 'Grannus' filter to correct install stanza

NetKAN/SIMPLEXKerbalism.netkan, NetKAN/SimplexPropulsion.netkan, NetKAN/SimplexTechTree.netkan, NetKAN/TETRIXTechTree.netkan
These mods have a versioning scheme that doesn't interact well with CKAN's sorting logic.
Basically it consists of a semver-like numbers separated by dots part, and a date part in at the end.
The first part alternates between two and three "subparts", so whenever a release with a third subpart comes out, it's compared against the date of the previous release, and is obviously less, so we get a epoch-bump staging PR.
TETRIXTechTree:
- https://github.com/KSP-CKAN/CKAN-meta/pull/1771
- https://github.com/KSP-CKAN/CKAN-meta/pull/1848
- https://github.com/KSP-CKAN/CKAN-meta/pull/1887
- https://github.com/KSP-CKAN/CKAN-meta/pull/2338
SIMPLEXTechTree:
- https://github.com/KSP-CKAN/CKAN-meta/pull/1847
- https://github.com/KSP-CKAN/CKAN-meta/pull/2339
SIMPLEXKerbalism:
- …
=> Strip date portion of SIMPLEX* and TETRIXTechTree versions

NetKAN/TUFX.netkan
I believe I have done this correctly; it's been a while. In particular, this needs to use a remote version file as hosted on github here ( https://github.com/shadowmage45/TUFX/blob/master/GameData/TUFX/TexturesUnlimitedFX.version ) -- I copied the vref and kref lines from the Ven Stock Revamp core netkan which @HebaruSan pointed out has a remote version link so hopefully that is correct. (The .version in the archive specifies a URL, so I think that will work? The point is that the remote file is good for KSP 1.12 while the release one is older).
(PR'd by permission of @shadowmage45 )
https://github.com/shadowmage45/TUFX
https://forum.kerbalspaceprogram.com/index.php?/topic/192212-19x-tufx-post-processing/
=> Add TUFX to CKAN

NetKAN/Biomatic.netkan
Follow-up to #8674, see https://github.com/KSP-CKAN/NetKAN/pull/8674#issuecomment-887033388
The BiomaticForAll patch isn't fully stable, so now we move it to suggests so it's "disabled" by default.
=> Move BiomaticForAll from Biomatic recommends to suggests

NetKAN/SimpleOrbitCalculator.netkan
#8680 left this mod in kind of a messy state. Now:
- The self-dependency is removed
- The empty `install` list is removed
- The `resources` are removed because they'll pull from SpaceDock
=> Clean up SimpleOrbitCalculator

NetKAN/RealSolarSystem.netkan
Small fix we noticed in the course of #8688.
https://github.com/KSP-CKAN/NetKAN/issues/8688#issuecomment-890592737
> What can we do to make as many of the visual enhancements, that I do think most players install, easiest to get?
https://github.com/KSP-CKAN/NetKAN/issues/8688#issuecomment-890598647
> Should they be recommended or suggested?
https://github.com/KSP-CKAN/NetKAN/issues/8688#issuecomment-890606367
> RSS should rec RSSVE, yes. (And thus by the non-transitive property of recs, RO/RP-1 should too :D ).
https://github.com/KSP-CKAN/NetKAN/issues/8688#issuecomment-890634780
> That may be something easy we can fix in the short term, then; RSS currently only recommends RO, KSCSwitcher, and RSSDateTimeFormatter. Do you want to switch this to a metanetkan hosted on your repo for easier …
=> Make RSS recommend RSSVE-Textures

NetKAN/KerbalMiniShuttle.netkan
Also B9PartSwitch is required now.
___
=> Fix KerbalMiniShuttle install

NetKAN/KSP-Data-Export.netkan
This time it is my turn. KSP-Data-Export 0.6 has originally been released for KSP 1.12.0
=> Pin min compat of KSP-Data-Export

NetKAN/MiniSampleReturnCapsule.netkan
I meant to start a pull request with https://github.com/KSP-CKAN/NetKAN/commit/c2155c7ec9ca187623e8f7dec699c78aab6f1c78 but accidentally committed it to master instead. The bot reported these warnings:
So far these changes are not available to users yet due to auto-epoching, see KSP-CKAN/CKAN-meta#2426.
Now it has tags and an MM dep.
Replaces KSP-CKAN/CKAN-meta#2425.
=> Continue unfreezing MiniSampleReturnCapsule

NetKAN/TrekDrive.netkan
The latest release `0.99w` of this mod changed the folder structure for crafts, as it now also includes files for the SPH.
Additionally, release notes say it also depends on B9PS now:
https://forum.kerbalspaceprogram.com/index.php?/topic/199749-wip-191-112-trekdrive-a-star-trek-like-warp-drive-by-shadowworks-v099w-nx-class-05082021/&do=findComment&comment=4015214
=> Fix TrekDrive install and depends

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
There is a netkan version override specifically for 723, but since that was done @LGHassen has released new versions of Scatterer. I believe the correct solution here -- since the forum OP and docs make clear that all these versions are compatible with 1.9+ -- is to apply this override to all versions going forward, until such time as there is a version that is not backwards compatible with 1.9 etc. The issue here appears to be that versioning from Spacedock has only the active KSP version, not a min/max, or such was done when new Scatterers were released, despite other sources maintaining that they are backwards compatible.
=> Correct minversion for Scatterer

NetKAN/MechJeb2.netkan
The new release of Mechjeb2 supports 1.8 to 1.12.
This should be the last required update of NetKAN for MJ.
=> Mechjeb2 - add support for current KSP

NetKAN/DeadlyReentry.netkan
This effectively reverts #8596 and #8696 to point the netkan back to https://github.com/Starwaster/DeadlyReentry, after @Starwaster became active again and created a new release.
As the new release has a lower version number than NathanKell's releases, the epoch is incremented to prompt users to "upgrade" to the new release.
A pull request in CKAN-meta will freeze the releases from the KSP-RO repository. Depending on the plans of @NathanKell, they can be moved to a new identifier after the corresponding netkan has been created,.
=>  Revert DeadlyReentry source back to Starwaster's fork 

.github/workflows/inflate.yml
In #8701 we are trying to test GUI work flows for some metadata changes, which requires copying each .ckan file manually from the validation output to local files, then creating a tar.gz file for CKAN to use. But the metadata tester already has such a file created for its own use.
Now `/repo/metadata.tar.gz` is uploaded as an artifact for pull requests, so we can download it and use it with CKAN directly.
=> Upload repo artifacts for pull requests

NetKAN/KSPBurst.netkan
#8419 added KSPBurst and KSPBurst-Lite, which provides KSPBurst.
In #8701 we would like to be able to depend on the "full" KSPBurst module without prompting the user to choose between them, but currently this isn't possible.
Now KSPBurst provides KSPBurst-Full, so modules can depend on it if they know they want the full featured module.
=> Provide unique identifier for the full KSPBurst module

NetKAN/RP-1-ExpressInstall-Graphics-High.netkan, NetKAN/RP-1-ExpressInstall-Graphics-Low.netkan, NetKAN/RP-1-ExpressInstall-Graphics-Medium.netkan, NetKAN/RP-1-ExpressInstall.netkan
This adds "express install" packages (a main package and three choices for graphics level) to allow express installation of RO/RP-1/RSS/etc.
RO/RP-1 users often ask for a simple gamedata zip, or "what mods should I install", or the like--to the point of asking which recommended or suggested mods to install, which graphics mods, etc.
This adds a single express install netkan that depends on the core mods for an RP-1 install, and then depends on an RSSGraphics package. That package is provided by three express packages, each reporting only as a detail level, which depend the various RSS-Textures packages, visual enhancements, and Canaveral terrain/pads necessary for a complete experience.
Metanetkans for easy reference:
- https://raw.githubusercontent.com/KSP-RO/RP-1-ExpressInstall/main/RP-1 …
=> Add RO/RP-1 express install netkans

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan
In #7794, #7800, #7870, https://github.com/Galileo88/JNSQ/pull/27 we made a bunch of planet packs depend on Scatterer-sunflare-default, to force them to install the default sunflare, as they would conflict with third-party sunflares.
This was done under the then correct assumption that Scatterer-sunflare does not depend on Scatterer, so that the sunflare would only have an effect if the user chooses core Scatterer additionally themself.
In #8475, we made Scatterer-sunflare and Scatterer-config depend on Scatterer, as by itself it would make more sense, but forgetting about the planet pack situation.
Effectively revert #8475
Now Scatterer-sunflare no longer depends on Scatterer, to right the above assumption again.
Scatterer-config is changed the same way, to keep both modules in sync, as …
=> Revert Scatterer-sunflare and Scatterer-config dependency on Scatterer

.github/workflows/inflate.yml
See https://github.com/KSP-CKAN/xKAN-meta_testing/pull/80 and https://github.com/KSP-CKAN/NetKAN/pull/8704#issuecomment-895115027, this uploads the `.ckans` directory instead of the `.repo/metadata.tar.gz` file, to avoid double compression. I hope the filename turns out the way I think it does.
=> Upload .ckans instead of .repo/metadata.tar.gz as workflow artifact

NetKAN/PanoceanCanal.netkan
Originally uploaded to SpaceDock for 1.11.2, just updated to 1.12.2. Let's see if I have the YAML right.
___
ckan compat add 1.5
=> Pin min compat for PanoceanCanal

NetKAN/HotSpot.netkan, NetKAN/PlaneMode.netkan
These errors haven't gone away.
As of a few hours ago, these mods no longer have a `master` branch and appear to have a `develop` branch instead.
Now we reference the metanetkans on the develop branches.
=> Fix dbent metanetkan branches

NetKAN/StockWaterfallEffects.netkan
This mod with hardcoded compatibility just had a new release, 0.5.2.
The author confirmed a compatibility range of KSP 1.11-1.12.2 on Discord:
=> Update StockWaterfallEffects compatibility for 0.5.2

NetKAN/TeaKettleRCS.netkan
The forum thread lists several mods that aren't in the SpaceDock entry or the README:
https://forum.kerbalspaceprogram.com/index.php?/topic/204633-1122-tea-kettle-rcs-10-sep-01-2021/
___
=> More TeaKettleRCS relationships

NetKAN/FlyingSaucers.netkan, NetKAN/IXSWarpship-Blueshift.netkan
I was lurking on this thread because IXS ships look neat, and the first question and answer was about CKAN:
- https://forum.kerbalspaceprogram.com/index.php?/topic/202697-111x-ixs-warpship-for-blueshift-warp-mod-v104/
- https://github.com/Araym-KSP/IXS-Warship-for-Blueshift
~~The author gave what I interpret as a "soft no," in that he isn't interested in spending extra time on figuring out CKAN procedures or metadata, but it's not clear how he would feel about it if all the work was done for him (hence this pull request, which is intended to do all the work for him).~~
It depends on Flying Saucers, ~~which Angel-125 says will be added to CKAN eventually, but not yet~~:
- https://forum.kerbalspaceprogram.com/index.php?/topic/173857-min-ksp-181-kerbal-flying-saucers-build-flying-saucers-in-k …
=> Add IXSWarpship-Blueshift and FlyingSaucers

NetKAN/VenStockRevamp-Core.netkan, NetKAN/VenStockRevamp-NewParts.netkan
https://github.com/Kerbas-ad-astra/Stock-Revamp/releases/tag/v1.16.0
> - Renamed "Part Bin" subfolder to "PartBin", to accommodate Module Manager patches
=> Update Ven New Parts install

NetKAN/TETRIXTechTree.netkan
The latest release of TETRIXTechTree has a typo in the version number, as confirmed by the author:
- https://spacedock.info/mod/2299/TETRIX%20TechTree#changelog (`2.13.202109.2` should be `2.13.20210902`)
- https://forum.kerbalspaceprogram.com/index.php?/topic/174731-1122-tetrix-techtree-213-and-simplex-techtree-121/&do=findComment&comment=4027073
Due to the regex added in #8646, the inflation fails.
The author offered us to completely drop the date parts of the version number in future releases, so we could get rid of the regexs completely.
However as we don't know when new releases will drop, for now I'm editing the regex to cope with the typo and get the release indexed.
This makes the regex more ambiguous, now we only rely on the date part beginning with at least 4 digits, and take …
=> Make TETRIXTechTree version_edit regex typo-safe

NetKAN/NewTantares.netkan
Closes KSP-CKAN/CKAN-meta#2447.
Looks like we didn't get a version file after all.
=> Update (New)Tantares compatibility

NetKAN/ScrapYard.netkan
@zer0Kerbal has clarified that the original version file is still applicable, and that this mod isn't bundling ContractConfigurator. Now we tell Netkan which version file to use.
https://forum.kerbalspaceprogram.com/index.php?/topic/192456-112x-scrapyard-the-common-part-inventory-2200-prerelease-2021-jul-19/page/3/&tab=comments#comment-4033347
=> Specify name of ScrapYard version file

NetKAN/GrannusExpansionPack-Rescale.netkan
The folder for this 2.X rescale patch has moved, because there's now also a new 10X rescale patch.
Probably won't inflate properly due to version file syntax errors, see OhioBob/Grannus-Expansion-Pack#7.
=> Fix GrannusExpansionPack-Rescale install folder

NetKAN/OreToParts.netkan
https://github.com/Goufalite/OreToParts
https://forum.kerbalspaceprogram.com/index.php?/topic/203705-11121121ore
Fixes #8781.
- `version` removed because it will be pulled from each release
- `asset_match` removed because the releases have only one non-source asset
- `resources.license` removed because it's just a link to the standard definition of CC-BY-SA-4.0
- `author` removed because the same value will be pulled from the repo automatically
=> Add OreToParts

NetKAN/HangarGrid.netkan
Some things were missed in KSP-CKAN/NetKAN#8796.
- Mod depends on itself unintentionally
- `resources.homepage` and `resources.repository` set unnecesarily
- Empty `install` list
These will be fixed here.
=> HangarGrid fixes

NetKAN/StrangeNewWorlds.netkan
The author has let me know that the current release of this mod works in the range of KSP 1.8 to KSP 1.12.
This also matches their comments on the forum thread:
https://forum.kerbalspaceprogram.com/index.php?/topic/202909-18-111-strange-new-worlds-a-new-high-quality-star-system-to-explore/&do=findComment&comment=4001617
They don't want to update the SpaceDock page or forum thread title until the next update though.
=> Override compat of StrangeNewWorlds v0.1.2

NetKAN/ModuleManager.netkan
ModuleManager has a pretty decent wiki describing the syntax, but it's not hugely discoverable.
Now it's added to `resources.manual` so I can easily click it from the Netkan status page.
=> Add resources.manual for ModuleManager

NetKAN/C1ustasTUFXProfiles.netkan
The author of this mod changed their username (on SpaceDock, the forum, Discord, and probably a lot of other places as well), and with the latest release the directory name in the ZIP has been adjusted accordingly:
> New inflation error for C1ustasTUFXProfiles: No files found matching find="C1usta TUFX" to install!
=> Fix install stanza for Adiri's TUFX Profiles

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
#8700 added an unbounded override.
See https://github.com/KSP-CKAN/NetKAN/pull/8700#issuecomment-965111147, the override should not apply to the next release.
Now the override stops at that next release's predicted version number.
=> More Scatterer compat adjustments

NetKAN/MinorPlanetsExpansionRevived.netkan
While reviewing #8859 I realized that these two mods probably functionally conflict as they add many of the same planets.
Now the conflict is in the metadata.
___
=> Conflicts between MinorPlanetsExpansionRevived and MinorPlanetsExpansion

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
Latest Scatterer update (0.0825b) changed the capitalization of the directory name in GameData from `scatterer` to `Scatterer`.
This seems to cause some issues within CKAN, especially on systems with case-insensitive filesystems (-> Windows).
The `install_to` stanza of the config and sunflare modules still install it with a the lower-case directory name.
On Linux, this creates to separate directories, on Windows the one that gets installed first wins.
There might still be code fixes needed in the client, but at least the metadata is correct now.
Note that while the `find` properties where still lowercase too, the relevant parts within netkan and the client did match those case-insensitive, that's why we didn't get "No file found to install errors" after the update.
=> Fix install_to capitalization of Scatterer config and sunflare

NetKAN/ShipManifest.netkan
KSP 1.12 can crash if it finds two DLLs with the same name.
Currently `ConnectedLivingSpace` ships a `CLSInterfaces.dll` file that is _intended_ to be used that way. `ShipManifest` bundles this DLL, so if both mods are installed, the game can crash.
The author is planning to rename this file to eliminate the conflict:
https://forum.kerbalspaceprogram.com/index.php?/topic/109972-111x-connected-living-space-v2006-29-dec-2020/&do=findComment&comment=4058927
Now CKAN will install the `CLSInterfaces.dll` from the current release of `ShipManifest` as `SM_CLSInterfaces.dll`. This should fix the problem without breaking anything else.
At the moment I just want to submit this to make sure it works as expected in the validation scripts. If so, it may be suitable to merge, but I want to confirm with …
=> Try to rename ShipManifest's CLSInterfaces.dll

NetKAN/GPP.netkan, NetKAN/GPPSecondary.netkan, NetKAN/GrannusExpansionPack.netkan
The latest release announcements for GPP, GEP, and JNSQ all say:
Now GPP, GPPSecondary, and GEP conflict with Scatterer 3:0.0825b and later (on the assumption that the latest Scatterer changes will not be rolled back).
JNSQ has a metanetkan, so Team Galileo will have to handle that one themselves.
https://raw.githubusercontent.com/Galileo88/JNSQ/master/CKAN/JNSQ.netkan
We will probably have to add this conflict to all the historical versions as well to prevent them from being installed if the user installs Scatterer first.
=> Try to enforce Scatterer compatibility for GPP and GEP

NetKAN/GPP.netkan, NetKAN/GPPSecondary.netkan, NetKAN/GrannusExpansionPack.netkan
Right now the latest versions of GPP, GPPSecondary, and GEP conflict with _all_ versions of Scatterer. That's very wrong.
In #8880, I tried to add a version-specific conflict to these mods. However, since I very frequently use the `ksp_version_min` property and almost never the `min_version` property, I typed `version_min` instead, which is not a relationship property. The client interprets this as a conflict with no version limits.
Now the `version_min` properties are changed to `min_version`.
=> GPP/GEP: version_min → min_version

NetKAN/ContractConfigurator-HistoricMissions.frozen, NetKAN/ContractConfigurator-HistoricMissionsRSS.frozen
There are two variants of HistoricMissions, one for RSS and one for "stock".
They are currently not marked as conflicts, which they should be as they try to write the same files.
Both modules are already frozen due to inactivity, a CKAN-meta PR will follow in a minute, this one is just for completeness.
=> Add conflicts between ContractConfigurator-HistoricMissions variants

NetKAN/BrickMod.netkan
#8886 missed a few things.
There's a version file in the wrong folder in the ZIP, but Netkan can still read it.
Tags.
=> Tags, vref, and license fix for BrickMod

NetKAN/StockWaterfallEffects.netkan
The author of StockWaterfallEffects kindly left us a a note on Discord that the [latest release](https://github.com/KnightofStJohn/StockWaterfallEffects/releases/tag/0.6.0) has a new dependency, B9PartSwitch:
=> Add B9PartSwitch dependency to StockWaterfallEffects

NetKAN/StratPlusPlus.netkan
This was supposed to be an auto-generated PR from SD, but `requests` threw these while trying to download it:
```
OSError: [Errno 14] Bad address
urllib3.exceptions.ProtocolError: ("Connection broken: OSError(14, 'Bad address')", OSError(14, 'Bad address'))
requests.exceptions.ChunkedEncodingError: ("Connection broken: OSError(14, 'Bad address')", OSError(14, 'Bad address'))
```
It worked fine when I tried it locally, so chalking this up to a transient network problem for now.
https://spacedock.info/mod/2921/Strat%2B%2B
=> Add StratPlusPlus

NetKAN/CactEyeCommunityRefocused.netkan
Fixes for #8923.
- `resources.homepage` was out of date and will now be retrieved from SpaceDock, which has the right URL
- `resources.repository` is now retrieved from SpaceDock
- `resources.bugtracker` is now retrieved from SpaceDock
- `resources.spacedock` is now retrieved from SpaceDock
- `name` is now retrieved from SpaceDock
- The conflict with `CactEyeTelescopesContinued` is removed because this was completely frozen in KSP-CKAN/CKAN-meta#1198 and is not in CKAN anymore
- YAMLized
=> CactEye fixes

NetKAN/DefaultActionGroups.netkan, NetKAN/IndicatorLights.netkan, NetKAN/MissingHistory.netkan
#8309 added overrides to pin the minimum compatibility of these mods to their original values. Since then, they have had new releases without overrides, and the latest wave of updates lost the original compatibility:
https://github.com/KSP-CKAN/CKAN-meta/compare/982c540e68...73a534f848
Now these versions have pinned min compat as well.
=> Update Snark compat overrides

NetKAN/UnKerballedStart.netkan
While we were working on #8936, @theonegalen said:
This PR switches the kref from SpaceDock to GitHub.
- The authors are added to the netkan to avoid dropping one of them
- A `x_netkan_version_edit` is added to strip the `v` from the version so v1.3.0 will match 1.3.0
- `resources.homepage` and `resources.spacedock` are added to the netkan
This should allow the intended compatibility, 1.12.2 and later, to take effect.
=> Switch UnKerballedStart to GitHub kref

NetKAN/AirlineKuisine.netkan, NetKAN/BARIS.netkan, NetKAN/BOMPs.netkan, NetKAN/CustomAsteroids-Pops-OPM-Outer.netkan, NetKAN/CustomAsteroids-Pops-OPM-Reconfig.netkan, NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan, NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan, NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan, NetKAN/DSEV.netkan, NetKAN/DavonSupplyMod.netkan, NetKAN/EVAHandrailsPackContinued.netkan, NetKAN/Heisenberg.netkan, NetKAN/JDiminishingRTG.netkan, NetKAN/KSP-PartVolume.netkan, NetKAN/KaptainsLog.netkan, NetKAN/KerbalKomets.netkan, NetKAN/MOLE.netkan, NetKAN/Mk-33.netkan, NetKAN/NavBallTextureChangerUpdated.netkan, NetKAN/Pathfinder.netkan, NetKAN/RoutineMissionManager.netkan, NetKAN/ServoController.netkan, NetKAN/TestFlightConfig-KerbalAtomics.netkan, NetKAN/TestFlightConfig-NFPropulsion.netkan, NetKAN/TestFlightConfig-NFSpacecraft.netkan, NetKAN/TestFlightConfig-Stock-S42.netkan, NetKAN/TestFlightConfigLibrary.netkan, NetKAN/WernherCheckerContinued.netkan
These mods were violating the spec by using `filter_regexp` with a spec version older than v1.10, which has been caught now that KSP-CKAN/CKAN#3494 is merged. Now they're updated to v1.10 (and YAMLized).
___
ckan compat add 1.8 1.11 1.12
=> Fix spec versions of mods with filter_regexp

NetKAN/KerbalKomets-PlayMode-CRP.netkan, NetKAN/KerbalKomets-PlayMode-ClassicStock.netkan, NetKAN/KerbalKomets.netkan, NetKAN/WildBlue-PlayMode-Pristine.netkan, NetKAN/WildBlue-PlayMode-Simplified.netkan
This mod has play modes and should have been included in #8275, but I only found out about it while reviewing output from #8943.
Now two new play mode modules are created for CRP and ClassicStock, and the WildBlueTools play modes for Pristine and Simplified provide KerbalKomets play modes as well.
=> Split out KerbalKomets play modes

NetKAN/KerbalKomets-PlayMode-CRP.netkan, NetKAN/KerbalKomets.netkan
After #8944 I noticed that:
- KerbalKomets doesn't need its MM dep anymore (MM syntax is only used by the play modes)
- The CRP play mode is installing into the wrong folder (`CRP` part of the path is missing)
Now this is fixed.
=> Fix KerbalKomets dependencies and paths

NetKAN/GroundEffect.netkan
The author does not draw a distinction between 1.11 and 1.12:
=> Mark GroundEffect compatible with 1.12

NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan
Hello, I'm about to release an update which restores compatibility to 1.9-1.12.x
I'm not sure I did this correctly though?  The [spec page](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md) explains how to use the operators but there seems to be no mention of what the `3:` preceding the version number does. In doubt I just pushed it like this.
=> Update scatterer Sompatibility

NetKAN/DistantObject.netkan, NetKAN/HotSpot.netkan, NetKAN/KSP-Recall.netkan, NetKAN/ModularFuelTanks.netkan, NetKAN/SpaceXLegs.netkan, NetKAN/SpaceY-Lifters.netkan, NetKAN/TweakScale.netkan, NetKAN/TweakScaleCompanion-ReStockPlus.netkan
=> Fix spec versions for supports and license arrays

NetKAN/FossilsMechazilla.netkan
See conversation in #8872; this is now set to 1.12.3 compatibility on SpaceDock, so we only need to pin the minimum compatibility.
=> Remove FossilsMechazilla max compat override

NetKAN/KerbalImprovedSaveSystem.netkan
This mod has been updating the same release's compatibility via SpaceDock since KSP 1.9. Now it spans that range.
There's an existing override that wasn't working because `version` was missing a `v`, which is now fixed.
=> Pin KerbalImprovedSaveSystem min compat

NetKAN/CollisionFXReUpdated.netkan, NetKAN/KSCExtended.netkan, NetKAN/MandatoryRCS.netkan, NetKAN/MandatoryRCSPartPack.netkan, NetKAN/RealHeat.netkan, NetKAN/TransparentPods.netkan
This is #8975 for mods where the remote version file URL can be retrieved but isn't a version file.
=> Set resources.remote-avc for mods with bad version file URL properties

NetKAN/GasGiantsEnhanced.netkan
This mod can be used with either RSS or [KSRSS](https://forum.kerbalspaceprogram.com/index.php?/topic/192818-beta-ksrss-07-kerbin-or-x25-sized-rss/), but currently we have it depending on RSS. If a user wants to use KSRSS instead, there's no way to not install RSS.
KSRSS is not in CKAN and is hosted on GitLab, so the best we can do is to allow RSS to be removed. So now RSS is recommended instead of a depends.
Fixes #9000.
=> Change GasGiantsEnhanced dep on RSS to rec

NetKAN/StockDepthMaskConfig.netkan
This mod is currently failing with:
> No files found matching find_regexp="Stock_DepthMask_Config-[0-9.]+" to install!
Release 1.0 for which this stanza has been written has been removed from SpaceDock.
With release 1.1 the mod had no root folder at all in the zip, but all the files directly.
Now with release 1.2 an above there is an easily installable  `StockDepthMaskConfig` folder.
=> Fix StockDepthMaskConfig find_regexp

NetKAN/PlanetInfoPlus.netkan
Confirmed on the thread, it's a MM patch to turn off some conflicting behavior in Kopernicus.
=> Add MM dep to PlanetInfoPlus

NetKAN/BuranEnergia.netkan
This mod's folder structure changed in its latest release. The `Buran Energia` folder was replaced by two new folders, but there were no inflation errors because there's also a `RealismOverhaul/RO_SuggestedMods/Buran Energia` folder, which is being installed instead of the right folder.
Now we install the two folders that replaced the original one.
=> Fix BuranEnergia install

NetKAN/ConformalDecals.netkan, NetKAN/Shabby.netkan
https://spacedock.info/mod/2451/Conformal%20Decals
https://github.com/drewcassidy/KSP-Conformal-Decals
https://forum.kerbalspaceprogram.com/index.php?/topic/194802-18-111-conformal-decals-028-decals-done-the-right-way/
http://taniwha.org/~bill/Shabby.version
https://github.com/taniwha/Shabby
~~We still need to check with @taniwha to see if adding Shabby to CKAN is OK before merging.~~ Submitting the PR just for metadata validation. Should merge KSP-CKAN/CKAN#3494 first to be safe, since the `filter_regexp` in Shabby is how I noticed that issue.
=> Add Conformal Decals and Shabby

NetKAN/RocketSoundEnhancement-Config-Default.netkan, NetKAN/RocketSoundEnhancement.netkan
The config module for RocketSoundEnhancement has been moved to its own repo.
- YAMLized both modules
- Pointed the config module to the new repo
- Removed the `asset_match`es that were stopping the current release from being indexed
- Removed "Configs" from the `name` as per author request
- Use default install stanza for RocketSoundEnhancement
- Update install stanza for config module to use new folder name
Fixes #9044.
=>  Switch Rocket Sound Enhancment - Default repo, rename

NetKAN/RealFuels-Stock.netkan, NetKAN/SmartDockingAid.netkan
See https://github.com/KSP-CKAN/CKAN-meta/compare/0191dd4b771bd9886ffeeea0189ecfaef1b31eac...1252839a77, ValiZockt is now @ValentinBischof. We have two netkans with the old name in the `$kref`, which are now updated so we are not at the mercy of GitHub's temperamental redirects.
=> Update krefs for ValiZockt name change

NetKAN/TransferWindowPlannerFork.netkan
I forked TWP to make it useful for transfers between planets that have non-zero inclination (by specifying which inclined parking orbit should be used). This is especially important in RSS, but also in stock it can reduce Δv requirements by several hundred m/s for some transfers. 
In the process, I updated it for 1.12.
It would be great to have on CKAN for easier installation, but I want it clear to users that it is a fork and not the original mod by TriggerAu.
Relates to Nazfib/TransferWindowPlanner#1.
___
https://github.com/Nazfib/TransferWindowPlanner
=> Add TransferWindowPlanner - Fork

NetKAN/Singularity.netkan
Singularity was set up with hard coded compatibility in #7885 because SpaceDock didn't match the forum thread.
Now this is replaced by a min compat override for the latest version.
https://spacedock.info/mod/2420/Singularity
Closes KSP-CKAN/CKAN-meta#2633.
=> Remove Singularity compat hard coding

NetKAN/IntercolorTantaresRecolors.netkan
The CKAN badge is checked on SpaceDock, but we didn't get a PR.
Author mentioned it on the forum:
- https://spacedock.info/mod/2604/Tantares%20Intercolor%20%28Recolors%29
- https://forum.kerbalspaceprogram.com/index.php?/topic/199605-112x-intercolor-cre-recolors-tantares-recolors/page/3/
- https://github.com/Zarbon44/Intercolor
A sibling mod was indexed in #8639.
=> Add IntercolorTantaresRecolors

NetKAN/BoosterGuidance.netkan
A warning was missed in #9077:
https://github.com/KSP-CKAN/NetKAN/pull/9077/checks
Now the crafts are installed to `Ships/VAB`.
=> Install BoosterGuidance crafts in Ships

NetKAN/KerbolsHumbleNeighboringStars.netkan, NetKAN/VertexMitchellNetravaliHeightMap.netkan
Adding KHNS has been requested by the author, and adding the dependency has been okayed by its author (Niako, on Discord seen as "Duck Trademark")
<details>
</details>
KHNS bundles some Scatterer configs, but they are only for the new planets so no `provides` required.
We'll likely have to epoch once this mod is out of alpha due to the `Alpha-` prefix for all existing releases.
Links:
- https://forum.kerbalspaceprogram.com/index.php?/topic/207835-khns-kerbols-humble-neighboring-stars/
- https://forum.kerbalspaceprogram.com/index.php?/topic/207768-112-niakos-kopernicus-utilities-smoother-heightmaps/
- https://github.com/parkerman-com/KHNS
- https://github.com/parkerman-com/KHNS/releases
- https://github.com/pkmniako/Kopernicus_VertexMitchellNetravaliHeightMap
- …
=> Add KerbolsHumbleNeighboringStars and VertexMitchellNetravaliHeightMap

NetKAN/ResourceOverview.netkan
The validator raised this warning on #9098:
Now tags are added.
=> Tags for ResourceOverview

NetKAN/OblivionAerospace.netkan
All previous versions of this mod started with a `v`, latest adoption dropped it, see KSP-CKAN/CKAN-meta#2690.
Now `x_netkan_force_v` is set to add the `v` instead of epoching.
Closes KSP-CKAN/CKAN-meta#2690.
=> force_v for OblivionAerospace

NetKAN/CraftManager.netkan
Forum thread says KSP 1.3-1.9:
https://forum.kerbalspaceprogram.com/index.php?/topic/174596-13x-19x-craft-manager%C2%A0-search-sort-tag-share-your-craft/
1.3 - 1.7 are covered by earlier releases:
So the latest one is 1.8-1.9 only.
=> Limit CraftManager compatibility to KSP 1.8-1.9

NetKAN/FerramAerospaceResearchContinued.netkan, NetKAN/InfernalRoboticsNext.netkan, NetKAN/InfernalRoboticsRealismOverhaul.netkan, NetKAN/TweakScale-Redist.netkan, NetKAN/TweakScale.netkan
See #9108, while the `Scale_Redist.dll` was [initially supposed to be redistributed by all mods](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-130-tweakscale-under-lisias-management-24612-2022-0429/&do=findComment&comment=3686252) that need it (to integrate with TweakScale), this [has changed recently](https://forum.kerbalspaceprogram.com/index.php?/topic/179445-18-112-ferram-aerospace-research-continued-v01605-mader-030422/&do=findComment&comment=4100878), likely as a response to KSP 1.12.0-2's crash on duplicate DLLs bug.
Now we split the `999_Scale_Redist.dll` into a separate module `TweakScale-Redist`.
TweakScale itself, InfernatRoboticsRealismOverhaul, InfernalRoboticsNext and FerramAerospaceResearchContinued have been updated to filter the `Scale_Redist.dll` and …
=> Add TweakScale-Redist, filter DLL from IR and FAR

NetKAN/SpaceDustUnbound.netkan
#9117 requested the GalaxiesUnbound recommendation to be changed to GalaxiesUnbound-Core (which we should have done in #8996) and BlueShift to be suggested instead of recommended. This is now done.
Fixes #9117.
=> Update SpaceDustUnbound's relationships

NetKAN/GPOSpeedPump.netkan
GPOSpeedPump (spacedock 546) is under new management, and being added to CKAN.
Cheers!
=> GPOSpeedPump under new management!

NetKAN/FoxDefenseContracts.netkan
In #9123 we updated the `install` property for this mod to compensate for some problems with how the previous release was packaged. After reporting these problems on the forum, the author pretty quickly uploaded a fixed version, which doesn't have all the paths we were picking out of the broken one.
Now the `install` is redone based on the latest upload.
___
=> Remove FoxDefenseContracts install workarounds

NetKAN/KerbolsHumbleNeighboringStars.netkan
The author pinged me on Discord that with the [latest update](https://github.com/parkerman-com/KHNS/releases/tag/Beta-1.1) Scatterer is now a hard dependency.
=> Move Scatterer to dependencies of KHNS

NetKAN/KerbolsHumbleNeighboringStars.netkan
#9127 added the Scatterer dependency to KHNS, but apparently it's one of the rare planet mods that ship a full Scatterer config instead of modifying it with a ModuleManager patch.
Now it provides `Scatterer-config` and `Scatterer-sunflare` so it doesn't pull in the default ones.
=> KHNS ships with a full Scatterer config & sunflare, provide them

NetKAN/StarshipLaunchExpansion.netkan
Also this mod is recommending itself.
Now a vref is added and it recommends StarshipExpansionProject as it should have in #8662.
=> Vref for StarshipLaunchExpansion, fix rec

NetKAN/AdjustableModPanel.netkan
A functional conflict has been discovered between these two mods, see:
https://forum.kerbalspaceprogram.com/index.php?/topic/207263-112x-adjustable-mod-panel-kamp-v15990-adoption-edition-09-apr-2022/&do=findComment&comment=4128958
=> Add conflict between AdjustableModPanel and JanitorsCloset

NetKAN/AlcubierreStandalone.netkan, NetKAN/CommunityCategoryKit.netkan, NetKAN/CommunityResourcePack.netkan, NetKAN/Karbonite.netkan, NetKAN/Konstruction.netkan, NetKAN/MalemuteRover.netkan, NetKAN/SoundingRockets.netkan, NetKAN/UKS.netkan, NetKAN/USI-ART.netkan, NetKAN/USI-Core.netkan, NetKAN/USI-EXP.netkan, NetKAN/USI-FTT.netkan, NetKAN/USI-LS.netkan, NetKAN/USI-NuclearRockets.netkan, NetKAN/USITools.netkan
There are various problems with the USI mods' metanetkans:
- ![image](https://user-images.githubusercontent.com/1559108/171032401-1f850820-16a5-4ba0-bb30-ce9b5b8561fd.png)
Orion's folder name was changed from `Orion` to `NuclearRockets`, and the metanetkan in this repo still has the old name.
- Some have dependencies that are probably outdated going by their bundled folders
- Some are missing a ModuleManager depends
Since all these mods have metanetkans in the https://github.com/UmbraSpaceIndustries/CKAN repo, we have to submit pull requests to fix these problems. However, that process has broken down:
- UmbraSpaceIndustries/CKAN#27 was submitted four years ago to fix some of the relationships
- UmbraSpaceIndustries/CKAN#29 was submitted two years ago to fix some of the relationships
- …
=> De-meta UmbraSpaceIndustries mods

NetKAN/KerbalTelemetry.netkan, NetKAN/RND.netkan
This is now replaced by two folders, `Textures` and `WebServer`.
The sample craft is no longer included.
=> Fix multiple mods' installs

NetKAN/NTChineseRocketsPack.netkan
- `NTCP` is replaced by `NCAP` (confirmed in the README)
- There's a `CRAFT FILES` folder containing some sample craft
- Might as well also install the changelog
=> Fix NTChineseRocketsPack install

NetKAN/EcoRocket.netkan
SpaceDock said MIT when #9185 was submitted, but it's been updated.
https://spacedock.info/mod/3050/EcoRocket
https://forum.kerbalspaceprogram.com/index.php?/topic/208750-112x-arcaspace-ecorocket-for-ksp/#comment-4149638
=> Fix EcoRocket license

NetKAN/BakerOperatingSystem.netkan
See KSP-CKAN/CKAN-meta#2822 and #9191 and KSP-CKAN/CKAN-meta#2823, this mod had some extra versions as a compatibility workaround, but as per the author they've been removed, so it's now unfrozen with an override for the min compat.
=> Unfreeze BakerOperatingSystem

NetKAN/PrakasaAeroworks.netkan
I think this was frozen before we added that warning.
=> Vref for PrakasaAeroworks

NetKAN/PlanetShine.netkan
#9011 switched this mod to a new fork, but it left `resources.repository` pointing to the old fork. This made KSP-CKAN/CKAN-meta#2844 more confusing to investigate. Now it's removed so the `GitHubTransformer` can set it to the correct value automatically.
=> Remove PlanetShine's repository override

NetKAN/BakerOperatingSystem.netkan
This mod's folder structure has changed.
There's also a version file now, but it has a `.txt` extension instead of `.version`, and we can't override Netkan's search logic to match that.
___
=> Fix BakerOperatingSystem install

NetKAN/ProceduralParts.netkan
As of the latest version of ProceduralParts, KSPCF is needed. Adding as a dependency
=> Add KSPCF as dependency to ProceduralParts

NetKAN/PhotoRealisticVisualEnhancement-64k.netkan, NetKAN/PhotoRealisticVisualEnhancement-LowRes.netkan
https://github.com/SpaceODY/PRVE
- Filename format for 64k changed from `PRVE64k-` to `PRVE-64k`
- New low res variant added starting as copy of regular variant
- Conflicts added between low res and regular. One conflict would be enough for the relationship resolver, but this way it will show up under the Relationships tab for both mods.
Fixes #9222.
=> Updates for PhotoRealisticVisualEnhancement

NetKAN/Spectra-VibrantSunsets.netkan, NetKAN/Spectra.netkan
- That install is changed from `2 -` to `2-` to match the latest version
- A new `Spectra-VibrantSunsets` module is added, suggested by `Spectra`, which installs from the `Step 3- Extras` folder
=> Spectra Vibrant Sunsets and install fix

NetKAN/Spectra-JoolShineOnLaythe.netkan, NetKAN/Spectra-KerbinLaytheSnow.netkan
#9233 and #9234 were merged too soon, the `Spectra_EVE` and `Spectra_Scatterer` folders are supposed to be installed into `Spectra` directly without extra parent folders. Confirmed with author via Discord VM.
=> Fix Spectras Extras installs

NetKAN/Spectra-JoolShineOnLaythe.netkan, NetKAN/Spectra-KerbinLaytheSnow.netkan, NetKAN/Spectra-MinmusGeysers.netkan, NetKAN/Spectra-MinmusScatterer.netkan, NetKAN/Spectra-VibrantSunsets.netkan
Spectra has "Extras" that look like this:
In #9238 and #9236 and #9235 and #9231 we set up netkans to install these by selecting the `Spectra_EVE`, `Spectra_Scatterer`, and `Spectra_textures` folders and installing them to `GameData/Spectra`. While this gives a correct result, it's somewhat inflexible; if @Avera9eJoe subsequently decides for example to add a `Minmus Geysers/Spectra_Scatterer` folder, we would need to update the netkan to install that. (Also I have some ulterior motives related to internal .ckan files which may come to fruition at a later time.)
Now we select the main folder for each Extra and use `as` to rename it to Spectra and install it to GameData. This should still produce a correct install but with more futureproofing for these modules. The `spec_version`s are …
=> Install whole subfolders of Spectra Extras

NetKAN/SRBWaterfallEffects.netkan
Folder names this mod has used in the ZIP:
- `srb_waterfall_effects` (#9028)
- `SWE 2.0` (#9188)
- `GameData/SWE` (#9030)
- `SWE` (#9101)
- `SRBWE` (#9214)
... and now back to `SWE`.
=> Fix SRBWaterfallEffects install again again again

NetKAN/Spectra-JoolShineOnLaythe.netkan, NetKAN/Spectra-KerbinLaytheSnow.netkan, NetKAN/Spectra-MinmusGeysers.netkan, NetKAN/Spectra-MinmusScatterer.netkan, NetKAN/Spectra-VibrantSunsets.netkan, NetKAN/Spectra.netkan
See KSP-CKAN/CKAN#3615, we are planning to move Spectra's relationships to internal .ckan files so @Avera9eJoe can manage them more easily. This PR removes them from the netkans. It should not be merged until there is a new Spectra release containing the corresponding internal .ckan files.
https://spacedock.info/mod/1505/Spectra
=> Let Spectra's internal ckan files set its relationships

NetKAN/AutomatedScreenshots.netkan
#7729 changed this mod to also recommend its dependencies. There's no point to that; since the mods are in `depends`, they must always be installed, unlike `recommends` which the user is supposed to be able to opt out of.
Now the recommendations are removed. Also YAMLized.
Noticed while randomly scrolling through mods looking for one with lots of relationships to illustrate a point for KSP-CKAN/CKAN#3616.
=> Remove redundant recommends from AutomatedScreenshots

NetKAN/Shabby.netkan
In #8922 we indexed Shabby based on an alternate version file at https://pileof.rocks/KSP/Shabby.version because it was the only way to index a release that worked with Conformal Decals, but apparently this was a fly-by-night release that wasn't really integrated with the main Shabby workflows or kept up to date with development, because now the inverse is true; the taniwha.org file has 0.3.0 but @drewcassidy's is stuck at 0.2.0. Noticed while investigating KSP-CKAN/CKAN#3623.
Now it's switched to the more official one, which should cause 0.3.0 to be indexed and allow installation allongside Shaddy.
=> Switch to main Shabby version file

NetKAN/Shaddy.netkan
In #9240 I suggested `v0.2.0` should be the minimum version of Shabby that Shaddy supports. 
Now that Shabby 0.3.0.0 has been added to CKAN in #9262, and apparently, CKAN doesn't think 0.3.0.0 is above v0.2.0 and is stopping me from installing Shaddy v2.1 when Shabby 0.3.0.0 is installed. The reverse is also true: when Shaddy v2.1 is installed, I cannot install Shabby 0.3.0.0.
I have therefore changed the max_version of Shabby in the conflicts section from `v0.2.0` to `0.2.0.0` to match the version scheme Shabby uses.
I am using CKAN v1.31.0 in case it is me who messed up something with CKAN.
Aso do we have to update the [meta file](https://github.com/KSP-CKAN/CKAN-meta/blob/master/Shaddy/Shaddy-v2.1.ckan)?
=> Fix Shabby max_version in conflicts section

NetKAN/ErsteSterne.netkan, NetKAN/KerbolsHumbleNeighboringStars.netkan
In #9184 and #9128 we added `Scatterer-config` and `Scatterer-sunflare` to the `provides` for two mods. These identifiers are supposed to be mutually exclusive, in that if you try to install multiple mods providing them, they won't work. Historically we've added conflicts for other mods, but we missed it in these cases.
Now both of these mods conflict with the identifiers they provide.
I'll also do this in CKAN-meta if needed.
Noticed while tracking down some weird behavior in the relationship resolver for KSP-CKAN/CKAN#3635.
=> Add conflicts to ErsteSterne and KHNS for provides

NetKAN/GalaxiesUnbound-StockClouds.netkan
There's one more module that we missed in #8515:
Now it's added.
=> Add Galaxies Unbound optional Clouds module

NetKAN/FoxDefenseContracts.netkan
This mod's February 2021 release changed its dependency from BDArmoryContinued to 
BDArmoryForRunwayProject (since rebranded "BDArmory Plus")
Now the dependency is updated to `BDArmory` in the netkan, which is in the `provides` list of both mods. We'll update the historical releases from then on as well.
=> Switch FoxDefenseContracts to BDArmoryForRunwayProject

NetKAN/RadialHeatShields.netkan
CKAN installs this mod to `GameData/RadialHeatShields`, however it needs to be placed in `GameData/OrionSpaceIndustries/RadialHeatShields` according to the zip.
=> Fix RadialHeatShields install location

NetKAN/FerramAerospaceResearchContinued.netkan
Next version of FerramAerospaceResearchContinued will depend on KSPBurst.
Also, could you change the indexed versioning to be dependent on the release tag instead of master branch? I'm not sure which field needs to be changed and to what. Thanks.
=> Update FerramAerospaceResearchContinued dependencies

NetKAN/Parallax-ScatterTextures.netkan, NetKAN/Parallax-StockScatterTextures.netkan, NetKAN/Parallax-StockTextures.netkan, NetKAN/Parallax.netkan
Parallax_ScatterTextures is required alongside Parallax_StockTextures as of release 2.0.0. If stock textures are installed, these must also be installed. However, installing Parallax will not prompt either the stock textures or scatter textures to download.
https://github.com/Gameslinx/Tessellation
=> Add Parallax-Scatter-Textures requirement

NetKAN/Parallax-StockScatterTextures.netkan, NetKAN/Parallax-StockTextures.netkan, NetKAN/Parallax.netkan
The core Parallax >=2.0.0 only works with the StockTextures and Textures >=2.0.0, so it makes sense to enforce this.
RP-1 depends on Parallax and Parallax-StockTextures 1.3.1, however making the dependency versioned doesn't work, as the relationship resolver pulls in the newer module of the other one when looking at the dependencies of whichever is listed first.
Then it fails with "Parallax - Stock Planet Textures 2.0.0 required, but an version is in the resolver".
https://github.com/KSP-RO/RP-1-ExpressInstall-Graphics/blob/d60207f63f0ef254095e7d4d3e3342dc1abdbc53/RP-1-ExpressInstall-Graphics-High.netkan#L18-L21
Now we make the latest (2.0.0) and all future Parallax releases conflict with Parallax-StockTextures <=1.3.1,
Parallax-StockTextures with Parallax <=1.3.1, and …
=> Make Parallax 2.0.0 modules conflict with <2.0.0 releases

NetKAN/Parallax-StockScatterTextures.netkan, NetKAN/Parallax-StockTextures.netkan, NetKAN/Parallax.netkan
In KSP-CKAN/NetKAN#9321, @infoman rightly points out a problem with that PR:
> But does ckan client even support `version_max` in conflicts? I don't see it being registered in `registry.json` and github search in this repo does not know about other records with version_max, and now parallax has conflict with it's own textures
> 
> maybe it should have been `max_version`?
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#relationships
Now it's `max_version`.
=> Fix Parallax conflict version deps

NetKAN/StarilexMk1NeedleIVA.netkan
This mod was uploaded to SpaceDock after we added it in #9326 and GitLab krefs for it in KSP-CKAN/CKAN#3661.
https://spacedock.info/mod/3113/Starilex%20Intra-Vehicular%20Solutions:%20MKI%20Pod%20'Needle'
Now `resources.spacedock` links to that page.
=> Add resources.spacedock to StarilexMk1NeedleIVA

NetKAN/Buffalo2.netkan
Moved KerbalActuators to the dependency list.
=> Buffalo 2 requires Kerbal Actuators

NetKAN/KerbalFlightworksCompany.netkan, NetKAN/OblivionBubblePatrolCraft.netkan
SpaceDock migrated to new hosting, but the whitelisted webhook IPs have not been updated, so we're in another period of having to add new mods manually. These are the recently uploaded mods with CKAN badges:
- https://spacedock.info/mod/3114/Oblivion%20Bubble%20Patrol%20Craft
- https://spacedock.info/mod/3116/Kerbal%20Flightworks%20Company
___
=> Post-migration SpaceDock catch-up 1

NetKAN/ColorChangingSmokeGenerator.netkan, NetKAN/KerbalBall.netkan, NetKAN/LudicrousParts.netkan, NetKAN/ShadoUFO.netkan, NetKAN/StockalikeAircraftCarrierDecks.netkan
SpaceDock migrated to new hosting, but the whitelisted webhook IPs have not been updated, so we're in another period of having to add new mods manually. These are the recently uploaded mods with CKAN badges:
- https://spacedock.info/mod/3105/SHADO%20UFO
- https://spacedock.info/mod/3106/Color%20changing%20smoke%20generator
- https://spacedock.info/mod/3108/LudicrousParts
- https://spacedock.info/mod/3110/S.A.C.D
- https://spacedock.info/mod/3111/Kerbal%20Ball
Follow-up to #9336.
=> Post-migration SpaceDock catch-up 2

NetKAN/BetterKerbol.netkan, NetKAN/BetterKerbolRescale.netkan
See KSP-CKAN/NetKAN-Infra#277, the SpaceDock webhooks are down so we have to check for mods with the CKAN badge manually. This time there's only one (but it has an optional component):
- https://spacedock.info/mod/3118/BetterKerbol
- https://forum.kerbalspaceprogram.com/index.php?/topic/207389-112x-kopernicus-betterkerbol-v100-a-kerbol-graphics-enhancement/#comment-4176305
=> Add BetterKerbol

NetKAN/ModeratelyPlaneRelated.netkan
Now it matches the identifier, so the default stanza is used.
Also the dependencies are updated to reflect the latest README.
=> Fix ModeratelyPlaneRelated install

NetKAN/DMTanks-AeroRTG.netkan, NetKAN/DMTanks-CargoBays.netkan, NetKAN/DMTanks-Fuselage.netkan, NetKAN/DMTanks-SphericalTanks.netkan
Since #8567, these mods have been split into their own new repositories and SpaceDock has been updated, so hard-coding the link in the netkans breaks the links instead of fixing them.
Now we get the links from SpaceDock again.
~~I'm not sure of the status of the `remote-avc` links. For now I've removed them, and if we get inflation warnings I'll put them back and update them.~~
Yup, gotta keep and update the overrides.
=> Get DMTanks repositories from SpaceDock again

NetKAN/ExtremePlaneContracts.netkan
KSP-CKAN/NetKAN-Infra#277 has been fixed :tada:, but this one snuck in just before that.
- https://github.com/StarshipSLS/ExtremePlaneContracts
- https://spacedock.info/mod/3122/Extreme%20Plane%20Contracts
- https://forum.kerbalspaceprogram.com/index.php?/topic/209839-112x-extreme-plane-contracts/
~~I'm getting a 404 trying to download it from SpaceDock, so this netkan gets it from the source archive on GitHub, but hopefully the SpaceDock problem will be resolved and we can switch the kref back.~~
Author retried and it works now, kref switched to SpaceDock.
Tagging @StarshipSLS as an FYI.
=> Add ExtremePlaneContracts

NetKAN/HooliganLabsAirships.netkan, NetKAN/MOTHS.netkan, NetKAN/PicoPortShielded.netkan, NetKAN/RSSVE-HR.netkan, NetKAN/RSSVE-LR.netkan, NetKAN/StarshipLaunchExpansion.netkan, NetKAN/USI-NuclearRockets.netkan, NetKAN/WildBlueCore.netkan
These mods have bad `URL` properties in their version files. Usually we submit pull requests to the upstream repo to fix this; sometimes they sit unmerged, sometimes they're merged but no new release is forthcoming, sometimes they get re-broken by more edits between merge and release. This clutters the status page.
Now they're overridden as per KSP-CKAN/CKAN#3451. There are other mods with the same error but without a remote version file for an override, which are left unchanged.
=> Override bad version file URL properties

NetKAN/kOS-Astrogator.netkan
I almost forgot, versions of Astrogator prior to the current latest won't work for kOS-Astrogator because the `KSPAssembly` attribute wasn't set. Now that'll be reflected in CKAN just in case anybody has an old version installed.
This is an update to #9357.
___
=> Specify minimum version of Astrogator for kOS-Astrogator

NetKAN/Pathfinder.netkan
The original Buffalo has been supplanted by Buffalo2 (which is already in CKAN).
This update removes the Buffalo dependency and recommends Buffalo 2 in its place.
=> Updates Pathfinder to recommend Buffalo 2 and not depend on Buffalo

NetKAN/kOS-Astrogator.netkan
See HebaruSan/Astrogator#32. Version v1.0.0 is now required.
___
ckan compat add 1.11 1.12
=> Update kOS-Astrogator dep min version for Astrogator

NetKAN/Sandcastle.netkan
WildBlueCore isn't mentioned as a dependency anywhere, but it's bundled in Sandcastle's ZIP, and an error is printed at game startup by KSPCommunityFixes if you run without it (as you will if you install with CKAN):
Now the dependency is added.
=> Add WildBlueCore dep to Sandcastle

NetKAN/TweakScale.netkan
I have an external tool that installs 999_Scale_Redist.dll on the GameData for people that do manual installation and forget to install the Redist.
Such tool **is not** available on CKAN installs for obvious reasons, so the presence of the "reference dll" is not a problem (it's inside `PluginData`, a folder KSP doesn't touch).
However ZeroMiniAVC recently started to inspect 3rd parties folders for duplicates, and bluntly ignores that anything inside `PluginData` is not loaded by KSP and then started to pesky users about the presence of the "reference DLL".
The goal of this pull request is to prevent this file to be installed by CKAN, avoiding spurious support calls from people complaining about what's a misfeature on the ZeroMiniAVC tool and not a real problem.
=> Filter Scale_Redist.dll out of TweakScale

NetKAN/ClickThroughBlocker.netkan, NetKAN/ToolbarController.netkan
`ZeroMiniAVC` is very widely installed because `ClickThroughBlocker` and `ToolbarController` "depend" on it, and most of @linuxgurugamer's mods depend on one or both of those mods. I used scare quotes because they don't actually need `ZeroMiniAVC` to function, but rather CKAN's dependency system has been exploited to make this mod artificially more popular because @linuxgurugamer wanted users to have their `MiniAVC.dll` files deleted because the game broke compatibility with old versions of them at some point.
That artificial popularity has been abused previously to show additional mesages that have nothing to do with MiniAVC, annoying users and causing support hassles for other mod authors long after the original problem was solved, see linuxgurugamer/QuickMods#18.
@linuxgurugamer has …
=> Remove fake ZeroMiniAVC dependencies from LGG's mods

NetKAN/NeidonPlus.netkan
The folder now has an `OPM-` prefix.
=> Fix NeidonPlus install

NetKAN/FreeIva.netkan
Move reviva and b9ps to recommendations, because they're rellevant for stock parts
add newly supported mods
=> FreeIVA Updates

NetKAN/TweakScale.netkan
This thing is old, the patching format is deprecated and I had revamped the patches on TweakScale. There's no way this thing would be usefull nowadays, and I'm starting to get tickets about it again.
Since the very source of the add'on (SpaceDock) is not providing it anymore, I don't see another way to solve this problem but to declare a conflict.
TweakScale works fine on previous versions of KSP, to in essence, TweakscaleMakingHistoryConfigs is really uneeded.
=> Declares `TweakScaleMakingHistoryConfigs` as a conflict.

NetKAN/IXSWarpshipOS.netkan, NetKAN/WarpDrive.netkan
- IXSWarpshipOS recommends AlcubierreStandalone and WarpDrive, but it really _requires_ one or the other (but that wasn't possible to represent in metadata back then, see #6079 and #6080)
- WarpDrive has a forum thread, but it's missing from the CKAN metadata
- Now these relationships are moved to a `depends.any_of` clause
- Now WarpDrive's netkan has `resources.homepage` set to its forum thread
Fixes #9562.
=> Make IXSWarpshipOS depend on warp drive mods

NetKAN/MK12PodIVAReplacementbyASET.netkan, NetKAN/Mk1CockpitIVAReplbyASET.netkan, NetKAN/Mk1LanderCanIVAReplbyASET.netkan
In #9560:
- I forgot to set the `name` property on three modules sharing a `$kref`, so they all got indexed with the same name, which is confusing
- SpaceDock also doesn't have the original author, which is also therefore missing from the metadata
- Now the `name` is set to distinguish the modules based on their previous names
- Now the `author` is set to credit the original author
=> Names and authors for ASET IVA adoptions

NetKAN/BDArmoryForRunwayProject.netkan
BDArmoryForRunwayProject has a `crafts` folder containing craft files, which CKAN installs to `Ships/SPH` so users can see them as sample crafts in the game.
However, in December 2021 (https://github.com/BrettRyland/BDArmory/pull/307/commits/e6df81e471102882af0be9813f5ed96f6c88b8a8), the BDArmoryPlus team started using this folder as the location for a craft file that they load at run time based on its path. They wrote C# code to look for the file in multiple places because CKAN was already treating it as a sample craft folder:
https://github.com/BrettRyland/BDArmory/blob/df836b190c40badc45031aa7eff092b35c363757/BDArmory/Competition/VesselSpawning/VesselSpawner.cs#L29-L30
```csharp
_spawnProbeLocation = Path.Combine(KSPUtil.ApplicationRootPath, "GameData", "BDArmory", "craft", …
```
=> Install crafts folder to GameData for BDArmoryForRunwayProject

NetKAN/HabTech2.netkan, NetKAN/HabTechRobotics.netkan
#9456 indexed this mod based on the dependencies listed in the SpaceDock description, which were out of date.
- <https://spacedock.info/mod/2078/HabTech2>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/133501-112x-bg-habtech2-stockalike-iss-parts-100-the-final-update/>
Now they're updated to reflect the forum thread (and the newly updated SpaceDock description).
As part of this, `HabTechRobotics` is added as well since it is a bundled dependency.
- <https://github.com/benjee10/htRobotics>
___
=> Add missing HabTech2 dependencies

NetKAN/ShuttleOrbiterConstructionKit.netkan
=> Switch HabTechRobotics from bundled to depends for ShuttleOrbiterConstructionKit

NetKAN/MinmarKerbinRings-Classic.netkan, NetKAN/MinmarKerbinRings-New.netkan
Either the ZIP folder structure changed, or we were installing these wrong previously (or both).
=> Fix MinmarKerbinRings installs

NetKAN/MK12PodIVAReplacementbyASET.netkan, NetKAN/Mk1CockpitIVAReplbyASET.netkan, NetKAN/Mk1LanderCanIVAReplbyASET.netkan
This mod is trying to mash together three mods that don't need to be, which were previously indexed separately. (This was probably the right approach, since it allows users to choose whether to install each piece rather than making it all-or-nothing.) Accordingly it/they were adopted in #9560 using `include_only` to select the files for each part.
Now the filenames have changed, and since we're selecting them with `include_only`, two of the mods now had no files to install. The third one has no inflation error or warning because it installs the `Assets` folder, despite the `include_only` clause still matching nothing.
Now the filenames are updated.
Note that we also need to update the install for the previous version, as we were supposed to create a `GameData/ASET` folder rather than just …
=> Fix ASET Consolidated installs

NetKAN/PlumeParty-StockConfigs.netkan, NetKAN/PlumeParty.netkan
- <https://github.com/JadeOfMaar/PlumeParty>
Fixes #9626.
This is a shift from the bundling approach agreed in #7711.
=> Add PlumeParty

NetKAN/kRPC-MechJeb.netkan
This mod's latest release says it's for KSP 1.12.
Closes KSP-CKAN/CKAN-meta#3181.
=> Update kRPC-MechJeb compatibility

NetKAN/BDArmoryExtended.netkan
For once this isn't GitHub's API's fault; the mod really had an out-of-order release, due to thinking that the `0` in `1.09.2` is significant:
https://github.com/BrettRyland/BDArmory-Extended/releases
=> Epoch BDArmoryExtended

NetKAN/Udarka.netkan
In #9543 I noted that this mod was bundling KopernicusExpansionContinueder, which wasn't in CKAN. Since it wasn't explicitly mentioned as a hard dependency, I guessed/hoped that it would work without it.
Now KopernicusExpansionContinueder has been added in #9655, so it's added to this mod as a dependency.
___
=> Add KopernicusExpansionContinueder dep to Udarka

NetKAN/HUDReplacer.netkan
- <https://forum.kerbalspaceprogram.com/index.php?/topic/216056-wip-112x-hudreplacer-v121-pre/&do=findComment&comment=4290832>
The pre-releases mean we can't just add it as a regular `depends`, which would add it to the current latest non-prerelease 1.1.0 version, so this PR uses `x_netkan_override` to make it version-specific. As soon as a version equal to or greater than 1.2.0 is released, the new relationship will be added.
Testing with and without the `--prerelease` parameter confirmed that the dependency is pulled in for the newer versions and not the older versions.
=> Add Harmony2 dep to HUDReplacer 1.2.0 and later

NetKAN/Lazarus.netkan
per the forum post, this is a dependency.  Handled a support issue on discord regarding this
<https://forum.kerbalspaceprogram.com/topic/210839-112x-lazarus-awakenings-planet-pack/>
<https://www.google.com/search?q=ksp+NIAKOUTILS>
=> Add VertexMitchellNetravaliHeightMap as a dependency of Lazarus

NetKAN/ModularRocketSystem.netkan
Accidentally committed the rename to master in ef5d666b9196b5e68307fdd4fedce3826c4a94e3 instead of making a PR. An inflation error occurred because the folder structure has changed.
<https://github.com/KSP-CKAN/NetKAN/actions/runs/5501979465/jobs/10025932810>
<https://spacedock.info/mod/86/Modular%20Rocket%20Systems>
Fixes #9696.
=> Fix ModularRocketSystem install

NetKAN/ROLoadingImages.netkan
Done via metanetkan. I think the tags are correct? _Is_ there a "Loading Screens" tag?
- <https://github.com/KSP-RO/ROLoadingImages>
- <https://raw.githubusercontent.com/KSP-RO/ROLoadingImages/master/ROLoadingImages.netkan>
=> Add ROLoadingImages to CKAN

NetKAN/SRBWaterfallEffects.netkan
CKAN-meta now has a file with an illegal name on Windows:
```
$ git pull --all
Fetching upstream
Fetching origin
error: invalid path 'SRBWaterfallEffects/SRBWaterfallEffects-1-0.3 "The Prettier Plumes Update".ckan'
```
And the mirrorer is spamming Discord every 5 minutes:
A mod version string was created containing a space and some quote characters, which propagated into the usual places where they're not allowed.
Now a netkan version edit directive trims characters from the version string for this mod starting at the first space or quote, keeping only the part at the beginning that actually describes a version number. This will involve another epoch increment to ensure users will be updated to the fixed version.
A subsequent change in NetKAN-Infra will purge the queue entries that are …
=> Trim extra characters from SRBWaterfallEffects versions

NetKAN/RecycledParts.netkan, NetKAN/RecycledPartsFTmNAtomicRockets.netkan, NetKAN/RecycledPartsFTmNImprovedAtomicRockets.netkan, NetKAN/RecycledPartsLVNClusters.netkan, NetKAN/TeaKettleRCS.netkan
<https://forum.kerbalspaceprogram.com/topic/164829-112x-spacetux-industries-recycled-parts/?do=findComment&comment=4311026>
The changes were merged in linuxgurugamer/RecycledParts#11. This should be merged after there's a full release (a pre-release was just created):
https://github.com/linuxgurugamer/RecycledParts/releases
@linuxgurugamer I am assuming here that you are OK with @JadeOfMaar's requested changes to your mods' relationships, since you merged that PR pretty readily. If you don't want these recommendations, please say so and I'll remove them.
EDIT: The pre-release was just turned into a regular release. 🏁 
___
ckan compat add 1.8 1.12
=> Update RecycledParts recommendations

EmbeddedKOSKirkuits.netkan, NetKAN/EmbeddedKOSKirkuits.netkan
https://github.com/rkunze/EmbeddedKOSKirkuits
https://forum.kerbalspaceprogram.com/topic/218872-112x-embedded-kos-kirkuits/
=> Add EmbeddedKOSKirkuits

NetKAN/DE-IVAExtension.netkan
These dependencies are no longer needed, per https://forum.kerbalspaceprogram.com/topic/211932-112x-de_ivaextension-adopted-aset-ivas-for-all-stock-pods/
=> Remove unnecessary dependencies of DE-IVAExtension

NetKAN/ProbeControlRoomRecontrolled.netkan
These are no longer necessary, per https://github.com/JonnyOThan/KSP-ProbeControlRoom/
=> Remove unneeded dependencies for ProbeControlRoomRecontrolled

NetKAN/CorrectifTraductionFrancaise.netkan
I thought CorrectifTraductionFrancaise would rely on its Discord server for support, but now there's a forum thread. 
https://forum.kerbalspaceprogram.com/topic/218994-correctif-traduction-fran%C3%A7aise/
So now SpaceDock can specify the homepage.
=> Get CorrectifTraductionFrancaise homepage from SpaceDock

NetKAN/InterstellarFuelSwitch.netkan
- <https://spacedock.info/mod/175/Interstellar%20Fuel%20Switch>
- <https://forum.kerbalspaceprogram.com/topic/106243-181-1125-interstellar-fuel-switch-ifs-3295/page/47/>
=> Interstellar Fuel Switch depends on Community Resource PAck, otherwise there are errors

NetKAN/CanaveralPads.netkan, NetKAN/Kerbalism-Config-RO.netkan, NetKAN/ROEnginesExtended.netkan, NetKAN/ROLib.netkan, NetKAN/ROTanks.netkan, NetKAN/RSSVE-HR.netkan, NetKAN/RSSVE-LR.netkan
https://github.com/KSP-CKAN/CKAN/pull/3892
=> Suppress recs on CKAN-hosted netkans for RO group mods

NetKAN/KerbalField.netkan
I got permission from the author on the ksp forums for this
___
Previous time this came up: #9328
=> Make KerbalField depend on the virtual BDArmory identifier

NetKAN/Parallax-StockScatterTextures.netkan, NetKAN/Parallax-StockTextures.netkan
Parallax's stock texture modules' depend on Parallax first and each other second, which potentially creates an ambiguity for the relationship resolver that could result in prompting the user twice if there were other texture packages to choose from.
Now the relationships are reordered to make it easier on the resolver.
I'll do another PR in CKAN-meta for historical data.
=> Put more specific Parallax texture dependencies first

NetKAN/KSPWheel.netkan
This works around the issue where the remote version file (which gives this compatibility) is hosted on the AVC server, which is down (as it sometimes is).
=> Force-allow KSPWheel on 1.12 while AVC is down

NetKAN/PhotonSailor.netkan
This mod breaks without TweakScale-Redist (it's also bundled in the download)
- https://spacedock.info/mod/1895/Photon%20Sailor
=> Add TweakScale-Redist as dependency to PhotonSailor

NetKAN/RONoCareer.netkan, NetKAN/ROUtils.netkan
@HebaruSan for once I actually made the mods (including netkan!) before making the PR. Woot!
(FYI the plan for these are that ROUtils will be a dependency for most KSP-RO mods, but should not be installed on its own; and RONoCareer will go into the express install in an any_of with RP-1 so that folks can choose to install RO but _not_ RP-1, finally. It's purely a stub so the any_of can work, so it doesn't actually do anything other than exist and be findable by CKAN.)
=> Add ROUtils and RONoCareer

NetKAN/SuperfluousNodes.netkan
This mod added a version file.
- https://spacedock.info/mod/2064/Superfluous%20Nodes
- https://forum.kerbalspaceprogram.com/topic/181663-112-superfluous-nodes-07-plethora-of-extra-nodes-for-stock-parts/
=> Vref for SuperfluousNodes

NetKAN/KerbalKrashSystem.netkan
A `v` prefix was dropped, which triggered an epoch in KSP-CKAN/CKAN-meta#2129, and the v0.4.7 version is now double indexed:
We'll need to do some clean-up in CKAN-meta in a subsequent PR.
=> Force_v for KerbalKrashSystem.netkan

NetKAN/kOS-AddOns-Ferram.netkan, NetKAN/kOS-Addons-Ferram.netkan
This is an addon for kOS providing access to FAR's API.
- https://github.com/giuliodondi/kOS-Ferram
The releases don't have normal assets, but the DLL is in the source ZIP, so we use that.
After this, users will be able to install this mod with CKAN instead of manually, which will prevent the error in giuliodondi/kOS-Ferram#3. (Though technically the renaming of the DLL already did that.)
Fixes #9856.
FYI to @giuliodondi.
=> Add kOS-Addons-Ferram

NetKAN/ArtemisConstructionKit.netkan
This mod has added several new dependencies since #9304.
Now it's updated based on the list in the SpaceDock entry description and repository.
Thanks to Discord user Sofie for pointing this out.
___
ckan compat add 1.11 1.12
=> Add new dependencies for ArtemisConstructionKit

NetKAN/WildBlue-PlayMode-ClassicStock.netkan, NetKAN/WildBlue-PlayMode-Pristine.netkan, NetKAN/WildBlue-PlayMode-Simplified.netkan
i.e. you must use the CRP or USI play modes if you're using CRP.
=> Make WBI ClassicStock, Pristine, and Simplified play modes conflict with CRP

NetKAN/RationalResources.netkan
See https://github.com/KSP-CKAN/NetKAN/pull/9896#issuecomment-1879791620, RationalResources currently recommends two mods with an indirect conflict, which trips `ckan install` when `--no-recommends` isn't passed (which is what the meta tester does).
Now ClassicStockResources comes before CommunityResourcePack so the conflict can be resolved automatically.
=> Reorder RationalResources's conflicting recommendations

NetKAN/Buffalo.netkan, NetKAN/ClassicStockResources-PlayMode-ClassicStock.netkan, NetKAN/ClassicStockResources.netkan, NetKAN/DSEV.netkan, NetKAN/Heisenberg.netkan, NetKAN/MOLE.netkan, NetKAN/Pathfinder.netkan, NetKAN/WildBlue-PlayMode-CRP.netkan, NetKAN/WildBlue-PlayMode-ClassicStock.netkan, NetKAN/WildBlue-PlayMode-Pristine.netkan, NetKAN/WildBlue-PlayMode-Simplified.netkan
These mods bundle ClassicStockResources:
- DSEV
- Pathfinder
- MOLE
- Heisenberg
- Buffalo
If you install any of them manually and choose the ClassicStock play mode, the ClassicStockResources configs will be active. However, if you install with CKAN and pick the ClassicStock play mode, ClassicStockResources is **not** installed (unless the user chooses it). This isn't the expected/intended state of the mod in that case.
In addition, most but not all of ClassicStockResources's .cfg files are renamed to .txt if you pick any play mode other than ClassicStock. But in CKAN you can end up with all or none of the .cfg files when you should only have one.
Finally, PathFinder installs `GameData/WBIPlayMode.cfg`, which is bad because it means this file will be overwritten at install and upgrade.
- …
=> Split out play modes for ClassicStockResources

NetKAN/KourageousTourists.netkan
Note: transfer was approved by original author here: https://forum.kerbalspaceprogram.com/topic/209560-ksp-131-kourageous-tourists-l-0601-2022-1128/#comment-4224575
A few issues/questions for @Lisias :
* Despite using the same identifier, ckan will use the name of the mod from spacedock - i.e. "Kourageous Tourists /L."  If you're OK with that there's nothing we need to do, or else we can override it in the netkan.
* I explicitly listed the authors here because your spacedock listing doesn't have whale_2 listed as an author (nor should it necessarily, unless you want them to be able to modify your releases etc).  Since the original license was MIT I think listing whale_2 in CKAN is required, but in any case it's nice to give credit to previous authors and I don't think you'd have a problem …
=> Point KourageousTourists at Lisias' fork on spacedock

NetKAN/CelestialRescale.netkan
<https://github.com/SpaceNerd24/Celestial-Rescale/releases>
`v.` should be just `v`
=> Work around bad version on GitHub for CelestialRescale

NetKAN/IXSWarpship-Blueshift.netkan
This error persists:
This mod's intended version format is `v.X.Y.Z`, **with** a leading dot after the `v`, but the dot is missing in the most recent version:
<https://github.com/Araym-KSP/IXS-Warship-for-Blueshift/releases>
Typically authors use `vX.Y.Z`, so normally we'd use a version-editing property to remove the dot, but in this case the _omission_ of the leading period is the exception.
The GitHub releases API fails to return the most recent release in about 0.005% of cases (that's what the message means by "unreliable server"). Instead, it presents the NetKAN bot the release before that as if it was the most recent. There's no way to detect that this has happened, so we need to establish rules that handle it smoothly.
When this glitch happens for this mod, this glitch causes the …
=> Stable solution to IXSWarpship-Blueshift versioning

NetKAN/JNSQ-PartRebalancer-10x.netkan, NetKAN/JNSQ-Rescale-10x.netkan, NetKAN/JNSQ-Rescale-1x.netkan
These optional mods are already included in the JNSQ distribution itself, this PR merely makes them installable in CKAN.
- <https://github.com/Galileo88/JNSQ>
=> Add optional JNSQ rescale mods to stock (1x) and real (10x) size

NetKAN/GrannusExpansionPack-Rescale-10x.netkan, NetKAN/GrannusExpansionPack-Rescale.netkan
- <https://github.com/OhioBob/Grannus-Expansion-Pack>
- #8330 added GEP rescale (2.5x)
- #7541 added GEP
- #9936 added the part rebalancer 10x that both JNSQ and GEP use
=> Add optional GEP rescale 10x mod

NetKAN/GPP.netkan, NetKAN/GPPSecondary.netkan, NetKAN/GrannusExpansionPack.netkan
In #8880 and #8881 the scatterer version for GPP was set, but it incorrectly allowed scatterer 0.0852 to be installed.
=> Fix gpp scatterer version

NetKAN/CryoTanks-Core.netkan, NetKAN/CryoTanks.netkan, NetKAN/SkyhawkScienceSystem.netkan
- Starting in version 1.6.0, CryoTanks bundles B9PartSwitch:
But its metanetkan has not been updated to reflect this dependency. @JonnyOThan submitted a fix in January, see post-kerbin-mining-corporation/CryoTanks#138, but it has not been merged.
- Installing CryoTanks-Core by itself creates a `GameData/CryoTanks` directory, which will cause ModuleManager to treat the full CryoTanks as installed. This would break any mods that use `:NEEDS[CryoTanks]` syntax to turn changes on or off depending on whether the full CryoTanks is present, including parts and so forth.
- SkyhawkScienceSystem recommends CryoTanks-Core, but there's no indication that this is more correct than recommending CryoTanks, so it might be breaking things
- Now CryoTanks and CryoTanks-Core no longer use a metanetkan
- Now …
=> De-meta CryoTanks to fix dependency issues

NetKAN/NearFutureSolar-Core.netkan, NetKAN/NearFutureSolar.netkan
If you install NearFutureSolar-Core by itself, a `GameData/NearFutureSolar` folder is created, which makes ModuleManager treat NearFutureSolar as installed. This will break mods that use `:NEEDS[]` directives to turn code on and off with and without that mod.
#9964 fixed an analogous situation with CryoTanks from the same author by removing its metanetkan. We tried to get the metanetkan fixed, but it seems to no longer be maintained.
- Now NearFutureSolar and NearFutureSolar-Core also no longer use metanetkans
- Now NearFutureSolar-Core depends on NearFutureSolar, to effectively eliminate the split
Fixes #9922.
=> De-meta NearFutureSolar to fix dependency issues

NetKAN/KcalbelohSystem-Textures-4k.netkan, NetKAN/KcalbelohSystem-Textures-8k.netkan, NetKAN/KcalbelohSystem.netkan
- <https://github.com/jcyuan06/Kcalbeloh-System>
This mod has split its textures into two separate 4k and 8k downloads.
Now they're added as modules, providing and conflicting with `KcalbelohSystem-Textures`, which the main module now depends on.
Fixes #9975.
=> Handle KcalbelohSystem textures

NetKAN/CommunityPartsTitles.netkan
- <https://github.com/yalov/CommunityPartsTitles>
This has been replaced by an internal .ckan file in this mod's latest upload...
=> Internal .ckan for CommunityPartsTitles

NetKAN/NewTantares.netkan, NetKAN/NewTantaresLV.netkan, NetKAN/TantaresSP.netkan
@Tantares said SpaceDock is no longer being used for these mods and requested for those links to be removed.
In addition, https://github.com/Tantares/Tantares has the forum thread link set up, so we'll pull that as well.
=> Remove Tantares SpaceDock and forum links

NetKAN/PlanesWithPurposes.netkan
This mod is multi-hosted, but the latest upload on GitHub has a `v` prefix that no other version has had.
Now it'll be pruned at inflation.
=> Consistent versioning for PlanesWithPurposes

NetKAN/RealChute.netkan, NetKAN/RealChuteForStock.netkan
An imminent release of `RealChute` will have a `Patches` folder instead of a `ModuleManager` folder. This is intended to be an optional patch for users who want to use the mod's features for stock parts; users who don't want this are not supposed to install the patch (they can still use the mod's own parts).
- <https://github.com/ChrisViral/RealChute>
Now a new `RealChuteForStock` module is added by request of the author. It installs the `Patches` folder, which is now filtered out of the main `RealChute` module.
(Need to wait for the new release before merge.)
=> Split RealChute Patches folder into separate module

NetKAN/NavUtilitiesContinued.netkan, NetKAN/NavUtilitiesUpdated.netkan
@JonnyOThan forwarded this screenshot from a user:
That error is from this code in `NavUtilitiesUpdated`:
<https://github.com/linuxgurugamer/NavInstruments/blob/master/Source/NavUtilLib/InstallChecker.cs>
It says:
> This will also detect duplicate copies because only one can be in the right place.
So that user must have installed both forks, and `NavUtilitiesUpdated` detected `NavUtilitiesContinued` and didn't like where it was installed.
Now the forks of `NavUtilities` conflict with each other, since they don't play nice together.
=> Make NavUtilities forks mutually exclusive

NetKAN/ModularLaunchPads.netkan
This mod's craft files have been re-organized to avoid installing incompatible crafts:
- <https://github.com/AlphaMensae/Modular-Launch-Pads>
Now only the `Bare Assemblies` are installed, since the other two groups would be incompatible with some installs some of the time.
___
=> Only install generic crafts for ModularLaunchPads

NetKAN/TechosStockPlanetRevamp.netkan
This mod is missing its dependency on `KopernicusExpansion`:
- <https://spacedock.info/mod/3455/Techo's%20(Stock)%20Planet%20Revamp>
Now it's fixed.
=> Add KopernicusExpansion dep to TechosStockPlanetRevamp

NetKAN/Lazarus-Content.netkan
This mod has recently been uploaded to GitHub insteaad of SpaceDock because of network timeout issues (like many very large planet mods). 
- <https://spacedock.info/mod/3157/Lazarus>
- <https://github.com/hmelioo/Lazarus>
The ZIP has been split into 2 parts to work around GitHub's 2 GiB release asset limit.
Now `Lazarus` is updated to point to the `Core` asset, and a `Lazarus-Content` module is added for the `Content` asset.
=> Split Lazarus to work around GitHub release asset limit

NetKAN/RealAntennas.netkan
RA v2.3 now uses (and therefore requires) clickthroughblocker
=> Add new dependency for RealAntennas

NetKAN/Lazarus-Content.netkan, NetKAN/Lazarus.netkan
Some relationship updates were missed in #10055.
- <https://github.com/hmelioo/Lazarus/releases/tag/1.2>
> REQUIREMENTS
> Kopernicus
> Scatterer
> EVE (NOT VOLUMETRICS)
> Instantiator
> NiakoUtils
> NOW REQUIRES: DUCKWEED'S VERTEXCOLORMAPEMISSIVE https://spacedock.info/mod/3620/VertexColorMapEmissive
Author confirms that EVE and Scatterer should remain recommended.
Now dependencies on `INSTANTIATOR` and `VertexColorMapEmissive` are added.
___
Needed for `INSTANTIATOR` (!):
ckan compat add 1.3
=> Add missing Lazarus dependencies

NetKAN/Lazarus.netkan
Now these are added.
___
Needed for `INSTANTIATOR` dependency:
ckan compat add 1.3
=> Recommend Parallax for Lazarus

NetKAN/VertexHeightOblateAdvanced.netkan
This mod's install path changed from `GameData/000_DuckweedUtils/VertexHeightOblateAdvanced` to `GameData/001_DuckweedUtils/VertexHeightOblateAdvanced`, but the CKAN metadata is "deep linking" to the original path. This was done because there were LICENSE and README.md files in `GameData/000_DuckweedUtils`, which would have caused a file conflict if another mod did the same thing.
Now we use a regex so the mod can pick whatever path it wants, and the author has moved the LICENSE and README.md into the `VertexHeightOblateAdvanced` folder.
=> Fix VertexHeightOblateAdvanced install path

NetKAN/PerSaveScreenshots.netkan
An update using the new Shabby dependency is now out. License and Homepage were removed in favor of it pulling them from the github repo, and now the mod has a standard install structure so I also removed `install`. (Edits mostly generated via webtool)
- <https://github.com/DeltaDizzy/PerSaveScreenshots>
=> Add Shabby dependency, remove license and homepage in favor of github autofill, remove install

NetKAN/RustyStarRockets.netkan
Discord user Frost pointed out that parts from RustyStarRockets weren't loading.
#9522 used the default install stanza, which installs the identifier `RustyStarRockets` directly to GameData, leaving out part of the path; now it's fixed.
```
MODEL { model = RustyStar/RustyStarRockets/Assets/rsr-capsule-0625/rsr-capsule-0625 }
```
=> Fix RustyStarRockets install path

NetKAN/SIMPLEXResources.netkan
I guess I forgot #8646 while working on #9385.
Noticed while reviewing KSP-CKAN/CKAN-meta#3274, which we might still need to add an epoch.
=> Fix SIMPLEXResources versioning

NetKAN/KeminiResearchProgram.frozen, NetKAN/KerbalEnvironmentalEffectsStudy.frozen, NetKAN/KerbalLifeScience.frozen, NetKAN/NehemiahInc-Complete.frozen, NetKAN/NehemiahMultiPurposeParts.frozen, NetKAN/NehemiahScienceCommon.frozen, NetKAN/OrbitalMaterialScience.frozen
#7100 introduced some syntax errors (extra braces, missing commas) and used `replaced-by` instead of `replaced_by`. This had no effect since the affected modules were already frozen, but it's possible that someone might copy-paste this metdata in the future if they want to do something similar.
Now these problems are fixed. This will have no effect other than reducing the risk of bad metadata in other mods.
A future PR in CKAN-meta will probably add `replaced_by` to the old .ckan files that were intended to be updated by #7100.
Fixes #10109.
=> Clean up replaced-by in frozen netkans

.github/workflows/inflate.yml, .github/workflows/manual_inflate.yml
`actions/checkout` and `actions/cache` both have v4 available, and we're using v2. Now both are updated to v4.
=> Update GitHub Actions from v2 to v4

NetKAN/NeidonPlus.netkan
#9446 added an `OPM-` prefix, #9447 removed it, now there's an `OPX-` prefix and a bunch of Mac cruft.
#10104 is a different mod from the same authors with a similar setup.
=> Fix NeidonPlus install again again

NetKAN/DSEV.netkan
While working on a bug related to RPM and DSEV, I discovered that it uses ASET Avionics props, and most of the IVAs have been converted to use MAS to drive them (the RPM versions are still there but renamed to .txt)
=> DSEV: adjust recommendations according to content in cfg files

NetKAN/ColdJsMilitaryPlanesF16.netkan
Both `ColdJsMilitaryPlanes` and `ColdJsMilitaryPlanesF16` contain `GameData/CJMP/License.txt` and `GameData/CJMP/Readme.txt`.
- Users who manually install both mods will overwrite these files during the install, and since the `Readme.txt` files are not the same, they will only have the readme file for one or the other mod, depending on the order of installation.
- For CKAN users, an error is emitted during installation instead:
```
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
If this problem re-occurs, then it may be a packaging bug.
Please report it at:
https://github.com/KSP-CKAN/NetKAN/issues/new/choose
Please include the following information in your report:
File      : GameData/CJMP/License.txt
Installing Mod : …
```
=> Resolve ColdJ Military Planes file conflicts

NetKAN/RSSOrigin-CelestialsPack-Centaurs.netkan, NetKAN/RSSOrigin-CelestialsPack-Comets.netkan, NetKAN/RSSOrigin-CelestialsPack-InterstellarObjects.netkan, NetKAN/RSSOrigin-CelestialsPack-JupiterMoons.netkan, NetKAN/RSSOrigin-CelestialsPack-JupiterTrojans.netkan, NetKAN/RSSOrigin-CelestialsPack-MainBeltAsteroids.netkan, NetKAN/RSSOrigin-CelestialsPack-MarsCrossers.netkan, NetKAN/RSSOrigin-CelestialsPack-NearEarthObjects.netkan, NetKAN/RSSOrigin-CelestialsPack-NeptuneMoons.netkan, NetKAN/RSSOrigin-CelestialsPack-PlutoMoons.netkan, NetKAN/RSSOrigin-CelestialsPack-SaturnMoons.netkan, NetKAN/RSSOrigin-CelestialsPack-TransNeptunianObjects.netkan, NetKAN/RSSOrigin-CelestialsPack-UranusMoons.netkan, NetKAN/RSSOrigin-GalaxyTex-16k.netkan, NetKAN/RSSOrigin-GalaxyTex-32k.netkan, NetKAN/RSSOrigin-GalaxyTex-64k.netkan, NetKAN/RSSOrigin-GalaxyTex-8k.netkan, NetKAN/RSSOrigin-JSUNrings.netkan, NetKAN/RSSOrigin.netkan
These modules were added with a `$vref`, but they don't have version files.
Now they have `ksp_version: 1.12` as specified in #10126.
And MM deps are added to the ones that use MM syntax.
=> Fix RSSOrigins compatibility

NetKAN/WaterfallExtensions.netkan
This mod seems to have been removed from GitHub (in an incident contrary to the author's intentions):
- <https://github.com/rbeap/WaterfallExtensions>
And hasn't been a new upload to what appears to be the author's new account:
- <https://github.com/rbeap0>
Now the GitHub kref is removed, and only the SpaceDock kref remains.
___
ckan compat add 1.11 1.12
=> Remove WaterfallExtensions GitHub kref

NetKAN/RSSOrigin-TopoRevampConfigs.netkan, NetKAN/RSSOrigin-TopoRevampTextures16k.netkan, NetKAN/RSSOrigin-TopoRevampTextures4k.netkan, NetKAN/RSSOrigin-TopoRevampTextures8k.netkan
- <https://github.com/CharonSSS/RSS-Origin>
From [the mod's readme](https://github.com/CharonSSS/RSS-Origin?tab=readme-ov-file#rss-origin-rsstexturetoporevamp):
> RSS-Origin RSSTexture&TopoRevamp is an overhaul to some of the RSS celestials. I've done a widely search for information and figure out some of the RSS celestials are using wrong and misaligned surface textures ,topograhy maps, false or enhanced color images. So this mod's purpose is to fix those issues, fixing texture alignment flip or rotation, and make them displayed in natural color. Different texture resolutions are provided (4k, 8k and 16k).
Fixes #10140.
=> Add RSSOrigin TopoRevamp

NetKAN/DKSalvageAgencyAndFlag.netkan, NetKAN/RoveMateClassicTuneUp.netkan, NetKAN/StructuralTubing.netkan
If you try to install `StructuralTubing` and `RoveMateClassicTuneUp`, you get a file conflict at `GameData/DKSalvage/Agencies/agency.cfg`. If we fixed just this one file, the same thing would happen in the `GameData/DKSalvage/Flags` folder.
- Now their common files are filtered out of `StructuralTubing` and `RoveMateClassicTuneUp`
- Now `GameData/DKSalvage/Agencies` and `GameData/DKSalvage/Flags` are installed by a new `DKSalvageAgencyAndFlag` module (from the `RoveMateClassicTuneUp ZIP)
- Now `StructuralTubing` and `RoveMateClassicTuneUp` depend on `DKSalvageAgencyAndFlag`
___
ckan install StructuralTubing RoveMateClassicTuneUp
=> Split DKSalvage agency and flags into standalone module

NetKAN/Mk-33.netkan
This mod's intended name is `Mk-33`.
Since it's not set in the netkan, the inflator derives it from the repo name, and in the process it converts the dash to a space, so the name in the metadata is `Mk 33`.
Now we override the name to retain the dash.
=> Set Mk-33's name to contain a dash

NetKAN/KcalbelohSystem.netkan
- <https://github.com/jcyuan06/Kcalbeloh-System>
New relationship requested by author, applies to a future release.
Fixes #10197.
=> VertexColorMapEmissive depends for KcalbelohSystem

NetKAN/BuranEnergia.netkan, NetKAN/NoIntakeOcclusion.netkan, NetKAN/ZeroMiniAVC.netkan
#10202 added GitHub hosting for these mods, but they have bad version strings on GitHub:
Now they're back to SpaceDock-only. I'll remove those versions from CKAN-meta separately.
=> Remove multi-hosting for three mods with bad repo versions

NetKAN/OPX-SarnusPlus.netkan
this was added in the zip file in the latest release, and the game fails to load without it
=> OPX-SarnusPlus depends on VertexHeightOblateAdvanced

NetKAN/RasterPropMonitor-Core.netkan
The `v` prefix has been dropped on GitHub:
Now the bot will add it.
=> force_v for RasterPropMonitor-Core

NetKAN/InterstellarFuelSwitch-Core.netkan
per forum post: https://forum.kerbalspaceprogram.com/topic/106243-181-1125-interstellar-fuel-switch-ifs-3295/
> Dependancies
Tweakscale ( 999_Scale_Redist.dll  only)
Module Manager
=> InterstellarFuelSwitch-Core only depends on tweakscale-redist

NetKAN/BetterSRBs.netkan, NetKAN/ZeroMiniAVC.netkan
- The name of BetterSRBs looks weird, with a space between the R and the B
- Discord user `dan` reported frequent prompts from the dev build to reinstall mods after running the game, which said "metadata changed" even though the metadata for those mods had either never changed or changed over two years previously
- When no `name` is defined in the netkan of a mod hosted on GitHub, some automatic logic is applied to compute a name from the repository title, which makes some assumptions about capitalization and word boundaries that do not hold for the string `BetterSRBs` (it interprets `Bs` as a word):
https://github.com/KSP-CKAN/CKAN/blob/228c887a0f281123ae482566479e928cc5d91886/Netkan/Transformers/GithubTransformer.cs#L200-L210
- When ZeroMiniAVC deletes files that CKAN installed, the …
=> Advertise install filters in ZeroMiniAVC, fix BetterSRBs name

NetKAN/CelestialHarmony.netkan
This mod previously had an `Alpha-` prefix on its versions, which is now removed.
- <https://github.com/ProximaCentauri-star/Celestial-Harmony/releases>
=> Bump CelestialHarmony epoch

NetKAN/SimpleRepaint.netkan
This mod depends on B9PartSwitch 2.16.0 or later.
Unfortunately, that matches _all_ versions of that mod because they all have a `v` prefix:
- <https://github.com/KSP-CKAN/CKAN-meta/tree/master/B9PartSwitch>
Should have been caught in #8720; maybe someday the inflator could warn if a version specific relationship fails to exclude any mods?
Now the relationship version has a `v` prefix as well.
=> Fix SimpleRepaint version specific depends

NetKAN/SunkWorks.netkan
Discord user Teusdv asked about this mod. Earlier this year, @Angel-125 described its absence from CKAN as "an oversight."
[![image](https://github.com/user-attachments/assets/04b2a914-926d-4ac4-a4ef-f1c03e7bdb94)](https://forum.kerbalspaceprogram.com/topic/202746-min-ksp-111-wip-sunkworks-maritime-technologies/?do=findComment&comment=4400332)
- <https://github.com/Angel-125/SunkWorks>
- <https://forum.kerbalspaceprogram.com/topic/202746-min-ksp-111-wip-sunkworks-maritime-technologies/>
Send a forum PM to make sure it's not a surprise.
=> Add SunkWorks

NetKAN/Buffalo-PlayMode-CRP.netkan, NetKAN/Buffalo-PlayMode-ClassicStock.netkan, NetKAN/DSEV-PlayMode-CRP.netkan, NetKAN/DSEV-PlayMode-ClassicStock.netkan, NetKAN/DSEV-PlayMode-Pristine.netkan, NetKAN/Heisenberg-PlayMode-CRP.netkan, NetKAN/Heisenberg-PlayMode-ClassicStock.netkan, NetKAN/Heisenberg-PlayMode-Pristine.netkan, NetKAN/Heisenberg-PlayMode-Simplified.netkan, NetKAN/MOLE-PlayMode-CRP.netkan, NetKAN/MOLE-PlayMode-ClassicStock.netkan, NetKAN/MOLE-PlayMode-Pristine.netkan, NetKAN/Pathfinder-PlayMode-CRP.netkan, NetKAN/Pathfinder-PlayMode-ClassicStock.netkan, NetKAN/Pathfinder-PlayMode-Pristine.netkan, NetKAN/Pathfinder-PlayMode-Simplified.netkan, NetKAN/WildBlue-PlayMode-CRP.netkan, NetKAN/WildBlue-PlayMode-Pristine.netkan, NetKAN/WildBlue-PlayMode-Simplified.netkan
While wokring on the relationship resolver refactor for KSP-CKAN/CKAN#4108, I noticed that the WildBlue play modes and Heisenberg play modes conflicted with the identifiers they provide, but the other mod-specific play modes don't. This is inconsistent and probably makes the resolver work a bit harder to figure these out.
Now all of the play modes conflict with the identifiers they provide.
In addition, "Heisenberg" is replaced by "Airships" in the play mode names for consistency with the main mod.
=> Add conflicts with WildBlue play modes' provided names

NetKAN/KerbalismModularScienceScienceOnly.netkan
From the mod's description:
"Requires Kerbalism (Kerbalism Code, not the Config) , Module Manager
A Science Only Kerbalism Config."
Current implementation does not work properly: Kerbalism-Config is required by Kerbalism, and installing one with KerbalismModularScienceScienceOnly makes Kerbalism display a "duplicate configs detected" warning.
=> KerbalismModularScienceScienceOnly provides Kerbalism-Config

NetKAN/Deferred.netkan
Users of Parallax Continued (manual install) will get an error trying to install Deferred "Deferred conflicts with an unmanaged DLL". Remove this version check in the absence of a better option. These old Parallax versions should be mostly phased out by now.
=> Remove Deferred marking old Parallax versions as incompatible

NetKAN/Grounded.netkan
This is a parts-only mod and doesn't really have any version restrictions, but the forum thread says 1.10
- <https://forum.kerbalspaceprogram.com/topic/171377-110x-grounded-modular-vehicles-r50-mining-modules-rotor-emergency-light-jun-5-2019/>
=> Grounded: set ksp version to 1.10 per forum

NetKAN/JebFarAway.netkan
The SpaceDock download of this mod doesn't pass ZIP validation in the Inflator:
<http://status.ksp-ckan.space/>
But the one on GitHub is OK. Now we get it from GitHub.
Fixes #10281.
=> Get JebFarAway from GitHub instead of SpaceDock

NetKAN/BDDMP.netkan, NetKAN/DarkMultiPlayer.netkan, NetKAN/KerbalEngineerRedux.netkan, NetKAN/KerwisChinaAerospacePack.netkan, NetKAN/Kopernicus.netkan, NetKAN/PartOverhauls.netkan, NetKAN/PlanetaryDiversity.netkan, NetKAN/Scatterer-config.netkan, NetKAN/Scatterer-sunflare.netkan, NetKAN/Scatterer.netkan, NetKAN/TextureReplacerReplaced.netkan, NetKAN/USI-NuclearRockets.netkan, NetKAN/kOSPropMonitor.netkan
The spec defines `release_status` as `stable`, `testing`, and `development`, in decreasing order of stability.
Currently no code looks at this value, which means we effectively treat all mods as `stable` today (since all mods will be installed for all users).
KSP-CKAN/CKAN#4159 is requesting that we finally follow through on the implicit promise of this property and make available a setting where users can choose their preferred mod stability. This **cannot** work if _Scatterer_, of all things, is telling us that it is a pre-pre-release only suited for the very most adventurous users.
Now all active netkans have non-`stable` values of `release_status` removed so we can start populating it with useful, meaningful metadata such as whether a release is marked as a pre-release on GitHub. No …
=> Remove release_status property from all netkans

NetKAN/BLEAK.netkan
As far as I can tell, this is the only field from #10297 that actually should be added.
Fixes #10297.
=> Vref for BLEAK

NetKAN/RSSOrigin-TopoRevampTextures16k.netkan, NetKAN/RSSOrigin-TopoRevampTextures16kPart2.netkan
This mod's 16k texture pack is now larger than the upload size limit on GitHub, which has been circumvented by splitting the file.
- <https://github.com/CharonSSS/RSS-Origin>
Fixes #10292.
=> Multi-part 16k texture pack for RSSOrigin

NetKAN/PhysicsRangeExtender.netkan
This mod has an extra space at the end of its `name`:
Now it's removed.
=> Remove trailing space from PhysicsRangeExtender name

NetKAN/CollisionFXReUpdated.netkan
The folder name for the current stable version of this mod is CollisionFXReUpdated, but the prerelease just uses CollisionFX. Now the netkan handles both.
=> More flexible install for CollisionFXReUpdated

NetKAN/StockAutoCutDrogues.netkan
https://github.com/SofieBrink/StockAutoCutDrogues/releases
https://spacedock.info/mod/3773/StockAutoCutDrogues
https://forum.kerbalspaceprogram.com/topic/226347-112x-stockautocutdrogues-v100-01dec2024/
StockAutoCutDrogues has just released,
The mod contains an internal .ckan file that contains all the dependencies and other fields [here](https://github.com/SofieBrink/StockAutoCutDrogues/blob/main/GameData/StockAutoCutDrogues/Versioning/StockAutoCutDrogues.ckan)
Versioning is done with the internal version file [here
](https://github.com/SofieBrink/StockAutoCutDrogues/blob/main/GameData/StockAutoCutDrogues/Versioning/StockAutoCutDrogues.version)
=> Add StockAutoCutDrogues to CKAN

NetKAN/KSPTOTConnect.netkan
This mod has the following quirks:
- Multi-hosting inflation error due to version 1.6.10.1 existing on SpaceDock and not GitHub
- 1-GB download thanks to 2 embedded copies of the MATLAB runtime
In combination, this means an extra 1 GB of downloading for the bot every 30 minutes, which may be causing the freezes that we've been seeing.
Now this mod is SpaceDock-only, which means its users (2882 downloads on GitHub, 369 on SpaceDock) will be deprived of GitHub's nicer download speeds, but the better metadata from SpaceDock won't disappear. We can restore the multi-hosting if the version numbers become consistent at some point.
=> De-multihost KSPTOTConnect

NetKAN/EstrelaDobre.netkan
This mod's repo seems to be having another mod's releases uploaded to it, which is causing inflation errors:
- <https://github.com/JcoolTheShipBuilder/Estrela-Dobre/releases>
Now the `$kref` has an `asset_match` filter to pick up only the correct mod.
=> Set asset_match for EstrelaDobre

NetKAN/StarshipExpansionProject.netkan, NetKAN/StarshipExpansionProjectIVA.netkan
This mod's last three versions are:
<https://github.com/Kari1407/Starship-Expansion-Project/releases>
- `v.2.1.0`
- `v.2.2.0`
- `v3.0.0-b1` (a pre-release)
It currently has an out-of-order inflation error because the dot after the v is dropped in the pre-release.
Now we put the dot back.
We also have to set the `abstract` because it isn't set on the GitHub repo.
=> Coerce StarshipExpansionProject versioning into consistency

NetKAN/BetterRocketDesigns.netkan
This mod has a prerelease with a tag of `canary`, which doesn't look like a version string, so it's probably not very likely to remain stable in the version history.
Now we skip prereleases for this mod.
=> Ignore prereleases for BetterRocketDesigns

NetKAN/AntennaRangePatches.netkan, NetKAN/ContractConfigurator-GrandTours.netkan, NetKAN/ContractConfigurator-RoverMissionsRedux.netkan, NetKAN/ContractConfigurator-UnmannedContracts.netkan, NetKAN/PersistentDynamicPodNames.netkan, NetKAN/ZPIF-4-Stock.netkan
These mods had some inflation warnings that weren't addressed in #10328.
Mod | Warnings
:-- | :--
AntennaRangePatches, ContractConfigurator-GrandTours, ContractConfigurator-UnmannedContracts, ContractConfigurator-RoverMissionsRedux, ZPIF-4-Stock | Tags added
PersistentDynamicPodNames | The latest release is a prerelease, and its structure is a mess. It has separate assets for three different game versions; there's no reasonable way we could pick out the right file to index. To fix this, prereleases are now disabled for this mod, and we'll have to freeze whatever was added for that prerelease separately.
=> Cleanup for recently unfrozen mods

NetKAN/BDArmoryMultiplayer.netkan, NetKAN/StockRealism.netkan
These mods have multiple assets in the latest release without `asset_match` or `version_from_asset`. This means the inflator will simply grab the first asset, which may be the actual mod or some optional side download that has been added to the release. Fortunately, they are correctly indexed already because in both cases the first asset is correct, but this isn't guaranteed to be the case in future updates.
Now an `asset_match` is added to filter out the optional side downloads.
=> Asset match for repos with multiple assets

NetKAN/TundraExploration.netkan, NetKAN/TundraTechnologies.netkan
With [version 7.1.1](https://github.com/TundraMods/TundraExploration/releases/tag/7.1.1) Tundra is moving to internal .ckan's for defining dependencies this PR removes them from the NetKAN files for both mods.
Thanks in advance!
=> Update Tundra NetKANs

NetKAN/ShineFix.netkan
@Clayell pointed out in https://github.com/KSP-CKAN/NetKAN/pull/10291#issuecomment-2564122763 that I missed some of this mod's dependencies. (I think I was distracted by the problem with the ZIP file, the early multi-hosting inconsistencies, and the bot overwriting my changes and forgot to go back and check everything.)
Now they're added.
=> Fix ShineFix depends

NetKAN/TourismOverhaul.netkan
This mod now has [a prerelease](https://github.com/iLikeGothMommys/TourismOverhaul/releases/tag/Release1.2PreRelease) only on GitHub, which doesn't provide the CC-BY-NC-SA license appropriately (for normal multi-hosted releases, we get the license from SpaceDock):
https://api.github.com/repos/iLikeGothMommys/TourismOverhaul
```json
"license": {
"key": "other",
"name": "Other",
"spdx_id": "NOASSERTION",
"url": null,
"node_id": "MDc6TGljZW5zZTA="
},
```
Now it's hard-coded in the netkan.
=> Add license for TourismOverhaul

NetKAN/MinorPlanetsExpansion.netkan
The author has been unable to update this mod on spacedock, and the current release has a gamebreaking bug when installed with parallax.  The fix is available on github, so let's just make that the primary download.
> A Word of Warning: SpaceDock/CKAN Still Carries the Initial 1.1.0 Build
DO NOT Use 1.1.0's Parallax Config - THEY ARE UNSTABLE
https://forum.kerbalspaceprogram.com/topic/192848-112x-planet-pack-minor-planets-expansion/
https://forum.kerbalspaceprogram.com/topic/192848-112x-planet-pack-minor-planets-expansion/?do=findComment&comment=4439323
=> MinorPlanetsExpansion: switch to github

NetKAN/AdvancedPQSTools.netkan, NetKAN/RSSOrigin-TopoRevampConfigs.netkan, NetKAN/RSSOrigin.netkan
Add [AdvancedPQSTools](https://github.com/CharonSSS/AdvancedPQSTools) as dependency for **RSSOrigin-CelestialsPackCore** and **RSSOrigin-TopoRevampConfigs** once [AdvancedPQSTools is added to ckan](https://github.com/KSP-CKAN/NetKAN/issues/10359)
Add [VertexColorMapEmissive](https://github.com/jamespglaze/VertexColorMapEmissive) and [VertexMitchellNetravaliHeightMap](https://github.com/pkmniako/Kopernicus_VertexMitchellNetravaliHeightMap) as dependencies for **RSSOrigin-TopoRevampConfigs**
Add **RSSOrigin-CelestialsPackCore** as dependency for **RSSOrigin-TopoRevampConfigs**
Also, I want to change the title of **_"RSS-Origin CelestialsPack Core"_** to **_"RSS-Origin Core"_**. Its nametag (RSSOrigin-CelestialsPackCore) can remain unchanged to avoid other fussy dependency, recommendation, …
=> Add AdvancedPQSTools.netkan

NetKAN/TweakScaleRescaled-Redist.netkan, NetKAN/TweakScaleRescaled-SafetyNet.netkan
These mods currently have a prerelease, but the netkans hard-code `release_status: stable`, which used to do nothing and now breaks things.
Now that's removed so the `release_status` can reflect the actual stability of the releases.
=> Remove release status from TweakScaleRescaled auxiliary mods

NetKAN/DMTanks-SphericalTanks.netkan, NetKAN/KeridianDynamicsVesselAssembly.netkan, NetKAN/MoldaviteMachines.netkan, NetKAN/SimpleConstruction.netkan
b9partswitch is a foundational mod that is rarely installed directly by a user's choice.  When trying to craft a .ckan modpack that has a dependency on B9PartSwitch, I was presented with a choice to install these 4 mods when they have nothing to do with my pack.  This isn't what "supports" is meant to be used for.  If the relationship isn't strong enough to be a dependency or recommendation, then "suggests" is appropriate.
=> Change mods that "support" b9partswitch to "suggest" instead

NetKAN/PersistentRotationUpgraded.netkan
See linuxgurugamer/PersistentRotation#13, this mod depends on exploiting a stock bug that is fixed by KSPCommunityFixes, so when both are installed, PersistentRotationUpgraded doesn't work.
@linuxgurugamer acknowledged the problem and said a fix is not currently in the works:
- <https://forum.kerbalspaceprogram.com/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1332-laplace-ksp-2-support/?do=findComment&comment=4443730>
Now they're marked as conflicting.
=> Add KSPCommunityFixes conflict to PersistentRotationUpgraded

NetKAN/FutureTechnologiesExpansion-FrontierAeronautics.netkan
This mod's folder now has a version string embedded in its name.
Now the install stanza accounts for this.
=> Fix FutureTechnologiesExpansion-FrontierAeronautics install

NetKAN/BetterKerbol.netkan, NetKAN/QuackPack.netkan, NetKAN/VertexColorMapEmissive.netkan, NetKAN/VertexHeightOblateAdvanced.netkan
@jamespglaze has reported difficulties uploading to SpaceDock and wishes to have his mods indexed from GitHub only.
- <https://github.com/jamespglaze/BetterKerbol>
- <https://github.com/jamespglaze/QuackPack>
- <https://github.com/jamespglaze/VertexColorMapEmissive>
- <https://github.com/jamespglaze/VertexHeightOblateAdvanced>
Now this author's mods are retrieved only from GitHub.
=> Remove SpaceDock hosting for Lt_Duckweed's mods

NetKAN/QuackPack.netkan
This mod's latest release has two assets:
<https://github.com/jamespglaze/QuackPack>
We're supposed to use the non-volumetrics one, but the default is the first one.
Now a zero-width lookahead filters out the one with `Volumetrics` in its name.
=> Use non-volumetrics asset for QuackPack

NetKAN/ZeroMiniAVC.netkan
This got excluded from #10462, #10463, and #10465 because it was missing from the latest QuickMods release. Turns out it has its own repo now.
- <https://github.com/linuxgurugamer/ZeroMiniAVC>
Hallelujah.
=> Multi-host ZeroMiniAVC

NetKAN/KerbinSideRemasteredGAP.netkan
Per author's request on the forum: https://forum.kerbalspaceprogram.com/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1332-laplace-ksp-2-support/?do=findComment&comment=4454740
However...  Kerbinside Core is only marked as compatible with KSP 1.5.1.  In order for someone to install your mod from CKAN, they will have to get CKAN to install that (ideally by force-installing it from the versions tab, but some people change ckan's compatibility settings to do this which often results in them unintentionally getting old versions of dependencies that break their game).
KerbinSideRemasteredGAP already depends on KerbinSideRemastered.  Is it even feasible to install both KerbinSideRemastered and Kerbinside Core together?
As a policy, we do not change KSP version compatibility for a …
=> Fixes #10474: KerbinSideRemasteredGAP: add dependencies on StockalikeStructures and KerbinsideCore

NetKAN/PersistentRotationUpgraded.netkan
The bug that motivated #10409 has been fixed in linuxgurugamer/PersistentRotation#15, and the fixed release was indexed in https://github.com/KSP-CKAN/CKAN-meta/commit/376745a492cb9099fbf8acbfb4e9f235606836ab.
=> Remove KSPCommunityFixes conflict from PersistentRotationUpgraded

NetKAN/KeridianDynamicsVesselAssembly.netkan
- move fuel switch mods to "recommended" per readme saying they are 99% required
- move PatchManager and fuel switch mods out of "supports"
- fix incorrect InterstellarFuelSwitch-Core relationship
=> KeridianDynamicsVesselAssembly fixes

NetKAN/MinorPlanetsExpansion.netkan
The homepage is set on SpaceDock but not GitHub, so it was lost in #10386.
=> Set MinorPlanetsExpansion resources.homepage

NetKAN/HabTechRobotics.netkan
<https://github.com/benjee10/htRobotics>
```
DEPENDENCIES
- B9PartSwitch
- KSP Breaking Ground DLC
```
<https://github.com/benjee10/htRobotics/commit/267d4e46bcda650a9346022e2012713bb8eace06>
Pointed out by @Clayell in <https://github.com/KSP-CKAN/NetKAN/pull/9582#issuecomment-2791375947>.
=> Add BreakingGround-DLC dep for HabTechRobotics

NetKAN/AircraftCarrierAccessories.netkan
AircraftCarrierAccessories and StarWarsShips both install `GameData/KFC/Resource/ResourcesGeneric.cfg`, but AircraftCarrierAccessories doesn't use it or need it.
Now it's filtered out.
Fixes #10496.
___
ckan compat add 1.10 1.11 1.12
ckan install AircraftCarrierAccessories StarWarsShips
=> Filter Resource dir out of AircraftCarrierAccessories

NetKAN/VuhrantiSystem.netkan
This mod's ZIP no longer has `GameData`, `VuhrantiSystem-Terrain`, or `GameData/VuhrantiSystem-Textures`.
=> Default install stanza for VuhrantiSystem

NetKAN/MinorPlanetsExpansion.netkan
#10512 said:
> !NOTICE! I made this mod believing that the original MPE doesn't include ribbons. Turns out, there is an official one on the [github repository of MPE](https://github.com/ExosLab/Minor-Planets-Expansion/tree/main) that isn't present on CKAN. This is why I've labeled this pack as an alternative version.
Upon investigation, this turned out to be true.
- Now MPE's ribbon pack is installed, and FinalFrontier is suggested and supported
- Now MPE depends on KSPCommunityFixes as specified in its latest release notes
- Now the Spanish and Russian translations are installed (the ZIP has them split into a separate folder unnecessarily)
=> Update MinorPlanetsExpansion relationships and install

NetKAN/ChemicalCore.netkan
- Added CryoTanks as a supported mod.
```
supports:
- name: CryoTanks
```
See #10503.
=> Add Chemical Core's supported mods

NetKAN/KiwiOrbitalDesignsServices.netkan
- <https://spacedock.info/mod/3602/KODS%20-%20Kiwi%20Orbital%20Designs%20Services>
- <https://github.com/nolifejordan/Kiwi-Orbital-Designs-Systems>
Requested by @nolifejordan
Unsure if other changes need to be made due to different auto-filled fields on GitHub vs SpaceDock.
=> Change Kiwi Orbital Designs Systems kref to GitHub

NetKAN/ChemicalCore.netkan, NetKAN/Tide.netkan
- Removed ModuleManager dependency for Tide.netkan because it is not needed.
=> Remove ModuleManager dependency for Tide

NetKAN/NightShift.netkan
Version 3.0 of NightShift now requires Shabby to be installed.
By the way, is there a way for this requirement to be version dependent, or is it better to just apply this to all versions?
=> Update NightShift requirements

NetKAN/CelestialHarmony-Chaos.netkan, NetKAN/CelestialHarmony.netkan
There are two assets attached to the latest release of CelestialHarmony:
As a default, the bot has chosen to use the first one in the list, `_Chaos.zip`, but `_Harmonia.zip` is meant to be the core module.
See also comment from author at https://github.com/KSP-CKAN/NetKAN/issues/10253#issuecomment-2925159856.
Now `CelestialHarmony` has `asset_match/Harmonia`, and a new `CelestialHarmony-Chaos` module is added with `asset_match/Chaos`.
=> Add new CelestialHarmony submodule

NetKAN/CelestialHarmony-Chaos.netkan, NetKAN/CelestialHarmony.netkan
See https://github.com/KSP-CKAN/NetKAN/issues/10024#issuecomment-2925216265.
- CelestialHarmony now suggests ParallaxContinued instead of Parallax, and conflicts with Parallax
- CelestialHarmony-Chaos now suggests Singularity and KopernicusExpansion (which should be provided by KopernicusExpansionContinueder)
=> Fix CelestialHarmony relationships

NetKAN/HeapPadder.netkan
With bad data in HeapPadder's latest version file, there's a strong risk of it being replaced or a new release, so it shouldn't stay frozen.
Now it's unfrozen with a janky `x_netkan_override` property to fix the compatibility no matter what it is upstream.
=> Unfreeze HeapPadder.frozen with compatibility overrides

NetKAN/GRAPEFRUIT.netkan, NetKAN/Grounded.netkan, NetKAN/MSP3000a.netkan, NetKAN/RetroFuture.netkan
- GRAPEFRUIT must have had a version file at some point, but it no longer does.
Now the `$vref` is removed, and while looking into that I noticed we can multi-host it as well.
- Grounded has a version file, but it's out of date. The current netkan uses `ksp_version` to set the compatibility based on the forum thread, but if this mod ever does another release with an up to date version file, we'll want to use it.
Now it uses `$vref` to get the version file's compatibility, and `x_netkan_override` to set `ksp_version_max` for the current release.
- MSP3000a's version file has bad data (see linuxgurugamer/Material-Science-Pod#4), but it currently has a `$vref` anyway since the SpaceDock translator will override the error.
Now the `$vref` is replaced by a `comment` explaining the problem with …
=> Compatibility tweaks for a few mods

.github/actions/manual_inflate/action.yml, .github/workflows/manual_inflate.yml
See KSP-CKAN/NetKAN-Infra#355; the manual inflate workflow can be improved, and that PR created a way to do that.
Now the `manual_inflate` workflow uses a new `manual_inflate` action to run the new `inflate-netkan` command in the `kspckan/netkan` container.
=> Better manual inflate action

NetKAN/RestockWaterfallExpansion.netkan
This mod seemingly bundles two other mods, but altered, which is a bad practice but not in our power to change.
CKAN wasn't installing those other folders, but now it does, and this mod conflicts with the other two.
Fixes #10616.
=> Fix RestockWaterfallExpansion install

NetKAN/ProceduralParts.netkan
@siimav is considering a new ProceduralParts release with an internal .ckan file (see KSP-RO/ProceduralParts#373) so a new dependency can be added smoothly (see KSP-RO/ProceduralParts#359).
Now the main netkan:
- is YAMLized
- has its relationships removed so they can be set by the internal ckan file
- has `x_netkan_allow_out_of_order` removed because the reason from #7644 (retrofits for KSP 1.7.3) no longer applies
- has `resources.homepage` removed because it's now set in the repo
Note that we can't merge this until there is an internal ckan because the relationships should not actually disappear from the module.
=> Move ProceduralParts relationships to internal ckan

NetKAN/KerbalPowersArmory.netkan, NetKAN/KerbalPowersCore.netkan, NetKAN/KerbalPowersInterstellar.netkan
These changes should cherry pick only a single subfolder in the same fasion as the USI modset. This will resolve file conflicts.
https://github.com/KSP-CKAN/NetKAN/blob/2b1581184dd0913dd18dbc667df3a32ba6a9efa7/NetKAN/MOLE.netkan#L35
KP Core is added as a new dependency hosting overlapping files between different suite mods. 
SpaceDock | GitHub
:-- | :--
<https://spacedock.info/mod/3821/Kerbal%20Powers%20Interstellar> | <https://github.com/KerbalPowers/KP-Dynamics>
<https://spacedock.info/mod/3767/Kerbal%20Powers%20Armory> | <https://github.com/KerbalPowers/KP-Armory>
<https://spacedock.info/mod/3943/Kerbal%20Powers%20Core> | <https://github.com/KerbalPowers/KP-Core>
___
ckan install KerbalPowersInterstellar KerbalPowersArmory
=> KerbalPowers Suite modifications

NetKAN/LunaCompat.netkan
https://github.com/TheXankriegor/LunaCompat
Miscellaneous compatibility patches for KSP's [Luna Multiplayer Mod](https://github.com/LunaMultiplayer/LunaMultiplayer).
```yaml
identifier: LunaCompat
$kref: '#/ckan/github/TheXankriegor/LunaCompat'
$vref: '#/ckan/ksp-avc'
release_status: development
resources:
bugtracker: https://github.com/TheXankriegor/LunaCompat/issues
license: https://github.com/TheXankriegor/LunaCompat/blob/main/LICENSE
homepage: https://github.com/TheXankriegor/LunaCompat
repository: https://github.com/TheXankriegor/LunaCompat
tags:
- plugin
install:
- file: GameData/LunaCompat
install_to: GameData
as: LunaCompat
- file: GameData/LunaMultiplayer
install_to: GameData
as: LunaMultiplayer
ksp_version: '1.12'
depends:
- name: ModuleManager
min_version: 4.2.3
- name: …
```
=> Add LunaCompat

NetKAN/PromisedWorldsCore.netkan, NetKAN/PromisedWorldsDebdeb.netkan
See #10704, #10705, #10707, and #10711 for previous.
Now that this mod is on SpaceDock, we can use the author-maintained values for name, abstract, and author.
And the core now suggests Debdeb.
=> Get PromisedWorlds name, abstract, and author from SpaceDock

NetKAN/XensPlanetCollectionRevived.netkan
This mod was offered as a "supports" when installing distant object enhancement, which seems wrong.  I'm leaving OPM and ResearchBodies since those could be more gameplay-oriented and someone installing those mods might be interested in planet packs that work with it.
=> XensPlanetCollectionRevived: move some supports to suggests

NetKAN/StockalikeMiningExtension.netkan
After #10729, StockalikeMiningExtension has an inflation warning about its unused version file.
Now it has a vref. If that doesn't work, we'll document it with a new `comment`.
=> Vref for StockalikeMiningExtension

NetKAN/PromisedWorldsCore.netkan, NetKAN/PromisedWorldsDebdeb.netkan
SpaceDock is very slow and mostly just cancels your upload.
This Pull request removes SpaceDock support for PromisedWorlds.
=> Drop SpaceDock support for PromisedWorlds
